### ISSUE TITLE
find and replace problem in unix version 

### ISSUE THREAD

**Issue by wpd0101** [wxMaxima-developers/wxmaxima#1006]
From the following:
H:(px^2+py^2+pz^2)(2*mu)-Ze_sq/sqrt(x^2+y^2+z^2);
px:-%i*hbar*diff(f(x,y,z),x);
py:-&i*hbar*diff(f(x,y,z),y);
pz:-&i*hbar*diff(f(x,y,z),z);
find and replace when substituting for hbar:
H:(px^2+py^2+pz^2)(2*mu)-Ze_sq/sqrt(x^2+y^2+z^2);
px:-%i*%h_bar*diff(f(x,y,z),x);
py:-&%h_barar*diff(f(x,y,z),y);
pz:%h_barhbar*diff(f(x,y,z),z);
when replace all is chosen. I checked, and the windows version worked as expected, but the Linux (Ubuntu) version fails as shown above.

**Comment by KubaO** [comment]
- [ ] @gunterkoenigsmann  Could you please re-check on linux?
- [ ] @KubaO note to self to check on macOS.

**Comment by gunterkoenigsmann** [comment]
Was a case-insensitive-search problem, in the end.
