### ISSUE TITLE
wxMaxima: strange linebreaks below graph in WXMX (and PDF)

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1022]
After wxplot2d command, the supplementary textual output:

`plot2d: expression evaluates to non-numeric value somewhere in plotting range.`

... shows several strange linebreaks and reads:

```
plot2d: expression evalua
t
es to non-numeric value somewhere in pl
otting range.
```

These nonsense linebreaks occur also in PDF file, but they are in different positions. See output (%t16) in the attached files:
* [3ebm_calc_e.wxmx.zip](https://github.com/andrejv/wxmaxima/files/2280556/3ebm_calc_e.wxmx.zip) = ZIPed WXMX file
* [3ebm_calc_e.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/2280557/3ebm_calc_e.wxmx.pdf) = WXMX file printed to PDF

Versions of my programs:
* OS: Windows 7 Professional
* wxMaxima: maxima-clisp-sbcl-5.41.0a-win64.exe
* update of wxMaxima: windows nightly built from 2018-08-11

**Comment by gunterkoenigsmann** [comment]
Not again! Could you please enable the XML viewer (for example by double-clicking the network symbol in the bottom left) and see if Maxima sends us the linebreaks or if wxMaxima somehow invents them?

Thanks in advance,

   Gunter.

**Comment by mirekslouf** [comment]
Dear Gunter, I am sending the required supplementary information:

1. output from `build_info();`
```
build_info(version="5.41.0a_dirty",timestamp="2017-10-24 09:10:11",host="x86_64-w64-mingw32",lisp_name="CLISP",lisp_version="2.49 (2010-07-07) (built on toshiba [192.168.43.206])")
```

2. Printscreen showing Maxima response in XML (hoping that this is what you want):
![wxmaxima_xml_monitor](https://user-images.githubusercontent.com/22853864/44000866-d3ee44e4-9e27-11e8-9d75-8cdae028ee1c.png)

**Comment by gunterkoenigsmann** [comment]
Then it is the clisp bug: If clisp isn't faster than the program that receives the data from clisp clisp produces spurious newlines.

Unfortunately clisp hasn't had a release in a out 10 Years.

If you are lucky your Maxima is shipped with a version that was compiled with sbcl. In that case adding

      -l sbcl

to Maxima's command line arguments in wxMaxima's config dialogue should resolve this problem.

**Comment by mirekslouf** [comment]
Yes, the option `-l sbcl` works. Thank you, Mirek

**Comment by mirekslouf** [comment]
I think that this issue has been resolved (see my comment just above) and can be closed.
Thanks for your support, Mirek

**Comment by gunterkoenigsmann** [comment]
It did recur for a while. But it now should have been fixed both on the maxima and the wxMaxima side. Thanks for your patience!
