### ISSUE TITLE
Two more levels of subsections needed

### ISSUE THREAD

**Issue by RolandSalz** [wxMaxima-developers/wxmaxima#1032]
When writing large .wxm files more Levels of subsections are needed. Mathematica allows for 5 Levels which is sufficient in almost all cases. wxMaxima presently has only 3 Levels of subsections. Would it be possible to extend this to 5 Levels, too?

**Comment by gunterkoenigsmann** [comment]
Wow... ...that would be much work. But it is possible => will do it once I have time.
