### ISSUE TITLE
plot error on macOS

### ISSUE THREAD

**Issue by uenz** [wxMaxima-developers/wxmaxima#1033]
I installed maxima / wxmaxima via brew on macOS 10.13.6. The brew formula should have a dependency to xquartz (brew install Caskroom/cask/xquartz) which is necessary for gnuplot.
But after solving the install isue plotting does not work.
`wxplot2d(x, [x,-1,1]);`
leads to 
`set terminal png picsize 600 400; set zeroaxis;; 
                 ^
"/var/folders/vv/fvjzv0ps48z693fxtr_qb3d40000gn/T/maxout22552.gnuplot", line 1: invalid color spec, must be xRRGGBB`

**Comment by gunterkoenigsmann** [comment]
Unfortunately I don't know who makes the brew packets. But we have just released a new wxMaxima version in which this bug is resolved.  A temporary fix would be to tell wxMaxima that this isn't an old Gnuplot version. Currently I cannot find which variable to set for this, though.

**Comment by KubaO** [comment]
Closing as this is a homebrew packaging error. Gnuplot builds on macOS shouldn't be using X11!
