### ISSUE TITLE
Asterisks in comments being converted to dots

### ISSUE THREAD

**Issue by endolith** [wxMaxima-developers/wxmaxima#1034]
When "Use centered dot character for multiplication" is selected, can there be an exception for comments?

![2018-09-27 16_52_03-wxmaxima 17 10 1](https://user-images.githubusercontent.com/58611/46174009-e2fd1880-c275-11e8-80d0-baa0b8594089.png)

<s>Maybe comments could be changed in color or something, too?</s>

**Comment by gunterkoenigsmann** [comment]
Changing the color of comments can be done in the settings dialogue.
Changing the dot back to a star is possible (even if a bit of work as escaped comment markers and comment markers inside strings need to be handled differently).But I am not completely sure which of the two possibilities is the best:

 * The "*5" actually describes a multiplication - as might do most stars in comments. I personally prefer the ordinary multiplication center dot in this case.
 * And I don't like characters to change as soon as they are inside a comment.

But I understand your point and don't think your idea is less valid than mine. @daute, @andrejv : Does any of you have a precedence in this case?

**Comment by endolith** [comment]
> Changing the color of comments can be done in the settings dialogue.

I didn't realize it's already a different color.  Too similar on my other screen.

> The "*5" actually describes a multiplication - as might do most stars in comments.

Yes, I would expect those to stay as dots

**Comment by dilijev** [comment]
Certainly the comment delimiters `/* ... */` should be displayed as expected, even if all other stars inside the comments are displayed as middle dots.

**Comment by gunterkoenigsmann** [comment]
I *think* I now have a framework in place that might allow me to fix this in a future step...
