### ISSUE TITLE
Cannot pull, "Your branch and 'origin/master' have diverged"

### ISSUE THREAD

**Issue by ckoe-bccms** [wxMaxima-developers/wxmaxima#1035]
Hello everybody,

I have a copy of the repository which I update sporadically every few weeks. But I do not do anything in it, it is just to have a copy. Today, I got an error from ```git pull``` which I have never seen before. Eventually this is just a local problem, but I wanted to mention  it anyways just in case.

It was originally pulling and apparently able to fast-forward and then printed the error shown below. Unfortunately I lost that output trying to figure out what was going on.

```
% git status 
On branch master
Your branch and 'origin/master' have diverged,
and have 5958 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
% git pull  
fatal: refusing to merge unrelated histories
% git log HEAD..origin/master
commit 35af37243b589dbe1e92ba3a5443ff66b4bc840f
Author: Andrej Vodopivec <andrej.vodopivec@gmail.com>
Date:   Tue Sep 25 21:58:05 2018 +0200

    Create README.md
```
Note the "nothing to commit, working tree clean" which I interpret as saying that I indeed have done nothing in my local copy.

Best Regards

Christof

**Comment by gunterkoenigsmann** [comment]
The same happened to me when wxMaxima moved to its new location. I guess the easiest way to fix the problem is to checkout wxMaxima anew from the new location.

Sorry for that,

   Gunter.

On 30 September 2018 12:48:50 CEST, ckoe-bccms <notifications@github.com> wrote:
>Hello everybody,
>
>I have a copy of the repository which I update sporadically every few
>weeks. But I do not do anything in it, it is just to have a copy.
>Today, I got an error from ```git pull``` which I have never seen
>before. Eventually this is just a local problem, but I wanted to
>mention  it anyways just in case.
>
>It was originally pulling and apparently able to fast-forward and then
>printed the error shown below. Unfortunately I lost that output trying
>to figure out what was going on.
>
>```
>% git status 
>On branch master
>Your branch and 'origin/master' have diverged,
>and have 5958 and 1 different commits each, respectively.
>  (use "git pull" to merge the remote branch into yours)
>nothing to commit, working tree clean
>% git pull  
>fatal: refusing to merge unrelated histories
>% git log HEAD..origin/master
>commit 35af37243b589dbe1e92ba3a5443ff66b4bc840f
>Author: Andrej Vodopivec <andrej.vodopivec@gmail.com>
>Date:   Tue Sep 25 21:58:05 2018 +0200
>
>    Create README.md
>```
>Note the "nothing to commit, working tree clean" which I interpret as
>saying that I indeed have done nothing in my local copy.
>
>Best Regards
>
>Christof 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wxMaxima-developers/wxmaxima/issues/1035

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ckoe-bccms** [comment]
Hello Gunter,

no problem, I will do that then ! I am relieved it is nothing serious. Thank you.

Best Regards

Christof

**Comment by KubaO** [comment]
FYI this happens when there was a change in git history (a.k.a. history rewriting) in either repository. The fix is to `git reset` the local (master) branch to the remote (master) branch's commit identifier ("hash").

**Comment by gunterkoenigsmann** [comment]
That was the first (and only time) I did history rewriting on my master branch ;-(

**Comment by KubaO** [comment]
Not a big deal. Resets can be done with no loss of data. But I wouldn’t dare from the command line. If you haven’t tried SmartGit yet - try it! It’s the kind of German engineering I like. On the other hand, VW “Service Position” - not so much :)

**Comment by gunterkoenigsmann** [comment]
If you know what you are doing for can do astonishing things and your tool has much knowletin charge for anyone who uses it. But many developers are still in the following state: https://xkcd.com/1597/ ...I always try not to scare that type of audience, neither.

**Comment by KubaO** [comment]
SmartGit visualizes things that I wouldn’t dare do by hand on the command line :)
