### ISSUE TITLE
Problem hitting 'ctrl+R' if the current path has a blank space

### ISSUE THREAD

**Issue by SengerM** [wxMaxima-developers/wxmaxima#1036]
I have noticed that if I open wxMaxima the "evaluate all cells" command works perfectly. Although if I save my work in any custom directory whose path contains a blank space, then I cannot execute again this command and get an error. For example, suppose the path where my wxMaxima document is located is "/home/me/my favorite directory". Then, if I hit "ctrl+R" I get the error message "Message from maxima's stderr stream: /usr/bin/maxima: 164: cd: can't cd too /home/me/my". It seems as if blank spaces are not being escaped. 

For reference, I am using wxMaxima 18.02.0.unofficial in Ubuntu 18.04, which I installed after [this issue](https://github.com/wxMaxima-developers/wxmaxima/issues/1031).

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this big report that contains an accurate analysis of the problem that actually lies in Maxima, not in wxMaxima. Will resolve it as fast as I can.

**Comment by gunterkoenigsmann** [comment]
This issue is resolved in the current release of wxMaxima.
