### ISSUE TITLE
wxMaxima slow

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1037]
Running the Windows version. Anybody else that had experienced that wxMaxima has become quit slow in updating the window, even when just resizing the window. Especially pronounced with large worksheets.

**Comment by gunterkoenigsmann** [comment]
In theory updating the window should have gotten way faster in the 18.10 version for most actions. Which means that redoing all line breaks (which is complicated for maths as fractions can be shown as a/b or as a 2d object) on resizing now feels much slower than the rest of the program.

The only new thing that needs time I have introduced - but that actually was a few years ago - was automatic line breaks for comments. 

=> updating the window on resizing is slow. But shouldn't be slower than it was in the past. Scrolling insine the window and displaying new text should be fast. If that isn't the case please protest. In this case we need to find out why. One reason might be that we now use antialiassing for displaying lines. But we don't display many lines and the library that does the antialiassing normally is faster than using the non-accelerated "dumb" output routines that don't support it...

...which means that the graphics driver might cause slowness. But we don't use anything that is complicated enough to make that probable...

**Comment by ReneSci** [comment]
Sorry for not having returned on this for a long time.
Just downloaded the latest daily build (8/10-2019) - it is still slow with a large worksheet. 
- Scrolling goes fine
- Making a wxMaxima window smaller (by dragging a corner)  goes fairly ok
- Making a wxMaxima window larger(by dragging a corner)  goes does almost not work
- Going between full screen and windowed by using the windows icons works fast and fine

wxMaxima version: 19.10.0
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_43_base_153_g07793e95c
Maxima build date: 2019-10-07 23:48:17
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

By the way:  Why are / and \ mixed in the directory (see above) - and which one is the correct one ?

**Comment by ReneSci** [comment]
Continued in https://github.com/wxMaxima-developers/wxmaxima/issues/1185.
There might not be anything to do.
