### ISSUE TITLE
copy & cut entire cells crashes wxmaxima on windows

### ISSUE THREAD

**Issue by adriaanph** [wxMaxima-developers/wxmaxima#1040]
using either ctrl+c, ctrl+x or the Edit pull-down menu **when i have an entire cell selected**, reliably leads to wxmaxima terminating abruptly. this happens for all cell types.

the same does not happen when i've got only part of the contents of the cell selected.

__my system configuration is as follows:__
wxMaxima version: 18.10.1
using wxWidgets version: wxWidgets 3.1.0
Maxima version: 5.42.0
Maxima build date: 2018-09-29 14:05:34
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Adriaan/maxima/
Help dir: C:\ProgramFiles\maxima-5.42.0\wxMaxima/help
Maxima lisp dir: C:\ProgramFiles\maxima-5.42.0\bin/../share/maxima/5.42.0

**Comment by gunterkoenigsmann** [comment]
If in the config dialogue you tell the program not to copy cells as EMF -Does that help?

**Comment by adriaanph** [comment]
spot on! disabling that option solves the issue.

i now remember enabling that option after installing the latest version, so it is presumably always disabled by default.
