### ISSUE TITLE
where can I get the install file

### ISSUE THREAD

**Issue by WhereNow** [wxMaxima-developers/wxmaxima#1041]
I would like to install wxMaxima 18.10.1 but I have not been able to find the windows installation "exe" file for this version (so far, I have found only the source code), where can I download the "*.exe"? Thank you.

**Comment by daute** [comment]
Hi,
wxMaxima for Windows is included in the Windows-Installer for Maxima, which can be downloaded from: https://sourceforge.net/projects/maxima/files/Maxima-Windows/
A new installer was released yesterday, it does include the current wxMaxima version.

Best regards, Wolfgang

**Comment by WhereNow** [comment]
A truly beautiful piece of work; thank you very much!
