### ISSUE TITLE
Windows: Unnecessary cmd and conhost processes

### ISSUE THREAD

**Issue by dilijev** [wxMaxima-developers/wxmaxima#1042]
It looks like the cause is that `wxmaxima.exe` launches `cmd.exe` to run `maxima.bat`, which launches `lisp.exe` to run maxima in the background, but that shouldn't mean that the `cmd.exe` originally running `maxima.bat` needs to stick around after launching the `lisp.exe` process. There should be a way to launch `lisp.exe` without keeping that unnecessary process around.

![image](https://user-images.githubusercontent.com/494055/47260387-97521f00-d46f-11e8-9828-d5f306ad8ef4.png)

**Comment by gunterkoenigsmann** [comment]
That is an issue that needs to be addressed in maxima, not in wxMaxima. Feel free to file a bug for the maxima project at https://maxima.sourceforge.net, though.

**Comment by gunterkoenigsmann** [comment]
Will close this report, not because it doesn't tread undesired behavior (a complaint about closing a shell on shutting down etc.), but because it needs to be addressed in a different project.
