### ISSUE TITLE
MacOS plotting issues

### ISSUE THREAD

**Issue by justdanyul** [wxMaxima-developers/wxmaxima#1044]
Hello there, 

I'm afraid I got some issues getting wxMaxima 18.02.0 to play nicely on my MacOS machine. Im running MacOS 10.14 and I can confirm I have Gnuplot installed and working well when used outside of wxmaxima.

Some plotting commands work, for example, wxplot2d() works fine, others do not. For example, contour_plot does nothing, plot2d prints a path to a gnuplot_pipes file, but doesn't produce a plot. and plotdf() works.

This is a brand new install, no bespoke configuration of wxmaxima have been done.

Update:

The plot (pun intended) thickens. When adding in [gnuplot_term, x11] to plot2d() and friends, it happily plots. I presume the default settings are somehow wrong? (I'll look into setting this through config, but, IMHO it still seems broken that its needed).

**Comment by gunterkoenigsmann** [comment]
That way my fault.
Try setting

     wxplot_old_gnuplot:false;

**Comment by KubaO** [comment]
@gunterkoenigsmann So I believe this is fixed now, right?

**Comment by gunterkoenigsmann** [comment]
I hope that some of the MacOs plotting issues are resolved now. But there seems to be no good .dmg version of gnuplot, currently (there seems to be none that supports cairo, for example) and there are many other gnuplot features that are sometimes reported to be missing in the various gnuplot versions that are available for the mac. I don't have a mac I can test anything on, unfortunately...

**Comment by KubaO** [comment]
I really would hope we could just support either macports or homebrew or even both, as a requirement, but the last thing we need is rebuilding gnuplot. I used to bootstrap gnuplot sources on Windows in times of cmake 2, with a bunch of dependencies, using msvc only and no mingw nor other tools. It worked but I’m not eager to repeat that anytime soon, and it sounds like a total waste of life even if the result may be pretty. I don’t mind figuring out around arcane build systems but it’s not much fun anymore.
