### ISSUE TITLE
scrolling below the first pages documents are blank

### ISSUE THREAD

**Issue by mar04** [wxMaxima-developers/wxmaxima#1045]
After updating from wxmaxima 18.02 to 18.10 wxm files display correctly only about the first 1 or 2 pages then it's all blank.
Here is a video demonstrating the problem: https://www.youtube.com/watch?v=TKbcpPgIhz8

**Comment by gunterkoenigsmann** [comment]
Where did you get your wxMaxima from? That nearly looks like the wxDc::Prepare command that sets up the crop-to-eindoe not being called in the Right Moment.

I still am unsure which is the right moment, though, as wxWidgets versions and operating systems seem to disagree here...

**Comment by mar04** [comment]
From Archlinux repositories: https://www.archlinux.org/packages/extra/x86_64/wxmaxima/

**Comment by gunterkoenigsmann** [comment]
The question is what is the difference between archlinux and Ubuntu...

**Comment by mar04** [comment]
I've opened a bug report against wxmaxima on Archlinux bug tracker, in case it's something distro specific: https://bugs.archlinux.org/task/60704

Here is output of wxbuild_info() I forgot to include before:
wxMaxima version: 18.10.1
using wxWidgets version: wxWidgets 3.0.4
Maxima version: 5.42.1
Maxima build date: 2018-10-31 07:38:43
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.18.16-arch1-1-ARCH X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.11
wxMaxima's idea of the directory layout is:
User configuration dir: /home/mariusz/.maxima/
Help dir: /usr/share/doc/wxmaxima
Maxima lisp dir: /usr/share/maxima//5.42.1

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

**Comment by gunterkoenigsmann** [comment]
Another idea: do you know how to compile a program?

**Comment by mar04** [comment]
Sure, you want me to build it from sources?

**Comment by gunterkoenigsmann** [comment]
That would be great! If you can do so we can try to debug the problem. With any luck at all it is already resolved in the current git master as I have fixed a few bugs in the display code.

**Comment by mar04** [comment]
I've build from git master but unfortunately it didn't change anything.
I won't have time for it today but I'm willing to experiment to find out what the problem is, so if you have any ideas write it down and I'll get back to you later.

**Comment by gunterkoenigsmann** [comment]
The issue most probably is in  MathCtrl::OnPaint. And as  PrepareDC sets up the clip-to-draw-region functionality I guess it has to do with PrepareDC. But more I don't know.

**Comment by mar04** [comment]
Today I run git bisect and this is the result:

```
0239447032fcc7a6063bd5826afa7528caf65382 is the first bad commit
commit 0239447032fcc7a6063bd5826afa7528caf65382
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Fri Jul 27 18:18:52 2018 +0200

    Depending on the gtk version the antialiassing gc is only scrolled if it is prepared, separately. On the Mac, though, preparing the antialiassed gc separately scrolls twice => a new #ifdef.
```

**Comment by mar04** [comment]
I also tried rebuilding current git master but this time with wxgtk2 instead of wxgtk3, which Archlinux uses, and it turns out it work just fine. So it's something to do with wxgtk3.

**Comment by mar04** [comment]
Still broken but in another way: https://www.youtube.com/watch?v=_KeZzetxIvA

**Comment by gunterkoenigsmann** [comment]
Did another commit. Perhaps we need an

     #ifndef __WXGTK30__ 

somewhere. If you can tell me where I'll commit it. And did another commit a few minutes ago.

**Comment by kosilin** [comment]
Hi! 

I'm very sorry to disturb you, but as it seems to me I've found the way to correct scrolling issues while using new wxGTK3.

It's necessary:
1. remove DoPrepareDC(antiAliassingDC); at line 394, file MathCtrl.cpp (master branch)
2. uncomment dcm.SetDeviceOrigin(0, 0); at line 531, file MathCtrl.cpp (master branch)

After these corrections have been done everything works good under wxGTK 3.0.4-4 (Fedora 29 Linux, for example).

I will be happy if somebody would make the corrections (under appropriate #ifdef's) in master wxMaxima branch.

Best regards,
Alexey

**Comment by mar04** [comment]
I've submitted #1049 based on fixes suggested by @kosilin. Both wxgtk2 and wxgtk3 versions seem to work.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot to you two! If the problem still exists please reopen this bug report.

**Comment by kosilin** [comment]
Thank you very much!
