### ISSUE TITLE
CLISP producing garbled output depending on read timing.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1047]
This is the code from the qinf project on the maxima 3rd party projects page.
this had been working.

I have a file that start with this and the lapack fails.
load("itensor");
load("qinf.lisp");
load(lapack);
load("log2.mac");
load("eigen");
load("diag");

Lapack does not load.  It gets may name errors.

The demo("tensor")   does not work again.   The lines of text are in lines of only 1 or 2 characters most of the time.

The last version I went back to is from 7/12/2018.  I have not been downloading any builds since then.

**Comment by gunterkoenigsmann** [comment]
That looks like being a change in Maxima or the lisp you are using, not in wxMaxima...

**Comment by gunterkoenigsmann** [comment]
Maxima on Windows comes in 2 versions: one was compiled using clisp and one using sbcl. Sbcl is fast whereas clisp is memory-efficient. If you give Maxima the command-line option

      -l clisp

It will use the latter.

In wxMaxima the command-line options for maxima can be specified in the settings dialogue.

**Comment by richardgobeli** [comment]
I get the same result when using the released version 5.42.1.
In demo("tensor");  the inputted lines come out 1 or 2 characters per line.  the output lines are displayed correctly.  I think this may be coms between wxMaxima and Maxima.

loading LAPACK causes many errors, because the new compiler does not like unused variables in a lisp function.

wxMaxima version: T
using wxWidgets version: T
Maxima version: 5.42.1
Maxima build date: 2018-10-16 22:11:32
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\100024837/maxima/
Help dir: C:\maxima-5.42.1\wxMaxima/help
Maxima lisp dir: C:\maxima-5.42.1\bin/../share/maxima/5.42.1

**Comment by richardgobeli** [comment]
Try to see if I can send the xlm codes as quote text.

"SENT TO MAXIMA:

:lisp-quiet (setq $wxplot_pngcairo t)
:lisp-quiet (setq $wxsubscripts t)
:lisp-quiet (setq wxUserConfDir "C:\\Users\\100024837/maxima/")
:lisp-quiet (setq wxHelpDir "C:\\maxima-5.42.1\\wxMaxima/help")
:lisp-quiet (setq wxMaximaLispLocation "C:\\maxima-5.42.1\\bin/../share/maxima/5.42.1")
:lisp-quiet (setq $wxplot_size '((mlist simp) 1200 800))
demo("tensor");

MAXIMA RESPONSE:


read and interpret file: C:\maxima-5.42.1\share\maxima\5.42.1\share\tensor\tensor.dem

At the '
_
' prompt, type ';' and <enter> to proceed with the demonstration.
To abort the demonstration, type 'end;' or 'eof;' and then <enter>.
(%
i
2
)
 
l
o
a
d
(
"
t
e
n
d
e
m
o
.
m
a
c
"
)
<variables>
<variable>
     <name>*wx-load-file-name*</name>
     <value>tendemo.mac
</value>
     </variable>
<variable>
     <name>*wx-load-file-start*</name>
     <value>1</value>
     </variable>
    </variables>
   <mth>
    <st>This is the main demonstration program for MAXIMA tensors.</st>
    <st> </st>
    </mth>
   <mth>
    <st>The following demos are available:</st>
    <st> </st>
    </mth>
   <mth>
    <st>
     </st>
    <st> </st>
    </mth>
<mth>
<st>INDICIAL TENSOR MANIPULATION        COMPONENT TENSOR MANIPULATION</st>
    <st> </st>
    </mth>
   <mth>
<st>1. Basics                           11. Initialization</st>
    <st> </st>
    </mth>
   <mth>
<st>2. Index contraction                12. Differential geometry</st>
    <st> </st>
    </mth>
   <mth>
    <st>3. Simplification and symmetries    13. Gravitational theory</st>
    <st> </st>
    </mth>
   <mth>
    <st>4. Special tensors                  14. Frame fields</st>
    <st> </st>
</mth>
<mth>
<st>5. Coordinate differentiation       15. Torsion and nonmetricity</st>
    <st> </st>
    </mth>
   <mth>
    <st>6. Covariant derivatives, curvature 16. Algebraic classification</st>
    <st> </st>
    </mth>
   <mth>
    <st>7. Exterior algebra                 17. Differential equations</st>
    <st> </st>
    </mth>
   <mth>
    <st>8. Generating CTENSOR programs      18. Using Taylor series</st>
    <st> </st>
    </mth>
<mth>
<st>9. Frames, torsion, nonmetricity</st>
    <st> </st>
    </mth>
<mth>
<st>
     </st>
<st> </st>
</mth>
<mth>
<st>A. Algebraic tensor manipulation</st>
    <st> </st>
    </mth>
   <mth>
<st>E. Complete examples</st>
    <st> </st>
    </mth>
<mth>
<st>X. Exit this demo</st>
<st> </st>
    </mth>
<mth>
<st>
     </st>
<st> </st>
</mth>
<PROMPT-P/>
   <mth>
    <st>Select an option by its number followed by a semicolon (;)</st>
    <st> </st>
    </mth>
   <PROMPT-S/>"

**Comment by richardgobeli** [comment]
I tried it again today and it seems to be working again.   I made no changes except -l sbcl.  
It works with -lsbcl and it does not work with -l clisp.  The previous comment is with clisp.

**Comment by gunterkoenigsmann** [comment]
With much luck clisp now works again for you in the current nightly build. But - as this is a timing problem in clisp it will spring to live again from time to time for users using clisp. At least until they make a release that fixes the problem.

**Comment by gunterkoenigsmann** [comment]
I hope this is fixed in the current nightly build of maxima.
