### ISSUE TITLE
wxMaxima bad build, but only related to Wx

### ISSUE THREAD

**Issue by archbugaboo** [wxMaxima-developers/wxmaxima#1050]
I am sorry to open this since it seems that any search gives no similar results to mine, which must mean I am, most probably, alone, and thus, my fault, but I don't know how to interpret this.

I usually compile wxMaxima for a faster GUI response, and, after the Archlinux update a few days ago, wxMaxima starts with this message:

Refusing to send cell to maxima: Mismatched parenthesis
; in: PROGN (SETQ $WXMAXIMAVERSION "18.10.0.unofficial")
;     (SETQ MAXIMA::$WXMAXIMAVERSION "18.10.0.unofficial")
; 
; caught WARNING:
;   undefined variable: $WXMAXIMAVERSION
; 
; compilation unit finished
;   Undefined variable:
;     $WXMAXIMAVERSION
;   caught 1 WARNING condition
; in:
;      PROGN ($PUT '$WXMAXIMA (READ-WXMAXIMA-VERSION "18.10.0.unofficial") '$VERSION)
;     (MAXIMA::READ-WXMAXIMA-VERSION "18.10.0.unofficial")
; 
; caught STYLE-WARNING:
;   undefined function: READ-WXMAXIMA-VERSION
; 
; compilation unit finished
;   Undefined function:
;     READ-WXMAXIMA-VERSION
;   caught 1 STYLE-WARNING condition
Maxima encountered a Lisp error:
 The function MAXIMA::READ-WXMAXIMA-VERSION is undefined.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
; in: PROGN (SETQ $WXWIDGETSVERSION "wxWidgets 3.0.4")
;     (SETQ MAXIMA::$WXWIDGETSVERSION "wxWidgets 3.0.4")
; 
; caught WARNING:
;   undefined variable: $WXWIDGETSVERSION
; 
; compilation unit finished
;   Undefined variable:
;     $WXWIDGETSVERSION
;   caught 1 WARNING condition

This happens with custom build and official build, with the only difference that the official build lists the missing version as `18.10.1` (the package has `18.10.1-1`). I got the sources from both master and 18.10 branch. I ran `pacman -Rsc wxmaxima` and reinstalled the official builds, same error whenever I start wxMaxima.

The only thing broken seems to be whatever is related to the Wx library, that is, I can evaluate `sin(%pi/4)`, but the result appears as if Maxima has been run in the terminal:

`                                       1`
`(%o2)                               -------`
`                                    sqrt(2)`

Commands involving Wx fail, for example `wxdraw2d()`:

`(%o3)                 wxdraw2d(explicit(sin(x), x, 0, 7))`

I'd be glad to have this bug deleted if this only happens on my computer, but I don't know how to solve this problem. `wxbuild_info()` and `wxbug_report()` also fail, so I can't say too much of the build.

**Comment by gunterkoenigsmann** [comment]
I am no great shakes in life so I cannot guarantee that I will find it out. But: If you double-click on the network symbol in wxMaxima's bottom right a network monitor springs to live that on startup shows what Maxima sends to wxMaxima in order to teach it the wx-specific stuff. Could you send me this input? The mismatched parenthesis shouldn't be impossible to find...

**Comment by archbugaboo** [comment]
I found that the official build won't even connect to Maxima, which is strange, I could have sworn it did. At any rate, the latest custom compiled version (the 18.10 branch) does, but with the mentioned shortcomings. Here's the output of the [raw XML monitor](https://pastebin.com/JQ1cXxh8). I had to go to pastebin since it's  a monster block of text. Thank you for the reply, but sorry for the bother.

**Comment by gunterkoenigsmann** [comment]
Thanks for this bug report and for helping me debug the problem. Seems like the C++ compiler ArchLinux uses doesn't like assembling large strings and removes the first portion of them => Will delegate the task of assembling the string to wxWidgets.

**Comment by archbugaboo** [comment]
I'm sorry for the necromancy, but the recent update for wxMaxima in Archlinux (19.01.3 dev snapshot) seems to have similar errors. Since for the previous bug report, it seemed to be quiet after your fix, would it be possible to post that fix here so that it remains a guiding light for ay (possible) future similar errors? The error appears in both the official build, and after a `git pull` for the source and building it on my computer.

**Comment by gunterkoenigsmann** [comment]
Arrgh! What I know is:

 * wxMaxima originally kept the instructions on how to talk an XML dialect that doesn't only tell what maxima output but only what was the meaning of the output (allowing to convert the output back to maxima commands for copy-and-paste) in a file named data/wxmathml.lisp. Keeping these instructions in a file is straightforward. But every every operating system and toolkit insists on storing it in a different place. ...and there are many of them: SuSE, Debian, Fink on Mac Os, MacPorts, Homebrew, An AppBundle using Mac Os, MS Windows using Cygwin, MS Windows not using Cygwin,... and making sure the file is installed and finding it isn't a trivial task.
 * Instead I included the instructions for maxima in a large string in src/wxMathml.cpp. But since the string was more than 64 kilobytes long MSVC aborted the compilation outputting an error.
 * I therefore split the string into several wxString objects that were combined in runtime. But some of the strings I initialized the wxString objects with were to long for ArchLinux' C++ compiler. That didn't output an error message but decided to ignore parts of the string
 * The wxStrings were no easy-to-edit place to store lisp code in, anyway. As we store all .png bitmaps in large arrays of hexadecimal numbers in .h files, anyway, Wolfgang therefore suggested to do the same with data/wxMathml.lisp converting it to data/wxMathML.h. That finally seems to work.

The last time the bug arised seeing the startup process in wxMaxima's XML monitor was helpful. If you send me the output in the XML monitor, this time, again I'll try to find out if there is an error to be found there.

**Comment by archbugaboo** [comment]
Sure thing, here's the output after `Maxima > Restart Maxima`:

```
:lisp-quiet (setf *prompt-suffix* "<PROMPT-S/>")
:lisp-quiet (setf *prompt-prefix* "<PROMPT-P/>")
:lisp-quiet (setf $in_netmath nil)
:lisp-quiet (setf $show_openplot t)
:lisp-quiet 
:lisp-quiet (setq $wxmaximaversion "19.01.3-DevelopmentSnapshot")
:lisp-quiet ($put '$wxmaxima (read-wxmaxima-version "19.01.3-DevelopmentSnapshot") '$version)
:lisp-quiet (setq $wxwidgetsversion "wxWidgets 3.0.4")


MAXIMA RESPONSE:

pid=3508
Maxima 5.42.1 http://maxima.sourceforge.net
using Lisp SBCL 1.4.13
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) ; in: PROGN (SETQ $WXMAXIMAVERSION "19.01.3-DevelopmentSnapshot")
;     (SETQ MAXIMA::$WXMAXIMAVERSION "19.01.3-DevelopmentSnapshot")
; 
; caught WARNING:
;   undefined variable: $WXMAXIMAVERSION
; 
; compilation unit finished
;   Undefined variable:
;     $WXMAXIMAVERSION
;   caught 1 WARNING condition
; in:
;      PROGN ($PUT '$WXMAXIMA (READ-WXMAXIMA-VERSION "19.01.3-DevelopmentSnapshot")
;              '$VERSION)
;     (MAXIMA::READ-WXMAXIMA-VERSION "19.01.3-DevelopmentSnapshot")
; 
; caught STYLE-WARNING:
;   undefined function: READ-WXMAXIMA-VERSION
; 
; compilation unit finished
;   Undefined function:
;     READ-WXMAXIMA-VERSION
;   caught 1 STYLE-WARNING condition
Maxima encountered a Lisp error:

 The function MAXIMA::READ-WXMAXIMA-VERSION is undefined.

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
<PROMPT-P/>(%i1) <PROMPT-S/>; in: PROGN (SETQ $WXWIDGETSVERSION "wxWidgets 3.0.4")
;     (SETQ MAXIMA::$WXWIDGETSVERSION "wxWidgets 3.0.4")
; 
; caught WARNING:
;   undefined variable: $WXWIDGETSVERSION
; 
; compilation unit finished
;   Undefined variable:
;     $WXWIDGETSVERSION
;   caught 1 WARNING condition
```

But, really, this sounds like it would be more productive to address the issue to the guys at Archlinux, to make it possible to pass on large string arguments. If you'll tell me what/who/where, I'll do it, no problem.

**Comment by archbugaboo** [comment]
This time, no monster text, but here's the output of `wxplot2d(sin(x),[x,0,10])$`:

```
SENT TO MAXIMA:

:lisp-quiet (setq $wxplot_pngcairo t)
:lisp-quiet (setq $wxsubscripts t)
:lisp-quiet (setq wxUserConfDir "/home/user/.maxima/")
:lisp-quiet (setq wxHelpDir "/usr/share/doc/wxmaxima")
:lisp-quiet (setq wxMaximaLispLocation "/usr/share/maxima//branch_5_42_base_87_g40314b08c")
:lisp-quiet (setq $wxplot_size '((mlist simp) 500 300))
wxplot2d(sin(x),[x,0,10]);

MAXIMA RESPONSE:

; in: PROGN (SETQ $WXPLOT_PNGCAIRO T)
;     (SETQ MAXIMA::$WXPLOT_PNGCAIRO T)
; 
; caught WARNING:
;   undefined variable: $WXPLOT_PNGCAIRO
; 
; compilation unit finished
;   Undefined variable:
;     $WXPLOT_PNGCAIRO
;   caught 1 WARNING condition
; in: PROGN (SETQ $WXSUBSCRIPTS T)
;     (SETQ MAXIMA::$WXSUBSCRIPTS T)
; 
; caught WARNING:
;   undefined variable: $WXSUBSCRIPTS
; 
; compilation unit finished
;   Undefined variable:
;     $WXSUBSCRIPTS
;   caught 1 WARNING condition
; in: PROGN (SETQ WXUSERCONFDIR "/home/user/.maxima/")
;     (SETQ MAXIMA::WXUSERCONFDIR "/home/user/.maxima/")
; 
; caught WARNING:
;   undefined variable: WXUSERCONFDIR
; 
; compilation unit finished
;   Undefined variable:
;     WXUSERCONFDIR
;   caught 1 WARNING condition
; in: PROGN (SETQ WXHELPDIR "/usr/share/doc/wxmaxima")
;     (SETQ MAXIMA::WXHELPDIR "/usr/share/doc/wxmaxima")
; 
; caught WARNING:
;   undefined variable: WXHELPDIR
; 
; compilation unit finished
;   Undefined variable:
;     WXHELPDIR
;   caught 1 WARNING condition
; in:
;      PROGN (SETQ WXMAXIMALISPLOCATION
;                "/usr/share/maxima//branch_5_42_base_87_g40314b08c")
;     (SETQ MAXIMA::WXMAXIMALISPLOCATION
;             "/usr/share/maxima//branch_5_42_base_87_g40314b08c")
; 
; caught WARNING:
;   undefined variable: WXMAXIMALISPLOCATION
; 
; compilation unit finished
;   Undefined variable:
;     WXMAXIMALISPLOCATION
;   caught 1 WARNING condition
; in: PROGN (SETQ $WXPLOT_SIZE '((MLIST SIMP) 500 300))
;     (SETQ MAXIMA::$WXPLOT_SIZE '((MAXIMA::MLIST MAXIMA::SIMP) 500 300))
; 
; caught WARNING:
;   undefined variable: $WXPLOT_SIZE
; 
; compilation unit finished
;   Undefined variable:
;     $WXPLOT_SIZE
;   caught 1 WARNING condition
(%o1)                    wxplot2d(sin(x), [x, 0, 10])
<PROMPT-P/>(%i2) <PROMPT-S/>
```

**Comment by gunterkoenigsmann** [comment]
Looks good so far. A few warnings I don't know how to get rid of. Maxima compiles most functions needed in order to plot things. ...but the command wxplot2d() seems not to defined => I want to see the monster text at start-up.

Does plot without "wx" work? And does

     wxdraw2d(explicit(sin(x),x,1,10),grid=true);

create a plot? Somehow this sounds surrealistic, again.

**Comment by archbugaboo** [comment]
I cannot make it spit out that monster. I tried both reinstalling from the official repo, and manually compiling it, then issuing wxdraw2d(), wxplot2d(), wxbuild_info(), wxbug_report(), all give the same (latest) block of text. Commands without `wx` work, it's just that the formatting is no longer Latex, but similar to what the console Maxima would output:

```
(%i4)	f(x):=integrate(sin(x),x); f(exp(x));
(%o3)                    f(x) := integrate(sin(x), x)

                                          x

(%o4)                             - cos(%e )
```

**Comment by gunterkoenigsmann** [comment]
If the code that tells Maxima how to talk XML and how to draw inline graphs is never sent to maxima that would explain all of these problems. But - why is it never sent?

Do you have any experience using gdb or another debugger or using the wireshark?

In theory wxMaxima::SetupVariables() should send the whole lisp program to maxima...
...the line that does do that should read:   

     SendMaxima(wxmathml.GetCmd());

If you don't have any experience with a debugger: Could you add the following line before or after this command? 

    std::cerr<<"wxMathml.GetCmd() returns\""<<wxmathml.GetCmd()<<"\"\n";

This way we get the result of wxmathml.GetCmd() printed to the console if wxMaxima is started from a terminal:

**Comment by archbugaboo** [comment]
I have found the `SendMaxima()` line in `wxMaxima.cpp` at line 2689, then added the `std::cerr` line after it, compiled it as "Debug", but when run from the command line it only outputs:
```
wxMathml.GetCmd() returns":lisp-quiet 
"
```
at the program start and then nothing, not even for any `wx...()` command I throw at it. Then I added the `std:cerr` before `SendMaxima()`, and it was nothing different. The raw XML monitor hasn't changed, either. Does that `:lisp-quiet` command make them all quiet? Is there a way to make it, or force it to be verbose?

**Comment by archbugaboo** [comment]
By accident I touched `F1`. Normally, when the cursor is nowhere near text, or inbetween the cells, the html manual appears, through whatever default html browser exists, but now the normal Maxima help came up, as if I had explicitely used the Maxima help. The same happens when I directly use the `wxMaxima Help` from the Help menu, but if I try to run the Maxima help, an error appears: "could not find the help files, please check installation". This happens with both the locally compiled version and with the official repo version. Maybe it's a clue?

**Comment by gunterkoenigsmann** [comment]
That is a different issue. Normally for most linuxes maxima really comes without help files in a readable html format.

:lisp-quiet sends lisp commands to maxima and tells maxima not to output a new input prompt after executing them. If we don't send commands to maxima that explains why maxima doesn't understand the commands...
...which again looks like being a compiler bug.

**Comment by gunterkoenigsmann** [comment]
Perhaps we should somehow involve the wxMaxima packagers for ArchLinux: https://www.archlinux.org/packages/extra/x86_64/wxmaxima/

**Comment by archbugaboo** [comment]
I have opened a bug there, https://bugs.archlinux.org/task/61703 , and linked it here, to see the discussion.

**Comment by archbugaboo** [comment]
It looks like there is something wrong with my installation, I will search on my own to see what. If it is so, I apologize for the false alarms and for the time wasted. Unfortunately, very busy time comes for the next few months, so, if you want to close this or put on hold, so be it. In fact, even if it won't be my fault, I am sorry for the waste of time.

**Comment by gunterkoenigsmann** [comment]
With computers the weirdest things can happen.  So no complaints from my side in case the problem should be limited to one single computer.

**Comment by archbugaboo** [comment]
I'm sorry to bother you again, but would it be possible to show the configuration files, or switches, maybe possible Wx-related environment settings to that you are using (unless they're private)? I only used the ones in the `Compiling.md`, and it still fails. I asked first in the Archlinux bug page, but no answer after a week.

**Comment by gunterkoenigsmann** [comment]
What error messages do you get? The only problems I can think of would be that cmake is too old or that if wxWidgets 2.8 is installed along with wxWidgets 3.x cmake uses the version that was obsolete 7 years ago.

**Comment by archbugaboo** [comment]
I have both wxgtk2 and wxgtk3 installed, both versions 3.0.4-2, but just now I tried to remove wxgtk2 and it was linked to the gnuplot package. Still, I removed it, then I tried to reconfigure wxMaxima again, but it complained about not having any Wx installed (but wxgtk3 was still there). It looked like `wx-config` was needed, but was deleted by the removal of wxgtk2, so I made a symlink, configured OK, compiled OK, but I get the same errors as above, always complaining about `undefined variable: $WXMAXIMAVERSION` and simular `$WX...` variables. It's most probably related to the wxgtk packages and how they coexist. Do you also have them both? I presume yes, since wxMaxima uses gnuplot. If so, do you have special environment variables?

**Comment by gunterkoenigsmann** [comment]
wxgtk2 and wxgtk3 both should be OK, as long as their version is >= 3.0 - which is the case.

The current source should cause an assertation failure if the lisp code that teaches maxima how  wxdraw and 2d maths work isn't sent to maxima. 

That means...
...what if the code is sent to maxima and maxima has problems understanding it? Perhaps I have an additional idea but give me a few day's time.

**Comment by scx** [comment]
@archbugaboo 

You could try flatpak package:
 * wxWidgets/wxGTK 3.0 (Gtk+3): https://github.com/scx/wxmaxima-flatpak/tree/master
 * wxWidgets/wxGTK 3.0 (Gtk+2): https://github.com/scx/wxmaxima-flatpak/tree/wxgtk2
 * wxWidgets/wxGTK 3.1 (Gtk+3): https://github.com/scx/wxmaxima-flatpak/tree/wxwidgets-3.1

Personally, I would recommend the Gtk+2 version.

All variants use ECL (Embeddable Common-Lisp).

**Comment by archbugaboo** [comment]
Just a thought: Maxima, by itself, is working, wxgtk3 is also working for other programs that use it, so what if it's the lisp (sbcl) that doesnt understand, somehow, what those variables are? I mean, I can compile wxMaxima using wxgtk3, it starts OK, so maybe wxgtk3 isn't really the culprit? The raw XML also shows that commands like `:lisp-quiet (setq $wxmaximaversion "19.01.3")` fail with `undefined variable: MAXIMA::$WXMAXIMAVERSION`, but, obviously, the command is sent, but not able to be intepreted?

Anyway, I got the new sources, and now it starts with this assert error, maybe it helps? I am running it locally, from `./wxmaxima-local`, but, if needed, I can also install it.

```
ASSERT INFO:
/home/user/tmp/wxmaxima/src/wxMathml.cpp(56): assert "cmd.Length()>58000" failed in GetCmd(): Compiler-Bug? wxMathml.lisp is shorter than expected!

BACKTRACE:
[1] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[2] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[3] wxEvtHandler::TryHereOnly(wxEvent&)
[4] wxEvtHandler::ProcessEventLocally(wxEvent&)
[5] wxEvtHandler::ProcessEvent(wxEvent&)
[6] wxEvtHandler::ProcessPendingEvents()
[7] wxAppConsoleBase::ProcessPendingEvents()
[8] wxApp::DoIdle()
[9] g_main_context_dispatch
[10] g_main_loop_run
[11] gtk_main
[12] wxGUIEventLoop::DoRun()
[13] wxEventLoopBase::Run()
[14] wxAppConsoleBase::MainLoop()
[15] wxEntry(int&, wchar_t**)
[16] __libc_start_main
```

I had a hunch and I added this line: `std::cerr<<"cmd = "<<cmd.ToStdString()<<'\n';` (with the help of the doc for Wx) right before the assert, and it comes out empty. It looks like there's nothing sent to it. It also seems that the autocomplete (Ctrl+Space) is no longer working.

**Comment by archbugaboo** [comment]
I have just applied the patches and it works now! This is a HUGE "Thank you!" and just as large "I am sorry" for the trouble. Also, the raw XML now splurts that elusive big block of text right at the startup, everything works, all wx commands. Thank you very much, I was one tiny step to wiping and reinstalling.

**Comment by gunterkoenigsmann** [comment]
Thanks to you for doing all the debugging.

I have just made a new wxMaxima release so as soon as the ArchLinux maintainer picks up the new release the bug will be fixed.
