### ISSUE TITLE
Allocation of processor power

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1051]
Once in a while I load quite big data files from txt files with more than 500000 lines of data like this:
2018.11.01	00:00:11	nan	nan	nan	nan	0	0	1	0	0	6.60323	1.01613	41.2401	43.909	1	3
2018.11.01	00:00:12	nan	nan	nan	nan	0	0	1	0	0	6.60323	1.01613	41.2401	43.781	1	3

I use my own routine to load in the data as it is a combination of various data formats in a line of data 
(why does this line become bold?  -  I do not understand this Markdown formatting - it is quite annoying sorry)
----
read_data_as_text([rdargs]) := 
    block ([s,r,l,filename,dsep,mult:true,mix:false,
              whole:[],ln],
 
     filename : rdargs[1],
     
     if not stringp (filename) 
       then ( disp (" file name must be a Maxima string "),
              return (false)),
      
    if not file_search (filename) then
      (disp (" file not found "),return (false)),
      
    if length (rdargs) = 1 then mix : true
       else if length(rdargs) = 2 then dsep : rdargs[2]
       else if length (rdargs) = 3 then (dsep : rdargs[2], mult : rdargs[3])
       else (dsep : rdargs[2], mult : rdargs[3],whole : rdargs[4]),    
      
    s : openr (filename),
    r : [],
    ln : 0,
    
    while (l : readline(s)) # false do   /* original (l : read_line(s)) */
      (          
       if l # "" then
       ( ln : ln + 1,
          wxstatusbar("Reading line ", ln),
         /* replace tabs by spaces */
         l : ssubst (" ",ascii(9),l),  /* ascii(9) is tab char */
                if not lfreeof (whole,ln) then            
            r : cons (l,r)
         else if mix then                      
             r : cons (split(l), r)              
         else r : cons (split(l,dsep,mult), r))),
            
    close (s),
    reverse (r));
----
Maxima version:
wxMaxima version: 18.02.0.unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_41_base_525_gc4aa30a_dirty
Maxima build date: 2018-09-11 20:15:16
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on toshiba [192.168.43.206])
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxx/maxima/
Help dir: C:\maxima-current\wxMaxima/help
Maxima lisp dir: C:\maxima-current\bin/../share/maxima/branch_5_41_base_525_gc4aa30a_dirty

Running Windows 10
-----------

Now my question:
Loading these data files takes several hours
1) It does seem like Maxima only gets allocated a very limited processor time (I have 8 processor kernels) ?
2) If I leave the mouse pointer on top of the main toolbar in wxMaxima, the calculations goes faster ???

Any clue ?
Best regards
Rene'

**Comment by gunterkoenigsmann** [comment]
The MarkDown has cnverted arbitrary lines to captions for me, too.
---
1.) Maxima and wxMaxima can work on different CPUs and in parallel. But Maxima only uses one CPU, currently. Much of mathematics is essentially single-process only. though... If you want speed ask wxMaxima to ask a "-l clisp" to maxima's command-line arguments. And you can create a function out of your code that reads in the file and run it through the compile() command. The maxima manual contains sections about speeding up the code some more. And Windows redraws the entire status bar everytime you use wxStatusBar() so outputting an update only every thousandth line might speed up things faster. Also read_matrix() tends to be fast, but not verbose.

2.) In this case Windows doesn't need to remember what to draw if the mouse pointer leaves the current position and it doesn't need to think what object the mouse pointer hovers above for popup tooltips. I hope it is one of those....

**Comment by gunterkoenigsmann** [comment]
The fact that MarkDown printed the last line of my comment in fat wasn't intended...

**Comment by gunterkoenigsmann** [comment]
There was a discussion if maxima could be changed to use several processes at once a few weeks ago in the maxima-discuss mailing list. Using several processes at once would be nice, but would not work on MS Windows. Using threads instead would require big changes...

**Comment by gunterkoenigsmann** [comment]
Closing this issue as this (hopefully) mainly is a maxima issue.

What might help is using a maxima that was compiled with sbcl instead of with clisp: sbcl is faster by a hundred times, depending on the problem.
