### ISSUE TITLE
Trouble with Lisp comments after going to_lisp(); from maxima

### ISSUE THREAD

**Issue by oakleaflr** [wxMaxima-developers/wxmaxima#1052]
The output below seems to show that Lisp comments cause errors, while removing or converting them to maxima comments is ok.  Shouldn't Lisp comments pass through to clisp ok?

(%i4)	to_lisp();
Type (to-maxima) to restart, ($quit) to quit Maxima.
 -->	; example of dolist to iterate through a list
	
	; print each element of a list 
	(defvar L '(1 2 3 4))
	
	(dolist
	     ; variable to use for iterating through L
	     (x L)
	     ; expression to apply to each element (x) of L
	     (format t "x is ~A~%" x)
	);
Refusing to send cell to maxima: Un-closed parenthesis on encountering ; or $

MAXIMA>	(defvar L '(1 2 3 4))
	(dolist
	     (x L)
	     (format t "x is ~A~%" x)
	);
L

x is 1

x is 2

x is 3

x is 4

NIL

MAXIMA>	/*; example of dolist to iterate through a list
	
	; print each element of a list */
	(defvar L '(1 2 3 4))
	
	(dolist
	     /*; variable to use for iterating through L*/
	     (x L)
	     /*; expression to apply to each element (x) of L*/
	     (format t "x is ~A~%" x)
	);
L

x is 1

x is 2

x is 3

x is 4

NIL

**Comment by gunterkoenigsmann** [comment]
That will be a lot of work. But I will try to fix it.

**Comment by oakleaflr** [comment]
Gunter,

Thanks for your reply.  Fixing this problem will make wxMaxima a nicer
front-end to both Maxima and Common Lisp.  I certainly appreciate the work
that has gone in to making the program available and as error free as
possible.
Best wishes.

Larry Reed

**Comment by gunterkoenigsmann** [comment]
I am not sure if we need to disable more checks in lisp mode. Feel free to file bug reports if you find some.

**Comment by oakleaflr** [comment]
Gunter,

Is it possible to download the updated wxMaxima without also downloading
and installing Maxima?

Larry Reed

**Comment by gunterkoenigsmann** [comment]
There should be an installer that only installs wxMaxima, but not maxima at https://wolfgang.dautermann.at/maxima/wxmaxima-daily.exe
...but currently the build host is broken which means that the nightly builds are compiled manually and not every day => It will last at least another day until the changes will appear in the Nightly Builds.
