### ISSUE TITLE
Startup commands in Preferences automatically replace " to ” on macOS 10.14

### ISSUE THREAD

**Issue by rinodrops** [wxMaxima-developers/wxmaxima#1053]
``[Preferences...]`` menu item on wxMaxima 18.02 opens the configuration window. In the window, click to activate Startup commands tab. There're two text edit area for startup files: wxMaxima (above) and Maxima (below). After clicking on either area, double-quotation mark (``"``) automatically replaced by slightly different mark (``”``), and saved to the startup files. It surely breaks the startup file, so next time wxMaxima freezes on startup due to infinite loop for reading output from maxima.

It looks like the issue relating macOS's "Use smart quotes and dashes" feature, which can be found in System Preferences: Keyboard: Text section. Are there any way to ignore the functionality on wxMaxima regardless the settings?

Environment: macOS 10.14, MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by gunterkoenigsmann** [comment]
Fixing this bug unfortunately only is possible for the two most recent development versions of wxWidgets.
