### ISSUE TITLE
horizontal cursor isn't cleared on horizontal scrolling

### ISSUE THREAD

**Issue by Murmele** [wxMaxima-developers/wxmaxima#1054]
When using the latest master at execute the complete file, the drawings of the equations are not correct ( See attached screenshot). When using the latest official version, wxmaxima is not usable, because it freezes the screen. With the latest master it's a bit better, but it lags extremely.

I'm using Antergos linux with gnomeshell 3.30

wxWidgets: 3.0.4
Unicode Unterstützung: ja
Maxima Version: 5.42.1 (x86_64-unknown-linux-gnu)
Lisp: SBCL 1.4.13

[TaylorreiheC_tilde_dot.zip](https://github.com/wxMaxima-developers/wxmaxima/files/2595229/TaylorreiheC_tilde_dot.zip)

![bildschirmfoto von 2018-11-19 13-17-10](https://user-images.githubusercontent.com/10099533/48706862-d0f88000-ebfd-11e8-8099-3cfa7e85a95a.png)

**Comment by gunterkoenigsmann** [comment]
Looks the same on my computer. My current guess is that the equation is long enough to Trigger an integer overflow in Gtk. But I will find out even if this kind of issue often needs much time.

**Comment by gunterkoenigsmann** [comment]
One question: Do you happen to know that this worked better in old wxMaxima versions?

**Comment by gunterkoenigsmann** [comment]
Created the branch MajorSpeedUp for working on this issue.

**Comment by gunterkoenigsmann** [comment]
Ok... ...works now - and scrolling in the equations now is fast - after calculating all the line breaks finally is over, that is. Not that calculating line breaks in matrices does make sense => feel free to file another bug report about that.

**Comment by Murmele** [comment]
wow cool. It is so fast now. Thanks!!
If you scroll sidewards with the touchpad or so. The cursor jumps from the left side to the right side. If you scroll really fast, the complete row is full of cursors, see attached image
![bildschirmfoto von 2018-11-20 20-41-38](https://user-images.githubusercontent.com/10099533/48799018-63844680-ed06-11e8-8b9d-eb941db9c39c.png)

**Comment by Murmele** [comment]
Yes this is fine. So they don't disturb.
