### ISSUE TITLE
[windows][frozen] wxMaxima cannot handle sarag test batch

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [wxMaxima-developers/wxmaxima#1055]
Hi,

I have no problem to run:
load(sarag);
batch("rtest_arag.mac",test)

under XMaxima and text-based Maxima but it won't run under wxMaxima: it freezes.

    Fabrizio

**Comment by gunterkoenigsmann** [comment]
Thanks for reporting this issue! It should be resolved in the current nightly build at https://dautermann.at.

wxMaxima will still stop redrawing the worksheet while maxima is outputting data faster than the line heights and widths can be recalculated. But after all the data from maxima is processed it should be quite fast again.
