### ISSUE TITLE
wxMaxima: PDF output, premature linebreaks

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1059]
I have downloaded wxMaxima nightly build (2018-11-27). Printing to PDF now works - thank you, but I noticed one small problem in comparison with the previous version (nightly build from 2018-08): the long lines tend to break too early.

Please compare the CORRECT output from previous version (wxMaxima nightly build 2018-08):
![wxmaxima_16-4-x_unofficial](https://user-images.githubusercontent.com/22853864/49076931-6ae1ad80-f23a-11e8-9c6e-920babc6dfe5.png)

And the WRONG output from recent version (wxMaxima nightly build 2018-11-27) - premature linebreaks appear in outputs (%o2) and (%o5):
![wxmaxima_18-11-2_unofficial](https://user-images.githubusercontent.com/22853864/49077011-98c6f200-f23a-11e8-9676-9bb803b116bf.png)

Version of my programs: Windows 7 Professional EN, PDF creator Free v.3.2.0, Maxima: 5.41.0a_dirty, wxMaxima 18.11.2-unofficial.

**Comment by gunterkoenigsmann** [comment]
Should be resolved in the next nighty build.

**Comment by mirekslouf** [comment]
Thanks a lot for your fast response, Mirek
