### ISSUE TITLE
number 2 does not type, but the shift 2 does give the @ symbol.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1060]
The number 2 on the number pad works, but the 2 on the main keyboard does not work.
All other numbers are OK.  My keys are OK.   They all work running windows 10.

I will try a newer version to see if the bug is gone.

The build info is below.

-->	wxbuild_info()$
wxMaxima version: 18.10.0.unofficial

using wxWidgets version: wxWidgets 3.1.0

Maxima version: branch_5_42_base_156_g5114247_dirty

Maxima build date: 2018-11-21 22:07:40

Host type: x86_64-w64-mingw32

System type: Win32 10.0.17134 X86-64

Lisp implementation type: SBCL

Lisp implementation version: 1.4.2

wxMaxima's idea of the directory layout is:

User configuration dir: C:\Users\Richard/maxima/

Help dir: C:\maxima-current\wxMaxima/help

Maxima lisp dir: C:\maxima-current\bin/../share/maxima/branch_5_42_base_156_g5114247_dirty

**Comment by richardgobeli** [comment]
The version from 11/28/2018 does work.  I am able to enter the number 2 from the main keyboard keys.

**Comment by gunterkoenigsmann** [comment]
I had done two things: I taught events like changing the font or window width to automatically trigger a recalculation of all cell sizes. Also I have told the recalculation logic to only recalculate the text if the font or font size has changed. But I forgot to tell that keeping the window size at the old value is no change.

**Comment by richardgobeli** [comment]
When I load a wxmx file, the saved lines look OK until I click the mouse on a line.
The clicked mouse causes rewriting of the lines inputs and outputs, but to a different position below the actual position.  It becomes unreadable.  If I execute the whole file, everything is OK.   The above rewriting does not happen anymore.

I have noticed that when I scroll up to a new position at least a page higher, a line maybe skewed sideways across the middle of the line sometimes.
As soon as I click the mouse to move the cursor or move the mouse outside of the execution window, the line is then OK.  

It is not a big deal, but I would like to tell you anyway.

**Comment by richardgobeli** [comment]
![snipimage](https://user-images.githubusercontent.com/31253976/49335438-082e4000-f5b3-11e8-8991-bf8d87eca918.png)
You can see the diff function is screwed.  I did a print screen to clipboard without moving the mouse.
I can't seem to repeat the other garbage screen to get a snap shot.

**Comment by gunterkoenigsmann** [comment]
Today's nightly build should no more show this behavior: I merged all functions that determine the horizontal position of the input cell into one so the different instances that calculate it cannot disagree with each other.
