### ISSUE TITLE
wxMaxima, PDF output, too small font

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1062]
Current nighly-build of wxMaxima (downloaded 2018-12-01) in my computer (Windows 7, Maxima version: 5.41.0a_dirty) shows too small font in PDF output:

Please, compare the following two files:

* wxMaxima file printed to PDF (font Consolas 12, page A4, margins ca 1cm): 
[if-then-else_linebreaks.wxmx.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/2635866/if-then-else_linebreaks.wxmx.pdf)
* MSWord file printed to PDF (font Concolas 12, page A4, margins exactly 1cm):
[msword_consolas12_one-line.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/2635869/msword_consolas12_one-line.pdf)

In the MSWord file printed to PDF, the font size in PDF is Ok and the first line exactly matches page witdh.
In the wxMaxima file printed to PDF, the font size is substantially lower and (exactly the same) first line occupies ca 2/3 of the page width.

**Comment by gunterkoenigsmann** [comment]
Today's nightly build contains a workaround. But I am not sure if it works...

**Comment by mirekslouf** [comment]
Downloaded, checked, font size is Ok - thank you.
BUT the linebreaks are wrong again (i.e. the longer output lines show premature linebreaks).
Moreover, the broken lines have wrong alignment (too much to the right, not just below the upper lines):
![if-then-else_linebreaks_2 wxmx](https://user-images.githubusercontent.com/22853864/49586324-22746f00-f961-11e8-99f5-2aacff6f595b.png)
The problem with wrong alignment has already been reported in issue #1064
