### ISSUE TITLE
wxMaxima, wrong alignent of output from [for-cycles]

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1064]
Current nighly-build of wxMaxima (downloaded 2018-12-01) in my computer (Windows 7, Maxima version: 5.41.0a_dirty) shows wrong alignment of the output from [for-cycle]:

* Formatting error description: the first line is aligned entirely to the left, the following lines are indented.
* The error occurs both in WXMX files and PDF-printed file.
* Please, see an example in the attachment: [test_for-cycle.wxmx.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/2635874/test_for-cycle.wxmx.pdf)

**Comment by gunterkoenigsmann** [comment]
You might be interested in wxMaxima's

      table_form()

command; A minimal example for this bug would be:

       printf(true,"qwe");

Will find out its cause.

**Comment by gunterkoenigsmann** [comment]
The indentation option that reverts indentation to the old behavior is named "Indent cells by the label width".
