### ISSUE TITLE
different result for Greek letter

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#1065]
The result of a calculation leads to a different result if a Latin letter is substituted by a Greek letter.

In order to reproduce the problem please use the attached file and run all.

Daniel
[uncanny.zip](https://github.com/wxMaxima-developers/wxmaxima/files/2636232/uncanny.zip)

**Comment by danielvolinski** [comment]
Hi Gunter,

I've reduce the function "fseriesrec1" to show the same problem.
Please notice both lst and lst2 list are different in both cases.

Daniel
[uncanny2.zip](https://github.com/wxMaxima-developers/wxmaxima/files/2636779/uncanny2.zip)

**Comment by gunterkoenigsmann** [comment]
This looks like you are narrowing down the problem.
My guess is that exactly one of maxima's functions is affected and we need to find out which one.

**Comment by danielvolinski** [comment]
I don't think is a problem with the usage of Greek characters.
It seems to me this algorithm, "fseriesrec1", is order dependent.
If you expand each one of the equations you will see they are shown in different order and this apparently confuses the algorithm.
Daniel

**Comment by danielvolinski** [comment]
Barton Willis sent the following response to Dimiter and me regarding the subject, what do you think?

My guess is that this bug is due to the way wxMaxima encodes non-roman characters, not a bug in fseriesrec1.

In wxMaxima, I used the platelet thingy to enter epsilon 

  (%i1)    ε-e;
  (%o1)    ε-e

  (%i2)    ?print(%);
  ((MPLUS SIMP) ((MTIMES SIMP) -1 $E) $Ε) 

  (%o2)    ε-e

I'm not sure of the magic that prevents Maxima from simplifying this to zero, but it's  a debugging nightmare and an accident waiting to happen. 

--Barton

**Comment by gunterkoenigsmann** [comment]
This rather looks like an error in

     ?print

wxMaxima sends UTF8 chars to maxima. And maxima is either configured to interpret every byte which has the most significant bit set as an ordinary letter in (In UTF8 all bytes a non-ASCII chars is comprised of have the most significant bit set). Or it is configured to understand unicode and treats every character which is non-ASCII to be an ordinary char. In each of these two possibilities variable names can contain unicode chars, if they want to.

But I had the impression, too that there are places in which using unicode for variable names makes a difference. The places I can imagine that might happen is is:

- Perhaps one function only accepts variable names with a length of only a single character. 
- Or the result of some function depends on the alphabetic order of its input. Unicode comes after the "z".
- The case inversion that converts "e" to "$E"
- Or one function for some reason needs to count the number of letters a variable name is long - and counts the number of bytes instead.

Perhaps we one day will find an example that is minimal enough to allow to find out if any of these assumptions is true.

**Comment by richardgobeli** [comment]
I type the letter epsilon where the greek ε was.  It seems to be a different letter, because it prints in a smaller font.  The equation with epsilon does calculate the same result as the e.
![image](https://user-images.githubusercontent.com/31253976/49925649-2c293580-fe7f-11e8-8d63-00da13f41a06.png)
this it from the greek letter symbols.
![image](https://user-images.githubusercontent.com/31253976/49925744-67c3ff80-fe7f-11e8-8d17-8dced1a57250.png)

**Comment by danielvolinski** [comment]
Mathematically the equations are the same but I get **different** results depending on whether I write the Greek letter epsilon or the name of the Greek letter epsilon, causing a different order in the equation. Is this a bug in Maxima or is the algorithm order dependent? 

Daniel

**Comment by richardgobeli** [comment]
If you type 
![image](https://user-images.githubusercontent.com/31253976/50453435-2c591480-0906-11e9-9b13-dc04cdadc961.png)
then
![image](https://user-images.githubusercontent.com/31253976/50453447-3ed34e00-0906-11e9-937c-310b31e7ac5c.png)

it puts the epsilon in front of the t^4 in the original lisp expression.  wxmaxima still displays it the same.
![image](https://user-images.githubusercontent.com/31253976/50453461-4c88d380-0906-11e9-8406-462a64d35a5e.png)
![image](https://user-images.githubusercontent.com/31253976/50453464-53afe180-0906-11e9-99f9-e8d55c71b234.png)
the answers is the same as with the letter e.
This is the lisp order with letter e.
![image](https://user-images.githubusercontent.com/31253976/50453564-0c762080-0907-11e9-8277-e8e954c54852.png)

this is with no ordering on epsilon.
![image](https://user-images.githubusercontent.com/31253976/50453598-4b0bdb00-0907-11e9-9de5-6d62f54097bd.png)

**Comment by gunterkoenigsmann** [comment]
Seems like this is the old problem that maxima sometimes gives different results depending on the sort order of the variable names: If you replace the greek epsilon by a z you'll still get wrong result (with the epsilon replaced by a z, obviously).
