### ISSUE TITLE
wxMaxima, text cells hide graphs after recalculation

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1066]
In the recent nightly build of wxMaxima (downloaded 2018-12-06) the text cells sometimes appear over the graphs as shown in the PrintScreen below. After minimizing and maximixing the window the text cell usually appears in the correct place below the graph, after recalculation [Ctrl+R] it is usually wrong again.

![text_over_graphs](https://user-images.githubusercontent.com/22853864/49583482-a544fc00-f958-11e8-88df-1ac349d426e7.png)

Version of my programs: Windows 10 Pro, Maxima: 5.41.0a_dirty, wxMaxima 18.11.14-unofficial)

**Comment by mirekslouf** [comment]
It seems that this error occurs as follows:
* when I am typing the first command (%1) - everything is Ok
* when I am typing the second command (%2) - the graphs is on screen - everything Ok
* when I recalculate the WXMX file (Ctrl+R) - the graph disappears for a while, and the text cell is shifted above (at the place where the graph used to be) and remains there even after the graph is redrawn
* when I minimize and maximize wxMaxima window, the outputs are correct again

**Comment by gunterkoenigsmann** [comment]
Wow... ...Now I can reproduce it.

Will find out what causes this problem. But give me a few days' time.

**Comment by gunterkoenigsmann** [comment]
Ok... ...should work in the next nightly build: I had forgotten to invalidated the cached cell size data on appending math cells. Thanks for reporting this bug!
