### ISSUE TITLE
wxMaxima, prepature linebreaks in PDF (again)

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1067]
Firstly, thank you for all previous improvements and corrections of my submitted issues. I really appreciate this.

Nevertheless, after all those corrections there is still one strange behavior, which tends to re-appear in various nighly-builds of wxMaxima: long lines tend to break too early when printing WXMX file to PDF. See outputs (%o2) and (%o5) - the input lines are Ok, but the output lines are broken in ca 2/3 of the page width. Also the text cell (the very first line) tends to break a little bit earlier than necessary.

![test1_linebreaks wxmx pdf](https://user-images.githubusercontent.com/22853864/49695662-a2d3e380-fb9e-11e8-8e38-1a523708e237.png)

In wxMaxima windows the output lines are Ok. In previous versions of wxMaxima this problem did not exist. The long lines simply did not break at all in PDF output. This was, in my opinion, better than current behavior, because I could break the lines manually. If it is difficult, for any reason, to determine the output line lenght, could you restore the previous behavior (i.e. no linebreaks, so that user can do this manually)?

I understand that this is a minor issue, but it is quite important for me: I am using wxMaxima calculations (in the form of PDF files)  in my lectures and if the output is wrong, it looks strange.

Version of my programs: Windows 7, Maxima: 5.41.0a_dirty, wxMaxima 18.11.14-unofficial, nightly build 2018-12-08.

**Comment by gunterkoenigsmann** [comment]
Found the 2nd issue: The 1st line of the output begins with a label that isn't indented but the linebreak logic still indents it.

**Comment by mirekslouf** [comment]
Any progress? Or should I perform some other tests?
(it seems that the recent nightly-build still does not resolve this issue)

**Comment by gunterkoenigsmann** [comment]
I was convinced that the issue no more occurs  => Will look into it in the next few days.

**Comment by mirekslouf** [comment]
Downloaded recent nightly build of wxMaxima, the resulting output is better, but still not 100% correct. Please, look at the PrintScreen below:
* the first five cells (text cells) should all fit into one line, but the linebreaks occur earlier than necessary
* moreover, the linebreaks appear later on longer lines and earlier on shorter lines - strange
* the last two cells (math cells) seem to be Ok at the moment

![test1_linebreaks_3 wxmx pdf](https://user-images.githubusercontent.com/22853864/51765321-b0561600-20d7-11e9-9f0b-40dc607dccde.png)
