### ISSUE TITLE
Can't copy cells in the latest nightly build

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1069]
Copying some selected test/commands goes ok but if I try to copy a cell (even before running Maxima) wxMaxima closes with the current error:
----------------
File 'C:Users\xxxxx\AppData\Local\Temp\wxm931C.tmp' couldn't be removed (error 32: the process cannot access the file because it is being used by another process.)
----------------
wxMaxima version: 18.11.4-unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_42_base_238_g1a02d7e18
Maxima build date: 2018-12-09 23:41:59
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on GPERSR7117 [10.12.201.245])
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxxxx/maxima/
Help dir: C:\maxima-current\wxMaxima/help
Maxima lisp dir: C:\maxima-current\bin/../share/maxima/branch_5_42_base_238_g1a02d7e18

**Comment by gunterkoenigsmann** [comment]
Copying content in some formats (namely emf and SVG) requires a temp file.
On Windows a virus scanner can prevent files from being deleted until they have been scanned.

Until I have time to disable the error you can unselect using the two formats by default in wxMaxima's config dialogue.

**Comment by ReneSci** [comment]
Thanks a lot - it works. Also with the latest build.
Please tell if I should do some test (however I am quite busy the next tree days)

Another curio that has been around for some time (sorry for not reporting): If wxMaxima has been running on the PC before installing a new Maxima/wxMaxima - all the *.ttf - fonts can not bee installed - you have to press "skip" to each one during the installation. However after a fresh restart of the PC - the installation goes just fine. This is even though I start the installer as an administrator.

**Comment by gunterkoenigsmann** [comment]
Both things you have reported are conceptual bugs in MS Windows:

- Every application can register its own private fonts. That are shared between all applications until the reboot after unregistering the fonts (Yuck!) and that (at least in Windows 7) are rendered using kernel privilleges - which would be an easy way to compromise the whole system using a bunch of document formats: Just package a crafted font with a flash animation/a webpage/a word document/a pdf document. ...if you want to earn money using a bug bounty feel free to craft a working example ;-) (but don't be too angry if things aren't really as bad as they looked to me).
- and as long as the virus scanner is still reading a file one cannot mark this file as "to be deleted once it has been closed in all applications currently accessing the file". Which means that you will sooner or later experience missing images/images swapping space in PowerPoint or MS Word as well as some of your text edits not being saved: All components of a MS Office savefile are saved in individual files that can only be packaged in the final file if they can be moved (aka that aren't currently scanned by the virus scanner).

The font workaround unfortunately only is available on wxWidgets 3.1.1 and later. The rest should now being worked around in wxMaxima. But MS Office still will sometimes produce broken files with your virus scanner configuration.
