### ISSUE TITLE
Missing update of the workbook during cell evluation

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1070]
When evaluating a cell, which has other cells below it, the output from this evaluation does not appear/become visible before the user collapses and reopens that cell. Foe example wxdraw2d()

Also when evaluating a cell which gives many separate outputs e.g. a list of files. The cursor moves downwards on top of the cells below but the filenames are not inserted in the worksheet during the evaluation.

To reproduce:
use menu "help/Build Info" - goes ok. Then place the cursor above this cell i.e. on top of the worksheet, and press "help/Bug Report" - the responses is then not visible.
----------------------------------

wxMaxima version: 18.11.4-unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_42_base_238_g1a02d7e18
Maxima build date: 2018-12-09 23:41:59
Host type: x86_64-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on GPERSR7117 [10.12.201.245])
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxxxxxx/maxima/
Help dir: C:\maxima-current\wxMaxima/help
Maxima lisp dir: C:\maxima-current\bin/../share/maxima/branch_5_42_base_238_g1a02d7e18

**Comment by gunterkoenigsmann** [comment]
That might be the key to #1066. Thanks a lot!

Am still unsure, though, what causes this: Adding an "recalculate" doesn't help. ...and #1066 seems to indicate that it is always the last item of a cell that gets lost...
