### ISSUE TITLE
Version string

### ISSUE THREAD

**Issue by scx** [wxMaxima-developers/wxmaxima#1075]
Although I understand the need for proper marking of nightly builds, I am sure that stable releases shouldn't have the `-unofficial` postfix in the version string.
https://github.com/wxMaxima-developers/wxmaxima/blob/626c38c697e40b7479bd226ebb2b8ba26ba0e7d0/CMakeLists.txt#L2
https://github.com/wxMaxima-developers/wxmaxima/tree/Version-18.12.0
https://github.com/wxMaxima-developers/wxmaxima/releases/tag/Version-18.12.0

See also:
https://github.com/wxMaxima-developers/wxmaxima/commit/29d31396395623862359aa9e6f57fd7ccab13771#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by gunterkoenigsmann** [comment]
Here we want to get three things right, in retrospect: "git describe" should produce the right version string, cmake and the . desktop file should contain it. Hope I find the Right Way to do that the next time.

**Comment by gunterkoenigsmann** [comment]
I've sent you an invitation as a collaborator to wxMaxima. If you accept it you'll have write access to the git repo.

**Comment by gunterkoenigsmann** [comment]
Will definitely write such a checklist.
