### ISSUE TITLE
cmake code picks up the wrong version of wxWidgets on Slackware

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1078]
On Slackware, both 2.8 and 3.0 series of wxWidgets packages may co-exist.

So ccmake on its 1st run pre-fills two config options with the 2.8 variants, namely _filename and wxWidgets_CONFIG_EXECUTABLE. So the build fails mid-way.

On 64-bit Slackware, these options have to be (manually) filled like this:

_filename                        /usr/include/wx-3.0/wx/version.h
wxWidgets_CONFIG_EXECUTABLE      /usr/lib64/wx/config/gtk2-unicode-3.0

**Comment by daute** [comment]
Hi,
you can set the environment variable `WX_CONFIG` to the "right" wx-config program, then it should find the correct libraries and include files.
(CMake >= 3.11 is required for that).

Best regards, Wolfgang

**Comment by daute** [comment]
wxWidgets 3 is required since wxMaxima 15.04.0 (according to the changelog). With commit [4549104f80ffe68bf8d979f0037c4db39f0d668f]. CMake will produce an error message, if wxWidgets < 3 is used.

**Comment by yurytch** [comment]
Where did my post go? Commit [4549104] (in fact, today's master) produces the attached errmsg (so, it requires 3, but is still picking 2.8 on mixed-wx-versions system).

I guess the 2.8 would still be there for a while, so I suggest changing the search path for pre-filling wxWidgets_CONFIG_EXECUTABLE variable to something like /usr/lib64/wx/config/gtk2-unicode-3.0:/usr/lib/wx/config/gtk2-unicode-3.0.

---
 CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
   Could NOT find wxWidgets: Found unsuitable version "2.8.12", but required
   is at least "3" (found
 -L/usr/lib64;-pthread;;;-L/usr/X11R6/lib64;;;-lwx_gtk2u_richtext-2.8;-lwx_gtk2u_aui-2.8;-lwx_gtk2u_xrc-2.8;-lwx_gtk2u_qa-2.8;-lwx_gt
 k2u_html-2.8;-lwx_gtk2u_adv-2.8;-lwx_gtk2u_core-2.8;-lwx_baseu_xml-2.8;-lwx_baseu_net-2.8;-lwx_baseu-2.8)
 Call Stack (most recent call first):
   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
   /usr/share/cmake-3.5/Modules/FindwxWidgets.cmake:887 (find_package_handle_standard_args)
   src/CMakeLists.txt:1 (find_package)

**Comment by gunterkoenigsmann** [comment]
wxwidgets 3.0 has replaced 2.8 5 years ago. I always wonder why Ubuntu distributions try to sell outdated software as the "stable alternative". 
Unfortunately I am not sure if this problem can be solved from the wxWidgets side or if it has to be addressed in cmake or in slackware: What I was waiting for was an idea on how to make cmake pick up the newest wxWidgets version without breaking support for wxWidgets 3.1/3.2 and support for platforms where wxWidgets lies in a different place than in Slackware.

**Comment by yurytch** [comment]
> wxwidgets 3.0 has replaced 2.8 5 years ago. I always wonder why Ubuntu distributions try to sell outdated software as the "stable alternative".

Because there's usable software using 2.8?.. I might just remember a package or two, scientific I think, (authors of) which didn't manage to transit to 3.0; and 3.1 was incompatible with 3.0, I believe?

> Unfortunately I am not sure if this problem can be solved from the wxWidgets side or if it has to be addressed in cmake or in slackware

There's no rush. I know how to fix it for me, and just posted this for the workaround to be accessible to everyone.

**Comment by yurytch** [comment]
> wxwidgets 3.0 has replaced 2.8 5 years ago. I always wonder why Ubuntu distributions try to sell outdated software as the "stable alternative".

Because there's usable software using 2.8?.. I might just remember a package or two, scientific I think, (authors of) which didn't manage to transit to 3.0; and 3.1 was incompatible with 3.0, I believe?

> Unfortunately I am not sure if this problem can be solved from the wxWidgets side or if it has to be addressed in cmake or in slackware

There's no rush. I know how to fix it for me, and posted this mostly for the workaround to be accessible to everyone.

**Comment by KubaO** [comment]
We can't really add all sorts of platform-build-related workarounds to core wxMaxima, since this would require significant maintenance effort and/or highly automated tests that can run on such platforms. It's a manpower issue at the moment.

1. If this is a problem with Slackware package, then the packagers should address it.

2. If this is a problem with user self-building on Slackware, then it's on the user to provide the wxWidgets path to the `cmake` command. 

  The following snippet from our [.appveyor.yml](../blob/master/.appveyor.yml) might provide insight into how to work around a FindwxWidgets.cmake bug that makes this less-than-obvious:

      # WX_ROOT_DIR is a workaround for a nasty bug in FindwxWidgets. Without it, the value
      # of wxWidgets_LIB_DIR gets cleared (!) in FindwxWidgets.cmake(495)
      # cmake issue report: https://gitlab.kitware.com/cmake/cmake/-/issues/19176
      cmake -G "$env:CMAKEGEN" --config Release  `
        -DAPPVEYOR_BUILD=1 -DCMAKE_UNITY_BUILD=YES  `
        -DWX_ROOT_DIR="$INSTALL_DIR"  `
        -DwxWidgets_ROOT_DIR="$INSTALL_DIR"  `
        -DwxWidgets_LIB_DIR="$INSTALL_LIB_DIR"  `
        -DwxWidgets_CONFIGURATION=mswu  `
        $env:TOOLKIT_CMAKE_ARGS ..

That's all we can do with this at the moment, I'm afraid.
