### ISSUE TITLE
Premature linebreaks in print output on Windows

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1082]
This is connected with closed issue #1067:
* the linebreaks in PDF output were improved, but they are still not 100% correct

Please look at my last comment in the closed issue #1067. It is copy+pasted also here:

I have downloaded recent nightly build of wxMaxima, the resulting output (wxMaxima -> Print -> PDFCreator) is better, but still not 100% correct. Please, look at the PrintScreen below:

* the first five cells (text cells) should all fit into one line, but the linebreaks occur earlier than necessary
* moreover, the linebreaks appear later on longer lines and earlier on shorter lines - strange
* the last two cells (math cells) seem to be Ok at the moment

![test1_linebreaks_3 wxmx pdf](https://user-images.githubusercontent.com/22853864/51765771-ff507b00-20d8-11e9-8351-c0831cc2fe01.png)

**Comment by gunterkoenigsmann** [comment]
That looks like a valuable observation. Thanks a lot!
...and the problem seems to only affect the first line of an multi-line equation. But still I seem to be missing the last piece of the puzzle...

**Comment by gunterkoenigsmann** [comment]
I have managed to make the problem no more appear everywhere. But I ab still searching the reason why it happens...

**Comment by KubaO** [comment]
This unfortunately still happens on master on Windows 10. It's a bug, but I don't know what level of effort is required to fix, and thus am not assigning milestones for ti.

**Comment by KubaO** [comment]
@gunterkoenigsmann Could you check if this also happens on Linux?
