### ISSUE TITLE
Small toolbar icons and text on High DPI display

### ISSUE THREAD

**Issue by PJSingh5000** [wxMaxima-developers/wxmaxima#1085]
I am running wxMaxima on Ubuntu 18.10.

The font size in the section labels "Mathematical Symbols", " Greek Leters", "Table of Contents" is very small.

Also, the icons in the tool bar are very tiny.

Please see the screen shot below.

Issue #605 from 2016 indicates this was fixed.

Is this still an issue for Ubuntu? Do I need a newer version of wxMaxima?

![screenshot from 2019-02-01 19-00-48](https://user-images.githubusercontent.com/19394936/52156053-efdeae00-2653-11e9-866c-9742a149054d.png)

**Comment by PJSingh5000** [comment]
I tried 19.01.1 from the nightly builds (https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies?field.series_filter=cosmic), and the same issue is present.

**Comment by gunterkoenigsmann** [comment]
The size of the title lines of the sidebars cannot be controlled by the application => I guess that needs to be resolved in wxWidgets and as Ubuntu uses 3.0.0 and 3.1.2 (the current development version) claims to contain big improvements for High-DPI displays probably all we need to do here is to wait.

But the toolbar icons I will look at.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I think I have found the toolbar issue: I provided wxWidgets with icons of the right size. But If I tell wxWidgets to save the toolbar state on closing wxMaxima it saves the toolbar size *and* the information that the toolbar cannot be resized. Which is half-true: It cannot be resized by the user. But it can be resized by wxWidgets => I've modified the code not to load the toolbar state, but only the info if the toolbar is active.

If that still didn't resolve this issue please protest.

**Comment by gunterkoenigsmann** [comment]
Cool! Thanks in advance!

Testers are always important.

**Comment by PJSingh5000** [comment]
Hummm.

I just compiled commit 07610ae on Ubuntu 18.10, and the icons are still tiny.

I did delete the `~/.wxMaxima` configuration file, in case an old setting was preventing the icons from resizing.

I saw some references to "`dock_size`" in the `~/.wxMaxima` file. Could the dock size influence the height of the toolbar, and restrict the icons to a certain size?

**Comment by gunterkoenigsmann** [comment]
Good idea. Does the dock_size of the toolbar start with "dock_size(1" on your computer, too?

Additionally I will add code that tells wxMaxima's debug sidebar what wxWidgets tells wxMaxima what the resolution of your display is.

**Comment by PJSingh5000** [comment]
There are four references to `dock_size` at the end of my `~/.wxMaxima` file.
Only the last reference to `dock_size` begins with "`dock_size(1`"...

```
$ cat .wxMaxima | grep dock_size
perspective=layout2|name=console;caption=;state=508;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=100;besth=100;minw=100;minh=100;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=history;caption=History;state=18876414;dir=2;layer=0;row=0;pos=0;prop=100000;bestw=104;besth=175;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=structure;caption=Table of Contents;state=18876412;dir=2;layer=0;row=0;pos=0;prop=100000;bestw=952;besth=417;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=XmlInspector;caption=Raw XML monitor;state=18876414;dir=2;layer=0;row=0;pos=0;prop=100000;bestw=8;besth=8;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=stats;caption=Statistics;state=18876414;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=376;besth=668;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=greek;caption=Greek Letters;state=18876412;dir=4;layer=0;row=0;pos=2;prop=100000;bestw=196;besth=252;minw=196;minh=252;maxw=196;maxh=252;floatx=-1;floaty=-1;floatw=196;floath=252|name=log;caption=Debug Messages;state=18876414;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=384;besth=216;minw=384;minh=216;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=384;floath=216|name=symbols;caption=Mathematical Symbols;state=18876412;dir=4;layer=0;row=0;pos=1;prop=100000;bestw=254;besth=331;minw=254;minh=331;maxw=254;maxh=331;floatx=-1;floaty=-1;floatw=254;floath=331|name=math;caption=General Math;state=18876414;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=368;besth=486;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=format;caption=Insert;state=18876414;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=400;besth=270;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=draw;caption=Plot using Draw;state=18876412;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=254;besth=331;minw=254;minh=331;maxw=254;maxh=331;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=toolbar;caption=;state=2106096;dir=1;layer=10;row=1;pos=0;prop=100000;bestw=1153;besth=52;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=100|dock_size(2,0,0)=864|dock_size(4,0,0)=256|dock_size(1,10,1)=58|

```

**Comment by PJSingh5000** [comment]
I really appreciate the extensive work you've put into this.
However, I still get very tiny icons in the toolbar.

I compiled commit ea21ee7 on Ubuntu 18.10.

I noticed that, if I edit `~/.wxMaxima` and change `dock_size(1,10,1)=58|` to something else like `dock_size(1,10,1)=116|`, before launching wxMaxima, this value always reverts back to `dock_size(1,10,1)=58|`.

In the image below, I've included a portion of the Firefox browser window to give a sense of scale.

![screenshot from 2019-02-04 21-23-06](https://user-images.githubusercontent.com/19394936/52249904-62a19080-28c3-11e9-9f07-fa25f6dc464b.png)

**Comment by gunterkoenigsmann** [comment]
If you enable the "view/debug messages" sidebar one of the first messages should tell us which resolution wxWidgets believes your screen to have. Not that this value is wrong...

**Comment by gunterkoenigsmann** [comment]
The bad news is: determining the right doing number might still be a work-in-progress: https://groups.google.com/forum/m/#!topic/wx-users/fERSXdpVwAI
But at least it is a problem which is beung actually worked on.

**Comment by PJSingh5000** [comment]
My system confusingly says 96 dpi or 192 dpi, depending on the tool used...

```
$ grep DPI /var/log/Xorg.0.log
[   151.424] (==) FBDEV(0): DPI set to (96, 96)

$ xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    3840x2160 pixels (1016x572 millimeters)
  resolution:    96x96 dots per inch

$ xrdb -query | grep dpi
Xft.dpi:	192
```



The wxDebug debug sidebar shows 96 PPI...
 
```
06:37:05 PM: Display resolution according to wxWidgets: 96 x 95 ppi
06:37:05 PM: Starting server on port 4010
06:37:05 PM: Starting server failed
06:37:05 PM: Starting server on port 4011
06:37:05 PM: Server started
06:37:05 PM: Running maxima as: "maxima"  -s 4011 
06:37:05 PM: Connected.
06:37:05 PM: Sending maxima the info how to express 2d maths as XML
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Switching to lisp mode for one line!
06:37:05 PM: Received 274 chars from maxima.
06:37:05 PM: Received maxima's first prompt: pid=5590↲Maxima 5.41.0 http://maxima.sourceforge.net↲using Lisp GNU Common Lisp (GCL) GCL 2.6.12↲Distributed under the GNU Public License. See the file COPYING.↲Dedicated to the memory of William Schelter.↲The function bug_report() provides bug reporting information.↲(11663029281) 
06:37:05 PM: Ready for user input
06:37:05 PM: Maxima is ready for input.
06:37:06 PM: Received 10100 chars from maxima.
06:37:06 PM: Maxima sends a new set of auto-completible symbols.
06:37:06 PM: Maxima user configuration lies in directory /home/psingh/.maxima
06:37:06 PM: Maxima uses temp directory /tmp
06:37:06 PM: Maxima's manual lies in directory /usr/share/info
06:37:06 PM: Maxima's share files lie in directory /usr/share/maxima/5.41.0/share
06:37:06 PM: Maxima was compiled using GNU Common Lisp (GCL)
```

**Comment by gunterkoenigsmann** [comment]
Ok... ...with help of the wxWidgets developers wxMaxima now should always be automatically adapting to the resolution of the current screen - if wxWidgets 3.1.2 or newer is used and if wxWidgets can determine the resolution. At least in theory: Don't have a system with different screen resolutions to test it on.
