### ISSUE TITLE
Segmentation fault with maxima 5.42.2

### ISSUE THREAD

**Issue by sangwinc** [wxMaxima-developers/wxmaxima#1087]
Thanks for wxMaxima.  It is a really useful interface, which I use a lot!
I'm working on Debian 8. 
(Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3 (2017-12-13))
I've just compiled Maxima 5.42.2 from source (both CLISP and SBCL)
```
version branch_5_42_base_441_gd935193, lisp sbcl
version branch_5_42_base_441_gd935193, lisp clisp

```
Maxima works well, but now with both versions wxMaxima gives a segmentation fault. 

I deleted .wxMaxima to give a clean config file, but no change.

I've uninstalled, and reinstalled wxMaxima (apt-get etc.) but no change.

I tried to compile wxMaxima from source, but "CMake 3.4 or higher is required.  You are running version 3.0.2" (which is what apt-get gave me....).  Before I go down this rabbit hole, do you have any further suggestions please?!

Many thanks,
Chris

**Comment by scx** [comment]
@sangwinc 

You could try flatpak package:
 * wxWidgets/wxGTK 3.0 (Gtk+3): https://github.com/scx/wxmaxima-flatpak/tree/master
 * wxWidgets/wxGTK 3.0 (Gtk+2): https://github.com/scx/wxmaxima-flatpak/tree/wxgtk2
 * wxWidgets/wxGTK 3.1 (Gtk+3): https://github.com/scx/wxmaxima-flatpak/tree/wxwidgets-3.1

Personally, I would recommend the Gtk+2 version.

All variants use ECL (Embeddable Common-Lisp).

**Comment by KubaO** [comment]
Closing since I believe such problems are resolved now. Please open a new issue should there be a specific problem with either the master branch or the nightly build.
