### ISSUE TITLE
Maxima result in a TeX: cell

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#1098]
Hi All,

What is the proper way to include the result of a maxima calculation as text that appears in a subsequent TeX cell?

Example: I have the following text cell:
TeX:

$\dfrac{\partial x sup \mu}{\partial \tau}=<insert here result of a previous Maxima calculation>$

Is this possible?

Thanks

Daniel

**Comment by danielvolinski** [comment]
Hi All,

For some reason the right hand side of the equation was deleted.

It should read:

$\dfrac{\partial x sup \mu}{\partial \tau}="insert result from a previous Maxima calculation"$

Daniel

**Comment by danielvolinski** [comment]
Hi All,

Another way may be:

$\dfrac{\partial x sup \mu}{\partial \tau}=%o14$

When %o14 is a previous result

Thanks,

Daniel

**Comment by gunterkoenigsmann** [comment]
Currently there is no such way. But you can do something like

diff(µ*x,τ)=%o14

**Comment by gunterkoenigsmann** [comment]
Currently there is no such way. But you can do something like

     diff(µ*x,τ)=%o14

in Maxima to do something at least a bit similar. But I believe you already know...

**Comment by danielvolinski** [comment]
Thanks Gunter.
