### ISSUE TITLE
entermatrix display covered

### ISSUE THREAD

**Issue by fekfoq259** [wxMaxima-developers/wxmaxima#1109]
wxMaxima 19.01.2x on Windows 10

When I type
`A : entermatrix(3,3);`
It shows only "Row 1"
It should be "Row 1 Column 1:" 
Only the last one display correct. It shows "Row 3 Column 3:"

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/56176891-3a6c9700-5fc2-11e9-814a-5a2d5bd08153.png)
This is what I get when I copy the text.   What I see is only the captial letter C for the column.
The input line over writes the displayed data.

**Comment by gunterkoenigsmann** [comment]
Thanks for all the screenShots. The last of them finally showed me where the problem lies. Let's hope that fixing this bug didn't cause a new one.
