### ISSUE TITLE
Cannot place cursor in text cell if last character is a greek omega

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1111]
Dear wxMaxima Team,

The issue can be reproduced as follows:

Create a new empty work book
Create a new Text cell with Ctrl+1
Enter a,b,c,ESC,o,m
Select omega from the drop down list
Click on the empty space after the text cell
Click in the text cell
=> The cursor is not placed in the text cell.

The issue goes away if more text cells are added after this cell.

This issue does only appear in recent nightly builds, not in the latest release version - see below.

Best regards,

Michael

Issue does appear in:
```
-------------------------------------------------------------
wxMaxima version: 19.04.1-DevelopmentSnapshot
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_42_base_548_g7a984380e
Maxima build date: 2019-04-10 23:46:34
Host type: x86_64-w64-mingw32
System type: Win32 10.0.16299 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\soegtrop/maxima/
Help dir: C:\bin\maxima-daily\wxMaxima/help
-------------------------------------------------------------
```
Issue does *NOT* appear in
```
-------------------------------------------------------------
wxMaxima version: 18.10.1
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_42_base_548_g7a984380e
Maxima build date: 2019-04-10 23:46:34
Host type: x86_64-w64-mingw32
System type: Win32 10.0.16299 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\soegtrop/maxima/
Help dir: C:\bin\maxima-5.42.1\wxMaxima/help
Maxima lisp dir: C:\bin\maxima-5.42.1\bin/../share/maxima/5.42.1
-------------------------------------------------------------
```

**Comment by gunterkoenigsmann** [comment]
In today's nightly build I can no more reproduce this - at least on linux. Hope it isn't another of these places where one operating system reacts completely different to the others.

**Comment by MSoegtropIMC** [comment]
I tried it with the nightly build from last night and I am still having this issue on Windows.
But I would treat it as low prio. The issue only happens if the last character in a document is a special character.

**Comment by MSoegtropIMC** [comment]
With the nightly build from last night (downloaded now) the issue is gone, so I close this.

**Comment by gunterkoenigsmann** [comment]
But I haven't touched anything that could have caused that ?!?

Hmmm...

**Comment by MSoegtropIMC** [comment]
You did write me a while back that a specific nightly build might work. It didn't but maybe this was just a misinterpretation of which nightly build - maybe it did work a day later.
