### ISSUE TITLE
Simple variable evaluation fails (works in text mode maxima)

### ISSUE THREAD

**Issue by jlindgren90** [wxMaxima-developers/wxmaxima#1112]
The following inputs do not produce the correct result:

a : 1;
b : 2;
c : a / b;

The result should be "1/2" but instead is "a/2".  Somehow the variable "a" is not being evaluated.

In text-mode maxima (started from a terminal), the expected result "1/2" is produced.

This has been occurring since wxMaxima 18.02 or earlier (see https://bugs.launchpad.net/ubuntu/+source/wxmaxima/+bug/1798167).

**Comment by jlindgren90** [comment]
![image](https://user-images.githubusercontent.com/1244737/56506758-6f5e7980-64ed-11e9-8010-d878b46814c8.png)

**Comment by jlindgren90** [comment]
wxMaxima 19.01.2x
wxWidgets: 3.0.4
Unicode support: yes
Maxima version: 5.42.1 (x86_64-pc-linux-gnu)
Lisp: GNU Common Lisp (GCL) GCL 2.6.12

**Comment by gunterkoenigsmann** [comment]
On my computer I cannot reproduce that. Are you sure that the spaces in your assignments are actual spaces?

**Comment by jlindgren90** [comment]
I am absolutely certain that I have entered those spaces using the spacebar on my keyboard.

Your question got me digging further, though, and I found that wxMaxima has a known bug where Shift+Space is interpreted as something besides ASCII space (0x20):
https://github.com/wxMaxima-developers/wxmaxima/issues/1031

This breaks 20 years of muscle memory for me.  There is intentionally no second character on the spacebar of U.S. English keyboards, because they are designed for TYPING IN ALL CAPS without letting go of the Shift key.

It looks like the bug has been known to you since at least last September.  Are you a developer of wxMaxima and would you be able to find a fix for this?  wxMaxima is a very valuable program to me and I would be willing to make a donation to support maintenance of it, if that would help.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/56612252-7bc00080-65d9-11e9-9493-20048b08ddd1.png)
It works for me on windows 7  machine even with spaces enter between each character.

**Comment by jlindgren90** [comment]
Closing as duplicate of #1031.
