### ISSUE TITLE
Trying to open the non-existing file

### ISSUE THREAD

**Issue by marinho-rubens** [wxMaxima-developers/wxmaxima#1117]
The infos of my system are

-------------------------------------------------------------
wxMaxima version: 19.01.2x
using wxWidgets version: wxWidgets 3.0.4
Maxima version: 5.42.1
Maxima build date: 2019-01-15 11:28:41
Host type: x86_64-pc-linux-gnu
System type: BSD BSD NIL
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.12
wxMaxima's idea of the directory layout is:
User configuration dir: /home/marinho/.maxima/
Help dir: /usr/share/doc/wxmaxima
Maxima lisp dir: /usr/share/maxima//5.42.1
-------------------------------------------------------------

When I call wxmaxima in a command line in a terminal, for instance
marinho@vaio:/home/marinho/maximaexamples$wxmaxima myfile.wxm
wxmaxima open but send a message
Trying to open the non-existing file /usr/bin/myfile.wxm

It works only when I give the full path to myfile.wxm, for instance
marinho@vaio:/home/marinho/maximaexamples$wxmaxima /home/marinho/maximaexamples/myfile.wxm

Obs.: This bug does not exist in the wxmaxima version 18.04

Sincerely
Rubens Marinho

**Comment by gunterkoenigsmann** [comment]
I believe this to have been corrected in the current version of wxMaxima.
