### ISSUE TITLE
input of non-ASCII chars broken between 19.04.1 and 19.04.2

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1118]

**Comment by yurytch** [comment]
In 19.04.2 and later it is not possible to input any kind of non-ASCII from keyboard (I tried Cyrillics and Latin glyphs with diacritics). Those chars may be pasted from clipboard, so the display itself is fine. 
19.04.1 and earlier are fine in that regard.

**Comment by gunterkoenigsmann** [comment]
There are at least two users who claim this to have happened. But - I still have no idea what causes this.
