### ISSUE TITLE
Variable names are not shown when using brackets in the variable name

### ISSUE THREAD

**Issue by Murmele** [wxMaxima-developers/wxmaxima#1125]
Normaly instead of %o151... the variable name is shown, but when using parts of a list, this isn't the case. Is there a way to show also a variable name?

![grafik](https://user-images.githubusercontent.com/10099533/57279219-baa98800-70a8-11e9-801a-b40ed52977e8.png)

**Comment by Murmele** [comment]
Thank you for closing so fast :+1:

**Comment by gunterkoenigsmann** [comment]
You are welcome ;-)

I never would have thought my heuristics that tries to determine which variable name the current statement might assign something to actually went such a long time without causing bug reports of which half show simple problems that are completely unsolvable: wxMaxima can only guess from maxima's input what maxima will be doing.
