### ISSUE TITLE
Feature Request: separate options for auto-save and save on close

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1131]
Dear wxMaxiam Team,

I would prefer separate options for auto-save every n minutes (to a separate backup file) and auto save on close. The latter I don't like a lot because I frequently make experimental changes to files I want to discard, and this gets difficult with "auto-save on close". E.g. I have a lot of wxMaxima files which just serve for data visualization, so I run them to load and plot the data and sometimes I add some commands to plot some extra information, but usually I want to keep the original file.

But a regular backup to a file with a different name (which is then removed on save) does make sense.

Best regards,

Michael

**Comment by MSoegtropIMC** [comment]
Thanks!

**Comment by gunterkoenigsmann** [comment]
You're welcome!

...and thanks for finding a more elegant solution!
