### ISSUE TITLE
Option "Auto-save on close and every n minutes" is not saved

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1132]
Dear wxMaxima Team,

the option "Auto-save on close and every n minutes" is not saved. When I restart wxMaxima, the option is always set to 3. For me this is a pretty severe issue, because I don't like auto save on close (see #1131), and can't switch this off cause of this issue.

Best regards,

Michael

**Comment by gunterkoenigsmann** [comment]
Arrgh... ...I meant this bug with commit d43a43d0.
