### ISSUE TITLE
 bug in wxMaxima 19.01 and 19.05 but NOT in wxMaxima 13.04

### ISSUE THREAD

**Issue by zmth** [wxMaxima-developers/wxmaxima#1139]
[bugs:#3567] bug in wxMaxima 19.01 but NOT in wxMaxima 13.04

Owner: Leo Butler

/*
,vc(j1,m1,j2,m2,j):=block([t],if j<abs(j1-j2) j="" or="">j1+j2 or j<abs(m1+m2) then return(0) else(t:(-1)^m1</abs(j1-j2)>sqrt(factor( /(2j+1)(j1+j2-j)!/(j1-m1)!(j2-m2)!(j+m1+m2)!(j-m1-m2)! /(/(j+j1+j2+1)!(j
+j1-j2)!(j-j1+j2)!/(j1+m1)!(j2+m2)!)))sum((-1)^s(j1+m1+s)!(j2+j-m1-s)! /( s!(j1-m1-s)!
(j-m1-m2-s)!(j2-j+m1+s)! ),s,max(0,j-j2-m1), min(j1-m1,j-m1-m2)),return(t))/end else/ )/*end blk*/
*/

in version 19.01 gives incorrect error message in red:
Refusing to send cell to maxima: Mismatched parenthesis

in version 13.04 just gives some irrelevant message which is not a problem. In both versions

vc(j1,m1,j2,m2,j):=block([t],if j<abs(j1-j2) j="" or="">j1+j2 or j<abs(m1+m2) then return(0) else(t:(-1)^m1
sqrt(factor( /(2j+1)(j1+j2-j)!/(j1-m1)!(j2-m2)!(j+m1+m2)!(j-m1-m2)! /(/(j+j1+j2+1)!(j
+j1-j2)!(j-j1+j2)!/(j1+m1)!(j2+m2)!)))sum((-1)^s(j1+m1+s)!(j2+j-m1-s)! /( s!(j1-m1-s)!
(j-m1-m2-s)!(j2-j+m1+s)! ),s,max(0,j-j2-m1), min(j1-m1,j-m1-m2)),return(t))/end else/ )/end blk*/ </abs(j1-j2)>

Runs with no problem. The main issue is for example:

(kill(a,a1,b,belis,blis,i,ii,in,lisr,listmp,lisx,ls1m,mlis,mm,n,nps,nt,ntop,ntp,p,pb,plis,pmb,pnps,t,tt,u2lis,u2ls)
,pmb(bblis):=block([fl1:false,jj,tmp],pb:makelist(i,i,1,nps), i0:1,loop, jj:0,if bblis[pb[i0+1]]

    bblis[pb[i0]] then(fl1:true,for j thru nps-1-i0 while bblis[pb[i0+1+j]]>bblis[pb[i0+j]] do
    jj:j,for i:0 thru floor(jj/2) do (tmp:pb[i0+i],pb[i0+i]:pb[i0-i+jj+1],pb[i0-i+jj+1]:tmp)/end i/)
    /end then/,if i0+jj<nps-1 then(i0:i0+jj+1,go (loop)) else if fl1 then (fl1:false,i0:1,go (loop))
    , blis:makelist(bblis[pb[i]],i,1,nps),for i:0 thru nps-2 while blis[nps-i]=0 do blis:rest(blis,-1)
    , d2lis:makelist(0,nps),pai:makelist(sum(p[pb[j]]^2/a[pb[j]],j,1,i-1)+sum(p[pb[j]]^2/a[pb[j]],j
    ,i+1,nps),i,1,nps) )/*end blk*/ /*bblis must be atleast length 2 */
/*
vc(j1,m1,j2,m2,j):=block([t],if j<abs(j1-j2) j="" or="">j1+j2 or j<abs(m1+m2) then return(0) else(t:(-1)^m1</abs(j1-j2)>sqrt(factor( /(2j+1)(j1+j2-j)!/(j1-m1)!(j2-m2)!(j+m1+m2)!(j-m1-m2)! /(/(j+j1+j2+1)!(j
+j1-j2)!(j-j1+j2)!/(j1+m1)!(j2+m2)!)))sum((-1)^s(j1+m1+s)!(j2+j-m1-s)! /( s!(j1-m1-s)!
(j-m1-m2-s)!(j2-j+m1+s)! ),s,max(0,j-j2-m1), min(j1-m1,j-m1-m2)),return(t))/end else/ )/*end blk*/
*/

,szp(iej,zd1,zd2):=block([tn:0], for i thru length(zd1) do for j:1+iej(i-1) thru length(zd2) do tn:tn+(1+iej
signum(j-i))zd1[i][nps+1]zd2[j][nps+1]prod((2(ls[k]+zd2[j][k]+zd1[i][k])+1)!!/2^(ls[k]+zd1[i][k]
+zd2[j][k]+2)/a[k]^(zd1[i][k]+zd2[j][k]+ls[k]+3/2),k,1,nps)%pi^(nps/2)(1+sum(km[k]a[k](4(zd1
[i][k]+zd2[j][k]-(zd2[j][k]-zd1[i][k])^2+ls[k](ls[k]+2))+3)/(4(ls[k]+zd1[i][k]+zd2[j][k])+2),k,1,nps))
,return(tn))/*end blk*/)$

in version 19.01 Also gives incorrect error message in red:
Refusing to send cell to maxima: Mismatched parenthesis. When it should NOT give any error message at all. And exactly the same runs in version 13.04 runs fine with NO error message as there is NO error. This a serious problem in the newer version 19.01 as means cannot run something with part(s) of it remmed out !

**Comment by zmth** [comment]
Why when i submit it, it DOES not give what i write ! It left out a comma and a few * before and/or after the /

**Comment by gunterkoenigsmann** [comment]
The issue is worked on in the branch NestedComments.

**Comment by zmth** [comment]
like in what versions will the change be written?

    On Monday, July 29, 2019, 1:45:52 AM CDT, Gunter Königsman <notifications@github.com> wrote:  
 
 
Closed #1139 via 13a239c.
