### ISSUE TITLE
Editor problem in latest version    maxima-clisp-sbcl-5.43.0-win64.exe

### ISSUE THREAD

**Issue by zmth** [wxMaxima-developers/wxmaxima#1140]
this editor here is very wrong also because i can't even submit anything because it DOES NOT SUBMIT what i write here after pressing submit new issue. so i will have to put it in discussion or some other appendix to this and hopefully that will write exactly what i write and not with things left out !

**Comment by zmth** [comment]
Don't know if you will blame wxmaxima or maxima but here it is. In the short program.

(nn:3, assume(r[1]>0,r[2]>0,rn[1]>0,sin(rn[2])>0,sin(rn[3])>0)
	,depends(f,[r[1],r[2],r[3],rn[1],rn[2],rn[3],w])
	,lisn:[sqrt(r[1]^2+r[2]^2),acos(r[1]/sqrt(r[1]^2+r[2]^2)),acos(r[3])]
	,lisnr:expand(makelist(rn[i]=lisn[i],i,1,nn))
	,lans:[rn[1]*cos(rn[2]),rn[1]*sin(rn[2]),cos(rn[3])]
	,mj:ident(nn),for i thru nn do for j thru nn do mj[i,j]:diff(lans[i],rn[j])
	,dj:trigsimp(abs(factor(determinant(mj))))
	,hv:trigsimp(lans[1]^2*lans[2]^2*dj)
	,disp(["reduced hyperspherical coord's",lisnr,"  where here", r[3]=w," cosine between the 2 particles"]
	,["volume element   ",hv," angles ",rn[2],0,%pi/2,"  ",rn[3],0,%pi]) 
	,ans:makelist(r[i]=lans[i],i,1,nn), een:exp(sum(an[i]*lisn[i],i,1,nn))
	,tdn:-sum(diff(r[i]^2*diff(een,r[i]),r[i])/r[i]^2,i,1,2)/2 
	-((1-r[3]^2)*diff(een,r[3],2)-2*r[3]*diff(een,r[3]))*(1/r[1]^2+1/r[2]^2)/2
	, lisanz:makelist(an[i]=0,i,1,nn)
	,td:expand(trigsimp(lratsubst(ans,ev(tdn/een,diff,eval))))
	  ,tfn:sum(sum(sum(sum(trigsimp(factor(lratsubst(lisanz,coeff(coeff(td,an[i],k),an[j],m))) )
	*diff(f,rn[i],k,rn[j],m),m,signum(j-i-1),min(2-k,3-i)),k,1,2),j,i+1,max(i+1,nn)),i,1,nn)
	,tfn:subst(denom(coeff(tfn,diff(f,rn[3],2)))=-2*rn[1]^2*cos(rn[2])^2*sin(rn[2])^2,tfn)
	,disp("This last total pde, tfn",tfn,["is only valid as KE if the masses of the 2 particles
	 were both equal to el mass."]  ,[" Otherwise only valid if  rescale distances
	 by cst's and write in terms of  y_i using d/dx=dy/dx*d/dy so"], [y[i]=x[i]/sqrt(m[i])
	,"   But then would have to redefine the interparticle distances."] )
	,tdn1:-sum(diff(r[i]^2*diff(een,r[i]),r[i])/r[i]^2/ms[i],i,1,2)/2 
	-((1-r[3]^2)*diff(een,r[3],2)-2*r[3]*diff(een,r[3]))*(1/r[1]^2/ms[1]+1/r[2]^2/ms[2])/2
	,td1:expand(trigsimp(lratsubst(ans,ev(tdn1/een,diff,eval))))
	,disp(/*["td1 ",td1],*/"coeff(coeff(td1,an[1]),an[2])"  
	, factor(coeff(coeff(td1,an[1]),an[2])))
	  ,tfn1:sum(sum(sum(sum(trigsimp(factor(lratsubst(lisanz,coeff(coeff(td1,an[i],k),an[j],m))) )
	*diff(f,rn[i],k,rn[j],m),m,signum(j-i-1),min(2-k,3-i)),k,1,2),j,i+1,max(i+1,nn)),i,1,nn)
	,tfn1:subst(denom(coeff(tfn1,diff(f,rn[3],2)))=-2*rn[1]^2*cos(rn[2])^2*sin(rn[2])^2,tfn1)
	,disp("KE in terms of new, both are angles, coord's where the 2 masses are indep. and arbitrary, tfn1"	,tfn1))
    
    In this i want to do the very common task of commenting out part of the in disp(... beginning at
	 ,[" Otherwise ....    to the end of that disp
  
  to end up with
  
  (nn:3, assume(r[1]>0,r[2]>0,rn[1]>0,sin(rn[2])>0,sin(rn[3])>0)
	,depends(f,[r[1],r[2],r[3],rn[1],rn[2],rn[3],w])
	,lisn:[sqrt(r[1]^2+r[2]^2),acos(r[1]/sqrt(r[1]^2+r[2]^2)),acos(r[3])]
	,lisnr:expand(makelist(rn[i]=lisn[i],i,1,nn))
	,lans:[rn[1]*cos(rn[2]),rn[1]*sin(rn[2]),cos(rn[3])]
	,mj:ident(nn),for i thru nn do for j thru nn do mj[i,j]:diff(lans[i],rn[j])
	,dj:trigsimp(abs(factor(determinant(mj))))
	,hv:trigsimp(lans[1]^2*lans[2]^2*dj)
	,disp(["reduced hyperspherical coord's",lisnr,"  where here", r[3]=w," cosine between the 2 particles"]
	,["volume element   ",hv," angles ",rn[2],0,%pi/2,"  ",rn[3],0,%pi]) 
	,ans:makelist(r[i]=lans[i],i,1,nn), een:exp(sum(an[i]*lisn[i],i,1,nn))
	,tdn:-sum(diff(r[i]^2*diff(een,r[i]),r[i])/r[i]^2,i,1,2)/2 
	-((1-r[3]^2)*diff(een,r[3],2)-2*r[3]*diff(een,r[3]))*(1/r[1]^2+1/r[2]^2)/2
	, lisanz:makelist(an[i]=0,i,1,nn)
	,td:expand(trigsimp(lratsubst(ans,ev(tdn/een,diff,eval))))
	  ,tfn:sum(sum(sum(sum(trigsimp(factor(lratsubst(lisanz,coeff(coeff(td,an[i],k),an[j],m))) )
	*diff(f,rn[i],k,rn[j],m),m,signum(j-i-1),min(2-k,3-i)),k,1,2),j,i+1,max(i+1,nn)),i,1,nn)
	,tfn:subst(denom(coeff(tfn,diff(f,rn[3],2)))=-2*rn[1]^2*cos(rn[2])^2*sin(rn[2])^2,tfn)
	,disp("This last total pde, tfn",tfn,["is only valid as KE if the masses of the 2 particles
	 were both equal to el mass."]    /* ,[" Otherwise only valid if  rescale distances
	 by cst's and write in terms of  y_i using d/dx=dy/dx*d/dy so"], [y[i]=x[i]/sqrt(m[i])
	,"   But then would have to redefine the interparticle distances."]  */  )
	,tdn1:-sum(diff(r[i]^2*diff(een,r[i]),r[i])/r[i]^2/ms[i],i,1,2)/2 
	-((1-r[3]^2)*diff(een,r[3],2)-2*r[3]*diff(een,r[3]))*(1/r[1]^2/ms[1]+1/r[2]^2/ms[2])/2
	,td1:expand(trigsimp(lratsubst(ans,ev(tdn1/een,diff,eval))))
	,disp(/*["td1 ",td1],*/"coeff(coeff(td1,an[1]),an[2])"  
	, factor(coeff(coeff(td1,an[1]),an[2])))
	  ,tfn1:sum(sum(sum(sum(trigsimp(factor(lratsubst(lisanz,coeff(coeff(td1,an[i],k),an[j],m))) )
	*diff(f,rn[i],k,rn[j],m),m,signum(j-i-1),min(2-k,3-i)),k,1,2),j,i+1,max(i+1,nn)),i,1,nn)
	,tfn1:subst(denom(coeff(tfn1,diff(f,rn[3],2)))=-2*rn[1]^2*cos(rn[2])^2*sin(rn[2])^2,tfn1)
	,disp("KE in terms of new, both are angles, coord's where the 2 masses are indep. and arbitrary, tfn1"	,tfn1)  )
        
    NOw first just try doing that very common simplest editing task directly with the built in editor and see what happens. Which is why still have to use an external editor and paste for everything!!
And in this particular case in maxima 5.43 , wxmaxima 19.05 it will not even run after using external editor and then pasting with external editor but gives error messages.  It did run and output correctly using the older version 5.38 and wxmaxima 13.04 but ofcourse can't use that older editor directly either as it is even worse in other ways.

**Comment by zmth** [comment]
Nope that did not even work without leaving out something - NOT printing out what i wrote ! HOw is one supposed to report an issue when the place to report issues DOES NOT print what i write but leaves out or changes things !!

**Comment by zmth** [comment]
Ok i might could get it to work and have submit exactly what i write but better yet will just post exact before/after of trying to use the maxima editor directly to insert a " /* " without the quotes to start to try to comment out part of the before procedure. Screenshots of the exact maxima screens in my windows 7 using wxmaxima 19.05.7 with maxima 5.43. First here is before attached as before.jpg.
![before](https://user-images.githubusercontent.com/5800011/61583363-bfed6f00-aafc-11e9-9fae-ddc7a7fabbca.jpg)

**Comment by zmth** [comment]
and here is after as after.jpg.
![after](https://user-images.gi
![after](https://user-images.githubusercontent.com/5800011/61583436-66397480-aafd-11e9-93b4-b551e93013ba.jpg)

thubusercontent.com/5800011/61583391-0fcc3600-aafd-11e9-9cbc-45eb7badb331.jpg)

**Comment by zmth** [comment]
didn't mean to close it.

**Comment by zmth** [comment]
but seemed to be the only way to get it to finish uploading

**Comment by gunterkoenigsmann** [comment]
Just wanted to say that I haven't forgotten you but that feature (even if it looks pretty innocent) is kind of hard to implement => will need an astonishing lot of time, as is stated in https://xkcd.com/1425/

**Comment by gunterkoenigsmann** [comment]
Ok... ...in tomorrow's nightly build this issue is solved. But as that was a >700-lines-change I guess the fix will open new bugs whilst fixing old ones.
