### ISSUE TITLE
Scrollbar is glitchy/blinking colors on macOS.

### ISSUE THREAD

**Issue by perryprog** [wxMaxima-developers/wxmaxima#1145]
Using the latest head for both WxWidgets and wxmaxima on macOS I'm getting a janky flickering scroll bar. Here's what I get if I drag it up and down with my mouse. When the red cursor blinks it'll also alternate between a dark and light color which is pretty distracting. 

I'm gonna guess it has to do with an issue in WxWidgets or something. If you want I can try to do a bisect. Sorry I can't provide more info.

<img width="38" alt="Screen Shot 2019-08-07 at 8 47 00 PM" src="https://user-images.githubusercontent.com/12972285/62667176-828a3d80-b954-11e9-8b46-de4133af0c22.png">

**Comment by gunterkoenigsmann** [comment]
As I don't own a mac I am thankful for any help I can get;  I have completely revised the display code in the last few day's, though => With any luck the issue is gone with the current git master of wxMaxima.

**Comment by perryprog** [comment]
Sadly no. Updated to the latest WxWidgets commit too.

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...all I do is to tell wxWidgets

- I want to use a wxScrolled<wxPanel>,
- that I want the scrollbars to be always visible
- What I think would be a sensible with of a scroll step
- and on every worksheet change: how large the scroll range is

Does the problem happen even if the worksheet is long enough that scrollbars actually make sense? I can tell wxWidgets to enable and to disable the scrollbars automatically when they are needed. But that caused an endless loop if the scrollbars were needed for displaying the last pixel which caused wxWidgets to try without scrollbars again which caused...

**Comment by perryprog** [comment]
Sorry for the belated reply! It happens with any amount of content. Scrolling works as expected of course. If you need I can record a quick video.

**Comment by gunterkoenigsmann** [comment]
Any piece of information is welcome.
But I fear your initial guess is right and this will be a bug in wxWidgets.

**Comment by gunterkoenigsmann** [comment]
In the meantime I've changed big parts of the display code => With a bit of luck if it wasn't a wxWidgets bug it might be accidentally resolved now...

**Comment by perryprog** [comment]
Well, something has been fixed. There was a weird issue (seems like I haven't recorded/reported it anywhere) that was causing display issues on the main entry bit. When there was a full page of text and I scrolled the whole screen would white out. Hopefully that makes sense. Anywho, it's fixed now.

Scrollbar is still the same though.

**Comment by KubaO** [comment]
I do development on both Mac and Windows and can eventually check what's going on here.

**Comment by KubaO** [comment]
There are also scroll at issues on Windows - not with redraw, but with “glitchiness”. The first time the scroll bar is dragged by mouse, the document doesn’t scroll at all even though the scroll bar works otherwise fine. The scrolling happens only after the mouse is released. Subsequent uses work as expected.

I’ll leave this open since there certainly is some scroll bar weirdness that requires a look.

**Comment by perryprog** [comment]
Because it seems like wxWidgets will never properly support dark mode, I think it's fair to consider this issue closed. It is only reproducible in dark mode which can be disabled with a plist entry of:
```xml
<key>NSRequiresAquaSystemAppearance</key>
<true/>
```

I'm closing this issue and will be opening a second one related to some other plist problems, as it would fit together well.
