### ISSUE TITLE
Old version on the official download page

### ISSUE THREAD

**Issue by jBitHub** [wxMaxima-developers/wxmaxima#1153]
There is an old version on the official download page. Instead of 19.08 only 19.05.
Since you can't report anything on the site, I'll report it here.

https://wxmaxima-developers.github.io/wxmaxima/download.html

**Comment by gunterkoenigsmann** [comment]
The windows installers are created by the maxima team only when a new version of maxima is created. But the nightly build from https://wolfgang.dautermann.at/maxima/nightlybuild/ either is stable or requires a tester as none of the developers is using MS Windows. As far as I know it is stable, currently.

**Comment by jBitHub** [comment]
Thanks for the answer.
The version by Wolfgang Dautermann is 19.07. Looks older than the version on the official website (19.08.1).
It is however directly under the Windows download the version 19.08. In the downloaded file is however only the version 19.05.7. Then this is a wrong announcement, if only the Linux versions are updated.

**Comment by gunterkoenigsmann** [comment]
The version by Wolfgang Dautermann should be built the day after the announcement. And things are even more complicated: If you install a stable version of Debian and Ubuntu the package wxMaxima won't be updated on your system, neither, as debian allows only small bug fixes as updates to new versions might introduce new bugs users might be angry about. If you on the other hand use ArchLinux or install wxMaxima on your windows system using cygwin or chocolatey as far as I know you will receive a new version within weeks:
If I feel I have fixed an important bug (In the last year in most cases these bugs affected only one of the supported platforms) or added an important feature I prepare a release of the source code. The releases for Fink, Chocolatey, Homebrew, Macports, Red Hat, SuSE, ArchLinux, Descent, SuSE, OpenSolaris, Windows, AppImages, .app bundles, Ubuntu and likely others I have never heart of are made by volunteers - and I am always surprised by the amount of work they are willing to invest. Especially Mac and Windows Builds of any given piece of software sometimes seem to require complicated magic.

In the meantime Wolfgang has found out how to make another thing work that might be helpful: Every time something is changed in wxMaxima's source code a new wxMaxima installer that isn't bundled with maxima is created and (if this step succeeds) uploaded to https://ci.appveyor.com/project/gunterkoenigsmann/wxmaxima/build/artifacts. If the step isn't successful a mail is sent to the developers so they can investigate.

**Comment by gunterkoenigsmann** [comment]
With a bit oft luck I habe found a way to make a virtual machine build a wxMaxima installer from each new wxMaxima release. This installer will come without Maxima, though. Don't know if this is any helpful.

**Comment by jBitHub** [comment]
Thank you very much for your detailed comments. I would like to know about the VM.

**Comment by gunterkoenigsmann** [comment]
I've uploaded a .exe installer created by the VM to https://github.com/wxMaxima-developers/wxmaxima/releases
...and Wolfgang has found out that I misinterpreted the original request: The download-Page no more claims that maxima ships a newer wxMaxima than it does
