### ISSUE TITLE
Characters on plots collapsing

### ISSUE THREAD

**Issue by spaceLem** [wxMaxima-developers/wxmaxima#1154]
On plots, all characters seem to collapse on top of each other.

Minimal working example:
![wxMaxima plot error 2019-09-05](https://user-images.githubusercontent.com/6231990/64326269-9495e500-cfc1-11e9-8246-985465faa67e.png)

Version information: wxMaxima and Maxima are installed bia homebrew (not using the --HEAD option) on OSX 10.14.6.
wxMaxima: 19.08.0
wxWidgets: 3.0.4
Unicode Support: yes
Maxima version: 5.43.0 (x86_64-apple-darwin18.6.0)
Lisp: SBCL 1.5.3

**Comment by spaceLem** [comment]
Note: this is what it should look like (wxMaxima 19.05.7, installed via the Maxima 5.38.0.dmg)

![wxMaxima plot correctly](https://user-images.githubusercontent.com/6231990/64327032-ec811b80-cfc2-11e9-87e3-bcdd050cde73.png)

**Comment by gunterkoenigsmann** [comment]
Wow... ...that looks like some tool believes each Charakter has the width 0. 

...and this time I am afraid I cannot help much: all wxMaxima does is to tell maxima to plot into an pmg image. All the plot commands are decided upon by maxima and maxima doesn't tell gnuplot the char widths or theos positions => I guess the gnuplot homebrew comes with is currently broken, at least as long as it tries to generate PNG images. I've once tried to make wxMaxima accept svg, as well. Which is quite simple from wxMaxima's side if I can delegate drawing the svg's content to wxSvg. But on Windows wxSvg needs nearly all of gtk which in turn requires about 20 external libraries... ...what is required on the Mac I didn't look at after that experience.
