### ISSUE TITLE
Lapack does not compile

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1155]
I downloaded the current night build today.   I found out that the Lapack fails to compile.  It always had some warning, but now it fails and then aborts the compiling.  This is the sbcl version.

**Comment by richardgobeli** [comment]
load(lapack);   

this will fail with false printed.

**Comment by gunterkoenigsmann** [comment]
The problem typically is that sbcl runs out of RAM: it allocates all the RAM it might need on start-up and never allocates more RAM afterwards even of it would need that. wxMaxima's config dialogue describes a command-line parameter that can increase the amount of RAM being used by SBCL (needs to be less than half of the RAM installed on your system). Unfortunately some maxima users still have only half a gigabyte available so increasing the amount of RAM sbcl allocates too much makes sbcl fail for them...

**Comment by richardgobeli** [comment]
Is there a way to see how much ram it is already using?

**Comment by richardgobeli** [comment]
I compiled after setting size to 2048.  I have it now to 4096.  They most have made the memory allocation smaller, because it compiled before.

**Comment by richardgobeli** [comment]
This is closed for me.
