### ISSUE TITLE
Updating/refreshing the wxMaxima window can be extremly slow.

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1163]
Sorry for not having returned on this for a long time.
This is a contunuation of
https://github.com/wxMaxima-developers/wxmaxima/issues/1037

Just downloaded the latest daily build (16/10-2019) 
It is slow going to extremely slow on updating the wxMaxima window when the size of a worksheet grows.

- Scrolling goes fine
- Making a wxMaxima window smaller (by dragging a corner) goes fairly ok
- Making a wxMaxima window larger(by dragging a corner) goes does almost not work
- Going between full screen and windowed by using the windows icons works fast and fine
- Folding/Unfolding a section or sub-section can take more than a minute. It seems like using the menu function "Cell" - "Remove all output" wxMaxima begins to run more smoothly.
- If I (by accident) presses "Unfold all" wxMaxima becomes inaccessible for several minutes.. - During that time, is uses quite a bit of CPU - but somehow never more that approximately 20% or so.... And, it constantly eats more and more memory I killed wxMaxima when it had eaten 700Mbytes and still continues...

Saving a large worksheet goes very fast.

(%i1)	wxbuild_info()$
wxMaxima version: 19.10.0-DevelopmentSnapshot
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_43_base_158_g0a5722d32
Maxima build date: 2019-10-15 23:47:02
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

By the way: Why are / and \ mixed in the directory (see above) - and which one is the correct one ?

**Comment by gunterkoenigsmann** [comment]
On windows the question about slash and backslash is complicated: In theory the backslash has been deprecated for many years. But as some programs and functions still don't support the slash none of them is correct in all cases.

I never use folding and for me wxMaxima is quite fast. Maybe that is a good hint...
