### ISSUE TITLE
code inserted by parametric plot wizard gives an error

### ISSUE THREAD

**Issue by fsenese** [wxMaxima-developers/wxmaxima#1166]
This code works:
````
wxplot2d([parametric, 3/2* sin(t)-sin(4*t), 3/2*cos(t)-cos(5*t), [t, -8*%pi, 8*%pi]])$ 
````

This code is inserted when using the menu's Plot->Plot2d -> Special ->Parametric wizard:
````
wxplot2d([['parametric, 3/2*sin(t)-sin(4*t), 3/2*cos(t)-cos(5*t), [t, -8*%pi, 8*%pi], [nticks, 300]]], [x,-5,5])$`
````
It gives this error message:
````
plot2d: parametric plots must include two expressions and an interval
 -- an error. To debug this try: debugmode(true);
````
-------------------------------------------------------------
wxMaxima version: 19.05.7
using wxWidgets version: wxWidgets 3.1.0
Maxima version: 5.43.0
Maxima build date: 2019-06-01 18:55:31
Host type: x86_64-w64-mingw32
System type: Win32 10.0.18362 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\FSenese/maxima/
Help dir: C:\maxima-5.43.0\wxMaxima/help
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
Wow... ...for plot I am no expert (I always use draw). But I will try to have a look at it.
