### ISSUE TITLE
proper position of tensor indices in wxmaxima

### ISSUE THREAD

**Issue by murakamiriyugi** [wxMaxima-developers/wxmaxima#1169]
The package itensor can keep track of the positioning of tensor indices by using signed tensor indices. Using signed tensor indices, negatively signed tensor index is read by maxima as a contravariant tensor index and unsigned tensor index is read by maxima as covariant tensor index. The problem is, proper index positioning is not reflected in the wxmaxima display. Consider an example below:

<img width="605" alt="tensor index pos" src="https://user-images.githubusercontent.com/4223730/68068671-1fad1480-fd92-11e9-9480-f24dd2697f06.png">

Since Q([–α, μ],[]) and Q([μ, –α,],[]) are displayed in the same way, it can be confusing which tensor one may refer to when performing some mathematical operations involving both of them.

Consider another example  below:

<img width="582" alt="riemann" src="https://user-images.githubusercontent.com/4223730/68068677-39e6f280-fd92-11e9-917d-994a5583a97d.png">

**Comment by murakamiriyugi** [comment]
To verify the request above, try the following code on wxmaxima:

load(itensor);
ishow(Q([-α, μ],[]))$
ishow(Q([μ, -α],[]))$
ishow(Q([-α, μ],[]) - Q([μ, -α],[]))$

<img width="603" alt="wxmaxima out tensor" src="https://user-images.githubusercontent.com/4223730/68068728-153f4a80-fd93-11e9-92fe-5fc6b066e5f0.png">

**Comment by gunterkoenigsmann** [comment]
Currently maxima has no way of telling this piece of information to the frontend. But work in making maxima more flexible in this respect are currently being discussed in the maxima-discuss mailing list on sourceforge.net - and once maxima is able to request the formatting you want  wxMaxima can be extended to understand what Maxima requests.

**Comment by richardgobeli** [comment]
In my version of Macsyma they used @ instead of the minus sign to indicate the contravariant index.  If I try with using minus sign, it tells me to convert to new method. All of the functions in Macsyma are compiled to none readable files.

**Comment by murakamiriyugi** [comment]
This is about the comment of gunterkoenigsmann. I am not an expert about the way wxmaxima communicates with maxima in the background so I maybe I am missing something. The output of maxima (not wxmaxima) when ishow() is used, is a tensor with a set of indices arranged in a consistent pattern. For instance, see %o2 and %o3 below

<img width="621" alt="Screen Shot 2019-11-06 at 00 18 14" src="https://user-images.githubusercontent.com/4223730/68225189-02df3e00-002b-11ea-8b72-f0d03bad1317.png">

The negative sign indicates that the index is a contravariant index (upstair) and its absence indicates it is a covariant index (downstair). And the order the indices are listed indicates their proper position in the way a tensor is handwritten. What I am thinking is that the negative sign or any of its representation and the way the indices are ordered could be passed to wxmaxima.

**Comment by gunterkoenigsmann** [comment]
In order to make this work wxMaxima would need to know first that the object that is equipped with sub- and superscript actually is a tensor. Currently only maxima knows for sure about this and currently it doesn't tell the front end about this knowledge.

**Comment by richardgobeli** [comment]
maxima does this for ishow:

;Displays P([L1],[L2],I1,I2,...) by making the elements of L2 into a single
;atom which serves as the exponent and the elements of L1 and I1,I2,... into a
;single atom with a comma in between which serves as the subscript.

Even when it uses -index for contravariant, it will get lumped in the exponent list and all order is lost.
the ishow would need rewriting to use a different form of writing other than with exponents for superscripts and array for subscripts.

**Comment by richardgobeli** [comment]
Gunter,
Do you know about any text writing functions in maxima lisp that I could try using to make a string of characters that would do the subscript and superscript of the tensor without using the exponent or array indexing?
The problem with using exponent for superscript is it gets compressed next to the base name and all index position is lost.  I think I understand how the ishow function currently works.  I duplicated it in a :lisp command from wxmaxima.

**Comment by richardgobeli** [comment]
Gunter,
I think this could work, if you implemented the windows ctl= character, which puts the text in subscript mode and all characters after are sub-scripted.  It is turned off by sending ctl= again.  The same would be for ctl+ character, which would switch to super-script text. This mode is also turned off by sending another ctl+.  The function ishow could then send the text which could switch back and forth between the two modes to display the tensor in the correct form.

**Comment by richardgobeli** [comment]
@robert-dodier, do you have time to work on the multiscript to get a function that can be used in ishow  from the tensor package to display indices correctly.

**Comment by robert-dodier** [comment]
@richardgobeli unfortunately, I can't promise to devote time to this problem at the moment. What I can see about this is that there needs to be display properties attached to the symbol which is actually displayed, which might or might not (not sure which one at this point) be the same as the symbol for the tensor. E.g. display properties might be associated with a different symbol than Q (although that other symbol might be displayed the same as Q -- I know this is confusing). The game would be for the tensor display code to construct suitable index strings, containing spaces as needed, and then display other-Q-symbol with those indices. 

Here's an example of how it could look. The missing part is to automatically construct the index strings from what's known about Q.
```{maxima}
(%i2) alias(Q, QQ);
(%o2)                          [Q]
(%i3) declare_index_properties (QQ, [postsuperscript, postsubscript]);
(%o3)                         done
(%i4) QQ[" a", "b "];
                                 a
(%o4)                          Q
                                b 
(%i5) QQ[" a c", "b d "];
                                a c
(%o5)                         Q
                               b d 
```
Well, the other missing part is to ensure that wxMaxima and maybe TeX output is suitable. I haven't investigated that. Hope this helps in some way.

**Comment by richardgobeli** [comment]
I did not think about doing strings with spaces, and the derivative with a "," in the string will also work.  This should not be hard to do with the ishow function.

**Comment by robert-dodier** [comment]
@richardgobeli  I agree that it should be possible to convince `ishow` to use sub/superscripts with spaces.  Is it sufficient to call `ishow` to display tensors, or is it much preferable to have tensors be displayed without calling `ishow`?

**Comment by richardgobeli** [comment]
I think ishow would be good enough for now. 
Viktor Toth would need to change a lot of itensor to make it automatic.
I already have a ctensorpatch on https://sourceforge.net/p/maxima/patches/   patch #96. Viktor has not had time to really look at it.  In July, the ctensorpatch will be 1 year old.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/124373891-0130a800-dc5c-11eb-8879-ebb20511136c.png)

@robert-dodier  
This does not seem to work anymore, if the data in QQ is a variable or string.
(%i2) alias(Q, QQ);
(%o2)                          [Q]
(%i3) declare_index_properties (QQ, [postsuperscript, postsubscript]);
(%o3)                         done
(%i4) QQ[" a", "b "];
                                 a
(%o4)                          Q
                                b 
(%i5) QQ[" a c", "b d "];
                                a c
(%o5)                         Q
                               b d 

This is what I get.
![image](https://user-images.githubusercontent.com/31253976/124373856-9b442080-dc5b-11eb-89f9-6469bd25e95f.png)

**Comment by robert-dodier** [comment]
@richardgobeli the XML error appears to be coming from wxMaxima. Looks like Gunter is taking it on.

**Comment by gunterkoenigsmann** [comment]
I guess I forgot to Quote an quotation sign in wxMathml.lisp, but give me a few day's time to look into. Kind regards, Gunter.

**Comment by richardgobeli** [comment]
I tried the new nightly build and the above code still gives the XML parsing error.
![image](https://user-images.githubusercontent.com/31253976/125907633-d64c046d-4279-478c-bb09-d91f89cd1f17.png)
![image](https://user-images.githubusercontent.com/31253976/125908025-c6f49a46-0a80-402e-bd20-551811930b02.png)
