### ISSUE TITLE
Button that can be clicked with mouse to do shift enter.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1170]
This would be nice to step through demos and not be doing the shift enter combination on the keyboard.  I always end up holding the keys too long and windows thinks I want to repeat.

**Comment by gunterkoenigsmann** [comment]
I'm not opposed to adding new buttons. But as there is only limited space available in the tool bar and there are many buttons that would make sense I'm kind of reluctant to do so. Let's see if others join this request showing this button being important to many...
...if I could find a way to dynamically hide buttons that would allow for more possibilities...

**Comment by richardgobeli** [comment]
Macsyma made a status bar in the window when a demo was running.  The OK was the enter button. 
 There was also an interrupt button to end the demo.
![image](https://user-images.githubusercontent.com/31253976/68452101-056e9e80-01b7-11ea-80b5-98cdfe8178eb.png)

**Comment by gunterkoenigsmann** [comment]
Let's see what the answers to https://groups.google.com/forum/m/#!topic/wx-users/iolGy7MGLIU are...

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/68533786-a4e47c00-02f2-11ea-8e28-7c388b1965ad.png)
This is a lot easier to go thru demos with the arrow button.  This also would be a great asset for the debugger, because it has all of different complex step commands.  Keep up the good work!

**Comment by gunterkoenigsmann** [comment]
You mean the lisp debugger? That would be great. But as every single lisp provides its own methods to debug programs this would require someone with deep knowledge of the debuggers and loads of time...
