### ISSUE TITLE
Wrong sort of UI languages in configuration dialog

### ISSUE THREAD

**Issue by sibskull** [wxMaxima-developers/wxmaxima#1171]
There is wrong order of UI languages in configuration dialog (Edit-Configure-Options-Language). This list begins from Ukrainian, then Turkish and so on. So default item with index 0 - "(Use default language)" is not on first position. After push of OK button all UI make on Ukrainian.

**Comment by gunterkoenigsmann** [comment]
Which wxMaxima version do you use?

In the current versions theory the list of languages is defined in src/ConfigDialogue.cpp:
````
ConfigDialogue::ConfigDialogue(wxWindow *parent, Configuration *cfg)
{
  m_languages[_("(Use default language)")]=wxLANGUAGE_DEFAULT;
  m_languages[_("Catalan")]=wxLANGUAGE_CATALAN;
  m_languages[_("Chinese (Simplified)")]=wxLANGUAGE_CHINESE_SIMPLIFIED;
  m_languages[_("Chinese (traditional)")]=wxLANGUAGE_CHINESE_TRADITIONAL;
  m_languages[_("Czech")]=wxLANGUAGE_CZECH;
  m_languages[_("Danish")]=wxLANGUAGE_DANISH;
  m_languages[_("English")]=wxLANGUAGE_ENGLISH;
  m_languages[_("Finnish")]=wxLANGUAGE_FINNISH;
  m_languages[_("French")]=wxLANGUAGE_FRENCH;
  m_languages[_("Galician")]=wxLANGUAGE_GALICIAN;
  m_languages[_("German")]=wxLANGUAGE_GERMAN;
  m_languages[_("Greek")]=wxLANGUAGE_GREEK;
  m_languages[_("Hungarian")]=wxLANGUAGE_HUNGARIAN;
  m_languages[_("Italian")]=wxLANGUAGE_ITALIAN;
  m_languages[_("Japanese")]=wxLANGUAGE_JAPANESE;
#if wxCHECK_VERSION(3, 0, 1)
  m_languages[_("Kabyle")]=wxLANGUAGE_KABYLE;
#endif
  m_languages[_("Norwegian")]=wxLANGUAGE_NORWEGIAN_BOKMAL;
  m_languages[_("Polish")]=wxLANGUAGE_POLISH;
  m_languages[_("Portuguese (Brazilian)")]=wxLANGUAGE_PORTUGUESE_BRAZILIAN;
  m_languages[_("Russian")]=wxLANGUAGE_RUSSIAN;
  m_languages[_("Spanish")]=wxLANGUAGE_SPANISH;
  m_languages[_("Turkish")]=wxLANGUAGE_TURKISH;
  m_languages[_("Ukrainian")]=wxLANGUAGE_UKRAINIAN;
````
...and in the config file the number of the language (for example `wxLANGUAGE_UKRAINIAN` is stored which should be read back correctly in src/main.cpp...

**Comment by sibskull** [comment]
Version 19.10.0.
I see code, but there is iterator usage for this dictionary. Possible, wrong order in iterator like
for( Languages::iterator it = m_languages.begin(); it != m_languages.end(); ++it )

**Comment by sibskull** [comment]
I expect to save wxLANGUAGE_DEFAULT if change any other settings.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this hint! a23e865ca48458a00f76821ed1bb3b9e53bf2005 should resolve this issue even if I still don't know what criterion wxWidgets uses for sorting the languages.
