### ISSUE TITLE
fonts configuration changes made via font settings dialog seem to be ignored

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1174]
wxMaxima 19.10.0 and 19.11.0 seems to ignore user's font settings. Whatever face and style I set in the dialog 'Edit-Configure-Style', those aren't used after commiting the changes, and aren't written out to .wxMaxima file. 
Face settings are read from .wxMaxima (they have effect), but fontsize setting isn't (no effect, whatever I put into the .wxMaxima by an external text editor).
Also, math font setting isn't read from .wxMaxima to 'Style' dialog.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot! Seems no-one has ever tested that in a long while. Will be resolved in tomorrow's nightly build.

**Comment by yurytch** [comment]
Thank you!

**Comment by gunterkoenigsmann** [comment]
You are welcome - and many thanks for you for being willing to test wxMaxima and for your patience until I manage to fix the bugs (hoping that this time I fixed the whole bug: Printing and getting every single thing right is a nightmare - even in theory the same graphics routines are used for printing and for displaying the worksheet so nothing can possibly go wrong ;-) ).
