### ISSUE TITLE
custom style settings are ignored when printing to file

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1175]
If there are custom style changes active, the printing function outputting to file still uses the default style settings.

**Comment by gunterkoenigsmann** [comment]
Seems like I forgot to copy some settings to the printing context. Which options did you try?

**Comment by yurytch** [comment]
I've used the options setting the default font face and size, the default math font face and size, the colours for variables, functions, numbers, output cells prefixes, comments, punctuation, and the background colour of text cells. All of these are used by their default values in the exported PDF.

**Comment by gunterkoenigsmann** [comment]
...at least the issue is solved for the use cases I tested it with. If you find other cases feel free to comment here or to open another ticket (one ticket per issue is the easiest way to work on multiple bugs without risking to forget one).

**Comment by yurytch** [comment]
Thank you! But... could you look again at the 'text cell background' setting? Of all things I mentioned, this one alone isn't retained when printing to file, in the 'master'.

**Comment by KubaO** [comment]
Indeed, the text cell background is not used.
