### ISSUE TITLE
wxMaxima forgets to delete temp-file at closing

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1177]
wxMaxima leaves the xxx.wxmx~ - file when closed.

(%i1)	wxbuild_info()$
wxMaxima version: 19.12.0-DevelopmentSnapshot
using wxWidgets version: wxWidgets 3.1.3
Maxima version: branch_5_43_base_237_gd60cd8c9b
Maxima build date: 2019-12-02 00:04:13
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
That should be caused by the virus scanner that still scans the file when it is about to be moved/deleted. At least I hope so...
