### ISSUE TITLE
Color of labels does not respect system preference 

### ISSUE THREAD

**Issue by perryprog** [wxMaxima-developers/wxmaxima#1180]
- Likely macOS only
- Fairly self explanatory
- Latest stable version of wxMac.
  - _Not_ the latest devel version. This one is 3.0.4 from March 8th, 2018. Could be fixed in a later wxMac/Widgets version.
- Latestish master commit ([`8e251a1`](https://github.com/wxMaxima-developers/wxmaxima/commit/8e251a1df45a4edc79f43cddee74c051daf72382))

<img width="504" alt="Screen Shot 2019-12-09 at 12 27 28 PM" src="https://user-images.githubusercontent.com/12972285/70458034-45a79200-1a7f-11ea-8cae-f63888c0b5e4.png">
<img width="628" alt="Screen Shot 2019-12-09 at 12 28 18 PM" src="https://user-images.githubusercontent.com/12972285/70458094-6243ca00-1a7f-11ea-80cc-a9df2761a38d.png">

**Comment by gunterkoenigsmann** [comment]
About the only thing wxMaxima assigns own colors to is the worksheet => I assume wxWidgets to fix dark mode. And I still am not secure if the worksheet in dark mode should be black or white: I don't own a Mac.

**Comment by perryprog** [comment]
It should most likely be white (although there is some conflicting opinions on that).

The whole UX idea behind dark mode is to allow the controls recede into the background so you can focus on the content. The worksheet is definitely fine how it is now, regardless.

If you think it's warranted go ahead and close this issue.

**Comment by gunterkoenigsmann** [comment]
I think I found the original wxWidgets ticket that matches your report: https://trac.wxwidgets.org/ticket/18146

**Comment by gunterkoenigsmann** [comment]
I think I found the original wxWidgets ticket that matches your report: https://trac.wxwidgets.org/ticket/18146 => closing the ticket hoping that wxWidgets will resolve it without needing any interaction from my side.

**Comment by perryprog** [comment]
Yeah, this is totally find on wxWidgets devel. My bad.

**Comment by gunterkoenigsmann** [comment]
Well... ...a typical case of "define stabile" ;-)
But it is good that you were able to test it with the "unstable" build: I had no idea where else to search for this bug...
