### ISSUE TITLE
Expression issue: incorrect display

### ISSUE THREAD

**Issue by lvch** [wxMaxima-developers/wxmaxima#1183]
![bug1](https://user-images.githubusercontent.com/6746594/70735423-4e1df800-1d1f-11ea-8cb7-2045ca9fda17.png)

**Comment by gunterkoenigsmann** [comment]
This issue seems to lie on the lisp side somewhere => I can acknowledge it is there - but I would need a skilled lisp programmer for resolving it...

**Comment by gunterkoenigsmann** [comment]
I think I managed to do without one, this time...
