### ISSUE TITLE
Still wery slow on updating the window content

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1185]
However a bit faster that for a week ago.
(%i1)	wxbuild_info()$
wxMaxima version: 19.12.1

using wxWidgets version: wxWidgets 3.1.3
Maxima version: branch_5_43_base_243_g526f8f3ad
Maxima build date: 2019-12-10 00:04:57
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
I am still a bit at loss what should be slow: wxMaxima doesn't try to use some exotic graphics accelerator API that some graphics cards implement and others don't. Some things have sped up => Are there things that are particularly slow and therefore may give a hint on what seems to be the problem? I can imagine that some fonts are complicated enough to generally be slow => can that be the problem?

**Comment by ReneSci** [comment]
Hmmm.... How can i be more specific... For example if I resize the wxMaxima window, it takes quite long time to update the window I am working on very a large worksheet  (a 3.5Mbyte *.wxmx -file). In the meantime it looks up the workbench so the PC can nut be used for anything else. 
When working with small worksheets there is no problem. It might be due to a large amount of data. I I use the function "Cell"-> "Remove all output" and resizes the window, it goes a lot faster.
There might not be anything to do other that limit the size of the worksheet.
Does that make sense ?

**Comment by ReneSci** [comment]
Sorry - thought https://github.com/wxMaxima-developers/wxmaxima/issues/1037 was closed..

**Comment by gunterkoenigsmann** [comment]
In theory the current nightly build now caches the result of asking the operating system how much space a given piece of text will occupy on the screen, which was what used 90% of the processor time. Am currently trying to get a profiler tell me what is the bottleneck now...

**Comment by gunterkoenigsmann** [comment]
i cannot guarantee that wxMaxima will be able to recalculate all line breaks in complex objects like maths objects that can (depending on their width relative to the worksheet's width) be either in linear o in 2D form) faster than MS Word will do the same if a style changes: In the end layouting maths is slow.

**Comment by gunterkoenigsmann** [comment]
(Seems I accidentally hit the "send" button, sorry for that) ...and trying to use more than one CPU won't help too much: Half of the methods the operating system provides for that are not re-entrant. But it seems like up to now we found quite a few places one can optimize...

**Comment by ReneSci** [comment]
It has improved quite a bit  :-)

**Comment by KubaO** [comment]
My profiling thus far places blame at algorithms only - nothing to do with graphics acceleration. wxMaxima wastes lots of time copying, destroying in reinstantiating lots of objects. For a long document (~80 printed pages), this causes millions of unnecessary allocations, copies and destructions. There's no need for any fancy tools: you can be the statistical profiler :)

All you need to do to see it is to open a long document and manually pause the process in the debugger. Most of the time it's not doing anything we don't have control over - it just wastes time creating and destroying lots of objects. Quite a bit of that should be easy to fix, and I'm working on that.

**Comment by KubaO** [comment]
I'm doing lots of work in this area, but there are large swaths of code that are being changed, so I'm submitting mostly housekeeping changes for now. Those get rather minor perf improvements but make the code more amenable to the primary fixes. It'll take a few more weeks to get the worst offenders taken care of - evenings only have so many hours, but there's light at the end of the tunnel I believe.

**Comment by ReneSci** [comment]
Actually som quite good improvements has been done already.

Den tir. 12. maj 2020 kl. 08.46 skrev Kuba Ober <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
But if everything Kuba has planned works out I believe we'll get a speed boost beyond what I thought would be possible.

**Comment by ReneSci** [comment]
Exiting - look forward to do the tests !

Den ons. 13. maj 2020 kl. 14.09 skrev Gunter Königsman <
notifications@github.com>:

**Comment by KubaO** [comment]
Quick update on this: The changes I've slowly merging don't improve performance much, but are needed to improve code quality and enforce correctness-by-design. This correctness-by-design aspect means that the code's design encourages correct use of the APIs, and also makes it hard or impossible to introduce bugs when modifying the code.

Once those changes are all merged, there are two major performance improvements that essentially solve the performance issue, or at least 90% of it:

1. Full use of font cache.

2. Deferral of confusable character warning recomputation. Right now the confusable warnings are reevaluated many times for each cell when opening the file or changing cell contents. They stand out badly in the profiles.

The remainder of time is wasted copying wxStrings during a variety of operations. That requires significant effort in multiple areas of the code to be thoroughly fixed. But it's "noise" compared to the current performance issues.

**Comment by KubaO** [comment]
The font cache rework has landed. Please evaluate git master or a nightly and report whether things got better.

**Comment by KubaO** [comment]
I'm closing this since things are much better now.
