### ISSUE TITLE
sigma sign is missing

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1187]
![bug_info](https://user-images.githubusercontent.com/59099908/71291137-037d2b00-2372-11ea-9920-f9847b5852c0.jpg)

![sum_Zeichen](https://user-images.githubusercontent.com/59099908/71291157-10018380-2372-11ea-8427-dee165755efe.jpg)

**Comment by gunterkoenigsmann** [comment]
I believe this to be resolved in the current nightly build. But as I don't ow. A MS windows computer I cannot guarantee this.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/71493857-111a3100-2808-11ea-9c02-993d0877c5ea.png)
the sum symbol is still not there.
![image](https://user-images.githubusercontent.com/31253976/71493870-3149f000-2808-11ea-972f-a10b6e9865b0.png)

**Comment by gunterkoenigsmann** [comment]
The current nightly build should no more replace "chi" by the corresponding greek letter if not instructed to do so in the config dialogue: As wxMaxma supports inputting "real" greek letters using the greek sidebar or by typing `<ESC>chi` replacing greek letters no more was necessary and often caused confusion.

---

To me this looks like a font is used that doesn't contain a "Sum" or "Product" sign and in the configuration "use unicode math symbols, if available" is checked. Unfortunately wxWidgets doesn't allow me to detect if they are actually available.

Perhaps the answer is not to try to use unicode math signs and to make the built-in unicode signs of wxMaxima nicer.

**Comment by gunterkoenigsmann** [comment]
Ok... ...tried that. Do the integral signs work for you? Something like:

      integrate(sin(f(x)),x,1,10);

**Comment by ljselmaier** [comment]
The integral signs is ok.:

![maxima_integral](https://user-images.githubusercontent.com/59099908/71516725-da492700-28aa-11ea-908e-bdcfe80e8ae5.jpg)

**Comment by ljselmaier** [comment]
Greek letters:
![Greek letters](https://user-images.githubusercontent.com/59099908/71522530-5cdee000-28c5-11ea-9173-4f8ade5cb5f4.jpg)

**Comment by richardgobeli** [comment]
I did see today that if I enter greek letters with esc chi it will be converted on the input line and stay that way. The example above was just using chi on input line and not all chi are converted on the output line. I do have the greek name to symbol checked.
![image](https://user-images.githubusercontent.com/31253976/71526723-ce0a9d00-289d-11ea-9abe-15188f449bc5.png)

The integral sign works, but not sigma.
![image](https://user-images.githubusercontent.com/31253976/71526626-605e7100-289d-11ea-802a-d628dc7fd291.png)
I have this selected for fonts.
![image](https://user-images.githubusercontent.com/31253976/71526818-293c8f80-289e-11ea-98e8-66592f5a05c7.png)
I tried many fonts and the sigma is always blank. how do I get back to the default math font Linux Libertine O (12) font?  It is not in the selection.

**Comment by richardgobeli** [comment]
build today!
![image](https://user-images.githubusercontent.com/31253976/71539488-355a3880-2902-11ea-914f-9f51f7d58e4a.png)
The sum is working and the product is partial working.   When using the product mathematical symbol it does not make a product, but a undefined function call.
![image](https://user-images.githubusercontent.com/31253976/71539483-270c1c80-2902-11ea-9979-e9a70b07124f.png)
proof it is an unknown function:
![image](https://user-images.githubusercontent.com/31253976/71539530-f5478580-2902-11ea-8b0b-c76ac6750d4d.png)

**Comment by gunterkoenigsmann** [comment]
I was not sure if to define the sum symbol as sum or as lsum... ...and was convinced that the same problem would arise with the product symbol. Would "sum" and "product" be a good translation to maxima?

**Comment by gunterkoenigsmann** [comment]
Ok... ...sum and product sign in the next nightly build are translated to the respective commands if they aren't used within a string or as part of a command or variable name. I hope that is within the range that is acceptable.

**Comment by KubaO** [comment]
I believe that this now works. @ljselmaier  - please reopen if the issue persists in master or nightly build.
