### ISSUE TITLE
editor not show matching parenthesis 

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1188]
(Migrating this item from Maxima bug #3600 at Sourceforge.)

`build_info(version="5.43.0",timestamp="2019-06-01 18:55:31",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="1.4.14",maxima_userdir="C:/Users/zmth/maxima",maxima_tempdir="C:/Users/zmth/AppData/Local/Temp",maxima_objdir="C:/Users/zmth/maxima/binary/5_43_0/sbcl/1_4_14",maxima_frontend="wxMaxima",maxima_frontend_version="19.05.7")`

anytime there is a double quote mark symbol just before a closing parenthesis, no spaces between,maxima does NOT show the match to the closing parenthesis
For example: `write_data(["abc"],"file")`
then hover over the last closing parenthesis it will not show . If there is a space between then it does. This is example is easy but it can be frustrating when it is embedded in a long program with many nested parenthesis and in other situations.

**Comment by KubaO** [comment]
Still happens - would be nice to fix now rather than later.

**Comment by KubaO** [comment]
This happens when there's a quote `"` at a second-to last position, i.e. `xxx"z`. Then, when `z` is q parenthesis, the quote preempts the parenthesis.
