### ISSUE TITLE
showing wrong files associated with dates - loading a recent file by a file with the same name as it was months ago

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1189]
(Migrating this item from Maxima bug #3601 at Sourceforge.)

`build_info(version="5.43.0",timestamp="2019-06-01 18:55:31",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="1.4.14",maxima_userdir="C:/Users/zmth/maxima",maxima_tempdir="C:/Users/zmth/AppData/Local/Temp",maxima_objdir="C:/Users/zmth/maxima/binary/5_43_0/sbcl/1_4_14",maxima_frontend="wxMaxima",maxima_frontend_version="19.05.7")`

In a notebook session say for example just beginning use ctrl O or 'file open it will show a file with the same name dated several months ago, at least that is what it did in my case, but NOT the latest version of the file with same name but instead will show the same filename but with the contents of that file as it was months ago - not the most recent version of that file. In particular if the name of that file is same as the most recent one on which you modified then it will load the same file but with it's contents months ago. Can be quite dangerous esp if you have autosave activated then you could end up losing all your work for the past several months. Don't know where it gets the information of the contents of that file months ago. 

And it also shows it as being of the same length but wrong date as your most recent file of that name but it is NOT the same file as your most recent version as you find out after opening it- all your work in the past several months is gone in my case.

**Comment by gunterkoenigsmann** [comment]
Thanks for migrating the bug. But I guess it must be a bug in an "open recent files" option the operating system provides and that was used from the start menu or similar, not from wxMaxima: wxMaxima doesn't show the length of files, nor the date they were last accessed. Also wxMaxima stores and compares the full absolute path to a file which means files in different folders cannot be treated as one being the other.

**Comment by gunterkoenigsmann** [comment]
Closing this bug as I still feel kind of guilty that much work was lost but I believe that wxMaxima cannot do anything about it.

If I am wrong or if wxMaxima can show information that helps finding out that the wrong file was opened please feel free to protest against me closing this ticket.

**Comment by robert-dodier** [comment]
Hi Gunter,

> If I am wrong or if wxMaxima can show information that helps
> finding out that the wrong file was opened please feel free to
> protest against me closing this ticket.

Yeah, I'm not sure what can be done. I guess at this point you might
consider posting a comment on the original Maxima bug report so that
the person who reported it is more likely to know the status of it.

best,

Robert
