### ISSUE TITLE
Yellow background using function depends

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1191]
![image](https://user-images.githubusercontent.com/31253976/71593335-373a1c80-2af9-11ea-83e5-68fe3dcac61b.png)
It only does this with the variable x in the list.
Here is the xml data.
![image](https://user-images.githubusercontent.com/31253976/71593300-1d98d500-2af9-11ea-8d19-6c3a255e2992.png)

**Comment by gunterkoenigsmann** [comment]
The yellow color is a feature the maxima-discuss mailing list has requested: It indicates that there is a mouse-over tooltip, in this case indicating that chi and x look similar to each other whichcan lead to hard-to-find errors. The original similarity that caused this feature request was X and x which caused way too many worksheets to go yellow. If there are too many protests (or if the first protester provides convincingly-enough arguments) I am willing to drop more visuals similarity tests. Or to add additional ones, that is.

**Comment by richardgobeli** [comment]
When you know it is not an issue it the code is there a way to disable it at the expression?

**Comment by KubaO** [comment]
Indeed, it'd be nice if there was a way to disable these tooltips selectively.

**Comment by gunterkoenigsmann** [comment]
Then I will add a right click-menu item that disables them.

**Comment by KubaO** [comment]
I believe that this is done now. @richardgobeli  please reopen if the nightly doesn't do enough in this respect.
