### ISSUE TITLE
Default screen scale shows equal sign without gap before fraction or minus sign

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1193]
![image](https://user-images.githubusercontent.com/31253976/71916367-6547de00-3143-11ea-8bbf-74968414f654.png)

Here is what it looks like:
![image](https://user-images.githubusercontent.com/31253976/71916410-801a5280-3143-11ea-8a14-b9c46b8f2204.png)

If I change screen scale by hold ctl and scroll the mouse it is OK.
![image](https://user-images.githubusercontent.com/31253976/71916518-b8219580-3143-11ea-885d-bc1deece3cee.png)

Scrolling back it is again the same error.
![image](https://user-images.githubusercontent.com/31253976/71916669-13538800-3144-11ea-870b-8ba73e8c114d.png)

Here is with minus after equals sign.
![image](https://user-images.githubusercontent.com/31253976/71916803-5d3c6e00-3144-11ea-93a9-975a8110f4db.png)

Fonts that are used.
![image](https://user-images.githubusercontent.com/31253976/71916897-8e1ca300-3144-11ea-8a87-c7305530309a.png)

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/72670473-5397ed80-3a03-11ea-98f1-56d7f35b6ac4.png)
This is still happening on my system.  You can also see that it is at the start of any term inside a fraction.  It is like the following term starts to soon.  The plus sign overlaps some of the following numbers.
The current system is still like the screenshots posted above.

I also have mu and omicron missing from the greek letters.
![image](https://user-images.githubusercontent.com/31253976/72670502-9063e480-3a03-11ea-8fde-2c2759496701.png)

**Comment by gunterkoenigsmann** [comment]
The missing letters can be re-enabled using the greek sidebar's right-click menu. But the plus sign overlapping something - that might hint at the direction I have to search the error in...

**Comment by gunterkoenigsmann** [comment]
I have tried to simplify the Code of TextCell.cpp in order to make searching for the bug there easier. ...and to me it looks like by doing this I have somehow resolved the problem. Is the problem resolved now for you, too?

**Comment by richardgobeli** [comment]
It looks great now.
Thanks!
![image](https://user-images.githubusercontent.com/31253976/73129420-ca575c80-3fa8-11ea-982f-716c248920c0.png)
![image](https://user-images.githubusercontent.com/31253976/73129418-c1668b00-3fa8-11ea-98c2-dc611831b370.png)
