### ISSUE TITLE
help points to wrong location (v 5.42.2, 5.43 not confirmed)

### ISSUE THREAD

**Issue by Hale812** [wxMaxima-developers/wxmaxima#1194]
In version 5.42.2 menu-help points to wrong location. While help files are present, they can not be read by user even in manual mode, because of non-traditional hhp format.
I could not confirm it in 5.43 branch, because it has broken locales, and unusable on my system.

**Comment by robert-dodier** [comment]
Hi, when you say that 5.43 has broken locales, can you be more specific? Is it a problem in Maxima itself, or in wxMaxima? Thank you for any information.

**Comment by Hale812** [comment]
I don't know such details. I use it in Windows, where they come in one bundle.

**Comment by KubaO** [comment]
@Hale812 Could you please try again with either the master branch or the nightly? I believe that this should be fixed now.

**Comment by gunterkoenigsmann** [comment]
I believed both issues are resolved in the current release: We now no more use wxWidget's help browser (which is based on an old webkit and broken in many ways), ask maxima for the help location and there was a complete re-write of the locale system.
