### ISSUE TITLE
Need guidance on implementation of XML for pre/post sub/superscripts

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1195]
I've pushed a new branch dodier-mmultiscripts-for-index-properties which has some modifications for wxMathML.lisp which output `mmultiscripts` for subscripted expressions for which index properties have been declared via `declare_index_properties`. When I load wxMathML.lisp into a console Maxima session and enter some subscripted expressions, I get output which is displayed correctly by Firefox (after changing `mth` to `math` and `f` to `mfrac` as needed). E.g. after `load("data/wxMathML.lisp")` I get the following output:

```
(%i2) declare_index_properties (bar, [presuperscript, presuperscript, postsubscript, postsubscript]);
<mth><lbl>(%o2) </lbl><mi>done</mi></mth>
(%i3) bar[a,b,c,d];
<mth><lbl>(%o3) </lbl><mmultiscripts><mi>bar</mi><mrow><mi>c</mi><mi>,</mi><mi>d</mi>
</mrow>
<none/>
<mprescripts/>
<none/><mrow><mi>a</mi><mi>,</mi><mi>b</mi>
</mrow>
</mmultiscripts>
</mth>
(%i4) 
```

and if I copy that into a file and open it with Firefox, I see `a` and `b` as presuperscripts, and `c` and `d` as postsubscripts, as expected.

When I load wxMathML.lisp into wxMaxima and try the same thing, I don't see that. Do I understand correctly that the `mmultiscripts` tag is not yet understood by the UI display? What else needs to be done in wxMathML.lisp in order to make the XML output suitable? Where do we go from here? Thanks for any guidance.

**Comment by gunterkoenigsmann** [comment]
Cool! Thanks a lot! 

Now I need a last pointer before I can adjust src/MathParser.cpp: 

     put(A, '[subscript, superscript, presuperscript, presubscript], 'display_indices);
     A[1][2][3][4];

doesn't result in the new tags being output but in an

     [mqapply,simp,array][4]

What am I doing the wrong way?

**Comment by robert-dodier** [comment]
Hi Gunter, I guess I should have made it clear, I think that the work on this new feature is unfinished, that's why I put it on a branch. But it has no effect unless the index properties are used, so maybe it won't cause any trouble.

Considering the example you gave. Index properties should be declared via `declare_index_properties` (I created that function some time ago so people don't have to use `put`). Also, in the example, `A` has 4 indices, so it's assumed you want to write `A[1, 2, 3, 4]` instead of `A[1][2][3][4]`.

`A[1][2][3][4]` should be handled in an appropriate way (with a descending trail of indices, as it is displayed in the console pretty printer) but that will not bring the declared index properties into play because there is only 1 subscript (namely 1) on `A`.

Note also that the post-subscript and post-superscript properties are named `postsubscript` and `postsuperscript`.

Try `declare_index_properties(A, [postsubscript, postsuperscript, presuperscript, presubscript])` and then `A[1, 2, 3, 4]`.

**Comment by gunterkoenigsmann** [comment]
I knew that the branch was experimental. But I consider Excel as highly experimental in respect to most experimental packages I've seen from you so I thought it was safe to try ;-)

Since I don't like if some program doesn't adher to standards where it could I've made the program now use `<math>` and `<frac>` instead of the `<mth>` and `<f>` tag which makes debugging the communication between maxima and wxMaxima easier.

After an

     declare_index_properties(A, [postsubscript, postsuperscript, presuperscript, presubscript]);

The XML monitor sidebar now says:

````
SENT TO MAXIMA:

A[1,2,3,4];

MAXIMA RESPONSE:

<math>
  <lbl>(%o2) </lbl>
  <munder>
   <mrow>
    <mi>A</mi>
    </mrow>
   <mrow>
    <mn>1</mn>
    <mi>,</mi>
    <mn>2</mn>
    <mi>,</mi>
    <mn>3</mn>
    <mi>,</mi>
    <mn>4</mn>
    </mrow>
   </munder>
  </math>
<PROMPT-P/>(%i3) <PROMPT-S/>
````

**Comment by gunterkoenigsmann** [comment]
Modified the code that the XML output you have posted here should produce a cell with correct pre-sub-and-superscripts. Copying and saving these cells requires more work from my side, though.

**Comment by gunterkoenigsmann** [comment]
I did forget to mention that copying and saving should also work. All that is left now is finding out why I get different XML output than you do. My guess is that it has to do with wxmathml.lisp being wrapped inside a big progn or with wxmathml.lisp being sent to wxMaxima inside a big :lisp command.

**Comment by robert-dodier** [comment]
Gunter, can you give an example of the problematic XML output and the Maxima input which leads to it. I would like to take another look at this topic but I'm not sure where things stand at this point.

**Comment by gunterkoenigsmann** [comment]
````
declare_index_properties(X,[presuperscript,presubscript,postsuperscript,postsubscript])$
X[presuperscript,presubscript,postsuperscript,postsubscript];
````
results in:
````
<mth>
  <lbl>(%o50) </lbl>
  <munder>
   <mrow>
    <mi>W</mi>
    </mrow>
   <mrow>
    <mi>presuperscript</mi>
    <mi>,</mi>
    <mi>presubscript</mi>
    <mi>,</mi>
    <mi>postsubscript</mi>
    <mi>,</mi>
    <mi>postsuperscript</mi>
    </mrow>
   </munder>
  </mth>
````
As far as I understand the XML output should have informed wxMaxima which is a presuperscript and so on.

I've put a test file containing all permutations of post-, and pre- super- and subscripts into the test folder: https://github.com/wxMaxima-developers/wxmaxima/blob/dodier-mmultiscripts-for-index-properties/test/automatic_test_files/presubsupcells.wxm 

One thing that might possibly be an additional bug - or rather lack of completeness might be that the following code produces an error:
````
for i in permutations([postsubscript, postsuperscript, presuperscript, presubscript]) do
    (
        declare_index_properties(A,i),
        A[i]
    );
````
But I might be wrong in this respect.

**Comment by gunterkoenigsmann** [comment]
Seems like the error was entirely on my side: After running data/update_wxmathml.sh everything seems to work fine. 

Thanks a lot for your support!
       Gunter.

**Comment by robert-dodier** [comment]
Hi Gunter, I am glad to hear that you got it working! About this code:
```
for i in permutations([postsubscript, postsuperscript, presuperscript, presubscript]) do
    (
        declare_index_properties(A,i),
        A[i]
    );
```
Because `declare_index_properties` is implemented as an argument-quoting function (in this respect it is the same as `declare`), you would have to ensure that `i` is evaluated. Also, when `i` is `[a, b, c, d]`, `A[i]` is `A[[a, b, c, d]]`, which isn't the same as `A[a, b, c, d]`. Similarly to `funmake`, you'll need to call `arraymake` to construct `A[a, b, c, d]`. Putting those together I get this:
```
for i in permutations([postsubscript, postsuperscript, presuperscript, presubscript]) do
 (apply (declare_index_properties, [A, i]), print (arraymake (A, i)));
```
(I also called `print` to display the result.) This is an interesting test case -- it should display the same thing every time even though the index properties are given in a different order.

**Comment by richardgobeli** [comment]
Is there a way to do this without inserting commas in the output and add only on comma for derivatives in the subscript.  The current display will not work for tensors.
![image](https://user-images.githubusercontent.com/31253976/75184425-f978ff00-5709-11ea-9432-7a42a9cb1c14.png)

**Comment by gunterkoenigsmann** [comment]
If the Problem is on the wxMaxima side I can replace the commas by spaces. Would that be better?

**Comment by robert-dodier** [comment]
There is already in the Maxima pat of the implementation a property named `display_index_separator`. I need to include the separator in the XML output. I can work on it in a day or two.

**Comment by richardgobeli** [comment]
This is the way it shows for tensors.  you also need a way to add a comma before the derivative indices at the end of the covariant indices.
![image](https://user-images.githubusercontent.com/31253976/75220311-c021ad00-5764-11ea-93c9-f79d81e3866c.png)

**Comment by gunterkoenigsmann** [comment]
@robert-dodier: Cool! Thanks a lot in advance!

**Comment by richardgobeli** [comment]
It alternates first down then up and then down again. <none/> does the blanks spaces.

This is section       3.4.7 Prescripts and Tensor Indices <mmultiscripts>, <mprescripts/>, <none/>

of this web site https://www.w3.org/TR/MathML3/Overview.html

**Comment by richardgobeli** [comment]
I just ran this and the display is wrong, but the mathml looks OK.
![image](https://user-images.githubusercontent.com/31253976/75293209-5dbfbf80-57eb-11ea-8974-fe46346af2c1.png)
![image](https://user-images.githubusercontent.com/31253976/75293278-7a5bf780-57eb-11ea-9c37-a57eb2e64957.png)

I also noticed that Robert coded it a bit different than the example in the MathML document.
Robert uses all subscripts first and then superscripts second and then pre-scripts at the end.

The example in the document alternated between subscript and superscript until done with the last superscript.

**Comment by gunterkoenigsmann** [comment]
The bug with multiple post-superscripts was in my code. The current Nightly Build should work fine now.

**Comment by robert-dodier** [comment]
Hi Gunter, hi Richard. I am working on incorporating the index separator character in wxMathML and I think I'll have it in a few days.

However, about displaying indices as raised or lowered, with a gap in some places, that's a functionality that is specific to tensors, and although the existing index display stuff can accommodate it, it will take some thinking to set up a user interface for that (that is, how does the user tell Maxima that some object is a tensor and therefore the indices should be handled in a certain way). `declare_index_properties` is a way to implement that stuff, but by itself it's not enough -- you wouldn't want users to struggle with the details. 

At this point I think a new feature request for tensor-specific stuff is the best way to proceed.

**Comment by gunterkoenigsmann** [comment]
I hope I didn't cause additional work by merging the changes in master into your branch so you won't have to work around the bug Richard has found. For the tensor stuff I agree with you: If the framework is in place that displays them in a nice way that is but a first step. But as always you never know in which additional places these first steps will prove useful.

**Comment by richardgobeli** [comment]
The package itensor has a function ishow(R([i,-j,k,l],[],div1,div2)) that takes the tensor and uses lisp to output the correct mathml code.  Tensors are hashed arrays with two lists of indices and followed with list of dervictive indices.  
The first list is the covariant indices with contravariant indices as minus indices followed by the list of contravariant indices and then derivative indices. The second list is the older style of contravariant indices.  The style putting contravariant indices in the covariant list with minus sign is to show the correct order of all indices. The order is important.   
The itensor package will need to be reworked to use the new code that is now being added.  It would be nice if the tensors had a property that would make wxmaxima automatically display correctly without having to use ishow.    

The above tensor would be output as R_i^j_k_l,_div1_div2 currently. Where ^ is superscript and _is subscript.  The superscript cannot be above any subscript.  It needs to be either before or after a subscript depending on the order of the indices.

I don't think the current postscript functions limit the positions of the superscript compared to the positions of the subscripts.

**Comment by robert-dodier** [comment]
I've pushed commit 8f77404 which makes MathML output honor the property `display_index_separator`. There are some examples in the commit message.

`display_index_separator` isn't documented, so I guess I need to write a description for it. Anyway it is pretty straightforward.

I'm closing this issue since this completes the implementation of the existing index display stuff. I would like to suggest that new issues be opened to cover any bugs or new features that are needed. Richard, thank you for your notes on the tensor package. I will take a look at the existing tensor code in Maxima.

**Comment by gunterkoenigsmann** [comment]
Cool! Thanks a lot! Will make a new wxMaxima release that contains the changes as soon as possible.
