### ISSUE TITLE
wxMaxima does not close Maxima on closing

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1199]
>When starting wxMaxima by opening (double-click) a .wxmx file these processes has been initiated:
![image](https://user-images.githubusercontent.com/2638713/72418719-ad868200-377b-11ea-9c6a-4914087479a6.png)
After having executed a Maxima function, this is what i running on the PC:
![image](https://user-images.githubusercontent.com/2638713/72418388-07d31300-377b-11ea-882f-67f3df083655.png)
However after closing wxMaxima it still leaves this running and thus preventing a new session:
![image](https://user-images.githubusercontent.com/2638713/72418455-26390e80-377b-11ea-8071-e5039fe39816.png)
Afterwards, when re-opening wxMaxima, it refuses to execute any Maxima commands until I manually kills the sbcl.exe previously left behind.
---------
>If I on the other hand just start wxMaxima (with a empty worksheet) this is seen:
![image](https://user-images.githubusercontent.com/2638713/72419321-e4a96300-377c-11ea-9bb1-2fdfd03541ed.png)
Running some Maxima functions does not start any extra sbcl.exe and the whole wxMaxima/Maxima complex shuts down as expected.

>Also, if I start wxMaxima and opens a file form within wxMaxima, it also works fine.

> Drag and drop also works fine.
------
So it seems like the double-click (opening a file on he command line) initiates an extra sbcl.exe where one of them is not being used.
---------
wxMaxima version: 20.01.2-DevelopmentSnapshot
using wxWidgets version: wxWidgets 3.1.3
Maxima version: branch_5_43_base_264_g292ed6cfd
Maxima build date: 2020-01-15 00:05:44
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxxxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

**Comment by ReneSci** [comment]
No - it still leaves a sbcl.exe behind when closed:
![image](https://user-images.githubusercontent.com/2638713/72527405-f700cb00-3868-11ea-9f0c-88daaba1e45f.png)
One for each time wxMaxima is opened:
![image](https://user-images.githubusercontent.com/2638713/72527432-0d0e8b80-3869-11ea-9d8a-06b5f3f11c2e.png)

However, now the next session works normally, so the user will not see the sbcl.exe left behind.
And - still this only happens when the windows double-click is used to open a wxmx file.

**Comment by daute** [comment]
This issue is hopefully finally solved with commit https://github.com/wxMaxima-developers/wxmaxima/commit/5afbd676103a77d51ce092e7597727bb14862f8a.
