### ISSUE TITLE
Copy text when in Full Screen mode

### ISSUE THREAD

**Issue by andrejv** [wxMaxima-developers/wxmaxima#120]
Converted from [SourceForge issue 3282271](http://sourceforge.net/support/tracker.php?aid=3282271), submitted by mitreude

When using the Full Screen mode in wxMaxima and you select text, the selected text is not copied to the clipboard when pressing CTRL+C.  The CTRL+X cut command also does not cut selected text when in Full Screen mode.

Maxima version: 5.24.0
Maxima build date: 18:27 4/5/2011
Host type: i686-pc-mingw32
Lisp implementation type: Clozure Common Lisp
Lisp implementation version: Version 1.7-dev-r14645M-trunk  (WindowsX8632)

**Comment by gunterkoenigsmann** [comment]
Does work on my linux box. Could be that this bug has been fixed since it was reported.

**Comment by KubaO** [comment]
This is fixed in the master.
