### ISSUE TITLE
Can not run two or more sessions simultaneously

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1200]
The second session can not execute Maxima commands (freezes) until the first session is closed:

![image](https://user-images.githubusercontent.com/2638713/72420806-a6617300-377f-11ea-8d23-86394a98c41b.png)

However, it seems to start up ok:
![image](https://user-images.githubusercontent.com/2638713/72421047-17a12600-3780-11ea-9e3f-252b0af3b7ed.png)
Upon closing the second session, it leaves some mess:

![image](https://user-images.githubusercontent.com/2638713/72421333-939b6e00-3780-11ea-97b3-c47ea51279fb.png)

When closing the first session, which runs ok, it cleans it all and leave no residue processes.

-----
wxMaxima version: 20.01.2-DevelopmentSnapshot
using wxWidgets version: wxWidgets 3.1.3
Maxima version: branch_5_43_base_264_g292ed6cfd
Maxima build date: 2020-01-15 00:05:44
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxxxxx/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
Force-Closing applications on Windows is surprisingly hard. But the info that it maxima is closed under some circumstances and not under others might have pointed me to a completely different issue. Hope in the next nightly build this issue no more occurs.

**Comment by ReneSci** [comment]
It is my impression that the fault happens during start-up of wxMaxima:
When double-click is used to open a worksheet, wxMaxima immediately starts
two sbcl.exe processes (where one of them is "lost") whereas if wxMaxima is
opened with an empty worksheet, it only initiates one sbcl.exe process as I
think is the right behavior.

Den tor. 16. jan. 2020 kl. 17.41 skrev Gunter Königsman <
notifications@github.com>:

**Comment by ReneSci** [comment]
It sill leaves the "lost" sbcl.exe proces behind, but it only uses the first one for doing calculations:
![image](https://user-images.githubusercontent.com/2638713/72600687-68e21e80-3914-11ea-97de-3214f444a36e.png)
When "killing" Maxima from within wxMaxima ("completely stop Maxima and restart it") only kills the one in use, the other is left. wxMaxima starts a new Maxima (sbcl.exe) right after stopping the sbcl.exe in use - but this new one can apparently not be used:
![image](https://user-images.githubusercontent.com/2638713/72601065-fd4c8100-3914-11ea-8c34-d94e6d085b6b.png)
Closing wxMaxima now leaces two sbcl.exe behind - the one not used during the start-up and the newly created but not usable:
![image](https://user-images.githubusercontent.com/2638713/72601133-1ead6d00-3915-11ea-82d2-8852209732ed.png)

**Comment by richardgobeli** [comment]
This version for me is now working again.
I can have more than 1 window connected to maxima and it also can do independent calculations.

![image](https://user-images.githubusercontent.com/31253976/72907355-5a6f7a80-3cf9-11ea-811f-0fea6e2c4d62.png)

**Comment by ReneSci** [comment]
Mee too, however it still starts up an extra maxima as discussed in
https://github.com/wxMaxima-developers/wxmaxima/issues/1202
and
https://github.com/wxMaxima-developers/wxmaxima/issues/1200

**Comment by richardgobeli** [comment]
For me in the task manager the sbcl is sometimes shown as an attached thread to wxmaxima and other times it is shown as an independent task.
When shown as a separate task it still gets killed with the main wxmaxima task.
Here one is shown as a thread and the other is separate task.
![image](https://user-images.githubusercontent.com/31253976/73003244-e8676600-3dca-11ea-9532-f3817f7caccf.png)
I don't know if this is an issue with thread linking.

**Comment by ReneSci** [comment]
I the latest versions, two or more sessions can run just fine again, however:
Remember it only does the extra SBCL.exe - thing when a *.wxmx file is opened by double-clicking.
Here, the topmost wxMaxima has been started by just starting wxMaxima and run a plot sin(x) command
The one below has been started by double-clicking a wxmx whorksheet
![image](https://user-images.githubusercontent.com/2638713/73068696-21c3d280-3eac-11ea-9122-518e5307799c.png)

After closing both of them, the latter leaves behind the additional sbcl.exe:
![image](https://user-images.githubusercontent.com/2638713/73068743-40c26480-3eac-11ea-9f33-b8497b7c8bed.png)

**Comment by gunterkoenigsmann** [comment]
The hint that that only happens when double-clicking files was really valuable.

**Comment by ReneSci** [comment]
Great :-)

lør. 25. jan. 2020 11.46 skrev Gunter Königsman <notifications@github.com>:
