### ISSUE TITLE
MacOS DMG does not contain app

### ISSUE THREAD

**Issue by pietvo** [wxMaxima-developers/wxmaxima#1201]
The MacOS DMG file (`https://github.com/wxMaxima-developers/wxmaxima/releases/download/Version-20.01.2/wxMaxima.dmg`) in the new release does not contain a `wxMaxima.app`.
Moreover, when the DMG is opened, its title is `wxmaxima-19.11.0-Darwin` (not `20,01,2`).

**Comment by gunterkoenigsmann** [comment]
That would explain why the dmg is so small...
...and the error clearly is in CmakeLists.txt. But not owning a mac I cannot guarantee that I can correct this issue.

**Comment by gunterkoenigsmann** [comment]
I *think* the first part of my idea to make the .app work might have been right. But I'm still struggling with the 2nd part of the idea that makes it build again.

**Comment by pietvo** [comment]
> Might be the solution for #1201. If that is true
http://www.peterpall.de/wxMaxima/nightly/wxMaxima.dmg will contain
a working .dmg within about 20 minutes.

No, but there isn't a new DMG there. It is still the old one and the files are from November 12.

**Comment by gunterkoenigsmann** [comment]
About 30 trys later the DMG image has changed from 6 Megabytes to 15 Megabytes. I hope that is a good sign: Not owning a Mac all I can do in this case is to make educated guesses and to look if the logs from the CI running a virtual mac tell me if everything went smoothly - which is a time-consuming proces, alas!

**Comment by pietvo** [comment]
It doesn't have the required directory structure inside the .app. So it will not run properly. It does start up but then it gives an error that it cannot open maxima.
Also in the top level of the DMG there are a lot of files that should be inside the app in proper directories.
And then there are no libraries in the app, so these would have to be found somewhere on the system. But these could be in different places on different systems or not present at all. I think a proper app must be self-contained, i.e. it must include all required libraries (for example wxWidgets).

**Comment by gunterkoenigsmann** [comment]
The problem with the missing maxima I can explain: wxMaxima is a graphical front-end for maxima - but comes without maxima, which is a separate application.

About the libraries: https://travis-ci.org/wxMaxima-developers/wxmaxima/jobs/643119534 seems to indicate that the app should contain the .dylib files;

Which files lie in the .dmg instead of the .app? I still haven't found a way to look into the .dmg - but this error might be easier to resolve than the others.

**Comment by pietvo** [comment]
Here is the directory listing:

[dirlisting.txt](https://github.com/wxMaxima-developers/wxmaxima/files/4125202/dirlisting.txt)

**Comment by pietvo** [comment]
The reason it didn't find maxima, is that I have it in a not so standard location: /opt/local/bin/maxima. This is the location of Macports, which isn't one of the locations that wxMaxima is looking for. It would be nice if wxMaxima could search the PATHJ,but I could solve it by specifying it in the Preferences. It would be nice if the error message would suggest that.
