### ISSUE TITLE
wxWidgets Debug Alert

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1208]
![image](https://user-images.githubusercontent.com/2638713/74643525-2874fb00-5175-11ea-9d07-051963424122.png)

Click "NO", then:
![image](https://user-images.githubusercontent.com/2638713/74643659-62460180-5175-11ea-99fe-0179010739c9.png)

Click "NO" then it seems to run ok.....

(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_339_g2816834ef",timestamp="2020-02-17 00:04:13",host="x86_64-w64-mingw32",lisp_name="SBCL",
lisp_version="2.0.0",maxima_userdir="C:/Users/u265227/maxima",maxima_tempdir="C:/Users/u265227/AppData/Local/Temp",maxima_objdir=
"C:/Users/XXX/maxima/binary/branch_5_43_base_339_g2816834ef/sbcl/2_0_0",maxima_frontend="wxMaxima",maxima_frontend_version=
"20.02.1-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by ReneSci** [comment]
Hmm... its still there:
![image](https://user-images.githubusercontent.com/2638713/74737435-22564b80-5255-11ea-902b-0ab36ce1f19a.png)
![image](https://user-images.githubusercontent.com/2638713/74737464-3437ee80-5255-11ea-90f6-c3c515a264ba.png)

(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_341_g58a173a1f",timestamp="2020-02-18 00:05:55",host="x86_64-w64-mingw32",lisp_name="SBCL",
lisp_version="2.0.0",maxima_userdir="C:/Users/u265227/maxima",maxima_tempdir="C:/Users/u265227/AppData/Local/Temp",maxima_objdir=
"C:/Users/XXX/maxima/binary/branch_5_43_base_341_g58a173a1f/sbcl/2_0_0",maxima_frontend="wxMaxima",maxima_frontend_version=
"20.02.1-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment]
Thanks for testing and for reporting this bug. I believe I have now found the place the problem occurred in.

**Comment by ReneSci** [comment]
Yes - it seems to work ok now.
