### ISSUE TITLE
Command 'to export'

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1209]
Hello,
the command 'to export' is not working.

**Comment by ljselmaier** [comment]
Hallo,
the command 'to export' is working now ( Version: 20.02.2 ).  But the selection don't work correctly. 

![Selection](https://user-images.githubusercontent.com/59099908/74938650-b3acf580-53ee-11ea-8a20-57bbfe30cdf0.jpg)

**Comment by ljselmaier** [comment]
Sorry, I would not closed.

**Comment by gunterkoenigsmann** [comment]
I am not sure if the drop-down box is supposed to change the extension or if it is only supposed to change the filter that chooses which files are to be displayed: I originally thought it should change the extension. But the wxWidgets maintainers told me that that would be a good idea but currently doesn't match the operating system's philosophy...

**Comment by ljselmaier** [comment]
OK, Thanks for the answer.
