### ISSUE TITLE
Incon has disappeared

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1210]
It seems like the wxMaxima icon has disappeared during the latest nightly builds.
Windows 10 now uses some standard icon.

**Comment by gunterkoenigsmann** [comment]
That might have been caused by me trying to make the build system find wxMaxima's icon in the out-of-tree-build whilst using the high-dpi manifest wxWidgets provides. Let's hope I found out how to fix it.

**Comment by ReneSci** [comment]
Yes, you got it.
