### ISSUE TITLE
menu: wxMaxima help calls up Maxima help instead

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1213]
So - wxMaxima help can not be reached

(%i2)	build_info();
(%o2)	build_info(version="branch_5_43_base_363_gbfed0b51b",timestamp="2020-02-25 00:04:11",host="x86_64-w64-mingw32",lisp_name="SBCL",
lisp_version="2.0.0",maxima_userdir="C:/Users/xxxxx/maxima",maxima_tempdir="C:/Users/u265227/AppData/Local/Temp",maxima_objdir=
"C:/Users/u265227/maxima/binary/branch_5_43_base_363_gbfed0b51b/sbcl/2_0_0",maxima_frontend="wxMaxima",maxima_frontend_version=
"20.02.4_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment]
In recent-enough wxMaxima versions the "debug messages" sidebar should document all of wxMaxima's decisions that lead to this error. With a bit of luck I did my jog right there and we'll find out what's going on.

**Comment by ReneSci** [comment]
Does this  make sense ?
![image](https://user-images.githubusercontent.com/2638713/75388566-8330f400-58e5-11ea-8901-b64ac1319003.png)

**Comment by gunterkoenigsmann** [comment]
It seems to search for maxima's help file - but not for the wxMaxima one. On my computer I can choose if I want to open the maxima or the wxMaxima manual - except if wxMaxima is convinced that the text the cursor is on might indicate that the maxima manual might be the better place to go. Perhaps that heuristics should be improved...
