### ISSUE TITLE
option for choosing autosave on/off has disapeard

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1216]
Can not find the option to turn autosave off ?

**Comment by gunterkoenigsmann** [comment]
It should reside under "Options/Save the worksheet automatically."

**Comment by ReneSci** [comment]
Found it - sorry.
But although autosave is disabled, is still seem so autosave?
[image: image.png]
[image: image.png]




Den fre. 28. feb. 2020 kl. 15.33 skrev Gunter Königsman <
notifications@github.com>:

**Comment by ReneSci** [comment]
Autosave seems to be ok now, however something that might be related to #1211 is happening now - please see #1211
