### ISSUE TITLE
wxmaxima help

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1217]
The links in wxMaxima help don't work.

![Error_2](https://user-images.githubusercontent.com/59099908/75781370-548ba100-5d5d-11ea-8efe-121b42a8e5ed.jpg)

**Comment by gunterkoenigsmann** [comment]
I hate that integrated help browser wxWidgets provides as it tends to be broken somehow. ...but making the default web browser jump to the right place has proved to be kind of had, too => I cannot guarantee when a better option is available. But as knowing that there is a problem is the first step in solving it I can at least thank you for having done the first step.

**Comment by ljselmaier** [comment]
In the old version the links works.

![wxMaxima_help](https://user-images.githubusercontent.com/59099908/75818067-8cfca080-5d98-11ea-98f0-d27171e45133.jpg)
