### ISSUE TITLE
wxMaxima crash on CTRL+C or CTRL+X on Windows 10

### ISSUE THREAD

**Issue by haubmi** [wxMaxima-developers/wxmaxima#1223]
Crash imediatedly closing the window, when CTRL-C or CTRL-X is pressed if e.g. something like this is marked:
![image](https://user-images.githubusercontent.com/62029826/76342459-ec116680-62fe-11ea-9deb-43d3c85998de.png)

Sorry can't cut and paste here because it crashes.

wxMaxima version: 20.02.4_MSW
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.43.2
Maxima build date: 2020-01-27 18:44:09
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxx/maxima/
Help dir: C:\wxmaxima\share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
I am convinced that I haven't touched anything near that code for a very long time. ...and I cannot reproduce this problem on linux - which is bad, because else gdb would have told me which line of code the problem resides in.

Do you happen to have a gdb64 (from msys64, mingw or something) installed on your system?

**Comment by haubmi** [comment]
No sorry I don't have no software development system installed. So no gdb64.
This is the PC at work. I'm not supposed to develop software. So can't be installed.

I have an older version too, which doesn't crash:
wxMaxima version: 19.05.7
using wxWidgets version: wxWidgets 3.1.0
Maxima version: 5.43.2
Maxima build date: 2020-01-27 18:44:09
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\xxx/maxima/
Help dir: C:\maxima-5.43.2\_old\wxMaxima/help

Also this version doesn't crash:
wxMaxima version: 19.05.7
using wxWidgets version: wxWidgets 3.1.0
Maxima version: 5.43.2
Maxima build date: 2020-01-27 18:44:09
Host type: x86_64-w64-mingw32
System type: Win32 10.0.17134 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\haub_m/maxima/
Help dir: C:\maxima-5.43.2\_old\maxima-5.43.0\wxMaxima/help

**Comment by haubmi** [comment]
I have stripped down the problem a bit:
It happens when you try to CTRL+C or CTRL+X a single "%" sign only!
![image](https://user-images.githubusercontent.com/62029826/76417959-19f9b800-639e-11ea-813a-7ed4b03634b9.png)
So any selection including a "%" sign crashes.

May be it has something to do with uincode support recently discussed.

**Comment by haubmi** [comment]
![image](https://user-images.githubusercontent.com/62029826/76430038-2424b200-63b0-11ea-85d5-f80f695c5c1e.png)

**Comment by gunterkoenigsmann** [comment]
Cool! I cannot reproduce the crash but I see every type of strange behavior where you see the crash => I guess you have found a way to make my computer misbehave which is the 1st step in solving the problem. Currently I see weird behavior in a second place so I cannot guarantee if I will be able to resolve the problem today or tomorrow. But the odds are good that I'll find the error you have found.

**Comment by gunterkoenigsmann** [comment]
Actually you found a whole class of small bugs that could cause crashes. Thanks a lot! 
Tomorrow's nightly build should finally be free of this issue.
