### ISSUE TITLE
Segmentation fault on FreeBSD

### ISSUE THREAD

**Issue by lsalvadore** [wxMaxima-developers/wxmaxima#1224]
Hello, I am the maintainer for the port of wxmaxima on FreeBSD. We are experiencing a segmentation fault due to function wxStandardPaths::Get().GetExecutablePath() in src/Dirstructure.cpp.
Please see the details at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244464 .

**Comment by gunterkoenigsmann** [comment]
Maintainers are important.

But do I understand it right that the function wxStandardPaths::Get().GetExecutablePath() itself crashes - or does it return an invalid string that causes the crash? Both cases would be bugs in wxWidgets, most probably as wxStandardPaths::Get().GetExecutablePath() should just return the value of argv[0]...

**Comment by lsalvadore** [comment]
It returns an empty string, so that
- `wxArrayString dirs = exe.GetDirs()` is an empty array;
- `if((dirs.Last().Upper() == wxT("SRC")) || (dirs.Last().Upper() == wxT("BIN")))` causes segmentation fault.

It does not seem to be a bug in wxWidgets: please see comment 14 and comment 16 in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244464 .

**Comment by lsalvadore** [comment]
I fear there is a bit more work to do on that bug: it's still broken for me. May I ask you how did you test your commit?

**Comment by gunterkoenigsmann** [comment]
On Linux it works fine ;-(

**Comment by gunterkoenigsmann** [comment]
Changed the only thing that was very slightly suspicious.

Do you happen to have a gdb or similar debugger that can make a backtrace? In order to make this backtrace compile the line number the segfault happens in cmake has to be run with the option

       -DCMAKE_BUILD_TYPE=debug

Once the place the crash happens in is known it normally is trivial to fix (at least if it is in wxMaxima and not in a totally different place of the system). If the place isn't known the amount of code that is involved in copying text isn't exactly big - but I completely fail to find an error in it.

**Comment by lsalvadore** [comment]
We already did a backtrace: please see comment 5 in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244464 .

**Comment by gunterkoenigsmann** [comment]
This backtrace was made after cmake was run with 

        -DCMAKE_BUILD_TYPE=release

instead of with

        -DCMAKE_BUILD_TYPE=debug

That means the backtrace tells at which address in gtk the crash has happened but neither why that happens nor which pieces of code were involved.

**Comment by lsalvadore** [comment]
Ah, you're right! I will soon post here a backtrace with `-DCMAKE_BUILD_TYPE=debug`.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot in advance!

**Comment by gunterkoenigsmann** [comment]
Arrgh! I have just seen that I missed the mail you described the complete solution in. Sorry for that. The issue should now finally be resolved.

**Comment by lsalvadore** [comment]
I confirm that the issue is now fixed. Thanks!

**Comment by gunterkoenigsmann** [comment]
Loads of thanks to you for doing all the debugging and finding the bug location for me!
