### ISSUE TITLE
"Match parenthesis in text controls" option does not work

### ISSUE THREAD

**Issue by pcurrivan** [wxMaxima-developers/wxmaxima#1225]
When I uncheck this option in the configure menu and click OK, it does not take effect.  When I open configure again it is still checked.  Other configure options seem to work normally.

wxMaxima 19.05.7
wxWidgets: 3.1.0
Unicode Support: yes
Maxima version: 5.43.2 (x86_64-w64-mingw32)
Lisp: SBCL 1.4.14

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this report! I hope this is resolved with commit 260d4097..907f85fa I just made.
