### ISSUE TITLE
the 'Default style', is it unused?

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1231]
A suggestion for another minor enhancement.
There's the 'Default' style, initialised as 'colour black+bold+italic' and saved in the config file in the '[Style]' section. This style doesn't seem to be used at all.
Maybe remove it from the configuration dialog and from the config file?
If it's impossible to remove it from the config file (looks like it's the root style for everything else?), add a auto-generated comment in the config file auto-generation code, explaining what this is and what it does. Like, 'This style is auto-generated but is not used. Leave it as it is.'

(are comments possible in config file at all?)

**Comment by gunterkoenigsmann** [comment]
Unfortunately the config file handling of wxWidgets doesn't support comments. But I guess the rest of this issue is resolved now in the current wxMaxima master.
