### ISSUE TITLE
Starting a lot of threads

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1236]
Below is a copy of "Debug messages" just after opening wxMaxima with a worksheet. Is seems like a lot of threads are initiated - are they all closed again ?
- just a question. Didn't know where to put it.
-------------------------------------------------------
12:24:55: wxMaxima version 20.03.1-DevelopmentSnapshot
12:24:55: Running on MS Windows
12:24:55: wxWidgets 3.1.3
12:24:55: Translations are read from C:\maxima-current\share/locale.
12:24:55: Reading the config from the default location.
12:24:56: Selected language: en_GB (57)
12:24:56: LANG=en_GB
12:24:56: Starting server on port 4010
12:24:56: Server started
12:24:57: Opening a wxmx file
12:24:57: Opening file
12:25:01: Starting background thread that loads an image
12:25:01: Starting background task that loads the gnuplot data for a plot.
12:25:01: Starting background thread that loads an image
12:25:01: Starting background task that loads the gnuplot data for a plot.
12:25:01: Starting background thread that loads an image
12:25:01: Starting background task that loads the gnuplot data for a plot.
12:25:01: Starting background thread that loads an image
12:25:01: Starting background task that loads the gnuplot data for a plot.
12:25:01: Starting background thread that loads an image
12:25:01: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:02: Starting background thread that loads an image
12:25:02: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background thread that loads an image
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:03: Starting background task that loads the gnuplot data for a plot.
12:25:03: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background task that loads the gnuplot data for a plot.
12:25:04: Starting background thread that loads an image
12:25:04: Starting background thread that loads an image
12:25:04: Starting background thread that loads an image
12:25:05: Starting background thread that loads an image
12:25:05: Starting background thread that loads an image
12:25:06: Starting background thread that loads an image
12:25:06: Starting background thread that loads an image
12:25:06: Starting background thread that loads an image
12:25:06: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:07: Starting background thread that loads an image
12:25:09: Starting background thread that loads an image
12:25:09: Starting background thread that loads an image
12:25:09: Running maxima as: "C:\maxima-current\bin\maxima.bat"  -s 4010 
12:25:10: File opened
12:25:12: Connected.
12:25:12: Setting a few prerequisites for wxMaxima
12:25:12: Sending maxima the info how to express 2d maths as XML
12:25:12: Updating maxima's configuration
12:25:12: Sending configuration data to maxima.
12:25:12: Telling maxima about the new working directory.
12:25:12: Received maxima's first prompt: pid=11192â†²Maxima branch_5_43_base_426_g4417b69e4 http://maxima.sourceforge.netâ†²using Lisp SBCL 2.0.0â†²Distributed under the GNU Public License. See the file COPYING.â†²Dedicated to the memory of William Schelter.â†²The function bug_report() provides bug reporting information.â†²(11) <suppress
12:25:12: Maxima's PID is 11192
12:25:16: Starting a background task that compiles a new list of autocompletible maxima commands.
12:25:16: Maxima user configuration lies in directory C:/Users/xxxxx/maxima
12:25:16: Maxima uses temp directory C:/Users/xxxxx/AppData/Local/Temp
12:25:16: Maxima's manual lies in directory C:/maxima-current/share/info
12:25:16: Gnuplot can be found at gnuplot
12:25:16: Maxima's share files lie in directory C:/maxima-current/share/maxima/branch_5_43_base_426_g4417b69e4/share
12:25:16: Starting a background task that setups the autocomplete builtins list.
12:25:16: Starting a background task that setups the autocompletable files list.
12:25:16: Maxima version: branch_5_43_base_426_g4417b69e4
12:25:16: Maxima architecture: x86_64-w64-mingw32
12:25:16: Maxima was compiled using SBCL
12:25:16: Lisp version: 2.0.0
12:25:16: Maxima sends a new set of auto-completable symbols.
12:25:16: Maxima user configuration lies in directory C:/Users/xxxxx/maxima
12:25:16: Maxima uses temp directory C:/Users/xxxxx/AppData/Local/Temp
12:25:16: Maxima's manual lies in directory C:/maxima-current/share/info
12:25:16: Gnuplot can be found at gnuplot
12:25:16: Maxima's share files lie in directory C:/maxima-current/share/maxima/branch_5_43_base_426_g4417b69e4/share
12:25:16: Starting a background task that setups the autocomplete builtins list.
12:25:16: Starting a background task that setups the autocompletable files list.
12:25:16: Maxima version: branch_5_43_base_426_g4417b69e4
12:25:16: Maxima architecture: x86_64-w64-mingw32
12:25:16: Maxima was compiled using SBCL
12:25:16: Lisp version: 2.0.0
12:25:16: Maxima sends a new set of auto-completable symbols.
12:25:16: Maxima has sent a new variable value.
12:25:16: Autocompletion: Scanning C:\maxima-current\share\maxima\branch_5_43_base_426_g4417b69e4\share\ recursively for loadable lisp files.
12:25:16: Trying to load a list of autocompletible symbols from file C:/Users/xxxxx/maxima/wxmaxima.ac
12:25:16: Autocompletion: Scanning C:\Users\xxxxx\maxima\ for loadable lisp files.
12:25:16: Found 1041 loadable files.
12:25:16: Autocompletion: Scanning C:\maxima-current\share\maxima\branch_5_43_base_426_g4417b69e4\ for loadable demo files.
12:25:16: Trying to load a list of autocompletible symbols from file C:/Users/xxxxx/maxima/wxmaxima.ac
12:25:16: Found 111 demo files.
12:25:16: Autocompletion: Scanning C:\maxima-current\share\maxima\branch_5_43_base_426_g4417b69e4\share\ recursively for loadable lisp files.
12:25:16: Autocompletion: Scanning C:\Users\xxxxx\maxima\ for loadable lisp files.
12:25:16: Found 1041 loadable files.
12:25:16: Autocompletion: Scanning C:\maxima-current\share\maxima\branch_5_43_base_426_g4417b69e4\ for loadable demo files.
12:25:16: Found 111 demo files.
12:25:16: Ready for user input
12:25:16: Maxima is ready for input.
12:25:20: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
12:25:20: Searching for maxima help file C:/maxima-current/share/info/maxima.hhp
12:25:20: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
12:25:20: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
12:25:20: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
12:25:20: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_43_base_426_g4417b69e4/share/../doc/html/maxima_singlepage.html
12:25:20: Compiling the list of anchors the maxima manual provides

**Comment by gunterkoenigsmann** [comment]
They are closed - but I wasn't sure if that info is helpful or if it just makes the log longer. If you tell me it is helpful I will add the corresponding messages.

**Comment by ReneSci** [comment]
No, its ok.

**Comment by KubaO** [comment]
Part of the problem is that no sane OpenMP implementation is spawning actual threads like that. Typical implementations have a thread pool and queue work items for available worker threads, rather than constantly spawning and terminating actual platform threads. So this message is misleading: what is started is a task, not a thread.

**Comment by gunterkoenigsmann** [comment]
Actually I chose OpenMP since it won't start more threads than there are processors - except if asked to do so using the OpenMP environment variables.

**Comment by KubaO** [comment]
That’s exactly how it needs to be :) Eventually we should port it all to C++11 concurrency primitives, since they are available, but it won’t improve anything by itself.

**Comment by gunterkoenigsmann** [comment]
Changed the messages to "Scheduling thread". I believe that makes their meanings clearer.
