### ISSUE TITLE
Latest Release version  in https://wxmaxima-developers.github.io/wxmaxima/download.html is outdated

### ISSUE THREAD

**Issue by shlomif** [wxMaxima-developers/wxmaxima#1238]
In https://wxmaxima-developers.github.io/wxmaxima/download.html it says 20.01.1 but there is 20.03.1 in https://github.com/wxMaxima-developers/wxmaxima/releases . Furthermore, note that [GitHub](https://en.wikipedia.org/wiki/GitHub) has a capital "H".

Please fix it.

**Comment by daute** [comment]
Fixed. Thank you for the notification.
Best regards, Wolfgang

**Comment by shlomif** [comment]
On Fri, 17 Apr 2020 11:38:30 -0700
Wolfgang Dautermann <notifications@github.com> wrote:

> Fixed. Thank you for the notification.
> Best regards, Wolfgang
> 

Thanks, Wolfgang!

-- 

Shlomi Fish       https://www.shlomifish.org/
Interview with Ben Collins-Sussman - https://shlom.in/sussman

The first phrase that needs to be taught when teaching a new language is how to
say “Do you speak English?”. The first thing that needs to be taught when
teaching a new computer tool is how to exit it.
    — https://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .
