### ISSUE TITLE
NumPad Enter key no longer evaluates cell

### ISSUE THREAD

**Issue by archbugaboo** [wxMaxima-developers/wxmaxima#1239]
Hello

This is a very minor issue, I hesitated to write it, but until now, wxMaxima evaluated the cell with `NumPad Enter`, and the regular `Enter` simply broke the line. Today I have updated on Archlinux to:

`build_info(version="5.43.2",timestamp="2020-04-04 09:55:38",host="x86_64-unknown-linux-gnu",lisp_name="SBCL",lisp_version="2.0.3",maxima_userdir="/home/user/.maxima",maxima_tempdir="/tmp",maxima_objdir="/home/user/.maxima/binary/5_43_2/sbcl/2_0_3",maxima_frontend="wxMaxima",maxima_frontend_version="20.03.1_GTK3_OpenMP201511+Locks")`

and both `Enter` keys require either to press `Ctrl`, or `Shift` to evaluate, and both break the line when no modifier key is pressed, "*Enter evaluates cells*" is unchecked, always was, and this behaviour had been like this for as long as I remember, it's practically a reflex now. As I said, it's a minor thing, but I'd like this behaviour back.

The only similar issue seemes to have been in [2018](https://github.com/wxMaxima-developers/wxmaxima/issues/84), and, unless someone else is interested in it, it doesn't seem to warrant an official change, so I'd gladly settle for a pointer to the right source file where I can modify this and compile it myself.

Regards,
Vlad

**Comment by David-UPCT** [comment]
Same problem here, also with archlinux. 

Of course it's a matter of taste and it depends on the developers', but I wouldn't say it's a very minor issue. After using wxmaxima for 10 years, I'm using to pressing NumPad Intro to evaluate, for me it wouldn't be easy to change and now to press Shift+Enter. I'd really appreciate if this change would be reverted, or at least, if it could be done in the Preferences.

**Comment by gunterkoenigsmann** [comment]
Arrgh! Seems like my answer to this issue never arrived. Sorry for that!

I don't own a numpad enter so I wasn't aware that this key is actually handled in an useful way. Seems like trying to simplify the logic I somehow missed this detail, therefore...
