### ISSUE TITLE
All symbols and variables (other than numbers) missing from printout of session

### ISSUE THREAD

**Issue by rknop** [wxMaxima-developers/wxmaxima#1241]
When I print out a maxima session -- in this case, "print to file", printing to a PDF file, in the displayed equations all of the variables and symbols are simply blank.  Numbers, however, show up.  I've attached a sample .wxmx file and corresponding .pdf file that demonstrates the issue.

I've had this problem on and off with wxmaxima for years.  I'm currently using 20.03.1, and am on Linux (Devuan ascii).
[printdemo_wxmx.zip](https://github.com/wxMaxima-developers/wxmaxima/files/4482929/printdemo_wxmx.zip)
[printdemo.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/4482930/printdemo.pdf)

  What's weird is that sometimes, on some systems, the problem goes away.  I can't for the life of me figure out what I did to make the problem go away.

**Comment by KubaO** [comment]
This likely has to do with broken font defaulting in the style system. I'll leave it open until the changes that could fix it are merged, and then we'll reassess.

**Comment by KubaO** [comment]
@rknop Please confirm that the issue still appears in the nightly. There's a possibility that the major Style system changes have fixed it. Note that I'm slating this issue as a 12.07 blocker, and I'll appreciate a timely reply.

**Comment by KubaO** [comment]
@rknop Please the confirm that the issue still appears in the nightly. There have been font defaulting changes that should help with these kinds of problems.
