### ISSUE TITLE
wxdraw2d graphics too small on printer

### ISSUE THREAD

**Issue by jihemd** [wxMaxima-developers/wxmaxima#1244]
Hi, thx for wxMaxima 20.04.0

wxdraw2d graphics are fine on the screen but ridiculously small on my laser printer (26x25 mm).

With wxMaxima 19.05.7 the graphic's size on the same printer from the same notebook/wxmx file 
is 120*120 mm...

The plot size is set to 600 x 600 in my wxmaxima configuration

load("draw");
wxdraw2d(user_preamble = "set grid polar", 
         nticks = 200, 
         xrange = [-10,10], yrange = [-10,10], 
         color = blue, line_width = 1, 
         title = "circle",
        polar(10,theta,-%pi,%pi))

regards
Jen-marc D.

------------------------------------------------------------
wxMaxima version: T 20.04.0
using wxWidgets version: T 3.1.3
Maxima version: 5.43.2
Maxima build date: 2020-01-27 18:44:09
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\JIHEMD/maxima/
Help dir: C:\Program Files\wxmaxima 20.04.0\share/doc/wxmaxima
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
I Neger managed to determine how THW Prinz scale is supposed to be calculated. But if you are using a New enough wxMaxima the config dialogue offers to enter your own scale factor.
