### ISSUE TITLE
wxMaxima hangs/freezes

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1259]
When performing time consuming tasks on Maxima (eg reading large data-files), wxMaxima hangs. The mouse-cursor becomes the "working-cursor". The user can not even access the menu or tools to perform a break.  When minimizing the window and getting it up again, it sometimes just becomes a white surface.
Reverting backwards to the 2020-03-13 Nightly build  does not help - maybe it is a setting in the registry?

(%i1)   build_info();
(%o1)   build_info(version="branch_5_43_base_492_gbc01344c1",timestamp="2020-04-28 00:05:00",
host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0",maxima_userdir=
"C:/Users/XXXX/maxima",maxima_tempdir="C:/Users/XXX7/AppData/Local/Temp",maxima_objdir
="C:/Users/XXX/maxima/binary/branch_5_43_base_492_gbc01344c1/sbcl/2_0_0",maxima_frontend
="wxMaxima",maxima_frontend_version="20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment]
wxMaxima tries not to store any magic in the registry. Basically all that should be stored there are the settings from the config dialogue.
And for the last at least 10 releases wxMaxima should have gone faster each time. If that didn't work: Do you have one example for the bad behavior?

The only known exception of this rule: wxMaxima on starting up starts a background task that generates an index of Maxima's manual and on MS Windows string handling for some reasons is slow, which means the moment wxMaxima needs data from a background task it sometimes waits for up to 20 seconds on slow computers.

And if you compile your own wxMaxima: Do you have libomp-dev or whatever package provides omp.h installed? Else the background tasks might be run in the foreground instead.

**Comment by ReneSci** [comment]
Yes - wxMaxima has become faster - nice.
I download the nightly builds from Wolfgang Dautermann's site.
The attached example shows the issue at my computer.
Especially at the line:
DataFromFile: read_data_as_text(concat(workDir, DataFile), " ", true)$

[DATAFILE READ.zip](https://github.com/wxMaxima-developers/wxmaxima/files/4548912/DATAFILE.READ.zip)

**Comment by ReneSci** [comment]
Just tried the current nightly build 2020-04-30.
 8351197 only solves the problem partly. The menus and toolbar bottoms are still not accessible during the evaluation of the 
DataFromFile: read_data_as_text(concat(workDir, DataFile), " ", true)$
  
Scrolling shows up like this, and freezes:
![image](https://user-images.githubusercontent.com/2638713/80692571-0b906880-8ad2-11ea-9562-a8baa73f4db7.png)

Why does maxima create that much output during the evaluation of
DataFromFile: read_data_as_text(concat(workDir, DataFile), " ", true)$
![image](https://user-images.githubusercontent.com/2638713/80692910-91141880-8ad2-11ea-8830-66351aa8176d.png)

**Comment by gunterkoenigsmann** [comment]
It calls wxstatusbar() every time it reads a line. If you replace

          wxstatusbar("Reading line ", ln),

by
          if mod(ln,1000)=0 then
               wxstatusbar("Reading line ", ln),

that problem should be much smaller.

**Comment by gunterkoenigsmann** [comment]
Additionally you could try to do a 

      compile(read_data_as_text);

I believe this type of function can get much faster if it is compiled, possibly after additionally adding a few mode_declare() commands.

**Comment by ReneSci** [comment]
Thanks for your advise.
If I try to compile. Then when using the function afterwards, I get this
one:

(%i7) DataFromFile: read_data_as_text(concat(workDir, DataFile), " ", true)$
Unable to evaluate predicate "C:/temp/DATAFILE.csv"
 -- an error. To debug this try: debugmode(true);




Den tor. 30. apr. 2020 kl. 14.20 skrev Gunter Königsman <
notifications@github.com>:

**Comment by ReneSci** [comment]
Found it !

  if (not file_search (filename)) 
      then  (disp (" File not found "),return (false)),

Should be

  if (false =  file_search (filename)) 
      then  (disp (" File not found "),return (false)),


And - indeed, compiling certainly speeds up the process
