### ISSUE TITLE
Rendering error for long lines -- missing parentheses

### ISSUE THREAD

**Issue by rknop** [wxMaxima-developers/wxmaxima#1262]
If I enter the expression

[code]1/2 * ( (a+b)^2 + (c+d)^2 )

wxMaxima gives me the right thing if the window is wide enough; it has the numerator, a long horizontal bar, and then a 2 in the denominator.  However, if the expression overflows the window, it instead writes it as ( (a+b)^2 + (c+d)^2 )/2, except that the outer parentheses are missing.  The two screenshots show the difference.

This is Maixma 20.0.3 on Linux.
![shot1](https://user-images.githubusercontent.com/842655/80850996-e6dce380-8bec-11ea-8678-d9e0b7f21f10.png)
![shot2](https://user-images.githubusercontent.com/842655/80850998-e93f3d80-8bec-11ea-8e57-9d896ae6e55e.png)

**Comment by gunterkoenigsmann** [comment]
Wow... ...you found a real monster bug. And a very nice minimal example. Lets see how it can be resolved...
