### ISSUE TITLE
Copy to clipboard is broken when expression contains square brackets

### ISSUE THREAD

**Issue by ProcyonTheEvil** [wxMaxima-developers/wxmaxima#1264]
Hello and thank you for your awesome work on wxMaxima.

I noticed a nasty bug:
When I copy the expression "x[i]^3" to the clipboard and paste it into a text editor, it comes out as "x[x][i]". This happens with "Copy", "Copy for Matlab/Octave" and "Copy as text". When I copy it as Latex-Markup, it comes out as "{x}^{3}^{i}", i.e. the subscript turned into a superscript.

Expected result is: The text in the clipboard should be "x[i]^3".

Tested with version 20.04.0.

Sincerely, Procyon

**Comment by gunterkoenigsmann** [comment]
That was a very kind and complete bug report. And testers are always needed. Thanks a lot!

The next nightly build will be free of this problem, again.

Kind regards,

       Gunter.
