### ISSUE TITLE
Diacritics have stopped working.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1265]
The combining symbol is not backspaced over the original symbol anymore.
It worked awhile back, but is now broken again.

![image](https://user-images.githubusercontent.com/31253976/81202289-02007800-8f8c-11ea-9962-e2720fdd9745.png)
version
-------------------------------------------------------------
wxMaxima version: 20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: branch_5_43_base_501_gcec33b610
Maxima build date: 2020-05-06 00:04:24
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Richard.000/maxima/
Help dir: C:\maxima-current\share/doc/wxmaxima

-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
Wow... ...why does this happen? I haven't changed anything that should be able to affect this - and diacritics still work on my own computer (which is running Linux).

**Comment by richardgobeli** [comment]
It seems to work only on the output line and on the input line it goes above the back slash.
![image](https://user-images.githubusercontent.com/31253976/87236498-1e67c900-c3b0-11ea-8c7e-479348f2aa12.png)
night build from today.
![image](https://user-images.githubusercontent.com/31253976/87236520-5cfd8380-c3b0-11ea-9055-dbe4db93d0ba.png)

**Comment by gunterkoenigsmann** [comment]
That is to be expected, I'm afraid: diacritics are always displayed above the char they immediately follow. on the input in this case they follow the backslash.

**Comment by KubaO** [comment]
It probably would need to get fixed since the way it is right now it doesn’t do the job properly, but I imagine this may need to be pushed down to 20.08, since the code that deals with that is brittle and it may be too easy to break something without noticing. But if you succeed anyway then all’s good of course :)

**Comment by richardgobeli** [comment]
It seems to be working now, but the symbols do not show in the side screen view.
![image](https://user-images.githubusercontent.com/31253976/108898395-c7300500-75dc-11eb-9be9-cb9c607afb8c.png)
