### ISSUE TITLE
Question display

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1267]
![wxMaxima](https://user-images.githubusercontent.com/59099908/81446489-4736cc80-917b-11ea-8a91-2d7fd95fc703.jpg)

![wxMaxima_Error](https://user-images.githubusercontent.com/59099908/81446770-b3193500-917b-11ea-9154-0b0866010e61.jpg)

**Comment by gunterkoenigsmann** [comment]
That was a typo in one try to optimize the speed of the program.  Thanks a lot!
