### ISSUE TITLE
integration error

### ISSUE THREAD

**Issue by WhereNow** [wxMaxima-developers/wxmaxima#1270]
Just trying to follow Woollett's tutorial and found this bug in v20.04.0. The xample is in Chapter 1, page 34. 

(%i1) is : integrate( exp(x^3),x,1,2 );

Woollett gets 275.5109837634787 

I get with my wxmaxima -238.5995109606697*%i-137.7554918816558 which is clearly wrong because the integral should be real. Here is my code:

(%i3)  is : integrate( exp(x^3), x, 1, 2 );
    	  float(is);
	 expand(%);
(is)	 (gamma_incomplete(1/3,-8)-gamma_incomplete(1/3,-1))/3
(%o2)	0.3333333333333333*(-719.2849028282662*%i-1.0*(0.666081907741618-3.486369946257051*%i)-412.6003937372257)
(%o3)	-238.5995109606697*%i-137.7554918816558

It appears that a factor of (sqrt(3)*%i-1)/2 will get you the correct value (assuming Woollett's result is correct).

**Comment by gunterkoenigsmann** [comment]
Hmmm... I am getting:

````
(%i1) is : integrate( exp(x^3),x,1,2 );

(%o1) (gamma_incomplete(1/3,-8)-gamma_incomplete(1/3,-1))/3

````
My guess is that the maxima team (https://maxima.sourceforge.net) has changed something. And to me it looks like you found a new bug. Would you be so kind and forward this issue to them? I guess you are able to answer questions about the right solution for this problem which I am not. Thanks a lot in advance.

**Comment by WhereNow** [comment]
done

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!
