### ISSUE TITLE
Bug: Missing contents

### ISSUE THREAD

**Issue by David-UPCT** [wxMaxima-developers/wxmaxima#1272]
The brackets (and maybe more contents) are missing in the output. See the attached images (In Spanish _Defecto: Faltan contenidos_ means _Bug: Missing contents_).

I'm using archlinux and wxmaxima-git in AUR: wxmaxima-git 20.04.0.r182.g78f4011e-1. This problem doesn't appear in wxmaxima-git-20.04.0.r104.g4049bb0e-1.
![Captura de pantalla de 2020-05-11 11-31-54](https://user-images.githubusercontent.com/5481139/81546842-3d7bb780-937b-11ea-9f10-b5e99025c0a2.png)
![Captura de pantalla de 2020-05-11 11-32-29](https://user-images.githubusercontent.com/5481139/81546859-44a2c580-937b-11ea-9a49-cf79082c3a94.png)

**Comment by gunterkoenigsmann** [comment]
I found a way to make the XML parser much faster, less error-prone and much more robust. But that was a big change => Let's hope that this is the only typo in this piece of code.
