### ISSUE TITLE
Some keystrokes don't work

### ISSUE THREAD

**Issue by David-UPCT** [wxMaxima-developers/wxmaxima#1273]
Some keys don't seem to work: Arrow keys, AltGr, Insert, Supr... My keyboard is Spanish. I've put wxmaxima in English (inside the program in Configure, and also starting it with LANG=en_GB wxmaxima but the problem remains).

I'm using archlinux and wxmaxima-git in AUR: wxmaxima-git 20.04.0.r182.g78f4011e-1. This problem doesn't appear in wxmaxima-git-20.04.0.r104.g4049bb0e-1.

**Comment by ReneSci** [comment]
See the same thing (Danish keyboard)

(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_509_g1cd666c87",timestamp="2020-05-11 00:05:51",
host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0",maxima_userdir=
"C:/Users/xxx/maxima",maxima_tempdir="C:/Users/U265227/AppData/Local/Temp",maxima_objdir
="C:/Users/xxx/maxima/binary/branch_5_43_base_509_g1cd666c87/sbcl/2_0_0",maxima_frontend
="wxMaxima",maxima_frontend_version="20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment]
Arrgh! I knew that this commit did not only fix things. Thanks a lot for this bug report!

**Comment by David-UPCT** [comment]
Thanks for your quick patch! Unfortunately the bug is not completely solved in my case: Arrow keys and Insert/Supr work, but not AltGr. This key is crucial in Spanish keyboards, because it's necessary for brackets **[ ]** and braces **{ }**.

PD: I don't know if I should open a new issue or if this one should be re-opened

**Comment by gunterkoenigsmann** [comment]
If a bug ticket contains more than one bug that still isn't resolved that makes it easy to loose track which bugs currently exist. Also tickets with long complicated discussions that no more have to do with the original bug make it hard for users to find duplicates for the bug they currently encounter.

In this case none of these is true => no complaints from my side.

Actually the most important thing is having competent testers, not having bug reports that adher to exactly an entirely undocumented scheme, so as long as things don't get so complicated that I get lost I am happy with all schemes to report bugs.
