### ISSUE TITLE
EMF Copy to Clipboard doesn't work on Windows

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxmaxima#1274]
I'm copying EMF to Windows clipboard, either using Edit->Copy as EMF, or just doing Ctrl-C with EMF selected in the configuration dialog. The clipboard gets some EMF data posted to it (there's `image/x-emf` listed as a data format), but:

1. The Preview looks empty when viewing using Free Clipboard Viewer 3.0.

2. No applications accepts the EMF for pasting. Bitmap and text formats work OK.

This is both on the master HEAD as well as 20.04.0 release.

I'll try and investigate. The temporary EMF files are valid and both MS Paint and LibreOffice Draw open them fine. It seems that the string clipboard format `image/x-emf` is not recognized on Windows.

OK, I figured it out. The problem is that `wxEnhMetaFileDataObject` has to be used to represent the enhanced metafiles, instead of the custom data object used thus far. But it's not a `wxSimpleDataObject`, and thus cannot be aggregated using the `wxCompositeDataObject`. A custom aggregate class needs to be devised that can compose arbitrary `wxDataObject`s, not merely `wxSimpleDataObject`s.

**Comment by gunterkoenigsmann** [comment]
The idea with the mimetype is good: The mimetypes I used were only a rough guess and I don't own a Windows computer to test them on. A potential additional problem might be that the EMF data we generate contains maths and MathOML is supported only by very few programs (Libreoffice + MS Word, but not by Powerpoint or Excel).

**Comment by KubaO** [comment]
EMF data is basically a low-key vector graphics format like simplified SVG. It is the result of rendering cells on a `wxDC`, and contains no other data. It is unrelated to MathOML, which is an XML format. I haven't checked whether MathOML clipboard format works on Windows - that's a separate issue and I'll worry about it if someone reports a bug in that area.

Anyway, the `___out` classes were a copy-paste mess and I've refactored them, and got EMF to work. It looks a bit on the small side, but at least is a starting point.

**Comment by gunterkoenigsmann** [comment]
You are right: MathOML was embedded into rtf, instead.

Refactoring the old code that not only contained duplicates, but that often had different bugs in every copy was a good thing. Thanks a lot!
