### ISSUE TITLE
Greek Letters panel is always ON at start

### ISSUE THREAD

**Issue by David-UPCT** [wxMaxima-developers/wxmaxima#1276]
When I start wxmaxima the Greek letters panel is always activated, even though it's unmarked in View. The rest of the items on View seem to work properly.

To reproduce:
- Unmark Greek Letters in View
- Close and open wxmaxima

I use archlinux. The bug is not present in wxmaxima 20.03.1. It appears in 20.04.0 (and also in wxmaxima-git-20.04.0.r189.gf7c87eee).

**Comment by KubaO** [comment]
This is a deliberate change it seems., but it can be undone if it's truly a bug. It was introduced by a88e01db.
