### ISSUE TITLE
The output of diff doesn't work properly

### ISSUE THREAD

**Issue by David-UPCT** [wxMaxima-developers/wxmaxima#1280]
Something is broken in the output of the **diff** function. Please see the differences in the attached pictures in wxmaxima 20.04.0
![Captura de pantalla de 2020-05-13 23-16-40](https://user-images.githubusercontent.com/5481139/81866748-f0ad0200-956f-11ea-8e7f-02c850d4f50e.png)

and in the development snapshot
![Captura de pantalla de 2020-05-13 23-15-34](https://user-images.githubusercontent.com/5481139/81866789-00c4e180-9570-11ea-8253-e3a41c67d345.png)

I'm using archlinux, and my version of maxima is 5.43.2. I've complied some wxmaxima-git development versions. In wxmaxima-git-20.04.0.r104.g4049bb0e the output of the function is fine (just like in 20.04.0), but in wxmaxima-git-20.04.0.r182.g78f4011e is wrong. I hope this info helps you to locate the commit that created the bug.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this very complete bug report. I've tried to make the XML parser much faster and much more stable - and it seems I forgot to add an important symbol.
