### ISSUE TITLE
Missin/smeared out toolbar bottoms

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1281]
Looks like this
![image](https://user-images.githubusercontent.com/2638713/81915751-49fa4d00-95d3-11ea-81cc-de58f1704b4a.png)

First time I stated this nightly build quite a bit more of the bottoms where visible, but second time they are vanished like shown..

Otherwise is seems like wxMaxima works ok.

(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_511_g6bd686968",timestamp="2020-05-14 00:05:44",
host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0",maxima_userdir=
"C:/Users/xx/maxima",maxima_tempdir="C:/Users/xx/AppData/Local/Temp",maxima_objdir
="C:/Users/xx/maxima/binary/branch_5_43_base_511_g6bd686968/sbcl/2_0_0",maxima_frontend
="wxMaxima",maxima_frontend_version="20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for reporting this! This time it was Kuba who has resolved the issue.
