### ISSUE TITLE
Crash when clicking "Copy to LaTeX"

### ISSUE THREAD

**Issue by ThexXTURBOXx** [wxMaxima-developers/wxmaxima#1288]
I am using wxMaxima 20.04 on Windows 10 64-bit primarily, but the issue exists on the Ubuntu version as well.
Whenever I click on "Copy to LaTeX", wxMaxima 20.04 crashes without any warnings or whatever. The clipboard doesn't contain the exported text as well.
Funnily, this issue didn't exist in the version, that was bundled with Maxima 5.43.2 (from here: https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.2-Windows/) - sorry, I don't know exactly which version this was.

**Comment by KubaO** [comment]
The version bundled with Maxima 5.43.2 was wxMaxima 19.05.7.

Thank you for the report. The bug is confirmed.

**Comment by KubaO** [comment]
Fixed by feature/fix-copy-to-latex. The feature will be merged after I add the regression test.

**Comment by KubaO** [comment]
Merged. Test is a TODO currently.
