### ISSUE TITLE
Math error while computing Riemann-Tensor?

### ISSUE THREAD

**Issue by MetriMax** [wxMaxima-developers/wxmaxima#1289]
There seems to be an error in the formula used here in the maxima manual[http://maxima.sourceforge.net/docs/manual/de/maxima_20.html](url)

![Riemann_maxima](https://user-images.githubusercontent.com/65812022/82729129-701b9d80-9cf5-11ea-9954-04c42e3167fc.jpg)

The given formula always produces results with a wrong sign. Look at the definition in Wikipedia
[https://de.wikipedia.org/wiki/Riemannscher_Kr%C3%BCmmungstensor](url)
![Riemann_wikipedia](https://user-images.githubusercontent.com/65812022/82729220-f506b700-9cf5-11ea-8c22-28bfa85f07c5.jpg)

**Comment by richardgobeli** [comment]
The sign change is correct, because the second and third indices j,k are swapped as compared to the wikipedia result.  If you use the indices R[i,k.p,m] for the maxima result you get just a sign change.
Therefore if it was R[i,p,k,m] by swapping the k and p you get the same as wikipedia.

**Comment by MetriMax** [comment]
Ok, but can you give a hint on how to get this swapping. I don't have much experience with maxima and used
`
if get('ctensor,'version)=false then load(ctensor);
ct_coords:[t,r,Θ,φ];
lg:ident(4);
lg[1,1]:-(1-rs/r)*c^2;
lg[2,2]:1/(1-rs/r);
lg[3,3]:r^2;
lg[4,4]:(r^2)*(sin(Θ)^2);
cmetric();
christof(mcs);
riemann(mcs);
ricci(mcs);
scurvature();
`

**Comment by richardgobeli** [comment]
All you need to do is copy it to another array with the 2nd and 3rd indices swapped. It will be displayed with ldisplay for single term or cdisplay(riemwiki) for complete array display.

  for i thru dim do for j thru dim do for k thru dim do for l thru dim do
  ( riemwiki[i,j,k,l]:riem[i,k,j,l],
    if  riemwiki[i,j,k,l]#0 then   ldisplay(riemwiki[i,j,k,l]) 
);

**Comment by danielvolinski** [comment]
You can load itensor and manipulate the result as you wish:
`if get('itensor,'version)=false then load(itensor)$`
also set:
`dim:length(ct_coords)$`

;; Example: Christoffel symbols
```
for a thru dim do for b:a thru dim do for c thru dim do
  if mcs[a,b,c]≠0 then 
    ishow(Γ([ct_coords[a],ct_coords[b]],[ct_coords[c]])=mcs[a,b,c])$
```
;; or Riemann Tensor
```
for a thru dim do
  for b thru dim do
    for c thru (if symmetricp(lg,dim) then b else dim) do
      for d thru (if symmetricp(lg,dim) then a else dim) do
        if lriem[a,b,c,d]≠0 then
          ishow(R([ct_coords[a],ct_coords[b],ct_coords[c],ct_coords[d]],[])=lriem[a,b,c,d])$
```
;; You can manipulate the last line to show the result as you wish.

**Comment by danielvolinski** [comment]
For the Riemann tensor with three indices down and one up you can write:
```
riemann(false)$
for a thru dim do
  for b thru dim do
    for c thru (if symmetricp(lg,dim) then b else dim) do
      for d thru (if symmetricp(lg,dim) then a else dim) do
        if lriem[a,b,c,d]≠0 then
          ishow(R([ct_coords[a],ct_coords[b],ct_coords[c]],[ct_coords[d]])=riem[a,b,c,d])$
```

**Comment by richardgobeli** [comment]
You can check out how you can do the actual riemann calculation like on the wiki page.
Then show that they are equal except for the sign.

[riemann_example.zip](https://github.com/wxMaxima-developers/wxmaxima/files/4706614/riemann_example.zip)

**Comment by KubaO** [comment]
I'm closing it since this is either a Maxima problem, or no problem at all. Please reopen with more details if needed.

**Comment by gunterkoenigsmann** [comment]
The guys at https://maxima.sourceforge.net often can help with this kind of problem.
