### ISSUE TITLE
Crash on certain input

### ISSUE THREAD

**Issue by michaelquellmalz** [wxMaxima-developers/wxmaxima#1292]
wxMaxima 20.04 on Windows crashes after the command
```
integrate(legendre_p(n,t),t);
```
This happens only in wxMaxima, when using Maxima from the command line, this works fine.
Further Info:
```
wxMaxima version: 20.04.0_MSW
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.43.2
Maxima build date: 2020-01-27 18:44:09
Host type: x86_64-w64-mingw32
System type: Win32 10.0.19041 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
```

**Comment by gunterkoenigsmann** [comment]
Kuba and I are currently trying to improve the reliability of the program - and it sems like we had success with this issue.

If you don't mind that the text styles currently are a bit messed up the Nightly Build from https://wolfgang.dautermann.at/maxima/nightlybuild/ should resolve this issue. As soom as we'll have a version that is ready for that I'll release an updated wxMaxima.

**Comment by KubaO** [comment]
This is fixed in the master branch.
