### ISSUE TITLE
Function "print" issue in wxMaxima

### ISSUE THREAD

**Issue by lvch** [wxMaxima-developers/wxmaxima#1293]
![wxMaxima 19 07 0](https://user-images.githubusercontent.com/6746594/83356143-acda3b00-a36c-11ea-898e-f93ea2a66676.png)
![wxMaxima 20 04 0](https://user-images.githubusercontent.com/6746594/83356147-b499df80-a36c-11ea-9d1d-39604aa789c3.png)
First screenshot shows correct work of function, but on the second one there are three functions, following each other in one line, which is incorrect.
Following to the description to this function;
Function: print (expr_1, …, expr_n) 
Evaluates and displays expr_1, …, expr_n one after another, from left to right,
starting at the left edge of the console display.

**Comment by gunterkoenigsmann** [comment]
I believe this to be resolved in the Nightly Build that can be found at https://wolfgang.dautermann.at/maxima/nightlybuild/
But I am not entirely sure.

**Comment by KubaO** [comment]
This is fixed in the master branch.
