### ISSUE TITLE
Function "conjugate" issue in wxMaxima

### ISSUE THREAD

**Issue by lvch** [wxMaxima-developers/wxmaxima#1294]
![conjugate](https://user-images.githubusercontent.com/6746594/83356686-5d960980-a370-11ea-9dd7-0e0e9519a816.png)
While using sqrt function, "conjugate" is without the upper line symbol.

**Comment by gunterkoenigsmann** [comment]
Good that you found this: Issues that make the output look OK, but being wrong are both real bad and really hard to find.
