### ISSUE TITLE
Unbreakable spaces in wrong places make code sharing difficult

### ISSUE THREAD

**Issue by knuesel** [wxMaxima-developers/wxmaxima#1296]
When writing code in wxMaxima, pressing Shift+space makes an unbreakable space. This happens often by mistake, for example when writing `a: 1;` if the finger stays a bit too long on the Shift key for `:`.

wxMaxima replaces these characters with normal spaces so the code works when executed (this was made to fix https://github.com/wxMaxima-developers/wxmaxima/issues/1031). However this doesn't help when code is shared with other applications.

Here's my use case: I use wxMaxima to prepare code for Moodle STACK questions (https://github.com/maths/moodle-qtype_stack). When the code is working in wxMaxima, I copy it to the STACK question editor (either from the GUI, or directly from the `.wxm` file). I then get strange behavior in STACK because of the unbreakable spaces.

I think the solution is to remove the `Shift-space`  shortcut. It's much too easy to press it by mistake. If a shortcut for unbreakable spaces is necessary, it should be one that is difficult to press by mistake.

**Comment by KubaO** [comment]
This is a valid usability concern. I consider it a usability bug.

The short-term workaround is to add a configuration option that disables this shortcut. The long term solution is to provide fully configurable shortcuts.

**Comment by gunterkoenigsmann** [comment]
The unbreakable space problem was fixed very long ago. I believe, though, that there was no maxima release after that so the windows installer doesn't contain the fix, still.

**Comment by knuesel** [comment]
@gunterkoenigsmann is this: https://github.com/wxMaxima-developers/wxmaxima/commit/8e9746d2b49f1b994b5050e0db029bac5c4e21ba the fix you have in mind? I don't think it helps in my case, since the code with unbreakable spaces is executed outside of wxMaxima.

@KubaO note that I'm just a user of STACK, not a developer, but I'm sure @sangwinc will appreciate your interest!

Configurable shortcuts would be very nice! But don't you think the default shortcut should be changed here? What about Alt+Shift+space?

**Comment by KubaO** [comment]
https://xkcd.com/1172/  is all I'm gonna say. That shortcut has been there
for a while. Changing it outright may not be all that great of an idea.

**Comment by knuesel** [comment]
Haha I actually thought about this comic when writing my previous comment!

Changing the shortcut will certainly annoy some users. But keeping it will annoy other users, so the question is which is worse? Considering how this can introduce bugs that are particularly subtle and confusing, I bet it would cause less grief to change the shortcut... But of course it's up to you!

**Comment by KubaO** [comment]
I think this could default to a new shortcut when a configuration is generated from scratch. For existing configurations, a flag would be added to retain old shortcut, and the flag would be also available as a setting in the config dialog.

**Comment by gunterkoenigsmann** [comment]
If the problem is code that is copied from wxMaxima to somewhere else perhaps the easiest fix would be automatically replacing non-breakable spaces by ordinary spaces when copying except when copying in wxm format (the wxm format is only used when wxMaxima copies text to wxMaxima).

**Comment by knuesel** [comment]
@gunterkoenigsmann thanks for the fix. This won't work when code is copied directly from the `.wxm` file but it solves the problem in the case of copy-and-paste from the GUI.
