### ISSUE TITLE
The 'is' operator

### ISSUE THREAD

**Issue by libo929** [wxMaxima-developers/wxmaxima#1297]
Hello,

When taking the 'is' operator to decide if two numbers are equal, it seems to have an issue for power computation. For instance:
%i: is( 2^(2/3)=4^(1/3) )
%o: false

Bo

-------------------------------------------------------------
wxMaxima version: 19.05.7
using wxWidgets version: wxWidgets 3.1.2
Maxima version: 5.43.0
Maxima build date: 2019-06-05 13:14:43
Host type: x86_64-apple-darwin13.4.0
System type: Darwin 19.0.0 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.5.3
wxMaxima's idea of the directory layout is:
User configuration dir: /Users/libo/.maxima/
Help dir: /Applications/Maxima.app/Contents/Resources/opt/Applications/wxMaxima.app/Contents/Resources/help
-------------------------------------------------------------

**Comment by KubaO** [comment]
That’s not a problem with wxMaxima though. You need to report this to maxima project itself.

**Comment by libo929** [comment]
I see, and I will try that. Thank you. @KubaO
