### ISSUE TITLE
Wxmaxima 20.06.5 compile error

### ISSUE THREAD

**Issue by beew** [wxMaxima-developers/wxmaxima#1302]
Hi, tried to compile wxmaxima 20.06.5  and  'make' produced these errors:

```
/home/bernard/src/wxmaxima-Version-20.06.5/src/wxMaxima.cpp: In member function ‘bool wxMaxima::OpenWXMXFile(const wxString&, Worksheet*, bool)’:
/home/bernard/src/wxmaxima-Version-20.06.5/src/wxMaxima.cpp:3183:9: error: ‘ProcessNewline’ was not declared in this scope
         ProcessNewline(false);
         ^~~~~~~~~~~~~~
/home/bernard/src/wxmaxima-Version-20.06.5/src/wxMaxima.cpp:3183:9: note: suggested alternative: ‘ProcessCommand’
         ProcessNewline(false);
         ^~~~~~~~~~~~~~
         ProcessCommand
src/CMakeFiles/wxmaxima.dir/build.make:1226: recipe for target 'src/CMakeFiles/wxmaxima.dir/wxMaxima.cpp.o' failed
make[2]: *** [src/CMakeFiles/wxmaxima.dir/wxMaxima.cpp.o] Error 1
CMakeFiles/Makefile2:7162: recipe for target 'src/CMakeFiles/wxmaxima.dir/all' failed
make[1]: *** [src/CMakeFiles/wxmaxima.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
```
OS is Ubuntu 16.04, with gcc-8.3
wxmaxima 20.06.4 build without error.

**Comment by gunterkoenigsmann** [comment]
That was my fault. 20.06.6 compiles again.

**Comment by beew** [comment]
@gunterkoenigsmann 

Thanks. 20.06.6 does compile but failed two tests. I will make a new thread for it.

**Comment by gunterkoenigsmann** [comment]
Wow... ...that would be worth a new issue that I assume  @KubaO will be interested in: 
He wrote the CellPtr magic and the tests for it and (since the tests work fine for him, me and all our CIs) and you obviously are able to compile wxMaxima and own a system that behaves differently to our systems you might be a very interesting resource for making CellPtr even more stable.

**Comment by beew** [comment]
@gunterkoenigsmann  I was planing to start a new thread but since I can't find any log and there was no output that contains any info I can't say anymore about it except it failed.

**Comment by gunterkoenigsmann** [comment]
The kind of bugs I like most are the ones that don't require a urgent release of a new bugfix-version of wxMaxima.
