### ISSUE TITLE
WxMaxima Nightly crashed on opening a .mac file

### ISSUE THREAD

**Issue by IInatas** [wxMaxima-developers/wxmaxima#1305]
Dear Dev's

I tried opening the *.mac file inside the GUI and from cli in both cases maxima opened the file, but after ~5s being frozzen it crashed.
```bash
$ wxmaxima histogram_ext.mac 
(wxmaxima:14071): Gtk-WARNING **: 11:13:23.289: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node entry, owner GtkEntry)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abgebrochen
```
The file works fine under imaxima.

regards,
Marcus Menzel

*I use KDE Neon (basically Ubuntu 18.04 LTS) and here are the build infos:*
wxMaxima version: 20.06.6-DevelopmentSnapshot_GTK3_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.0.4
Maxima version: 5.43.2
Maxima build date: 2020-02-01 23:05:41
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.15.0-106-generic X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.1
wxMaxima's idea of the directory layout is:
User configuration dir: /home/marcus/.maxima/
Help dir: /usr/share/doc/wxmaxima

**Comment by KubaO** [comment]
I believe this bug is now fixed. @IInatas Please reopen if it's still a problem with the nightly, and please attach a file that reproduce it.
