### ISSUE TITLE
Integral differential not shown

### ISSUE THREAD

**Issue by TomasRiker** [wxMaxima-developers/wxmaxima#1307]
wxMaxima doesn't show the differential in integrals any more (e. g. "dx"):

![image](https://user-images.githubusercontent.com/295205/84750137-34ee5080-afbb-11ea-9916-b827fbc2334b.png)

**Comment by gunterkoenigsmann** [comment]
Sorry that it took this long, this time. But it finally is resolved with commit 0645ba30a
