### ISSUE TITLE
linker error (libomp not found) if libomp isn't installed

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1310]
If cmake generates makefiles, not a Ninja project on my computer the program compiles fine, but the linker complains that the lock() and unlock() functions of libomp could not be found. No idea why, though.

**Comment by KubaO** [comment]
What system is this on, what compiler etc?

**Comment by gunterkoenigsmann** [comment]
Ubuntu 20.10 preview and gcc. In the meantime I have tried to switch to ninja again - which failed, too. The real cause seems to have been that I had deinstalled `libomp-dev` => Will change the title of this issue.

**Comment by KubaO** [comment]
Is there something we can or should do to prevent other people from running into this problem? Is there a place to maybe put it in a readme? I'm imagining myself running into something like this while dead tired 10 minutes before a release is due :)

**Comment by gunterkoenigsmann** [comment]
I was convinced that if there is no libomp we wouldn't use `omp_unset_lock` and friends. Will investigate tomorrow why we do use them instead.

**Comment by gunterkoenigsmann** [comment]
Ok.. ...found the first half of the problem: We should link wxMaxima with the libraries found in the cmake variable `OpenMP_CXX_LIB_NAMES`. How to tell cmake that I haven't found out yet, though.

**Comment by gunterkoenigsmann** [comment]
Found another puzzle piece: We seem to be required to use the "-fopenmp" compiler option to gcc for the image cell test.

**Comment by gunterkoenigsmann** [comment]
Let's see what the CIs say. But I believe feature/linkOmpWithImgcellTest2 should resolve this issue.

**Comment by KubaO** [comment]
Good work, thank you!
