### ISSUE TITLE
Travis integration is broken

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1317]
I just as a last resort have revoked Travis' access rights, have uninstalled the Travis github app and have installed it anew. No idea if that finally helped.

**Comment by gunterkoenigsmann** [comment]
A manually-triggered build feels like it has eorked. Maybe the issue is resolved already.

**Comment by KubaO** [comment]
It's useful to see whether the cloud providers report problems:

https://www.githubstatus.com/
https://www.traviscistatus.com/
https://status.appveyor.com/

Yesterday GitHub had problems, and that was the cause.

Because such issues are usually due to degradation of cloud services, *configuration changes should be avoided at that time*. They increase the risk of loss of data or potentially ending up with a account configuration in an invalid state that would require a support request to resolve. So this is one case where doing nothing is usually the best thing.

**Comment by gunterkoenigsmann** [comment]
The travis integration had been broken for several weeks now: Github did still trigger travis builds. But the mail notification if the build status has changed and the channel that informs github about the build status no more worked. My guess is that somewhere in the upgrade chain from the old webhooks to the new webhooks to the github app to using the github app with a build matrix something broke.

And I waited for the end of the 2-hour github outage before I tried to fix travis. I am still curious if they do a post-mortem: Often knowledge about the failure modes gives you insights into the inner workings of services you use.

**Comment by gunterkoenigsmann** [comment]
The travis integration seems to fully work again: For the last commit github was again notified that travis is currently working => Closing this issue.

**Comment by gunterkoenigsmann** [comment]
The last few commits have again not caused travis to tell github about the CI status ;-(

**Comment by gunterkoenigsmann** [comment]
A place one can see the problem is clicking on the CI icons on the page https://github.com/wxMaxima-developers/wxmaxima/commits/master

**Comment by KubaO** [comment]
Commits can't do that. It'd defeat the purpose of the whole thing.

**Comment by gunterkoenigsmann** [comment]
Commits cannot cause that. But the commit page shows a symptom, which is why I added a link to the commit page.

I think I found another puzzle piece: Travis believes that I am member of no organization (not even wxMaxima-Developers). Where did you find reports about travis not communicating back to github? But perhaps you are right: We'll most probably have to wait until travis resolves the problems.

**Comment by KubaO** [comment]
Travis is broken again. It seems to come and go. I'm triggering builds by hand. Now AppVeyor is broken too - builds are stuck in the Queued status. Ugh.

**Comment by gunterkoenigsmann** [comment]
I tried to restart an appveor build that was stuck. Don't know if that completely broke it, somehow. 

---

I can try to again remove travis from our github project and to re-add it, if you want to. But I guess that this is not the real solution to the problem...

**Comment by KubaO** [comment]
﻿
This resolved itself now.

It is stupid, but it was a browser cookie issue. I had to clear all cookies, log in, and everything started to work again. Ugh.

I don’t think that removing and reading Travis is needed, at least not without clearing cookies fiest - what it does is incidentally invalidate cookies in the browser and then things “work” even though this is an extreme measure for fixing often a browser problem.

But things are OK on my end now.
