### ISSUE TITLE
spacebar and new line issue

### ISSUE THREAD

**Issue by lvch** [wxMaxima-developers/wxmaxima#1322]
![build_info](https://user-images.githubusercontent.com/6746594/86462151-ce479180-bd33-11ea-989d-f2b0109bb3e8.png)
![spacebar1](https://user-images.githubusercontent.com/6746594/86462162-d1db1880-bd33-11ea-80c4-140120c08ef7.png)
![spacebar2](https://user-images.githubusercontent.com/6746594/86462166-d4d60900-bd33-11ea-8665-17d1f98c016f.png)
The problem is when using "enter" key the new line seems to appear in the wrong place, if it starts with a spacebar.
On the second screenshot there are two lines: "1234567890" and "     test", cursor stands at the beginning of the second line. When using "enter" we got 3 lines: "1234567890", "     ", "test", but the second line here must be empty
and the third one must be "     test".

**Comment by gunterkoenigsmann** [comment]
The description how to reproduce this issue is simple and clear. But still I fail to reproduce this issue on my computer => something important seems to be set up differently in your computer than it is in mine.
