### ISSUE TITLE
Slow display

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1326]
Wanted to separate the performance issue in #1301 into a separate issue in order to make it easier to track it:

The following file loads way slower in the current version of wxMaxima as it did in a a-year-old version:
[untitled.wxmx.zip](https://github.com/wxMaxima-developers/wxmaxima/files/4877274/untitled.wxmx.zip)

Another testcase would be:

````
a:1/b$
for i:1 thru 75 do a:subst(b=1/b+1,a)$
a;
kill(a)$
````
...and my suspicion that the problem is that we draw things over and over again on every screen refresh has proven false with commit 3069516e56fbfdad5d10af2aa2a841288bbca2a8. I am convinced that we don't keep recalculating the worksheet all the time, neither => what else can have grown much slower?

**Comment by gunterkoenigsmann** [comment]
About recalculation: Recalculation is way too slow. But if you only scroll through the above testcases that should not include recalculation - but surely is slow. Are we using too many system calls? Is something involving the font cache fast on Windows, but slow on Ubuntu? What else can we be doing wrong? Will try to debug using callgrind. But often one needs an expert for interpreting the output of it.

**Comment by gunterkoenigsmann** [comment]
The typicall result I always get from profilers: we spend 98% of the time in an unknown function of an unknown library. That function is called by GTK's main loop and it calls hundreds of functions. One of them is our event handler and in this event handler we spend 4% of the time. As valgrind gets the caller graph wrong all the time my guess is that this means we somewhere call a library function that is slow and spends  98% of our time. No idea which library function that is, though ;-(

**Comment by gunterkoenigsmann** [comment]
This time it was only 95%. Does anyone know how to install debug symbols for libwxgtk and libgtk on Ubuntu?
![image](https://user-images.githubusercontent.com/5041537/86574228-cd9e3d80-bf75-11ea-88da-0b72a3e32580.png)

**Comment by KubaO** [comment]
I don't think you need any symbols. What's important is the callstacks. Look for those that account for most time :)

I'll write some worst offenders below:

1.`GroupCell::UpdateConfusableCharWarnings` - called constantly during parsing. Should be deferred until given cell is visible. Quadratic in nature.

2. `MathParser::ParseLimitTag` - calls `ToString` and those recurse into internal cells. `ToString` takes lots of time in general, since it's never cached and it's called willy-nilly everywhere.

3. Repetitive ``Recalculate` calls from `GroupCell` when loading. Qaudratic.

4. Font-related calls - working on that one :)

**Comment by gunterkoenigsmann** [comment]
For 3) I believe I found a place I can remove many Recalculate commands. But this time the problem isn't recalculation: The problem I see happens, when scrolling through an already-recalculated document.
2.) is not to blame, this time, as the problem occurs during scrolling => long after parsing.
1.) was told me to be very important by the maxima mailing list. But as this time the problem occurs during scrolling it is not the main problem here - even if I don't like this feature.

If it is 4) I am curious. But why did things get worse since the last release?

And a bad performance regression? Hope I didn't cause this somehow: I was trying to resolve many recalculation errors, even successful in case I didn't cause new problems in other places. And in a few places I even managed to improve the performance. In others I did what I believed I had to do...

**Comment by gunterkoenigsmann** [comment]
About callstacks: gprof gets the percentages wrong, callgrind the callstacks. Do you know any open-source tool that should work for me in the current situation?

**Comment by gunterkoenigsmann** [comment]
gprof's output looks like the thing that uses up most of the time is the font cache. But I might interpret the data wrong and I am no expert in profiling but I believe the data from gprof might lead into a completely wrong direction (aliasing effects, etc.):
````
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
  4.11      0.06     0.06   502296     0.00     0.00  Cell::Draw(wxPoint)
  3.42      0.11     0.05   442250     0.00     0.00  Cell::BreakLineHere() const
  2.74      0.15     0.04  1101054     0.00     0.00  wxFontInfo::wxFontInfo(wxFontInfo const&)
  2.74      0.19     0.04   366762     0.00     0.00  FontInfo::GetFor(wxFont const&)
  2.74      0.23     0.04   186236     0.00     0.00  TextCell::SizeHash_wxImplementation_HashTable::GetNode(double const&) const
  2.74      0.27     0.04   186235     0.00     0.00  TextCell::RecalculateWidths(int)
  2.40      0.31     0.04  3670975     0.00     0.00  operator!=(wxSize const&, wxSize const&)
  2.05      0.34     0.03  2640807     0.00     0.00  Configuration::Scale_Px(double) const
  2.05      0.37     0.03  1861514     0.00     0.00  Observed::ControlBlock::Get() const
  2.05      0.40     0.03   734213     0.00     0.00  FontCache::GetFont(wxFontInfo const&)
  2.05      0.43     0.03   375306     0.00     0.00  TextCell::Draw(wxPoint)
  2.05      0.46     0.03   365921     0.00     0.00  TextCell::SetFont(int)
  2.05      0.49     0.03   183944     0.00     0.00  wxDC::DrawText(wxString const&, int, int)
  2.05      0.52     0.03     1052     0.03     1.24  GroupCell::Draw(wxPoint)
  1.37      0.54     0.02  1840780     0.00     0.00  CellPtrBase::base_get() const
  1.37      0.56     0.02  1036390     0.00     0.00  std::__detail::_Hashtable_base<wxFontInfo, std::pair<wxFontInfo const, wxFont>, std::__detail::_Select1st, std::equal_to<wxFontInfo>, std::hash<wxFontInfo>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, false, true> >::_M_equals(wxFontInfo const&, unsigned long, std::__detail::_Hash_node<std::pair<wxFontInfo const, wxFont>, true>*) const
  1.37      0.58     0.02   976479     0.00     0.00  Configuration::ClipToDrawRegion() const
  1.37      0.60     0.02   734216     0.00     0.00  std::pair<std::__detail::_Node_iterator<std::pair<wxFontInfo const, wxFont>, false, true>, bool> std::_Hashtable<wxFontInfo, std::pair<wxFontInfo const, wxFont>, std::allocator<std::pair<wxFontInfo const, wxFont> >, std::__detail::_Select1st, std::equal_to<wxFontInfo>, std::hash<wxFontInfo>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_emplace<wxFontInfo const&, wxFontInfo const&>(std::integral_constant<bool, true>, wxFontInfo const&, wxFontInfo const&)
  1.37      0.62     0.02   734215     0.00     0.00  unsigned long mixHash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
````

**Comment by KubaO** [comment]
Well, it's the "font cache" because that's where most font-related calls are made. Thus it gets the blame. What really happens is that wxWidgets font code is a joke. But that's fixed and should be getting integrated today.

Another **big problem**:

    Worksheet::InsertLine -> Worksheet::ScrollToCaret -> Worksheet::RecalculateIfNeeded

This is done **for each and every line insertion**!

**Comment by gunterkoenigsmann** [comment]
Looks like I should definitively move the ScrollToCaret to the idle task after the recalculation, if idle...

**Comment by KubaO** [comment]
**Extremely Good News**  (at least on Windows)

In a nutshell: when running `maxima --eval file.wxmx`, with file having some plots in addition to math, the CPU time distribution is 60% to `sbcl.exe (Maxima)` and the rest to wxMaxima. 

With all the changes (yours and mine pending merge) wxMaxima is waiting for Maxima a lot of the time, even with big documents - as long as there are some plots :). On Windows, the response to everything is instantaneous - and the profiles have essentially no big hotspots like they used to (I'm using Intel VTune). A lot of things can be improved still, of course - those mostly stand out on documents without plots.

One thing that does stand out still: The History list is constantly being rewritten from scratch, and now that everything else got quick, it stands out. It'd help to fix that.

Processing the plots is slow, but I imagine that is Maxima's fault.

**Comment by gunterkoenigsmann** [comment]
The history rewrite is currently being checked by the CI. ...and on Linux scrolling through
````
a:1/b$
for i:1 thru 75 do a:subst(b=1/b+1,a)$
a;
kill(a)$
````
has sped up by a factor of perhaps 3. The question is if one can speed this up further as this single example is still slower than I used to. If I've interpreted your log messages right you currently try to get rid of some of the dc->SetFont() that set the font to the one we are currently using. If not: Due to a bug we used to not use many font sizes in this example. But we do now => perhaps the faster display was a symptom of a bug, anyway...

**Comment by gunterkoenigsmann** [comment]
With a bit of luck I can get access to a Windows box the day after tomorrow. Am curious to see how much your font cache has sped up things on windows...

...and in case that might provide an additional data point your profiling expertise can convert precise info about a bottleneck: in the manual test suite displaying the input seems to be fast, even if syntax highlighting should cause many font cache and dc->SetFont() calls. But drawing complicated output seems much slower...

**Comment by Mequin** [comment]
Sorry, I do have some personal urgency to solve but I will contune to look at this thread
I am obvisouly ready to rerun my stuff at anytime
Morevover, I will prepare some more demonstrative data
Regards

**Comment by KubaO** [comment]
The font cache rework has been merged :)

**Comment by gunterkoenigsmann** [comment]
On linux this has drastically improved the performance. But drawing complicated 2D maths still is slower than drawing big input cells => It perhaps again might lead to improvements if we manage to find the bottleneck.

**Comment by gunterkoenigsmann** [comment]
I have to apologize:

I always tried to measure the draw speed by spinning the virtual mouse wheel of my touchpad and looking at the framerate I got - which on linux wasn't high.

Now I have instead grabbed the scrollbar and moved it. The result is impressive: The smoothest scrolling one could ever imagine => The speed boost we got with the font cache is astounding. Thanks a lot!

**Comment by gunterkoenigsmann** [comment]
@Mequin : Today's nightly build has sometimes issues determining the size of objects. But in tomorrow's Nightly Build Kuba's massive speedup and the bugfix to the recalculation issue will both be available.

**Comment by KubaO** [comment]
Trivia: wxWidgets has a font cache. Why don’t we use it?

Answer: Because wxFontInfo is almost just as bad as wxFont. Not only does it copy and compare strings - it also reads the environment variables and/or wxConfig every time it’s constructed. It’s quite bad in itself. That’s why my first attempt at caching fizzled out. We now use Style instead of wxFontInfo, and the latter is constructed only when a unique wxFont is about to be constructed. 

Large documents end up using a dozen fonts or two, and the cache persists as long as wxMaxima is running. I don’t imagine it will be a problem (I’m terms of running out of handles), but eventually the cache can be made “leaky” and fonts not used in the last few minutes can be dropped.

**Comment by Mequin** [comment]
Thursay,

I have dowloaded the maxima-clisp-sbcl-abcl-current-win64.exe<https://wolfgang.dautermann.at/maxima/nightlybuild/maxima-clisp-sbcl-abcl-current-win64.exe>       2020-07-09 00:51       153M

Both  --eval  and speed are fine

You are my heros

Best regards,
      Jacques

________________________________
De : Gunter Königsman <notifications@github.com>
Envoyé : mercredi 8 juillet 2020 11:34
À : wxMaxima-developers/wxmaxima <wxmaxima@noreply.github.com>
Cc : Mequin <thunk@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [wxMaxima-developers/wxmaxima] Slow display (#1326)


@Mequin<https://github.com/Mequin> : Today's nightly build has sometimes issues determining the size of objects. But in tomorrow's Nightly Build Kuba's massive speedup and the bugfix to the recalculation issue will both be available.
