### ISSUE TITLE
Line breaking in SumCell doesn't work

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxmaxima#1329]
For me, faf56eb7 has the following effects:

1. There's no change to lack of line breaking inside of SumCell, and
2. It breaks repainting of the interior of sums and products: they don't occupy any more vertical space, and look just like their non-line-broken variants.

When scrolling right, the internal ParenCell inside of the SumCell is not drawn anymore as soon as the sum/product sign and the over/under cells are off the screen.

Integrals, limits nor sqrt are not affected.

I have followed the code a bit as it was about to break into lines, but ran out of time.

This is definitely reproducible and definitely broken :(

**Comment by KubaO** [comment]
I've marked it as a blocker, since it is an oft-cited complaint.

**Comment by gunterkoenigsmann** [comment]
SumCells currently don't support line breaking. 
And it seems like I broke Sums when trying to repair fractions. But at least I believe I have finally understood the line breaking code. Let's see if I find the sum problem.

**Comment by gunterkoenigsmann** [comment]
Resolved in commit bff566b7d43efd3eab59ac0dd9a44e452db94824 and a3a9b571514677afcc5d80fef7f8c2fddd49a89a.
