### ISSUE TITLE
History pane is repainted too often

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxmaxima#1330]
Re 5a54bfb8 and OnThumbtrack: we need framerate limiting for the history pane. At least on Windows, it is continuously repainting while processing Maxima output and is a significant source of slow-down and UI unresponsiveness.

It is my untested hypothesis that maxima output is processed in the event loop, but only one quantum of output is processed before returning, perhaps without checking if there's more output available. So, the sequence would be:

1. Process a chunk of Maxima output, leaving some output in the buffer even if available.
2. Update History pane -> immediate repaint
3. More output available -> goto 1.

There's no idle, since history redraws are slower than Maxima's output rate.

The problem is, then, that this slows down input processing by interleaving it with forced history repaints. One approach would be to queue the items to be added to history, and only do history change from idle. But that would be a workaround. The solution is:

1. Process all available Maxima input before doing anything else (i.e. before leaving the "process input" handler). Perhaps this is already the case?

2. Have History pane update itself from idle, like it should. Maybe it's a msw platform bug, or maybe we use it in some wrong way.

I'm hopeful that there's a proper way of handling such issues on wxWindows, i.e. that the controls queue a single repaint even if multiple changes were done to their state, and don't repaint immediately. Our History doesn't seem to do any of it, at least on Windows. Here the behavior may be different between Windows and X11.

**Comment by KubaO** [comment]
This is a blocker since it kills user experience (UX) on Windows.

**Comment by gunterkoenigsmann** [comment]
Would it be reasonable to use a wxUpdateBlocker on the history panel until the evaluation queue is empty?

**Comment by gunterkoenigsmann** [comment]
What additionally slows down the updates during evaluation is that if maxima doesn't send data we recalculate and only if maxima still doesn't send data update the UI. But that speeds up sending commands to maxima in a cooperative-multitasking fashion. Faster, but much more complicated would be using concurrent threads.

**Comment by gunterkoenigsmann** [comment]
Seems like that was a bottleneck on linux, too: If I let maxima evaluate simple cells it now is able to evaluates tens of cells per second.

**Comment by KubaO** [comment]
And that’s exactly how it should be. Thank you for all the fixes and enhancements – it still takes me too much time to figure out the flow of recalculation sand how things interact there. 

The next release is shaping to be awesome, I dare say :)

**Comment by gunterkoenigsmann** [comment]
My guess is that the secret of the intention behind most of the redraw logic has been lost in some point of time - or that there were many different concepts on it: Sometimes it is very hard to figure out what interacts with what and why that is...

**Comment by KubaO** [comment]
I tried to lay down some hints to let you have the pleasure of figuring the rest out (can’t have all the fun myself), so now I’ll have to open up the spoiler :)
  
I may be of course mistaken, but History has a search regex and UpdateHistory was meant to be called when that regex was changed, since it completely re-filters and rewrites the entire list. That’s the only intent I can see for that code. Especially that there *is* normal history append code elsewhere.

Having an IDE where you can immediately see the uses of a variable (such as a history widget) makes finding that other code two clicks or one keyboard shortcut away and such explorations are second nature when digging into unknown code base. So if you don’t work in such environment it surely must be unnecessarily hard to figure such things out. I’m far from a wizard, just use the tools I got :)

Back to the code: We call HistoryUpdate every time we append (well did until you added the idle trick). Even now we still call the wrong function - UpdateHistory simply does way too much work when all you need is to append (or do we prepend?) some items.

The work of appending one item is done around where Maxima output is consumed, and that should be factored out to a method like “AppendHistory”. 

All that had to be done was to remove that incorrect UpdateHistory call to fix the performance bug. And one can see where it was added in blame; I haven’t looked but I imagine the commit message might reveal the intent. It was probably a work around for some other bug either in wxWidgets or GTK, but this is my imagination at work here only.
