### ISSUE TITLE
Download link for current wxMaxima.exe

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1343]
in the gh_pages branch we should perhaps offer a link to the current self-contained wxMaxima.exe.

According to https://www.appveyor.com/docs/packaging-artifacts/ that should be something like https://ci.appveyor.com/api/projects/gunterkoenigsmann/wxmaxima/artifacts/build/src/wxmaxima.exe.zip?branch=master&job=TOOLKIT%3AMinGW
...but the "job" part of this URL seems not to be correct. No idea what they expect instead.

**Comment by gunterkoenigsmann** [comment]
After commit d2e14cabcf760c9ace1c2ca09ad68e8037b93865 the URL should read  https://ci.appveyor.com/api/projects/gunterkoenigsmann/wxmaxima/artifacts/build/src/wxmaxima.exe.zip?branch=master&job=MinGW

**Comment by KubaO** [comment]
Wonderful!! Thank you for figuring it out.

**Comment by gunterkoenigsmann** [comment]
Unfortunately I am afraid I didn't still: If I understood the docs right it should have that jobname. But it seems it currently hasn't. Or the URL actually works but I somehow managed to break appveyor: When one of my build jobs stuck in the "queued" state I cancelled and restarted it. Since then all jobs are stuck as "queued"...

**Comment by KubaO** [comment]
Curious. Looks like indeed this broke it but now I don’t know how to fix AppVeyor…

**Comment by gunterkoenigsmann** [comment]
According to https://help.appveyor.com/discussions/problems/5675-all-builds-stuck-at-queued-status wildly cancelling jobs might do the trick. The job I originally restarted looked like it were both cancelled and running at the same time. Not that cancelling the job didn't decrease the number of running jobs...

**Comment by gunterkoenigsmann** [comment]
If you want you can cancel all jobs I still have in the queue... ...but I don't dare to experimentally cancel your jobs without asking.

**Comment by KubaO** [comment]
I can’t do that. With Travis I can, but on AppVeyor I can only look. I have setup another instance on my own account and there I can do all that, but it seems like a waste of cpu cycles.

**Comment by daute** [comment]
Now I usually create a Windows installer for wxMaxima (crosscompiled on Linux (using the https://github.com/wxMaxima-developers/Crosscompiled-Windows-installer repository) , as I do for Maxima itself).
Closing this issue.
