### ISSUE TITLE
Help Maxima Error Current build.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1344]
Current build has error doing help Maxima.
The browser does still open the manual for Maxima.
 [image](https://user-images.githubusercontent.com/31253976/87390006-89123380-c56d-11ea-8043-3b830a624f8c.png)

**Comment by KubaO** [comment]
This is probably expected and due to a developer build. This shouldn't be happening once you run the installer, I hope.

**Comment by richardgobeli** [comment]
The last two night builds it did this. Last week it was OK.
I don't know what you mean by running the installer.  I think, I am running the installer each time I load the wxMaxima nightly build.
I uninstall the old version and make sure the Maxima-current folder is gone.  Then I run the install for the new build.
