### ISSUE TITLE
pgi errors and warnings

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1346]
Don't know how relevant the warnings pgi outputs are. But wxMaxima currently doesn't compile using this compiler: https://wolfgang.dautermann.at/maxima/pgi.txt

**Comment by KubaO** [comment]
It’s a big mess of silly warnings but I don’t see the word “error” there anywhere. It looks like it finishes Ok?

**Comment by gunterkoenigsmann** [comment]
It didn't produce a  binary so I assumed at least one of the messages to indicate a real error. But if the warnings make any sense I cannot tell...
