### ISSUE TITLE
Search replace all results in garbage for multiple occurrences in one line

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1353]
When I search and replace all in a text cell with content "abcd abcd abcd abcd" the text "abcd" with "de", the result is "de abdebcddedded".

Version: master of today (8848017)

**Comment by gunterkoenigsmann** [comment]
Should now be resolved - and I had a rough guess at the mac menu issue. Don't know if that resolved that issue
