### ISSUE TITLE
some functions only evaluate on 2nd invocation

### ISSUE THREAD

**Issue by eli-damon** [wxMaxima-developers/wxmaxima#1356]
This is the kind of thing that should be a bug in the Maxima engine, but it does not occur in terminal-based Maxima, only in Wxmaxima.engine.

Some functions are not evaluated when called for the first time after starting Wxmaxima or after restarting Maxima engine. But after failing to be evaluated when called for the first time, it is evaluated when called the second time. For example, see the following.

(%i2)	eval_string("test1");
	eval_string("test2");
(%o1)	eval_string("test1")
(%o2)	test2

I know this happened with at least one other function, but I can't remember what it is.

wxMaxima version: 19.11.0
using wxWidgets version: wxWidgets 3.0.4
Maxima version: 5.41.0
Maxima build date: 2018-04-09 18:33:03
Host type: x86_64-pc-linux-gnu
System type: BSD BSD NIL
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.12
wxMaxima's idea of the directory layout is:
User configuration dir: /home/eli/.maxima/
Help dir: /usr/share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
Since 2019 I have rewritten wxMaxima's maxima parser. That seems to have resolved this problem. The question is now if we need to search a workaround that works for you with the old version.

**Comment by eli-damon** [comment]
As a workaround, I can just pre-call the functions I want to use.

**Comment by robert-dodier** [comment]
Not observed in wxMaxima 24.08.0_DevelopmentSnapshot. I will assume the problem was fixed as stated in the preceding comment.
