### ISSUE TITLE
pressing ESC freezes/crashes Wxmaxima

### ISSUE THREAD

**Issue by eli-damon** [wxMaxima-developers/wxmaxima#1357]
Every time I press the ESC key in Wxmaxima, a new window pops up with the following error message, along with "Stop" and "Continue" buttons. Pressing either botton or the close (x) button at the top of the window causes Wxmaxima to sometime freeze and sometime shut down.

--------------------
An assertion Failed!

/build/wxmaxima-XHmyyD/wxmaxima-19.11.0/src/Worksheet.cpp(8666): assert "(pos.x>=0) && (pos.y >=0)" failed in Autocomplete().
----------------

wxMaxima version: 19.11.0
using wxWidgets version: wxWidgets 3.0.4
Maxima version: 5.41.0
Maxima build date: 2018-04-09 18:33:03
Host type: x86_64-pc-linux-gnu
System type: BSD BSD NIL
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.12
wxMaxima's idea of the directory layout is:
User configuration dir: /home/eli/.maxima/
Help dir: /usr/share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
Getting rid of the underlying problem is a 300-lines-patch that was only possible after the major rewrite Kuba did before. But I think I found a patch that prevents the crash if the "continue" button is pressed in the assert dialogue.

**Comment by gunterkoenigsmann** [comment]
Don't know how easy or hard it would be to make OpenBSD provide a newer wxMAxima instead.
