### ISSUE TITLE
Nightly Build

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1358]
I have not been available for the last two months and thus not done any testing during this period.
Just tested the latest nightly build 220/07/28:
When opening with an empty  or a small worksheet, it seem to be ok. But with a large worksheet, wxMaxima comes up with this error:
 
![image](https://user-images.githubusercontent.com/2638713/88630162-7c82f480-d0b0-11ea-8e04-711952cb0422.png)

Pressing "Continue" a couple of times, it seems to work ok .

**Comment by KubaO** [comment]
That’s a bug in the code I wrote - sorry about that. But it may be exposing an earlier, latent bug. I’ll investigate. For now it’s OK to let wxWidgets not display the message anymore (there’s a checkbox for that in the message window).

It also doesn’t depend on the document size: there’s one group cell somewhere that has output that attempts to use alttext in an unsupported way.

It would help us immensely if you could bisect your document to find out which group cell (the input+output pair) causes this trouble, and make a small reproducer based on that.

I have a 1000 page document that doesn’t cause this issue so it’s definitely unrelated to size. It just so happens that your larger document(s) have some output that makes alt text where there maybe shouldn’t be any.

**Comment by gunterkoenigsmann** [comment]
Would you be willing to send such a file to me? Both Kuba and I were convinced that AltCopyTexts for plain text don't make any sense and I would like to ask the debugger where we were wrong.

@KubaO In the meantime I have added these asserts to all kinds of cells that don't support AltCopyTexts, currently.

**Comment by gunterkoenigsmann** [comment]
If you cannot give us the file the next Nightly Build will produce a more helpful assert message, hopefully.

**Comment by ReneSci** [comment]
Try to run this one.
It produces the error on my computer:

[untitled.zip](https://github.com/wxMaxima-developers/wxmaxima/files/5006948/untitled.zip)

**Comment by gunterkoenigsmann** [comment]
Resolved with commit 64e45eadea7095375fb85d713c0b1ac189923ccc

One TextCell that has an AltCopyText is the command "not".
