### ISSUE TITLE
Show labels

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1362]
![wxMaxima_3](https://user-images.githubusercontent.com/59099908/88937380-60d04780-d284-11ea-9835-4f420b0887c3.jpg)

![wxMaxima_2](https://user-images.githubusercontent.com/59099908/88937402-662d9200-d284-11ea-8c21-2b942230df8e.jpg)

**There is no effect, when Ichage the settings**

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!
