### ISSUE TITLE
"Load Package" Window Pops Out When Press L Key

### ISSUE THREAD

**Issue by qrqiuren** [wxMaxima-developers/wxmaxima#1366]
When I start to type in the console window in wxMaxima, if I press L key or B key, a window of "Load Package" or "Load Batch" will pop out.

This is very painful to me because I can no longer use functions or variables with L or B in it, like `log`, `float`, etc.

- wxMaxima version: 20.06.6
- Maxima version: 5.44.0
- Platform: Windows 10 1909
- Language: Chinese (simplified)

**Comment by qrqiuren** [comment]
I used the prebuilt package from Maxima's SourceForge.

**Comment by KubaO** [comment]
Switch to the English language for wxMaxima and report back. I.e. make sure that the wxMaxima UI is in English. It’s likely a problem with the accelerators in the Chinese translation, and thus has to be resolved by the translators (unless there is translation - I didn’t check).

**Comment by qrqiuren** [comment]
@KubaO Thank you. I switched to English and it is OK now.

I can read & edit po files, but currently didn't find any possible problems in the po file. If anyone has some clues about this issue, e. g. related to which file in the source code, please tell me.

BTW, My Windows 10 is in Chinese (simplified) but the internal coding is Japanese, the language when I install Windows 10.

**Comment by KubaO** [comment]
Thank you! I will investigate when I get back from vacation.

**Comment by gunterkoenigsmann** [comment]
I believe that to have indeed been a translation issue - of some sorts: 

Instead of "Ctrl+L" there was " Ctrl+L" in one place [with an additional space in front]" and wxWidgets surprisingly seems to not have been able to understand this.

Tomorrow's wxMaxima version from https://wolfgang.dautermann.at/maxima/nightlybuild/ will be free of this error.
