### ISSUE TITLE
Function 'printf' with format directive 'm'

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1368]
![wxMaxima_1](https://user-images.githubusercontent.com/59099908/89644089-7adadd00-d8b7-11ea-919b-87260f73af24.jpg)

### wxMaxima have problems with function 'printf' with format directive 'm':

![wxMaxima_2](https://user-images.githubusercontent.com/59099908/89644154-9d6cf600-d8b7-11ea-82b2-60f766727c53.jpg)

### but not with XMaxima:

![wxMaxima_3](https://user-images.githubusercontent.com/59099908/89644206-b4abe380-d8b7-11ea-88ae-37af0bff4588.jpg)

**Comment by gunterkoenigsmann** [comment]
Are you sure that this is a symptom of an actual problem with that directive? To me it looks like the tests just assume that the lisp variable `*alt-display2d*` is set to `nil`, which in other words means that nothing has told maxima to display maths in a different way than usual. wxMaxima tells maxima to display maths as nice 2d objects and for that means needs to tell maxima to use a different output routine. 

     set_display('ascii)$

should make wxMaxima display ASCII arts like Xmaxima does and therefore should make it pass these tests.

**Comment by ljselmaier** [comment]
Your assumption is right.
A checkmark in the menu 'View/Display equations' would be helpful.

![wxMaxima_1](https://user-images.githubusercontent.com/59099908/89709018-4b41d880-d97c-11ea-8da4-b74d9855f69a.jpg)

![wxMaxima_2](https://user-images.githubusercontent.com/59099908/89709021-4f6df600-d97c-11ea-8cca-829bc5af77a8.jpg)

Also in the menus 'View/Autosubscript, .../Matrix parenthesis, .../Set Zoom' a checkmark would be helpful.

Thanks!
ljselmaier

**Comment by gunterkoenigsmann** [comment]
These Checkmarks sound like being a good idea. But they would require wxMaxima to keep a constant watch on Maxima's internal variables.

Will first have to think how to do so in an efficient way.

**Comment by ljselmaier** [comment]
Good speed!

**Comment by gunterkoenigsmann** [comment]
I hope the next Nightly Build will contain the Radio Button. And I believe that you have caused me to stumble over the reason for a long-standing bug I have been searching for a long time now.
