### ISSUE TITLE
ASCII Art and 1D mode: Output labels aren't displayed in the place 2d Math labels are in

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1370]
**While testing the Radio Buttons ( tey seem to work ), I noticed the display of the output labels (see red rectangles ).
Is that okay?**

![wxMaxima_1](https://user-images.githubusercontent.com/59099908/89786365-19677800-db1c-11ea-97b8-984df06072a9.jpg)

**Show labels;  Never:**

![wxMaxima_2](https://user-images.githubusercontent.com/59099908/89786390-1ff5ef80-db1c-11ea-8f89-676a6e341e99.jpg)

**Show labels; Automatic labels:**

![wxMaxima_3](https://user-images.githubusercontent.com/59099908/89791534-bda0ed00-db23-11ea-858f-c7db5f311e36.jpg)

**Comment by gunterkoenigsmann** [comment]
In ascii-art or 1D mode maxima doesn't tell us what is a label and what isn't. What is worse: It doesn't tell what is meant by which letter. So we cannot entirely trust that an (%o4) is actually meant as an output label.

=> The current behaviour looks strange. But I have no idea if there is a way to reliably improve it.

---

In the meantime I have added the logic that asks if we are in 2D mode to all menu items that not knowing, for example, if we are in numeric mode or not, could only offer to toggle numeric mode leading to surprising results if one evaluates a line of code twice.

**Comment by KubaO** [comment]
Awesome!
