### ISSUE TITLE
DiffCell line breaking suppresses display of subsequent commands in a multi-command group

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxmaxima#1371]
In `all-celltypes.wxmx`, when the output window is narrow, we get:

![image](https://user-images.githubusercontent.com/5444571/89837696-80465a80-db37-11ea-93be-a48526d1f327.png)

Notice how `%o25` is missing. This is only a display issue, as the next output cell is correctly numbered `%o26`.

Other line-broken cells like `abs()` or `at()` don't have the problem. The problem predates my recent changes (within the last week). I didn't investigate any further.

**Comment by gunterkoenigsmann** [comment]
That normally means that SetNextToDraw() or BreakUp() of the cell (or of any cell it contains) does result in a truncated list...

**Comment by gunterkoenigsmann** [comment]
I still wonder if there is a way to create an automatic test for this kind of recurring issue...
