### ISSUE TITLE
Something is broken with line breaks and/or text sizes

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1374]
Something seems to be broken, currently, with formatting of small text snippets.

My guess is (I haven't looked) that this might indicate that the work on the size cache common to small text snippets has begun:

![image](https://user-images.githubusercontent.com/5041537/90336755-31d50800-dfde-11ea-8087-03621ac86b28.png)

**Comment by gunterkoenigsmann** [comment]
`git bisect` tells the offending commit to be:

````
[0f00f7ef0a552b1bf265e69b5302db0f3ccf2530] Get rid of quadratic behavior on cell appending, improving performance when cells come from maxima.
````

**Comment by KubaO** [comment]
Yep, and that's a single line change. The bug has to be fixed somewhere else. It exposes the bug, but is not a bug by itself. I'll try to find the source of it

**Comment by KubaO** [comment]
I'll revert it for now since this is the sort of a bug that will come back over and over again. Some design changes may be needed for a fix that will prevent further bugs.

**Comment by gunterkoenigsmann** [comment]
Any ideas are welcome. But your code that improved the speed and made bugs visible looked like being the Right Thing to do so I wouldn't be unhappy if yo reverted the revert after we told GroupCell to recalculate itself on Draw, if needed, naturally.

**Comment by KubaO** [comment]
I'll leave it up to you when you find the "real fix", if any. It's either something like a single- or two-line fix, or bigger. In any case, I have other ways of improving things before this absolutely needs to be tackled.

We should very close the being able to run "the benchmark" with reasonably real-time response at size 17, while just a few months ago it looked hopeless. At the moment, wxMaxima itself is using less than 500MB for cell storage with this benchmark - a rather remarkable improvement over a few months.

```
hs(n):=ratsimp(ratexpand(product(x-a[i],i,1,n)));
hs(17);
```
