### ISSUE TITLE
Regression: Inserting a new first line

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1376]
- Fill a worksheet with at least one line of text
- Go with the cursor above the first line
- type in a letter which inserts a new code cell

What is expected to happen?

 -  a new code cell is inserted above the first line

What actually happens?

 - A new code cell is inserted below the first line

Guess: The (m_hcaret==NULL) that catches the case that the cursor is above the 1st line currently isn't working, somehow. But my guess might be widely wrong.

**Comment by KubaO** [comment]
The problem is in Worksheet::OnCharNoActive.
