### ISSUE TITLE
WXMaxima hangs pasting any data from LibreOffice (or other similiar data)

### ISSUE THREAD

**Issue by v-mil** [wxMaxima-developers/wxmaxima#1378]
I used WXMaxima 20.07.0 built from source in LUbuntu 20.04 with the kernel 5.7.0-16.1-liquorix-amd64.
My LibreOffice build is 1:6.4.6~rc2-0ubuntu0.20.04.1.
Pasting a text from LibreOffice inside any input cell formula by middle-click or CTRL+V causes hanging dialog.

1. Open WXMaxima (It is easier to use a terminal);
2. Type any formulas in input cells;
3. Copy any text from LibreOffice (at least some characters without a space, I tried Latinic and Cyrillic);
4. Set cursor in any input cell and press mouse wheel (Fig.);
5. My result is on Fig.
6. To close WXMixima the terminal should be closed. If no terminal, closing the window by [x] button is not helpful/ I found only one way - "kill" command in a terminal.

![Window](https://user-images.githubusercontent.com/70109066/90985906-99afc380-e587-11ea-8398-bc274fca9cc5.png)
Fig. WXMaxima window after pressing mouse wheel.

Backtrace:
//AFTER RUNNING:

~$ wxmaxima
21:17:47: Debug: Unrecognized accel key 'пробіл', accel string ignored.
21:17:47: Debug: Unrecognized accel key 'пробіл', accel string ignored.
21:17:47: Debug: Unrecognized accel key '↑', accel string ignored.
21:17:47: Debug: Unrecognized accel key '↓', accel string ignored.

(wxmaxima:79605): Gtk-CRITICAL **: 21:17:48.152: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed

(wxmaxima:79605): Gtk-CRITICAL **: 21:17:48.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(wxmaxima:79605): Gtk-CRITICAL **: 21:17:48.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.221: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.221: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node entry, owner GtkEntry)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.228: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.228: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.229: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.230: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.230: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.230: Negative content width -25 (allocation 1, extents 13x13) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.230: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.230: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkToggleButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.231: Negative content width -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.231: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:79605): Gtk-CRITICAL **: 21:17:48.231: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScale

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.238: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkToggleButton)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.238: Negative content width -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:79605): Gtk-WARNING **: 21:17:48.238: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:79605): Gtk-CRITICAL **: 21:17:48.238: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScale

//AFTER PRESSING MOUSE WHEEL

../src/common/string.cpp(1185): assert "c < 0x80" failed in FromAscii(): Non-ASCII value passed to FromAscii().

(wxmaxima:79605): Gtk-WARNING **: 21:20:45.099: gtk_window_set_titlebar() called on a realized window

**Comment by gunterkoenigsmann** [comment]
My guess (it's only a guess) is that the middle mouse wheel drags-and-drops non-ascii text into wxMaxima, somehow. Will test if I can reproduce this tomorrow.

**Comment by v-mil** [comment]
After reboot, middle click pastes in WXMaxima the same as CTRL+V. Outside WXMaxima it pastes the last selected item. I tried to copy an image. It works normally. After copying some audiodata from Audacity nothing is pasted. But copying some text from LibreOffice 1:6.4.6~rc2-0ubuntu0.20.04.1 cause the same hanging after middle-click or Ctrl+V. The picture is the same as on Fig. All previous unsaved data is lost! Today there was no important data, only tests. But yesterday I loosed one formula but recover it by my memory.
The dialogs such as "Create matrix" operate normally without hanging.
Incorrect command wxplot2d([y=5*x+2*y], [x,-5,5]); causes Wxmaxima Error dialog "cant open file...". It operates normally, no hanging. Pressing the button re-opens and closes it without any crashes.
The hanging after pasting a text from LibreOffice or similiar data is the main problem.

**Comment by KubaO** [comment]
We used to have a problem like this, except last time it was a crash IIRC. I'd like you to reproduce this problem using no external applications, though.

**Comment by v-mil** [comment]
No problem copying and pasting from wxMaxima itself

**Comment by gunterkoenigsmann** [comment]
With a bit of luck one of my latest commits has changed this problem.

**Comment by KubaO** [comment]
I believe that this is fixed in master. Please reopen if that's not the case.
