### ISSUE TITLE
Accelerators with cyrillic letters

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1381]
The following lines in #1378 seem to indicate that at least one wxWidgets version on at least one platform seems to mis-indicate text that comes behind a `\t` in a translation => Filing that as a bug so it doesn't get lost.

21:17:47: Debug: Unrecognized accel key 'пробіл', accel string ignored.
21:17:47: Debug: Unrecognized accel key 'пробіл', accel string ignored.
21:17:47: Debug: Unrecognized accel key '↑', accel string ignored.
21:17:47: Debug: Unrecognized accel key '↓', accel string ignored.

**Comment by yurchor** [comment]
Thanks. Sorry for my mistake. I will fix the problem with the "Space" translation ASAP.

**Comment by gunterkoenigsmann** [comment]
Some aspects of gettext in wxWidgets are neither logical, nor documented nor reproducible on every system. Also translating is a manual process that is bound to go wrong sometimes => no complaints from my side.

**Comment by KubaO** [comment]
I believe this is fixed now.
