### ISSUE TITLE
The manual testsuite has grown suspiciously slow

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1385]
No idea what has happened: All files I use wxMaxima with have grown extremely fast over the last few months. All automatic tests have grown extremely fast. The display is as smooth as one wishes for - but now I pressed Ctrl+R in the manual testsuite - and that file was evaluated extremely slow. Seems like we have hit some important test case => Started valgrind with the file. 4 hours later it has evaluated the first few cells. I hope that this time I will see the right pieces of information in its output...

**Comment by KubaO** [comment]
There’s quadratic behavior on second Ctrl-R in all-celltypes and really in all files and it shows on Focal - not on Windows :(. First recalc: super fast, second and subsequent is slow and you can see that it goes faster the further down in the document it is. Seems like a regression so I’ll investigate that. Likely due to platform specific behavior of wxWidgets.

**Comment by gunterkoenigsmann** [comment]
That is good news! With help of the profiler you have done real wonders already

But if we currently have qudratic behavior the base speed must be extremely high: All real-live examples I own are fast under linux, as well.

**Comment by KubaO** [comment]
What distro do you run on? It looks like Focal-specific thing when you compare to Bionic. Also happens on the CI where the performance test is ~3x slower on Focal vs Bionic.

**Comment by gunterkoenigsmann** [comment]
Ubuntu 20.10. I wasn't happy when debian dropped gtk2 support because gtk3 was way slower and caused me nearly a month's work for making everything work again. My guess that the slowdown is gtk3-related, somehow. But I may be wrong.

**Comment by gunterkoenigsmann** [comment]
Ok... ...another puzzle piece: I have now made my wxMaxima copy output the reason why a cell is recalculated: My guess was everything gets slow if cells below the current cell already have output => the slowdown is likely to be caused by recalculating already-recalculated cells. The result of this test: We seem to call ResetSize() once to often, somewhere.

**Comment by KubaO** [comment]
That makes sense. The presence of output definitely has direct impact on speed when modifying cells above.

**Comment by gunterkoenigsmann** [comment]
Resolved with 9de12897e5d605cc79d4c8192afe7217d09c9d21.
The question that is still standing is why the fact that all cells always believed that they need to be recalculated didn't cause massive slowness on MS windows. But perhaps we just had increased the performance on windows so much that even massive recalculation overkill no more consumed measurable amounts of time...

**Comment by KubaO** [comment]
The recent releases of Visual C++ 2019 are really very good - both in terms of compile performance and the quality of generated code. But I wouldn’t ascribe it all to the compiler. I’ll have to figure out what’s the impact on Windows.

**Comment by gunterkoenigsmann** [comment]
Back when I used msvc the code it generated it was real slow. Or I did automatically optimize my programs for the gcc I was used to. No idea which of the two, to be honest
