### ISSUE TITLE
Open wxmx files

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1390]
![wxMaxima_1](https://user-images.githubusercontent.com/59099908/91668151-a0e84b80-eb0a-11ea-9247-62bbc423f998.jpg)

**I cannot open a wxmx file, saved with this version.**

**Comment by gunterkoenigsmann** [comment]
If you are willing to send me the file I will try to recover it and to find out what went wrong.

What ai already know what can go wrong is spaces or unicode characters in the filename sometimes give problems when trying to open files that (under a different name) work fine.

**Comment by ljselmaier** [comment]
Link to two corresponding files:

https://drive.google.com/drive/folders/1Ma3s16fiTwEBDbpjiTDfwnwNbgrm8lmI?usp=sharing

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

That test case actually allowed to find two bugs:

 * Labels that weren't displayed weren't saved and 
 * on loading wxMaxima assumed that a label always contains text.

As soon as my fix passes all ci tests I will commit it to the master branch.
