### ISSUE TITLE
Today's and yesterday's  builds crash when clicking on a result in a list

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1391]
If I click on any part of %o2 to try to copy the second solution, the program WxMaxima crashes.
![image](https://user-images.githubusercontent.com/31253976/91679546-3a652c80-eb0e-11ea-94a4-fef06a9c0ff6.png)
![image](https://user-images.githubusercontent.com/31253976/91679673-a2b40e00-eb0e-11ea-86bc-d46ab6fe7b21.png)

**Comment by richardgobeli** [comment]
I found out that it does not need to be a list, but almost any equation that you click on in the result area.

**Comment by gunterkoenigsmann** [comment]
This is a duplicate of #1387

**Comment by KubaO** [comment]
Closing, this is a duplicate.
