### ISSUE TITLE
Rootscontract

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1397]
Rootscontract is in the manual, but it is not connected to a function.  Is it still in Maxima?

**Comment by gunterkoenigsmann** [comment]
If I right-click on the word "rootscontract" I get a "help on rootscontract" menu entry that leads to the manual entry for the function rootscontract => either the problem has been resolved in the maxima master or I misunderstand this ticket.

**Comment by richardgobeli** [comment]
I don't know now.  If I misspelled the word.  But I know I used the ctl space to finish the command and I selected the rootscontract at the bottom of the list and it did nothing on Sept. 7 build.
I know why now!  The input line was stuck in text mode.
I have been having issues with that.  If you enter a text and then go to a Math line I think it show switch to math, but it stay in text mode.

**Comment by gunterkoenigsmann** [comment]
On my computer the drop-down-menu updates correctly. A least in all cases I have tested. Do you know of any way to trigger the problem reliably?

**Comment by richardgobeli** [comment]
I think if you enter text and then do a shift enter to end the text line. Then next math line I think works with shift enter, but now if you go to enter a new line it switches back to text.

**Comment by gunterkoenigsmann** [comment]
Now I see it, too. Thanks!

Will try to find a solution tomorrow.

**Comment by richardgobeli** [comment]
Is this the way you wanted it to always remember the type of line that was lasted added?  I thought if you add a section line and then execute math lines that it switches back to math line and not stay on section line entry.
