### ISSUE TITLE
Main toolbar "huge"

### ISSUE THREAD

**Issue by PJSingh5000** [wxMaxima-developers/wxmaxima#1398]
The Main Toolbar icons are huge on HDPI screen...

wxmaxima version 19.07.0
Ubuntu version 20.04
GNOME Shell version 3.36.4
GTK-3 version 3.24.20
Using HDPI LCD screen (3840x2160 resolution)

I've tried various different icon themes (Papirus, Yaru, Newaita) with the same results.

![wxMaxima 2020-09-09](https://user-images.githubusercontent.com/19394936/92657901-99bbfd00-f2c3-11ea-9606-e1d4a468b4a5.png)

**Comment by gunterkoenigsmann** [comment]
Having an High-DPI tester is valuable: I don't own a device with that high a resolution.

**Comment by PJSingh5000** [comment]
Does anyone know which Ubuntu package version this fix would show up in?
I currently have 19.07.0-1.1build1 from the Ubuntu repos, but the fix is not in that version.
