### ISSUE TITLE
summation sign missing.

### ISSUE THREAD

**Issue by dowkeruk** [wxMaxima-developers/wxmaxima#1401]
When parsed, any command applied to `sum', eg    su(u):= expand(sum(n,,n,1,u) lacks the summation sign. on my machine. Computes correctly.

Also is there any way to get the mathematical output not in italics?

My system:

wxMaxima version: 20.06.6_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\dowke/maxima/
Help dir: C:\maxima-5.44.0\share/doc/wxmaxima

**Comment by gunterkoenigsmann** [comment]
I believe both of these issues are resolved in the wxMaxima version that can be downloaded at https://wolfgang.dautermann.at/maxima/nightlybuild/.

**Comment by robert-dodier** [comment]
Not observed in wxMaxima 24.08.0_DevelopmentSnapshot. I will assume the problem was fixed as suggested in the previous comment.
