### ISSUE TITLE
Output formula wrongly rendered - corrected by simp

### ISSUE THREAD

**Issue by ian11213** [wxMaxima-developers/wxmaxima#1415]
In the case identified, an output formula is clearly wrong - applying an operation such as trigsimp or ratsimp results in a reasonable-looking result. The attached files represent a fairly minimal demonstration - see in particular output cells %o7, %o8
(Zip file is .wxmx with extender changed to please github)
[renderbug.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/5391133/renderbug.pdf)
[renderbug.zip](https://github.com/wxMaxima-developers/wxmaxima/files/5391149/renderbug.zip)

**Comment by gunterkoenigsmann** [comment]
It looks like @KubaO has fixed that problem for the current nightly builds. For Windows that would be https://wolfgang.dautermann.at/maxima/nightlybuild/, for debian-like systems https://code.launchpad.net/~maxima-developers/+recipe/wxmaxima-for-maxima should work instead.

Sorry that I used such a short-handed answer on launchpad: I was in a hurry back then and was afraid that if the bug isn't in this bug list here it would get lost. And bugs that produce plausible output that is deeply wrong are the worst => Thanks a lot for providing a way to reproduce one.
