### ISSUE TITLE
Todays nightly build does not start

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1421]
The nightly build 2020/10/29 does not start:
![image](https://user-images.githubusercontent.com/2638713/97551398-3ac95900-19d3-11eb-94d3-1002427615f3.png)
Windows 10

**Comment by richardgobeli** [comment]
I just tried the new build and it does not start.
date & time 29-OCT-202 at 9:50 PM CDT.  Build is the 30-OCT-2020.

**Comment by ReneSci** [comment]
Did a test on this nightly build 2020/10/30, but still:
![image](https://user-images.githubusercontent.com/2638713/97678198-bd195200-1a93-11eb-82c0-3e4fd84969bc.png)

**Comment by gunterkoenigsmann** [comment]
In the meantime I've borrowed a Windows computer, installed Cmake, TDM-GCC, compiled wxWidgets - and have spent a whole day trying to tell cmake where wxWidgets is, to no avail. But it seems like one of my tries what might have gone wrong has happened to make wxMaxima work again - and as a side-effect it seems it has gotten nicer buttons, somehow.

Thanks for reporting wxMaxima on windows was broken!

**Comment by ReneSci** [comment]
Now it works again.

**Comment by KubaO** [comment]
> have spent a whole day trying to tell cmake where wxWidgets is

Unfortunately, this is a problem with cmake's wxWidgets supports and has not been fixed for ages. If you look into the appveyor configuration file, you'll see how I worked around that problem. It took me half a day to figure it out and was a total waste of time. I'm sure many people run into that :(
