### ISSUE TITLE
latest Version as well as git clone won't compile

### ISSUE THREAD

**Issue by IInatas** [wxMaxima-developers/wxmaxima#1423]
Hi

_First of all thank you to all who contribute to wxmaxima - it is fun to use it._

I normally use a git clone to pull the latest git version and compile it on Manjaro following the Compile.md file. 
Since yesterday (02.11.) the procedure is failing (as well as the tar.gz of version 20.11.0) with the following messages.

[wxmaxima-Version-20.11.0]$ **mkdir -p ../build-wxm**
[wxmaxima-Version-20.11.0]$ **cmake -G Ninja -S . -B ../build-wxm**  
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Looking for wxWidgets in:           
-- Looking for wxWidgets libraries in: 
-- Found wxWidgets: -pthread;;;-lwx_gtk2u_richtext-3.0;-lwx_gtk2u_aui-3.0;-lwx_gtk2u_adv-3.0;-lwx_gtk2u_html-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found suitable version "3.0.5", minimum required is "3") 
-- Found CCache /usr/bin/ccache
-- Found Git: /usr/bin/git (found version "2.28.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Using OpenMP for multiprocessing.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.20") found components: doxygen dot 
-- Copied and patched /Daten/Basteln/wxmaxima-Version-20.11.0/Doxygen/Doxyfile to /Daten/Basteln/build-wxm/Doxygen/Doxyfile
-- Found pandoc at: /usr/bin/pandoc
-- Found Perl: /usr/bin/perl (found version "5.32.0") 
-- Found po4a-translate at: /usr/bin/vendor_perl/po4a-translate
-- Found po4a-translate (version 0.61) at: /usr/bin/vendor_perl/po4a-translate
-- pandoc version >= 2 found - using option --pdf-engine=/usr/bin/xelatex
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- The updated POT and PO files were generated in the build directory.
-- Call 'make update-locale' to update the .po files in the source tree, too.
-- Call 'make update-locale-manual-in-source' to update the language specific .po files for the manual IN THE SOURCE TREE.
-- rpmbuild found - RPM package can be build with make package.
-- Configuring done
-- Generating done
-- Build files have been written to: /Daten/Basteln/build-wxm

[wxmaxima-Version-20.11.0]$ **cmake --build ../build-wxm**
[1/217] Generating wxmaxima.fi.md
FAILED: info/wxmaxima.fi.md 
cd /Daten/Basteln/build-wxm/info && /usr/bin/vendor_perl/po4a-translate -k 0 -f text -o markdown -m /Daten/Basteln/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /Daten/Basteln/wxmaxima-Version-20.11.0/locales/manual/fi.po -l wxmaxima.fi.md -M UTF-8
YAML::Tiny failed to classify line '    <link rel="icon" type="image/svg+xml" href="wxmaxima.svg" />' at /usr/share/perl5/vendor_perl/Locale/Po4a/Text.pm line 587.
[2/217] Generating wxmaxima.el.md
FAILED: info/wxmaxima.el.md 
cd /Daten/Basteln/build-wxm/info && /usr/bin/vendor_perl/po4a-translate -k 0 -f text -o markdown -m /Daten/Basteln/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /Daten/Basteln/wxmaxima-Version-20.11.0/locales/manual/el.po -l wxmaxima.el.md -M UTF-8
YAML::Tiny failed to classify line '    <link rel="icon" type="image/svg+xml" href="wxmaxima.svg" />' at /usr/share/perl5/vendor_perl/Locale/Po4a/Text.pm line 587.
[3/217] Generating wxmaxima.zh_CN.md
FAILED: info/wxmaxima.zh_CN.md 
.....
ninja: build stopped: subcommand failed.

Maybe I messed something up or is there a new additional step necessary ?

regards,
Marcus Menzel

**Comment by badshah400** [comment]
See it on my system too, the msg here reads:

```
[   14s] [1/217] cd /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/build/info && /usr/bin/po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/locales/manual/en.po -l wxmaxima.en.md -M UTF-8
[   14s] FAILED: info/wxmaxima.en.md 
[   14s] cd /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/build/info && /usr/bin/po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/locales/manual/en.po -l wxmaxima.en.md -M UTF-8
[   14s] YAML::Tiny failed to classify line '    <link rel="icon" type="image/svg+xml" href="wxmaxima.svg" />' at /usr/lib/perl5/vendor_perl/5.30.1/Locale/Po4a/Text.pm line 587.
[   14s] [2/217] cd /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/build/info && /usr/bin/po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/locales/manual/es.po -l wxmaxima.es.md -M UTF-8
[   14s] FAILED: info/wxmaxima.es.md 
[   14s] cd /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/build/info && /usr/bin/po4a-translate -k 0 -f text -o markdown -m /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/info/wxmaxima.md -p /home/abuild/rpmbuild/BUILD/wxmaxima-Version-20.11.0/locales/manual/es.po -l wxmaxima.es.md -M UTF-8
[   14s] YAML::Tiny failed to classify line '    <link rel="icon" type="image/svg+xml" href="wxmaxima.svg" />' at /usr/lib/perl5/vendor_perl/5.30.1/Locale/Po4a/Text.pm line 587.
```

and so on.

**Comment by gunterkoenigsmann** [comment]
@daute : The latest Ubuntu release comes with that broken version of po4a, too...

**Comment by varadpatil** [comment]
I don't want to use translations. How can I install without po4a?

`gmake[1]: Entering directory '/home/varad/source/build-wxm'
gmake[2]: Entering directory '/home/varad/source/build-wxm'
Scanning dependencies of target build_wxmaxima.es.html
gmake[2]: Leaving directory '/home/varad/source/build-wxm'
gmake[2]: Entering directory '/home/varad/source/build-wxm'
[  0%] Generating wxmaxima.es.md
YAML::Tiny failed to classify line '    <link rel="icon" type="image/svg+xml" href="wxmaxima.svg" />' at /usr/share/perl5/Locale/Po4a/Text.pm line 587.
gmake[2]: *** [info/CMakeFiles/build_wxmaxima.es.html.dir/build.make:66: info/wxmaxima.es.md] Error 255
gmake[2]: Leaving directory '/home/varad/source/build-wxm'
gmake[1]: *** [CMakeFiles/Makefile2:1831: info/CMakeFiles/build_wxmaxima.es.html.dir/all] Error 2
gmake[1]: Leaving directory '/home/varad/source/build-wxm'
gmake: *** [Makefile:163: all] Error 2
`

**Comment by daute** [comment]
If po4a is not installed (po4a-translate can not be found), wxMaxima compiles without translations. You could deinstall it (temporary).
I get (other) error messages when I want to compile with po4a 0.61.

One easy solution would be, to disable manual translations with po4a by default (translations for the manual only exist for three languages) and add an option to enable it. Would that be okay?

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment]
I was already thinking if there was a way to move po4a to the update-locales target so po4a can only be run by the one developer that happens to own a working po4a install.

Currently my update-locales target seems to be broken, though...

**Comment by daute** [comment]
I assume, with commit a77b8f9 I fixed the problem (in the latest git version). The build system should now correctly detect, if po4a is not installed or a too old version is installed and in that case does not generate translated manuals.
If a recent po4a version is installed, they are generated automatically.
Best regards, Wolfgang
