### ISSUE TITLE
Cannot evaluate input, Enter key not recognized

### ISSUE THREAD

**Issue by naipmoro** [wxMaxima-developers/wxmaxima#1427]
I'm on a fresh install of **ubuntu 20.04**. I cloned **wxmaxima 20.11.0** from git and compiled according to the instructions. Everything seemed to go well, but neither the **Enter** key, nor **Ctrl+Enter,** nor **Shift+Enter** does anything -- doesn't even move to a newline. I _can_ evaluate with **Ctrl+R,** but that evaluates all cells, so isn't a usable alternative.

Changing the evaluation options in **Edit>Configure** has no effect. The **Enter** key doesn't seem to work in any context.

**Comment by gunterkoenigsmann** [comment]
That's strange. Which language is your wxMaxima set to? Are you using X11 or Wayland and are you using xim as input method or ibus?
Normally it is one of these programs if something completely strange happens...

**Comment by naipmoro** [comment]
My system's language is US English. Wxmaxima was set to 'default language,' but changing it to English didn't help. I haven't changed 20.04's defaults: ibus and Xorg.  I noticed that in Edit>Configure Arial is the default math & documentation font. Ubuntu doesn't have Arial. I tried changing the font to Sans, but wxmaxima doesn't accept it (and usually crashes when I hit the OK button).

Btw, over the years I've compiled wxmaxima a number of times without issue, but this is the first time I've used the cmake approach.

**Comment by naipmoro** [comment]
I should probably also mention, though I assume it's known: one of the compiling requisites, **libwxgtk3.0-dev**, isn't available on ubuntu 20.04. Users are advised/required to use **libwxgtk3.0-gtk3-dev** instead.

**Comment by naipmoro** [comment]
I decided to blow away the 20.11.0 install and try 19.01.0 instead. That is working well except for one issue -- on start up, it emits the following warning: "Message from maxima's stderr stream: WARNING: Setting locale failed. Check the following variables for correct values: LANG=en_GB"

A small price to pay for a working wxmaxima!

**Comment by gunterkoenigsmann** [comment]
Good news everyone: Now the enter problem happens on my computer, too, which means I can finally debug the problem.
