### ISSUE TITLE
wxmaxima can't find .maxima directory and init files

### ISSUE THREAD

**Issue by naipmoro** [wxMaxima-developers/wxmaxima#1432]
I'm on **ubuntu 20.04** using the latest **20.11.0** version built from git. When wxmaxima starts up, I get this message:
**can't open file '"/home/naip/.maxima"/wxmaxima.ac' (error 2: No such file or directory)**
Note the strange quote marks.

When I tried to change the default font, I get similar messages:
**can't open file '"/home/naip/.maxima"/maxima-init.mac' (error 2: No such file or directory)**
and
**can't open file '"/home/naip/.maxima"/wxmaxima-init.mac' (error 2: No such file or directory)**

Directory .maxima does exist and it does contain both maxima-init.mac and wxmaxima-init.mac (but not wxmaxima.ac)

**Comment by gunterkoenigsmann** [comment]
Maxima takes the path part of the init file location from the environment variable `HOME` and tells wxMaxima where it finds these files. You can see what it tells to wxMaxima if you look at the output of the following maxima command:

          maxima_userdir;

My guess that this time something is wrong with the shell script `/usr/bin/maxima` in this case. Which shell do you use? `/usr/bin/maxima` actually contains double quotes, but on my computer they just make sure that the assignment works even if the path to the home dir contains a space.

**Comment by naipmoro** [comment]
Sorry, I was away for the last 2 days and didn't see your reply. I'm using bash. maxima_userdir; returns "/home/naip/.maxima"
