### ISSUE TITLE
config dialog box starts small

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1437]
Have you seen this.
The configuration window just needs moving to get it to expand, but still annoying. 
![image](https://user-images.githubusercontent.com/31253976/99306342-b3754580-281a-11eb-86a1-89561bedda0c.png)

**Comment by gunterkoenigsmann** [comment]
I allowed the config dialogue to resize - and told it to use a minimum size. Now I am wondering what went wrong...

**Comment by gunterkoenigsmann** [comment]
I have now told wxMaxima's config dialogue that it not only has a minimum size, but also a "initial size". Hope that this helps.

**Comment by richardgobeli** [comment]
I''l try it again in a few hours.

**Comment by gunterkoenigsmann** [comment]
I cannot guarantee that the computer the nightly build is done on currently works, though...

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/99719533-07c63280-2a72-11eb-97bf-39d77a9bc1db.png)
This build now works to open to the initial minimum size.  The configuration Dialog box starts in the normal size.  
The initial size is also the minimum size.  I can only make it bigger.

**Comment by KubaO** [comment]
@richardgobeli  So, do I understand correctly that from your perspective it works as it should now? I just want to make sure.

**Comment by richardgobeli** [comment]
Yes it works now.  I just thought that maybe the minimum size could be smaller than the initial size.   I don't know if anyone would want to use it smaller.

**Comment by gunterkoenigsmann** [comment]
I am still trying to find out how the details for setting the dialogue sizes work and am still unsure which size would be the best. But as the config dialogue is usable now I hope this bug can count as kind of resolved...

**Comment by richardgobeli** [comment]
This find with me.
