### ISSUE TITLE
We'll need a replacement for travis-ci

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1447]
Dear all,

Seems like we'll need a requirement for travis-ci, see https://news.ycombinator.com/item?id=25338983. Can't complain, though: They sponsored us over 1000 hours of CPU time for free and always provided a good service.

abcl seems to have moved all MacOs and linux builds to github actions instead: https://github.com/armedbear/abcl/blob/master/.github/workflows/abcl-test.yml

I cannot guarantee that I will have much time in the next few weeks that I can invest into the transition, though, so help is really appreciated.

**Comment by KubaO** [comment]
I think GitHub actions it will be. I’ll spend some time this week and the next to move the builds over 

- Kuba

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

The linux builds I've moved in the meantime - and they allow to finally reproduce a crash I was informed about per mail and that I never managed to reproduce.

**Comment by gunterkoenigsmann** [comment]
Migrated all builds to github-actions. And it is fast. I guess, though, that you'll find ways to optimize it further.

---

I've merged the segfault we get to master as the build is actually arguably broken. But for some reason even if I use the debug build I don't get informed about the line number the problem was in...

**Comment by KubaO** [comment]
"I've merged the segfault we get to master" - is there an issue for that? I'd like to have a look at that too, if possible.

**Comment by KubaO** [comment]
I'm closing this since @gunterkoenigsmann did an awesome job of porting our builds over to GitHub actions. Thank you!!!
