### ISSUE TITLE
Request: Dark theme

### ISSUE THREAD

**Issue by endolith** [wxMaxima-developers/wxmaxima#1450]
Referring to [this comment](https://sourceforge.net/p/wxmaxima/discussion/435775/thread/6c51363407/#7296/18f9) it doesn't look like anyone has requested it yet.  I have [this theme](https://gist.github.com/motchy869/fd68dba6d7320f0335092c9ffe47611a) enabled but it doesn't show parentheses, etc:

![image](https://user-images.githubusercontent.com/58611/102021382-64ed9500-3d4d-11eb-8a2f-a632398fcba2.png)

It would be nice if there were an official dark theme, especially one that affected the rest of the UI, but I'd be happy with a style.ini for just the main pane for now.  For comparison, I like the colors in Spyder's Dark color scheme:

![image](https://user-images.githubusercontent.com/58611/102021409-a1b98c00-3d4d-11eb-972f-a42473fd11c7.png)

and Notepad++'s Obsidian theme:

![image](https://user-images.githubusercontent.com/58611/102021432-c3b30e80-3d4d-11eb-84e8-e4654c7f4bd5.png)

**Comment by endolith** [comment]
It would also be nice to publish a default style.ini so we can go back to default color scheme, since I'm stuck with this broken one now and [there's no "restore to defaults" button](https://github.com/wxMaxima-developers/wxmaxima/issues/934) :)

**Comment by gunterkoenigsmann** [comment]
[style.txt](https://github.com/wxMaxima-developers/wxmaxima/files/5685338/style.txt)
[all.txt](https://github.com/wxMaxima-developers/wxmaxima/files/5685340/all.txt)

**Comment by gunterkoenigsmann** [comment]
With a bit of luck in tomorrow's nightly build parenthesis work fine...

**Comment by gunterkoenigsmann** [comment]
...and I forgot to mention: The nightly build also should contain a dark theme ("view/invert worksheet colors") and a "reset to all" button.

**Comment by KubaO** [comment]
See also #1080 - it should get closed whenever this one is, I think.
