### ISSUE TITLE
Assertion on selecting convoluted cells

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1454]
If trying to select text in the following construct:

````
a:1/b$
for i:1 thru 75 do a:subst(b=1/b+1,a)$
a;
kill(a)$
````

sometimes an assert fires telling cells not to have a parent cell. After that happens sometimes parenthesis are highlighted even if the cursor isn't above them.

**Comment by KubaO** [comment]
I’ll have to see how far back that goes. There’s a chance I broke it.

**Comment by gunterkoenigsmann** [comment]
We both have changed so much in the last few months => might have been any of us. What I am sure about, though, is, that the overall experience is much better than it was a few months ago...

**Comment by KubaO** [comment]
- 20.07.0 asserts in Group::GetGroup since there's no group
- 20.04.0 doesn't assert

I'll look some more into it. Should be a refactoring bug, or a latent bug that didn't have an assert before.

**Comment by KubaO** [comment]
The problem was that sometimes a valid cell might have had a null group, and this tripped the assertion. I've refactored things so that cells have constant groups - this got rid of all the post-hoc group setting code. Instead, whenever cells are created, they are assigned to the correct group.

**Comment by gunterkoenigsmann** [comment]
Setting groups only after the creation of cells and then forgetting to do so was a constant source of bugs, to begin with.
