### ISSUE TITLE
Binary distribution for Windows

### ISSUE THREAD

**Issue by dprodanov** [wxMaxima-developers/wxmaxima#1465]
Dear all,
Can you include release builds for Windows. The Maxima update cycle is quite uneven. 
I can't build the new releases from source.

best regards,

Dimiter

**Comment by gunterkoenigsmann** [comment]
I seem again to fail to tell cmake where to find wxWidgets even if I tried to ship around the problem that wxWidgets isn't reliably detected if it was compiled using cmake. 
@KubaO: Sorry to disturb you in the middle of the holidays. But do you have any idea what I am doing wrong, again, in https://github.com/wxMaxima-developers/wxmaxima/blob/feature/KoenGu/minGWBuild/.github/workflows/compile_windows.yml?

**Comment by KubaO** [comment]
I’ll have a look. The workaround from AppVeyor has to be copied verbatim, essentially.

**Comment by daute** [comment]
A Windows Installer was released for the current release (wxMaxima 21.01.0) now.
This was build by crosscompiling it from Linux (as the Windows installer for Maxima).
The code for creating this crosscompiled installer can be found here:
https://github.com/wxMaxima-developers/Crosscompiled-Windows-installer

Note: you will still need a Maxima installation and have to configure at the first start of this wxMaxima distribution, where Maxima can be found.

I am closing this ticket now.
