### ISSUE TITLE
Maxima help does not open

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1466]
![image](https://user-images.githubusercontent.com/31253976/103493982-2d2cb700-4dfa-11eb-8c25-4357b72aafdc.png)
Clicking on Maxima Help in the Help tab does not seem to do anything.  The WxMaxima help does work correctly.

**Comment by gunterkoenigsmann** [comment]
What does the "debug messages" sidebar say in that case - and which is your default html browser? And have you configured wxMaxima to use a specific browser as help browser 

In theory for opening the manual there are lots of good methods:

- We can ask wxWidgets to open the manual in its built-in browser.
- We can ask the system what programs it would open html files with and can tell this program to open the right chapter of the file.
- We can ask the system to open the file in the default html browser
- We can ask the system to open the right chapter of the file - and let the system decide which program to use for that.

Additionally each of these methods can tell us if the program could not be launched - so we can try another one. In reality, though, there are a few caveats:

 - wxWidget's built-in browser is slow, not meant to handle big files and crashes frequently.
 - on some systems the "open the default html browser" returns "success", but opens no browser if no default browser is selected.
 - and there are programs that first tell "success" and then choke on the information which chapter to open.

=> I am no more entirely sure if there is a method that will work on 100% of all systems.

**Comment by richardgobeli** [comment]
This is the debug output. The default browser is Chrome.
I tried setting directly the browser command and it still does not work.
This set as default.
![image](https://user-images.githubusercontent.com/31253976/103518604-b0b9c880-4e39-11eb-963e-ac062a96536e.png)

2:59:00 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
2:59:00 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
2:59:00 AM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
2:59:00 AM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
2:59:00 AM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
2:59:00 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
2:59:01 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
2:59:01 AM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
2:59:01 AM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
2:59:01 AM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
2:59:01 AM: Opening help file file:///C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/doc/html/maxima_singlepage.html#g_t_0025
2:59:01 AM: Error: Failed to open URL "file:///C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/doc/html/maxima_singlepage.html#g_t_0025" in default browser. (error 2: The system cannot find the file specified.)
2:59:01 AM: Launching the system's default help browser failed. Trying to execute "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --single-argument file:///C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/doc/html/maxima_singlepage.html#g_t_0025 instead.
2:59:06 AM: wxMaxima help file URI: file:///C:/maxima-current/share/doc/wxmaxima/wxmaxima.en.html


This is showing only the end of the path command.
The same happens when using this: 
![image](https://user-images.githubusercontent.com/31253976/103518763-f2e30a00-4e39-11eb-8879-79f406268620.png)

3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
3:09:30 AM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
3:09:30 AM: Opening help file file:///C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/doc/html/maxima_singlepage.html#g_t_0025

**Comment by daute** [comment]
It seems that anchors are not required to work with `file://` URIs (see e.g. https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6477862 - maybe there are better references).

For some reason, an anchor (`#g_t_0025`) is added, even if one opens only the maxima manual - and that file ("`maxima_singlepage.html#g_t_0025`") is not found (I got the same error using a test with wine).

We can probably change that, so that `maxima_singlepage.html` is opened without that anchor (where is that added? I didn't find that string in the wxMaxima source), but that will solve the issue with the complete Maxima manual, but not for the contextsensitive help.

Another - similar - issue: If one sets the help browser to firefox (using Linux), `file:///usr/share/maxima/5.41.0/doc/html/header.hhp#g_t_0025` is opened, instead of  `maxima_singlepage.html`. Why?

Best regards, Wolfgang

**Comment by richardgobeli** [comment]
I think now it may have been my Chrome that was open with 20 tabs that was the issue.
After stopping Chrome and restarting with the original tabs the manual does now open.
I gets the file error only when using the autodetect mode.
When it uses the Chrome path as a backup it works.
This is the Chrome backup "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --single-argument %1

3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/html/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/info/../html/maxima_singlepage.html
3:04:44 PM: Searching for maxima help file C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/share/../doc/html/maxima_singlepage.html
3:04:44 PM: Opening help file file:///C:/maxima-current/share/maxima/branch_5_44_base_210_g5d2af47b6/doc/html/maxima_singlepage.html#g_t_0025

**Comment by richardgobeli** [comment]
I searched my registry for g_t_0025 and did not find anything that would be in the wxMaxima configuration data to do this.

**Comment by daute** [comment]
This issue should be solved with commit 723c0e1.
