### ISSUE TITLE
I find a bug(or a feature?) when I use wxMaxima in Chinese simplified.

### ISSUE THREAD

**Issue by wang-xudong** [wxMaxima-developers/wxmaxima#1483]
When I use wxMaxima in Chinese simplified, and when I input 'l' or 'b', it will open a load package window, and when I use English, It doesn't happen. I found it seem like that  'l' and 'b' is a Shortcut equal to 'Ctrl+L' and 'Ctrl+B', so this bug may be a feature? But I want to know if I have a way to close this Shortcut , because it bring some inconvenience to me.

![image](https://user-images.githubusercontent.com/29012049/106737047-30150480-6651-11eb-891e-c8aa49acafcb.png)

**Comment by gunterkoenigsmann** [comment]
Clearly a bug. Are you happening to use Windows? If that is the case uninstalling wxMaxima and installing the one from https://wolfgang.dautermann.at/maxima/nightlybuild/ instead should resolve that issue.
