### ISSUE TITLE
block of installation due to user privileges

### ISSUE THREAD

**Issue by dprodanov** [wxMaxima-developers/wxmaxima#1487]
When I try to install I get a block from our ICT stating that the install program needs elevated user privileges. 
This can affect many users on corporate CyberArk EPM controlled systems.
Should be reconfigured.

**Comment by gunterkoenigsmann** [comment]
@daute : I seem to remember that we can only switch between "uninstallation is partially broken" and "we require root privileges". Is this correct?

**Comment by dprodanov** [comment]
Can you configure the installer to require minimal privileges?

**Comment by daute** [comment]
I tried it now to build an installer, which does work for 'everybody' (as admin) and 'just for me' (as user), but this needs more work.
Would a ZIP-File (which you can extract anywhere) be helpful?

(Maybe with a new release (Gunter), I assume, we fixed some important bugs in the meantime too).

**Comment by daute** [comment]
I created a new installer now, which can installed without admin permissions.

**Comment by daute** [comment]
Is your problem solved with the new installer? Can I close this ticket?

**Comment by dprodanov** [comment]
Where did you upload the installer?

**Comment by daute** [comment]
Github, of course. There, where the source code for wxMaxima 21.01.0 was released:
https://github.com/wxMaxima-developers/wxmaxima/releases/tag/Version-21.01.0

Under "Assets" you find `wxMaxima-21.01.0-2-win64.exe` (and the "-2" means, that that is the second version of the installer, which can be installed without admin permissions. I did also add some comments what I changed in the installer.
Best regards, Wolfgang

**Comment by dprodanov** [comment]
The integration could proceed after the choice Run anyway.
It detected an older installation but it gave an error Uninstall failed.

[image: image.png]

**Comment by daute** [comment]
[There is no image.png attached, but I will try to answer]

Yes, the first thing is clear, you get a warning, if you want to install a program which is not signed with an "Extended validation (EV) code signing" certificate. [Which does not mean, that the program was checked in any way, just that you paid much money...]

What's the second issue? If you have already installed the first version of the installer (which required admin permissions), you can't uninstall it with normal user privileges - of course.
Uninstall the first version before (of course with admin permissions).

Then you can install the new installer, which you requested, without admin permissions.
Best regards, Wolfgang

**Comment by dprodanov** [comment]
I can confirm that the new installation can override the old one.
So indeed the problem is solved.

best regards,
Dimiter

**Comment by daute** [comment]
Ok. I will create a similar crosscompiled wxMaxima-(only) Windows-installer for future releases.
