### ISSUE TITLE
wxMaxima error: can't open file wxmaxima.ac on evaluate all cells

### ISSUE THREAD

**Issue by KerryL** [wxMaxima-developers/wxmaxima#1489]
Hello,

I'm on Windows using wxMaxima 20.06.6 with Maxima version 5.44.0 (dowloaded the MSW installer from here: https://wxmaxima-developers.github.io/wxmaxima/download.html).

When I launch wxMaxima and any time I Evaluate All Cells, I get two identical wxMaxima error message boxes containing the following text:

` can't open file 'C:/Users/kloux/maxima/wxmaxima.ac' (error 3: The system cannot find the path specified.) `

There is no maxima directory under C:\Users\kloux.

The symptoms sound similar to Issue #1432, except that I'm on a different OS and appear to be using the latest Maxima version (so no problem with the installation routine).

wxMaxima appears to be working fine otherwise.

**Comment by gunterkoenigsmann** [comment]
I you uninstall your wxMaxima and install the one from https://wolfgang.dautermann.at/maxima/nightlybuild/ instead that should resolve your problem, I hope: My guess is that the directory `C:/Users/kloux/maxima/`  doesn't exist which means that `C:/Users/kloux/maxima/wxmaxima.ac` cannot be created - which normally only contains documentation about what this file can be used for.

The wxMaxima version from dautermann.at automatically creates this folder, if needed.

**Comment by KerryL** [comment]
Thanks Gunter. This did resolve the issue.
