### ISSUE TITLE
wxdraw3d with variables x[1], x[2] not working

### ISSUE THREAD

**Issue by b606** [wxMaxima-developers/wxmaxima#1490]
Hi,
I am running into an issue I did not have before : wxdraw3d does not seem to recognize x[i] in an expression as variables for explicit 3d plots (See screenshot below for a test session, f and g are the same functions). Do I miss something here in order to make the input cell %i5 work? (Renaming all variables in my real codes is a no go.)
![BUG_wxmaxima](https://user-images.githubusercontent.com/7627533/107852255-048fd800-6e10-11eb-9a8a-f0681d2d7fc4.png)

My system is an up to date debian buster

```
apt policy wxmaxima maxima
wxmaxima:
  Installé : 19.01.2-1
  Candidat : 19.01.2-1
 Table de version :
 *** 19.01.2-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
maxima:
  Installé : 5.42.1-1
  Candidat : 5.42.1-1
 Table de version :
 *** 5.42.1-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by gunterkoenigsmann** [comment]
Even if that is hard to see: This one seems to be a change in maxima -> would you be so kind and report the change to the maxima-discuss mailing list at https://maxima.sourceforge.net? These guys aren't against images in mails but will want to see all commands as ordinary text and often resolve bugs in a jiffy.

**Comment by b606** [comment]
Thank you very much for the quick answer !
Reported at https://sourceforge.net/p/maxima/bugs/3715/

Best regards

**Comment by daute** [comment]
I am closing this bug report - it is a bug in Maxima not wxMaxima, and the Maxima bug was solved and closed.
