### ISSUE TITLE
reproducible build: Timestamp in manpage

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1494]
Source: wxmaxima
Severity: normal
Tags: patch
User: reproducible-builds@lists.alioth.debian.org
Usertags: timestamps timezone
X-Debbugs-Cc: reproducible-bugs@lists.alioth.debian.org

The timezone affects the date embedded in the wxmaxima.1 manpages:

  https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/wxmaxima.html

  wxmaxima.1

  .TH·"WXMAXIMA"·"1"·"2020-12-27"·"wxMaxima·20.12.1"
  vs.
  .TH·"WXMAXIMA"·"1"·"2020-12-29"·"wxMaxima·20.12.1"

The attached patch fixes this by setting the timestamp to use the UTC
timezone.

Thanks for maintaining wxmaxima!

live well,
  vagrant

**Comment by daute** [comment]
Fixed by commit 3346749. Thanks for notification!

**Comment by daute** [comment]
How does one get the new release to be tested, to see, if the patch worked? Is our branch 'DebianPackaging' relevant? The first line of the file `debian/changelog`???

**Comment by gunterkoenigsmann** [comment]
The DebianPackaging is used for creating the official debian packages. DebianPackaging_NightlyBuild is used for the Ubuntu PPAs instead.
