### ISSUE TITLE
Unable to configure the proper language files

### ISSUE THREAD

**Issue by mtjmohr25** [wxMaxima-developers/wxmaxima#1499]
Under Windows 10 Pro: maxima 5.44.0 + wxMaxima 21.01.0 (C:\wxMaxima-21.01.0 or, alternatively, C:\maxima-5.44.0).

wxMaxima saves all my other changes in the configuration (Edit -> Configure) but not the one for the language: setting it to "German", for example, has no effect irrespective of the directory of installation (v. s.) for both user-based and Administrator-based runs of wxMaxima.

Where is my mistake?

**Comment by daute** [comment]
Hi,
The language selection did not work on Windows but I fixed the issue on 2021-02-08 (with commit f251359).

I published now a new release (Version-21.02.0) including an updated Windows installer (wxMaxima only), where the issue is fixed).
If you want a combined Maxima/wxMaxima installer, you can use my automatic build from:
https://wolfgang.dautermann.at/maxima/nightlybuild/
This includes the current Maxima and wxMaxima development version.

Best regards, Wolfgang

**Comment by mtjmohr25** [comment]
Danke, Herr Dautermann,

hat mit der Version 21.02.0 bestens funktioniert.

Eine Frage abschliessend: Gibt es ein Theme, das alles, nicht nur den "Formelbereich", in einem Dark Mode beherbergt?


Herzliche Grüsse



Ihr Markus Mohr

--

Dr. Dr. Markus Mohr

Facharzt für Allgemein-, Viszeral und Unfallchirurgie

Chirurgischer Fachgutachter (Traumatologie)

Experte für medizinische Zweitmeinungen

Medizinwissenschafts-Journalist

Software-Entwicklungen für die Medizin

Externer Datenschutz-Beauftragter

Deutsch- und Englischlehrer für Sprachschulen



Dott. Dott. Markus Mohr

Specialista di Chirurgia Generale, Viscerale e Traumatica

Perizie di chirurgia generale e traumatica

Esperto in seconde opinioni medico-scientifiche

Giornalista medico-scientifico

Sviluppi di software per la medicina

Delegato esterno per la protezione dati

Insegnante di tedesco ed inglese per scuole lingue



Markus Mohr MD PhD

Senior Surgeon Scientist (General, Visceral and Trauma Surgery)

Medical Assessor in the fields of Surgery, Visceral Surgery and Trauma

Specialist for Medical Second Opinions

Medical Science Journalist

Software Development for Medicine

External Data Security Official

Teacher of German and English for Language Schools



Reutterstrasse 62

80689 München

T: +39 348 362 3210

E: mtjmohr@hotmail.com<mailto:mtjmohr@hotmail.com>



LinkedIn: https://www.linkedin.com/in/dr-dr-markus-mohr-01b14218/

XING: https://www.xing.com/profile/Markus_Mohr2/cv

Facebook: https://www.facebook.com/mtjmohr25

Instagram: https://www.instagram.com/mtjmohr25/

reddit: https://www.reddit.com/user/mtjmohr

Twitter: https://twitter.com/mtjmohr

ResearchGate: https://www.researchgate.net/profile/Markus_Mohr


________________________________
Von: Wolfgang Dautermann <notifications@github.com>
Gesendet: Sonntag, 28. Februar 2021 21:04
An: wxMaxima-developers/wxmaxima <wxmaxima@noreply.github.com>
Cc: Markus Mohr MD PhD <mtjmohr@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [wxMaxima-developers/wxmaxima] Unable to configure the proper language files (#1499)


Hi,
The language selection did not work on Windows but I fixed the issue on 2021-02-08 (with commit f251359<https://github.com/wxMaxima-developers/wxmaxima/commit/f251359af6c7500ae92f4eb4ec0d3feb1a627455>).

I published now a new release (Version-21.02.0) including an updated Windows installer (wxMaxima only), where the issue is fixed).
If you want a combined Maxima/wxMaxima installer, you can use my automatic build from:
https://wolfgang.dautermann.at/maxima/nightlybuild/
This includes the current Maxima and wxMaxima development version.

Best regards, Wolfgang

**Comment by mtjmohr25** [comment]
Sorry, did not see that my email reply did come up here.

Just the same: After successfully installing and running version 21.02.0 of wxMaxima, I would like to know whether there is a dark mode theme covering the entire GUI.

I will open a new topic for that.
