### ISSUE TITLE
plot2d option incorrect in manual

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1501]
This should read as follows:
**grid2d** _[grid2d, value]_
Default value: false
original description
true will enable and false will disable.
![image](https://user-images.githubusercontent.com/31253976/109438832-4795a200-79f1-11eb-9b97-39c2055eae85.png)

**Comment by richardgobeli** [comment]
This is the document in Maxima.

**Comment by daute** [comment]
Fixed with Maxima commit: https://sourceforge.net/p/maxima/code/ci/4b4720
