### ISSUE TITLE
windows 10 security warning

### ISSUE THREAD

**Issue by WhereNow** [wxMaxima-developers/wxmaxima#1503]
When trying to download/install I get this friendly "blue note" from Microsoft:

Microsoft Defender SmartScreen prevented an unrecognized app from starting. 
Running this app might put your PC at risk.
App: | wxMaxima-21.02.0-win64.exe
Publisher: | Unknown publisher

Is there a way to let MS Defender know that this is not a virus?

**Comment by richardgobeli** [comment]
You should be able to add an exclusion in defender to ignore the file.

**Comment by daute** [comment]
Yes, that happens for not often downloaded programs, especially new releases.
[What also means, they track, what programs you download].

Code signing means, that you just spent much money for an expensive code signing certificate (probably more money for an  "Extended Validation (EV) Code Signing Certificate"), not that the code was checked in any way.

I assume, most free software is not signed.

**Comment by daute** [comment]
I got a code signing certificate now, the latest Maxima and wxMaxima Windows installers are digitally signed.

See the release note at:
https://github.com/wxMaxima-developers/wxmaxima/releases/tag/Version-21.11.0

I am closing this issue, I hope it is solved by using signed installers (although not an "EV" certificate).
