### ISSUE TITLE
A mac-dmg installer upload for each release

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1505]
In #1498 there was a request for uploading a dmg image of each release that runs both on intel and arm macs.

The .dmg is now built routinely. But https://github.com/marketplace/actions/github-release-create-update-and-upload-assets doesn't work under windows nor on macintosh computers => no idea on how to tell github actions to upload the .dmg without creating a new release for that.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : In the Coq project we use "https://github.com/actions/upload-artifact" - it is quite flexible, but it does not create a release automatically. We don't care because for a release the binaries need to be signed anyway, so we create the release and upload the binaries manually.

**Comment by gunterkoenigsmann** [comment]
I could upload the unsigned binaries to my private homepage. But how does one sign them? And can that be done using a Linux computer? I don't own a Mac...

**Comment by gunterkoenigsmann** [comment]
Found out how to sign them. As a first step basically you pay 99€ per year and Apple signs your ssh key.  Don't they want us to develop for them? Closing this issue as "wontfix", because currently too costly for me ;-(
