### ISSUE TITLE
Windows Wolfgangs x64 build 21.02.0 Font file "share/wxMaxima/fonts/LibertinusSerif-SemiboldItalic.otf" couldn't be loaded

### ISSUE THREAD

**Issue by Hale812** [wxMaxima-developers/wxmaxima#1506]
After uninstalling and updating to Wolfgang's x64 build 21.02.0 upon start I get an error message:

```
14:55:47: Font file "C:/maxima-current/share/wxMaxima/fonts/LibertinusSerif-SemiboldItalic.otf" couldn't be loaded (error 2: 指定されたファイルが見つかりません。)
14:55:47: Font file "share/wxMaxima/fonts/LibertinusSerif-SemiboldItalic.otf" couldn't be loaded (error 2: 指定されたファイルが見つかりません。)
```
"指定されたファイルが見つかりません" means the file can not be found.

But the file is there.

Tried reading it with Windows font tool and failed. Seems like the file is damaged, or incompatible with windows font engine.

I have Windows 7 x64 7601 on this machine.

Seems like the font has a bug: https://github.com/alerque/libertinus/issues/402
It should be replaced with something close and compatible.

**Comment by Hale812** [comment]
The last version compatible with Win7 of that font can be found here https://github.com/alerque/libertinus/releases/tag/v6.11

**Comment by Hale812** [comment]
Where's the font config file in windows btw? It seems it does not fit much with the new version, and I want to fix the config for using another typeface.

**Comment by daute** [comment]
Sorry, did not know about the problems with Windows 7.
The last release of the Linux Libertine fonts was 2012 and the Libertinus fonts are the active fork of the project.
They do provide nice math fonts, so maybe they can be the default math font for wxMaxima, that was the reason why I did include them.

I downgraded the Libertinus fonts now to version 6.11 (commit cc1f65d), that should solve the problems with Windows 7 (I can't test it here).

**Comment by Hale812** [comment]
I tried your latest nightly, now it starts up fine. To my surprise, the Libertinus typeface is actually nowhere present in the exported style.ini. Looks like you included it just as a nice alternative. let me check how it looks for a few days

**Comment by Hale812** [comment]
first impression from "Libertinus Math" 6.11, badly arranged large parentheses:
![image](https://user-images.githubusercontent.com/25519954/112774789-b4926b00-9075-11eb-8c88-a44c2e87be27.png)

With "Libertinus Serif Display", and "Libertinus Sans" large parentheses may **DISAPPEAR** completely in some formulas.

The only usable is "Libertinus Serif", but it still has not so nice large parentheses matching.

So the question is, was it really worth adding "Libertinus" typeface in the package?

**Comment by Hale812** [comment]
P.S.

I just got somenting like "getdefaultfontsize(...)" "need recalculate" error, and the unsaved project has closed itself.
Seems, it was a bad idea assigning "Libertinus Sans" font instead of default Windows font (which was assigned since ""Libertinus Sans O" can not be found in Windows)

**Comment by Hale812** [comment]
The "stable" v.20 release also crashes when choosing different fonts with something "error ... font size in pixels".

Looks like all the font-related code should be rewritten for Windows compatibility.

**Comment by gunterkoenigsmann** [comment]
As none of the developers owns a windows system this is an important piece of information - and for finding windows aspect fix bugs we always need as much information as we can. In this case we'll need the exact trigger and the full error message.

**Comment by daute** [comment]
Thanks for the feedback. Yes, in a first step, I only added them, they are not used by default.

We include Linux Libertine fonts now, but the last release was 2012 and "the actively developed Libertinus fonts are de facto a continuation of the now stalled Linux Libertine project." (citiation from Wikipedia). I think, including something, which is actively developed is better.
And they do include some math fonts (which Linux Libertine fonts didn't).

**Comment by Parlazo** [comment]
wxMaxima version: 20.06.6_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0

in options i can chance some font for title,chapter,subchapter and so on ... when changing the font with the button a window pops up to select the font ... there are options for color bold italic underline ... nothing works .. only font and size is working... and when i click abort many alert dialog windows pop up .... i always abort the alerts and then all is fine

i think this is maybe a bug at the same place... this is why i report here

**Comment by daute** [comment]
wxMaxima version: 20.06.6 is rather old. (Yes, I know, that's included in the latest Maxima installer...)

Does it work, if you use a current version?

Either self compiled, or use the wxMaxima-only Installer, which I released recently (https://github.com/wxMaxima-developers/wxmaxima/releases/tag/Version-21.02.0).
Or a nightly build from: https://wolfgang.dautermann.at/maxima/nightlybuild/

**Comment by daute** [comment]
The fonts are no longer included. Closing this issue.
