### ISSUE TITLE
printing now omits input/output labels?

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1507]
If I print (to file), I get no input/output labels in the printout. 
Can I have labels in the printout, is this configurable?
Also, output cells are centered in the printout. Same question.

Wxmaxima is at 21.02.0, 
the 'Show labels' setting is set to 'User-defined labels if available' (if relevant; but other variants don't work, either).

**Comment by yurytch** [comment]
After some messing with configuration options (not specifically aimed at the issue, just the general use), I see the issue's gone. Looks like I now can't replicate it (easily). 
It was, however,  quite real and annoying at the moment it happened (I had to break out some old AppImage version of wxmaxima to make a PDF), so let's not yet close the ticket, and keep an eye open on this issue (re)appearance.

**Comment by yurytch** [comment]
The issue is definitely happening. 
In printout (to PDF, and in print preview, too), 
1) resulting cells are centered (which wasn't required and can't be set or unset)
2) labels on both input and output cells are not rendered.

As far as I was able to research this, when cell objects are copied to a new tree before the printing out, LabelCells get created via calls of TextCell constructors (the 1st variants of those) with empty 'text' arguments. (In the tree of on-screen cells those arguments aren't empty.)

How the content part of output cells gets centered, I don't know, but might be it's the similar process.

The constructors in question are these:
```
TextCell::TextCell(GroupCell *group, Configuration **config,
                   const wxString &text, TextStyle style)
```

Can't help any further, sorry.

**Comment by gunterkoenigsmann** [comment]
Hey! That is exactly the bit of information I needed! Seems like LabelCell doesn't offer the right constructor for `LabelCell::Copy`.

**Comment by peterknicol1951** [comment]
Is this the same as #1579 in the Discussion section?

**Comment by yurytch** [comment]
> Is this the same as #1579 in the Discussion section?

Looks like it.

**Comment by yurytch** [comment]
The regression happened between 20.07.0 (works as expected) and 20.09.0 (shows the 'offending' behaviour), but between those tags there was a massive restructuring as well.

**Comment by yurytch** [comment]
I think I've got it (at least it works with my settings).

Instead of line 50 in LabelCell.cpp:
` DEFINE_CELL_TYPEINFO(LabelCell) `

this fragment is needed:
` DEFINE_CELL_TYPEINFO(LabelCell) `
` `
`std::unique_ptr<Cell> LabelCell::Copy(GroupCell *group) const`
`{`
`  std::unique_ptr<LabelCell> rr = std::make_unique<LabelCell>(group, m_configuration, m_displayedText, GetTextStyle() ); `
`  return rr;`
`} `
