### ISSUE TITLE
Visualization problems, 21.02.0 on Windows 7 64bit

### ISSUE THREAD

**Issue by DenisSbragion** [wxMaxima-developers/wxmaxima#1512]
Hello,

performing an "Evaluate all cells (Ctrl+Shift+R)" the visualization of some cell gets corrupted, see the following image:

![immagine](https://user-images.githubusercontent.com/32162088/111450510-c1779c00-8710-11eb-8d4b-4e8ee75ab947.png)

This doesn't happen if I evaluate each cell line by line:

![immagine](https://user-images.githubusercontent.com/32162088/111450721-f7b51b80-8710-11eb-976b-c991352ffcc1.png)

All cells get also immediately fixed if I select a different font in the configuration form and then I switch back to the original font. 

Tried with many different fonts to see if it was just a font problem, but the behaviour doesn't change no matter what the font selected.

Thank you very much for this useful software.

Bye,

Denis Sbragion

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this report! On my own machine that for some reason could not be triggered. But I have now found a setup in which it was obvious that we started cell size recalculations in the wrong place...

**Comment by gunterkoenigsmann** [comment]
Wow... ...your bug report seems to have helped to resolve several classes of bugs I failed to find the reason for. Thanks a lot!

@daute : Since we now support ARM Macbooks and the display code has grown much more reliable - would you think this might be a good time for a new release?

**Comment by DenisSbragion** [comment]
> Wow... ...your bug report seems to have helped to resolve several classes of bugs I failed to find the reason for. Thanks a lot!

You're welcome, but I did nothing more than refreshing one of my wxMaxima files and taking a couple of screenshots. Glad to be of help, but it's me who have to thanks the wxMaxima team for its great work. Looking forward for the new release.

**Comment by richardgobeli** [comment]
This was the same problem I saw in this report. https://github.com/wxMaxima-developers/wxmaxima/issues/1471

**Comment by daute** [comment]
> @daute : Since we now support ARM Macbooks and the display code has grown much more reliable - would you think this might be a good time for a new release?

Another release? The last one was made is just a few days ago. I assume, I will be rather busy on the weekend maybe on Sunday or next week. Maybe a minimum interval time between releases - like one month, as SBCL - should be used?

**Comment by DenisSbragion** [comment]
Downloaded and installed the latest version right now. I just wanted to let you know that the problem is fixed to me.

Thank you very much.
