### ISSUE TITLE
Question: which Lisp implementation is best when using Maxima under Linux?

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1513]
I realise, that this is probably very off-topic and I did make an effort to find an answer (found this, for example [https://maxima.sourceforge.io/lisp.html](https://maxima.sourceforge.io/lisp.html) ), but I noticed that wxMaxima maintainer uses SBCL rather than GCL, so I wanted to know if there are some advantages (e.g. speed) of using that particular or some other Lisp implementation. On Android we have to use ECL, because that is the smallest and easiest to compile. But on Linux all flavours are available and I would really like to know the experts' opinion as to which Lisp is the best for Maxima. Again, apologies for off-topic question and thank you in advance to anyone who would give his advice on this.

**Comment by daute** [comment]
Concerning the Lisp info on the Maxima website: The "README-lisps.md" in the Maxima code (https://sourceforge.net/p/maxima/code/ci/master/tree/README-lisps.md) - I recently converted it to Markdown - provides more up-to-date information, e.g. working lInks and it mentions ABCL, which also works.

It's a pity, that some Lisp compilers which **are** under active development (there are recent commits in their repositories) do not produce releases for several years, e.g. CLISP (11 years ago), GCL (7 years ago (but they released **98** "pre"-releases - (Version_2_6_13pre98 is available from https://git.savannah.gnu.org/cgit/gcl.git), ...).

And Clisp was the first Lisp, which enabled me to crosscompile Maxima for Windows (and I tested several Lisps for that project), thats why I like it. And I do not do really time-consuming computations with Maxima, so the speed 'problem' is not so large for me.
Best regards, Wolfgang

**Comment by tigran123** [comment]
Thank you, guys, for answering my question. (I leave this issue open to give more people the opportunity to read this information, but when you feel it is time to close this issue, please do so, of course).

**Comment by tigran123** [comment]
UPDATE: I said above, that on Android we are limited to ECL and Maxima 5.41. This is no longer the case. I have just now compiled the latest SBCL (2.1.2) and Maxima 5.44.0 under Android inside UserLand. Even xmaxima works (under lxde graphical environment). Furthermore, I have compiled wxMaxima and it works as well.

**Comment by tigran123** [comment]
Another update: yesterday it (wxmaxima) did work fine on Android under UserLand in LXDE session, but now it does not. And neither does xmaxima -- they both fail to start maxima with "-s port". I tried `wxmaxima --logtostdout --pipe" and it confirms that maxima process dies unexpectedly. Oh well, still all the graphical stuff like plot2d, plot3d, plotdf -- all work fine and interactively. So I am quite happy, but it would be nice to figure out why "maxima -s port" sometimes works and sometimes does not.

**Comment by tigran123** [comment]
I know that this sort of discussion belongs to Discussions part (at the time I opened it I was not aware that the Discussions part existed, or maybe it didn't then), but I thought it may be useful to post this comparison on calculating the digits of Pi using maxima with various Lisp implementations, as well as doing the same in other CAS systems:

```
$ rmaxima
Maxima 5.45.1 https://maxima.sourceforge.io
using Lisp SBCL 2.1.2
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) showtime:true;
Evaluation took 0.0003 seconds (0.0040 elapsed) using 0 bytes.
(%o1)                                true
(%i2) fpprec:10^6;
Evaluation took 1.3625 seconds (1.3640 elapsed) using 1.836 MB.
(%o2)                               1000000
(%i3) bfloat(%pi)$
Evaluation took 30.3202 seconds (30.3236 elapsed) using 104.549 MB.
(%i4) 
$ rmaxima -l ecl
;;; Loading #P"/usr/lib/ecl-16.1.2/sb-bsd-sockets.fas"
;;; Loading #P"/usr/lib/ecl-16.1.2/sockets.fas"
Maxima 5.45.1 https://maxima.sourceforge.io
using Lisp ECL 16.1.2
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) showtime:true;
Evaluation took 0.0000 seconds (0.0000 elapsed)
(%o1)                                true
(%i2) fpprec:10^6;
Evaluation took 0.0190 seconds (0.0200 elapsed)
(%o2)                               1000000
(%i3) bfloat(%pi)$
Evaluation took 0.7040 seconds (0.5450 elapsed)
(%i4) 
$ rmaxima -l gcl

Maxima 5.45.1 https://maxima.sourceforge.io
using Lisp GNU Common Lisp (GCL) GCL 2.6.12
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) showtime:true;
Evaluation took 0.0000 seconds (0.0000 elapsed)
(%o1)                                true
(%i2) fpprec:10^6;
Evaluation took 0.0100 seconds (0.0200 elapsed)
(%o2)                               1000000
(%i3) bfloat(%pi)$
Evaluation took 0.5200 seconds (0.5500 elapsed)
(%i4) 
$ math11
Mathematica 11.3.0 Kernel for Linux x86 (64-bit)
Copyright 1988-2018 Wolfram Research, Inc.

In[1]:= AbsoluteTiming[N[Pi,10^6];]                                                                                                  

Out[1]= {0.250804, Null}
$ math
Mathematica 12.3.0 Kernel for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= AbsoluteTiming[N[Pi,10^6];]                                                                                                  

Out[1]= {0.252919, Null}
$ ipython
Python 3.8.0 (default, Dec  3 2019, 12:20:10) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy import *                                                                                                          

In [2]: %time a=pi.evalf(10**6);                                                                                                     
CPU times: user 649 ms, sys: 8.46 ms, total: 657 ms
Wall time: 657 ms
$ maple
    |\^/|     Maple 2019 (X86 64 LINUX)
._|\|   |/|_. Copyright (c) Maplesoft, a division of Waterloo Maple Inc. 2019
 \  MAPLE  /  All rights reserved. Maple is a trademark of
 <____ ____>  Waterloo Maple Inc.
      |       Type ? for help.
> st:=time(): evalf[10^6](Pi): time() - st;                                                                                         
                                                               23.672

>                                                                                                                                   
> quit                                                                                                                              
memory used=13699.8MB, alloc=26.5MB, time=23.70
```

**Comment by robert-dodier** [comment]
This has been an informative discussion, however, since the question has been resolved, the ticket can be closed, as has been noted previously. Let's open any further discussion under a new heading as appropriate.
