### ISSUE TITLE
Weather icons in toolbar (KDE Plasma/Breeze Icon Theme)

### ISSUE THREAD

**Issue by qwerty287** [wxMaxima-developers/wxmaxima#1514]
Hello,
if I use wxmaxima on my KDE Plasma with the default Breeze Icons, there are two weather icons in the toolbar (a sun and a sun with clouds). This could be confusing, even if there are tooltips.
![Screenshot_20210319_090351](https://user-images.githubusercontent.com/80460567/111909886-522ae080-8a5f-11eb-9392-adfef6fd5b2c.png)

**Comment by daute** [comment]
Do you have some recommendations, which (free to use) icons should be used for these functions (described in the tooltips)?

**Comment by qwerty287** [comment]
As replacement for the second icon (the sun with clouds) maybe an eye or an crossed out eye. And for the first maybe an arrow up?

**Comment by daute** [comment]
I replaced the icons as suggested.
