### ISSUE TITLE
Critical bug in copy-paste of saved/loaded results: parentheses lost in denominator. 

### ISSUE THREAD

**Issue by Hale812** [wxMaxima-developers/wxmaxima#1518]
In the ver **21.02.0**-dev by Wolfgang, there is a very serious bug destroying the math during copy-pasting (and it is the main thing I do in "wx" frontend, when solving problems)

The outer parentheses in the denominator may disappear changing the expression in most unpleasant way.

It happens when copying strings loaded from wxmx files. (i.e. not that output just generated by computation)
So, it may have roots not only in textbuffer copy code, but in file load code as well.

A way to reproduce:
1. Create a new project and put a formula there, something like:
(1-a)·p·(a^2·p+a·p+p+2·a·m+m)/(3·(p+a·m));
![image](https://user-images.githubusercontent.com/25519954/112587794-96dcc000-8e41-11eb-82f5-70918c00de83.png)

2. Save the project to wxmx file, and load the file using file-open.
...the displayed string seems the same...
3. but now click the string, copy it to the text-buffer, and paste as a new string.
-the outer parentheses in the denominator will disappear. 
![image](https://user-images.githubusercontent.com/25519954/112587995-0357bf00-8e42-11eb-89ca-68a5758409d4.png)

**Comment by Hale812** [comment]
P.S.
The cell code saved is
`<cell type="code">
<input>
<editor type="input">
<line>(1-a)·p·(a^2·p+a·p+p+2·a·m+m)/(3·(p+a·m));</line>
</editor>
</input>
<output>
<mth><lbl altCopy="(%o1)	">(%o1) </lbl><f><r><r><p><n>1</n><v>−</v><v>a</v></p></r><h>·</h><v>p</v><h>·</h><r><p><e><r><v>a</v></r><r><n>2</n></r></e><h>·</h><v>p</v><v>+</v><v>a</v><h>·</h><v>p</v><v>+</v><v>p</v><v>+</v><n>2</n><h>·</h><v>a</v><h>·</h><v>m</v><v>+</v><v>m</v></p></r></r><r><n>3</n><h>·</h><r><p><v>p</v><v>+</v><v>a</v><h>·</h><v>m</v></p></r></r></f>
</mth></output>
</cell>
`
BTW, again: is it necessary saving each symbol in its private xml wrapping? The stored data size gets 8(!) times overbloated. It is not even a bitmap image, but the wxmx file gets crazy big.

**Comment by Hale812** [comment]
P.P.S.
I just checked it with 20.06.6 stable release.
It loads the file with the same bug.
But saves it with the abovesaid parentheses. So saving the project from v.21.02.0 will damage all the result strings there, and make them interpreted wrong in any version of "WX".

It may look that the problem is in the "save" code of v.21.02, but I should underline that it is also in the "load" interpreter code of ANY WXmaxima frontend. It just should honour the whole denominator of the output with parentheses, even when such are not explicitly inserted in mth string.

**Comment by gunterkoenigsmann** [comment]
If it has the potential to change user data we need to resolve it as fast as we can.

**Comment by Hale812** [comment]
Weirder it gets.
I checked v.20 saved code.
And you know, there are no parentheses either!

check it:
`</lbl><f><r><r>(1−a)</r> * p * <r>(a^2 * p+a * p+p+2 * a * m+m)</r></r><r>3 * <r>(p+a * m)</r></r></f>`
(simple tags were replaced for readability)

The difference is the multiplication symbol! It is possible that the new ver.21 saves the multiplication symbol as on screen in Unicode.
But the code of the load interpreter can not handle it correctly, and never could.

**Comment by Hale812** [comment]
____________
I confirm.
The problem is in multiplication symbol. The load interpreter can not handle it well.

I just replaced the Unicode "dot" with a classic "*", and repacked the test file, and it loads without problems.

So the workaround would be changing the multiplication back to "*" when saving, before the interpreter is fixed.

**Comment by gunterkoenigsmann** [comment]
That explains a lot! Thank you very much for debugging this!
