### ISSUE TITLE
Pressing Ctrl-X while a math cell is selected causes a crash

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1519]
Version 21.02.0-DevelopmentSnapshot (Build from Git version: 89d9f1470)

To reproduce just open a new file and enter `2+2;` followed by `Shift-ENTER` to evaluate it and then select the cell, i.e. just to the left of both the input and output markers. The cell is selected which is indicated by the orange colour. So, now I expected that pressing `Ctrl-X` would cut this cell. I wanted to select just the input part, of course. But anyway, it shouldn't crash, should it? So, after selecting it press `Ctrl-X` and observe that wxmaxima process terminates with the message `Aborted` printed on the terminal, as if someone sent it `SIGABRT` (e.g. via `kill -6 <pid>`).

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this report! Resolved this in commit 05a55c3b4cf63e79e48ccaf6744f88a351888a6c
