### ISSUE TITLE
Subscripts don't work on Greek letters

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1522]
wxMaxima provides a nice extra feature to Maxima, providing subscripts via underscore, so that writing `x_0` we get `x` with the subscript `0`. However, this does not work with Greek letters for some reason.

**Comment by gunterkoenigsmann** [comment]
I guess your maxima was compiled using gcl, which doesn't know about unicode and therefore cannot guess how many letters a greek letter is.

````
wxsubscripts: 'all$
````

should work around that. Perhaps I should make it the default...

**Comment by tigran123** [comment]
It was actually SBCL, but thank you, yes, setting it to `'all` worked and also preserved it in `~/.wxMaxima` in the form of the line `autosubscript=1`, so it works after the restart of wxMaxima.
