### ISSUE TITLE
Some issues with non standard use of header files on older macOS

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1523]
Dear wxMaxima Team,

on older Macs there are issues with nullptr_t. The comment from an expert says - as far as I understand it - that nullptr_t in the global namespace is a C++11 feature. Including <stddef.h> to get this is not portable. Instead one can include <cstddef> and use std::nullptr_t.

The original post from a MacPorts expert:

> This code is likely trying to get nullptr_t in the global namespace by including <stddef.h>. Firstly, nullptr_t is a C++11 feature, and if a C++11 compiler is needed to build this port, it should indicate it by setting compiler.cxx_standard 2011. Secondly, <stddef.h> is a C compatibility header, and using those in C++ is deprecated. So while the headers on El Capitan may be buggy in that <stddef.h> doesn't provide all the functionality it should, it's more future-proof to include <cstddef> instead and use std::nullptr_t, which should neatly fix the El Capitan issue as well.

Note: the `compiler.cxx_standard 2011` is a MacPorts setting enforcing C++11. I can do that, if you say wxMaxima requires C++11.

**Comment by daute** [comment]
The header `stddef.h` is **not** included in the wxMaxima sourcecode, but in the wxWidgets project (which is the base for wxMaxima (therefore the "wx" at the start of the name)) - so they should probably change that:

```
$ fgrep -r stddef.h ~/Software/wxmaxima   # (no results)
$ fgrep -r stddef.h /usr/include/wx-3.0
/usr/include/wx-3.0/wx/hashmap.h:#include <stddef.h>             // for ptrdiff_t
/usr/include/wx-3.0/wx/memory.h:#include <stddef.h>
/usr/include/wx-3.0/wx/chartype.h:    #include <stddef.h>
/usr/include/wx-3.0/wx/defs.h:#include <stddef.h>
```

And we expect a C++14 compiler by setting the following CMake variables:
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
But CMake does probably not set the flags for the used compiler.

**Comment by MSoegtropIMC** [comment]
Thanks for the quick answer!

As far as I can tell CMake does not fail if there is no C++ 14 compiler, but I can specify this in the MacPorts file.

So should I require C++14 there?

**Comment by daute** [comment]
If there is one available - yes please. And tell, if the compilation worked.

**Comment by daute** [comment]
I believe, I found out, how one can require C++14.

**Comment by daute** [comment]
Does it work, if you require C++14? Can we close the ticket?
(Release 21.04 should set the flags for a C++14 compiler automatically)

**Comment by gunterkoenigsmann** [comment]
In theory wxMaxima 's Cmake construct asks the ocmpiler to provide C++14...

**Comment by MSoegtropIMC** [comment]
I haven't heard of issues regarding this in the last 6 months, so I guess it is either fixed of machine which don't have at least CXX 14 by default are getting obsolete.

I will close this.
