### ISSUE TITLE
Long result output can not wrap

### ISSUE THREAD

**Issue by zhulaojianke** [wxMaxima-developers/wxmaxima#1528]
wxMaxima version: T
using wxWidgets version: T
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Administrator/maxima/
Help dir: C:\maxima-5.44.0\share/doc/wxmaxima

**I check the menu, edit -> configuration -> worksheet, -> "Autowrap long line" dropdown box. But only two option there, "no" and "text only". When a calculation rerult a very long output, and I need to read it, I must horizontal scroll the workplace window.**

**I suggest change this dropbox to a list of check boxs, and list all the elements that are displayed, such as "text", "result", "math expression", etc. And users can check the corresponding elements according to their needs.** 

**Plus, there's a bug, when the result is very very long, and I check the "Always show all digits" from right-click context, there will display It will display a white line. For example:**
![image](https://user-images.githubusercontent.com/16543111/114130982-46329000-9934-11eb-8c58-fac93e86d7a3.png)
**and I check the "Always show all digits":**
![image](https://user-images.githubusercontent.com/16543111/114131096-81cd5a00-9934-11eb-99c4-85c5617e0e7c.png)
**Hopefully, at least you can fix this.**

**I have tried this expression in xMaxima and Maxima, and they work well, so it seemly is only a wxMaxima bug.**
![image](https://user-images.githubusercontent.com/16543111/114131305-fe603880-9934-11eb-8e32-b95bdcdf2a78.png)
![image](https://user-images.githubusercontent.com/16543111/114131439-32d3f480-9935-11eb-83ee-092f51492f91.png)

**Comment by zhulaojianke** [comment]
I have try this bug on wxMaxima version: 21.02.0_MSW, it still exists.

**Comment by zhulaojianke** [comment]
Another method, press shift + mouse middle wheel to horizonal scroll the page, and press shift + ctrl + mouse middle wheel to horizonal scroll by pages, this can not fix the long result display problem, but at least it makes users feel better.

**Comment by Parlazo** [comment]
Maybe you can turn the result into a string and break the string on multiple lines after X characters?
Its probably not a optimal solution but maybe it helps out instantly until some perfect solution exists.

**Comment by zhulaojianke** [comment]
What I do now is switch to Xmaxima when a problem I'm working on might have a long result output.

And I have written an Autohotkey app to achieve this function that pressing shift + mouse middle wheel to horizontal scroll in maxima.

[horizontalscroll.zip](https://github.com/wxMaxima-developers/wxmaxima/files/6293396/horizontalscroll.zip)

**Comment by Parlazo** [comment]
this...
sum(1/x^2,x,1,10000);

gives me this...
1.644834071848065

may i miss some thing?

auto warp is = text only
Always show all digits" from right-click context

wxMaxima version: T
using wxWidgets version: T
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0

**Comment by Parlazo** [comment]
now i did somehow play in the numbers menu and ...

sum(1/x^2,x,1,10000);

and i see your problem.... the whole result is gone but there is a long line ... i use black background and all numbers are in color ... but not this result .... all i see is ...

a looong empty line 
/
a looong empty line 

if i copy the empty lines as text and paste it to some where out of wxMaxima i can see the long number as...

5[...] and /[...]200000000 each on a line

here my findings.... if you like you can use the DIY printer option ... i have not testet it on paper .. may it works may not

`
numer: false$;
float2bf: false$;
bftorat: true$;
bftrunc: false$;
fpprintprec:4680$;
fpprec: 4680$;
simp: true$;

print("Test Magic Number:")$;

print("")$;
print("Magic Number as a fancy formula:")$;
print("(This is non-problematic.)")$;
simp: false$;
Formula: ev(sum(1/x^2,x,1,10000));
simp: true$;

print("")$;
print("Magic Number as a crazy long ratio:")$;
print("(This is able to break the display,")$;
print("the number is on two lines,")$;
print("you can copy each line,")$;
print("with fancy dark colors it is invisible)")$;
set_display('none)$;
LongRatio: sum(1/x^2,x,1,10000);
set_display('xml)$;

print("")$;
print("Magic Number as a crazy long broken line:")$;
print("(wxMaxima will show this as a long line,")$;
print("the line will break according to the settings in wxMaxima,")$;
print("some where in the middle is a division '/'.)")$;
set_display('ascii)$;
LongDivision: sum(1/x^2,x,1,10000);
set_display('xml)$;

print("")$;
print("Magic Number as a ratio:")$;
print("(Right-Click on the result,")$;
print("select the option to show all numbers,")$;
print("the numbers will break the wxMaxima display,")$;
print("all numbers get invisible except of '/',")$;
print("if you rerun the calculation even the '/' will be invisible,")$;
print("to reset the view you must go to the wxMaxima-Settings,")$;
print("select max. digits to display and press OK.")$;
fpprintprec:4680$;
fpprec: 4680$;
ShortRatio: sum(1/x^2,x,1,10000);

print("")$;
print("Magic Number as a miracle:")$;
print("(Right-Click on the result,")$;
print("select the option to show all numbers,")$;
print("the numbers will break the wxMaxima display,")$;
print("the number will get invisible,")$;
print("the number can be nonvisible but you can copy it,")$;
print("to reset the view you must go to the wxMaxima-Settings,")$;
print("select max. digits to display and press OK.")$;
bftrunc: false$;
fpprintprec:4680$;
fpprec: 4680$;
bfloat(LongLine);

print("")$;
print("Magic Number through a DIY-Printer:")$;
print("(The line lengh is adjustable at 'lbrk',")$;
print("you see the whole ratio,")$;
print("some where in the middle is a fancy division '...----...',")$;
print("you can adjust the divisor at 'FancyLiner'.")$;
string: string(sum(1/x^2,x,1,10000))$;
lbrk:80$; /* Desired Line Lengh */
brkTok: "/"$; /* Search for ... */
FancyLine: ""$;
FancyLiner: "-"$; /* ... and replace with fancy - */
getstrl: slength(string)$; /* Check String Lengh once upon a time */

p1: ssearch(brkTok, string, 'sequalignore, 1) -1$;

/* Print unit */
for i:1 step lbrk while i <= p1 do (
    printf(stdout,"~a~%",substring(string, i, if i+lbrk < p1 then i+lbrk else p1+1))
)$;
/* Print fancy - */
for i:1 thru lbrk step 1 do FancyLine: concat(FancyLine,FancyLiner)$;
/* Print divisor */
printf(stdout,"~a~%", FancyLine)$;
for i:p1+2 step lbrk while i <= getstrl do (
    printf(stdout,"~a~%",substring(string, i, if i+lbrk < getstrl then i+lbrk else getstrl+1))
)$;

print("")$;
print("")$;
print("")$;
print("Have a nice time and keep in mind ...")$;
print("Валентина Владимировна Терешкова")$;
print("... was the first woman in space.")$;
`
do copy paste and try... may it helps

**Comment by zhulaojianke** [comment]
O_O!!! Nothing to say, rather surprised!

I try your code and the result so AWESOME!

Thank you very much Parlazo!

**Comment by gunterkoenigsmann** [comment]
In the mean time I perhaps have found a way to allow linebreaks in numbers if the numbers are wider than the screen. But I will need a few days before I can try to start implementing it...

**Comment by gunterkoenigsmann** [comment]
Do you want all lines of a number to end in a backslash - or do you want the program to just insert a linebreak at the end of the line?

**Comment by gunterkoenigsmann** [comment]
I can also try to add a "↵" sign or similar before all linebreaks that are in the middle of a number, instead.

**Comment by Parlazo** [comment]
> 
> 
> Do you want all lines of a number to end in a backslash - or do you want the program to just insert a linebreak at the end of the line?

The very best would be if we can choose?
Some want just a line break and no annoying fancy stuff
others need some how a special kind of symbol at a line break
some may like to adjust the line width by default as in the settings or instantly with a special magic wxMaxima command similar to the wxMaxima table_form() command.

a other question is how such big outputs will handle special symbols
will it be all as one text block... or can a user choose how to handle special symbols?
the number above is a good example its crazy long number... to search for a slash in it is confusing.. thats why i have taught it could be nice to break the long numbers but to replace the / divisor with a line ... so some one can see where things end or start in this ratio.

and also important is to break such lines in a way so some can print the lines on multiple papers with or without fancy line break symbol and in a line width as desired.

**Comment by zhulaojianke** [comment]
If there are some "root sign" or "integral sign" in the long result, or a matrix contain long expression elements, that realy seemed like a disaster.

**Comment by gunterkoenigsmann** [comment]
If I don't need to add a fancy linebreak symbol that would make things much easier; Automatically adding a linebreak after long numbers that are broken into lines should be easy to code, instead. But if it looks too strange I will add a separate config option for this.

**Comment by Parlazo** [comment]
>  I will add a separate config option for this

To give options to users always sounds good to me, probably to others too. :smiley:

**Comment by zhulaojianke** [comment]
I thought carefully about what kind of word wrap I wanted, and after all, very long strings of numbers are rarely encountered in practical calculations, but very long derivated functions often turn out to be, so it would be very nice if WxMaxima allowed "fold line operator" to be used for input, and if the output was too long, it also allowed the user to add "fold line operator" in a "set" statement after previewing the result. The operator is similar to /r/n in Windows.

For example:
a+b+c*d-e
After manually folding the line:
a+b+...
c*d-e

Below is a example using Mathcad 15, using Ctrl + Enter to fold the line inputing:
![image](https://user-images.githubusercontent.com/16543111/115016876-40b2e800-9ee8-11eb-8340-29335b4e905b.png)
But in Mathcad 15 can not manually fold the output line.

**Comment by gunterkoenigsmann** [comment]
Tomorrow's nightly build might resolve most of your issues.

**Comment by Nody22** [comment]
Hello, did you find a solution for this problem ?
I have long algebraic expressions and when I want to export the file or save it in pdf or print it, the expressions goes beyond the right border, and it is not readable. 
thanks for your help,
