### ISSUE TITLE
Visualization and cells evaluation problem in hide code cells mode.

### ISSUE THREAD

**Issue by Fran6J** [wxMaxima-developers/wxmaxima#1532]
Hello,
With my configuration the behavior described in #1502 persist (The height of brackets don't change in Hide Code Cells mode). 
example:
> code cells visible:
![image](https://user-images.githubusercontent.com/24839759/114522311-8f8c2380-9c43-11eb-91ce-248ebce23c30.png)
> V21.01 or V21.04: when I toggle in hide code cells mode:
![image](https://user-images.githubusercontent.com/24839759/114522889-117c4c80-9c44-11eb-9fe2-973cfd285585.png)
as the version V20.06, I think the expected behavior is: 
![image](https://user-images.githubusercontent.com/24839759/114523570-b26b0780-9c44-11eb-8fbb-adfd9c31b781.png)

moreover when I perform "Send current cell to maxima.." or "Evaluate the file from.. " **in Hide code cells mode**, I get the next message:
![image](https://user-images.githubusercontent.com/24839759/114523906-0ece2700-9c45-11eb-8f34-e21a61ecf4d3.png)

Thank you very much for this useful development.

Francis.

for information:
-------------------------------------------------------------
wxMaxima version: 21.04.0_MSW
using wxWidgets version: wxWidgets 3.1.4
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\SPB_Data/maxima/
Help dir: C:\wxMaxima-21.04.0\share/doc/wxmaxima
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment]
I believe I have found now where this error originates.
