### ISSUE TITLE
Invalid space 'c2a0' instead of valid space '20' ruins evaluation

### ISSUE THREAD

**Issue by qknight** [wxMaxima-developers/wxmaxima#1538]
# Problem description

For the given document (xxd representation):

    663a c2a0 312b 320a     f:..1+2.
    773a 2031 2b32 0a       w: 1+2.

Problem: for some reason my wxmaxima sometimes introduces spaces which look like spaces but actually can't be processed by maxima:

    f: 1+2

evaluates to (there is a space before the 1, i keept it intentionally):

     1+2

instead of:

    3

The w evaluates properly to 3.

$ xxd f 
00000000: 663a c2a0 312b 320a 773a 2031 2b32 0a    f:..1+2.w: 1+2.

My interpretation is:

    663a c2a0 312b 320a     f:..1+2.
    773a 2031 2b32 0a       w: 1+2.

* space in f is 'c2a0'
* space in w is '20'

# Used versions

* Ubuntu 20 (pretty much default installation)
* wxMaxima 19.07.0

     wxWidgets: 3.0.4
     Unicode support: yes
     Maxima version: 5.43.2 (x86_64-pc-linux-gnu)
     Lisp: GNU Common Lisp (GCL) GCL 2.6.12

# Note

In the wxMaxima editor in a document one can select a valid space, aka '20', and then all the other valid spaces highlight pretty much like the equation highlights. Interestingly yhis is also true for the invalid space, aka 'c2a0', it will then highlight all the invalid spaces. 

Summary: So the wx toolkit already knows the difference between the two. 

I see two potential fixes:

* internal document conversion on evaluation 
* the document in the IDE could automatically convert the space (wish) transparently

# Wish

It would be nice if the IDE could detect these charset issues and report that or even mitigates it automatically. See also: https://stackoverflow.com/questions/34926154/c2a0-and-20-string-comparision

**Comment by gunterkoenigsmann** [comment]
The bug that the non-breakong space that results from pressing shift+space was passed to maxima has been resolved long ago. But I have never found out how to introduce bugfixes into Ubuntu...
