### ISSUE TITLE
wxMaxima integral sign and draw_renderer bugs

### ISSUE THREAD

**Issue by ghost** [wxMaxima-developers/wxmaxima#1543]
Bugs in wxMaxima 21.05.1-DevelopmentSnapshot (Windows 10 64-bit 20H2):

1. The integral sign is displayed incorrectly. Times New Roman is selected as the math font, but I`m sure the problem isn`t with the font. Perhaps there are similar problems with other big math signs, symbols etc. although I didn`t check it up.
2. The default parameter for the "draw_renderer" is "gnuplot_pipes". But with the default setting, fuctions "draw2d", "draw3d" etc. (not the wxdraw functions) don`t work at all (I mean the "gnuplot graph" window is not displayed.). I have to change the value of this parameter every time (or use maxima-init file).

![wxMaxima](https://user-images.githubusercontent.com/84374539/118613661-40e02500-b7bf-11eb-9c99-521dcd2bc854.png)

**Comment by daute** [comment]
(it is better to report unrelated issues as separate tickets).
Concerning the draw problem: It seems to work when running Maxima with CLISP, but not SBCL (CLISP/SBCL are two different implementations of Lisp, the programming language, in which Maxima is mostly written).

There is a small utility included ("Configure default Lisp for Maxima" in the Maxima folder in the start menu) , where you can choose the used Lisp interpreter, if you select CLISP, it works.
Best regards, Wolfgang

**Comment by daute** [comment]
Another comment to the draw issue: If you use my nightly build, you have 3 Lisp's, (ABCL, CLISP, SBCL), it does also work with ABCL.
And it seems to work with SBCL, if you set the variable
`draw_renderer : gnuplot_pipes;`
before issuing a draw command.

**Comment by daute** [comment]
(reopening the bug report because of the draw issue and the current discussion on the Maxima mailing list (although it is probably a Maxima bug...)).

Can you provide the used Maxima version? The output of
`wxbuild_info();`
or `build_info();`

Thanks.
Best regards, Wolfgang

**Comment by daute** [comment]
I released an installer for the currently released Maxima (5.45.0) now, which includes of course the current wxMaxima release and the fix for this draw-issue:
https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.45.0-Windows/

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment]
the integral issue should be resolved now, as well.
