### ISSUE TITLE
Suggestion: allow seeing all files in the file save dialog

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1557]
Currently wxMaxima shows only filenames matching the patterns `*.wxmx` and `*.wxm` in the "Save" or "Save As..." dialogs. However, it would be nice to allow the user to select `*` (all files) and here is the reason why. Some complex problems are solved in more than one CAS system, just to be sure that the result is correct and so the current directory may contain a file with the long filename like `Spin0-Particle-Nonstationary-Wigner-3D.nb` with the solution as a Wolfram Mathematica notebook and I wish to give my wxMaxima notebook a similar name like `Spin0-Particle-Nonstationary-Wigner-3D.wxmx` but I would have to switch to the terminal and list the files to remember the exact name I gave to it. But if the pattern `*` was allowed in wxMaxima I would just select the `.nb` file and then modify the extension in the same dialog from `.nb` to `.wxmx`.

**Comment by daute** [comment]
Thanks for the suggestion.
