### ISSUE TITLE
greek letters produce bold diagonal slash instead of greek symbols

### ISSUE THREAD

**Issue by ejbarth** [wxMaxima-developers/wxmaxima#1563]
typing the name of the greek symbol results in a bold horizontal slash in the output

![image](https://user-images.githubusercontent.com/36115695/124630337-5503e280-de50-11eb-90b6-25043be36ece.png)

-------------------------------------------------------------
wxMaxima version: 21.05.2_MSW
using wxWidgets version: wxWidgets 3.1.4
Maxima version: 5.45.1
Maxima build date: 2021-06-21 17:43:28
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Eric Barth\maxima\
Help dir: C:\maxima-5.45.1\share/doc/wxmaxima
-------------------------------------------------------------

**Comment by richardgobeli** [comment]
The current nightly build works OK for me using windows 10.
![image](https://user-images.githubusercontent.com/31253976/124832796-d2a81b00-df42-11eb-9219-ccca1ceb8c26.png)

**Comment by daute** [comment]
It depends on the font, which you selected (using Edit -> Configure -> Style)
E.g. "Courier" for example seems not to have these greek characters included and in fact produces these slashes. The free 'Libertinus' fonts which are included in wxMaxima, should not have these problems (and many other fonts too). 
Best regards, Wolfgang

**Comment by ejbarth** [comment]
Yes, thank you!  I was using courier and now I see Libertinus fixes the
problem...
except with "lambda"  which returns the word lambda rather than a greek
symbol

Eric

**Comment by daute** [comment]
One guess: There is a Maxima function lambda:
https://maxima.sourceforge.io/docs/manual/de/maxima_25.html#lambda
So if wxMaxima would change
lambda(...) to λ(...), the function would probably not be recognized as function.
But there is a side pane for greek letters, which helps to enter these characters.
Best regards, Wolfgang

**Comment by richardgobeli** [comment]
I find it better to enter these directly as greek letters by typing first escape and then alpha.  A drop down list will be displayed to pick your letter and displays the greek letter on the input line and not the named text of the letter.
![image](https://user-images.githubusercontent.com/31253976/125150455-835e1800-e105-11eb-85d1-63a588c906e4.png)

**Comment by daute** [comment]
Added a note to the manual, that the selected font may be the problem.
Closing this issue.
