### ISSUE TITLE
run_testsuite(display_all=true) results in an error

### ISSUE THREAD

**Issue by barton-willis** [wxMaxima-developers/wxmaxima#1564]
Doing run_testsuite(display_all=true) results in the error

********************** Problem 66 (line 421) ***************
Input:
"<": wrong number of arguments.
 -- an error. To debug this try: debugmode(true);
Evaluation took:

while running rtest_rules.  I'm using maxima_frontend_version="19.05.7"

**Comment by gunterkoenigsmann** [comment]
I believe to have fixed that right now. If I don't have please protest!
