### ISSUE TITLE
WxMaxima + CYGWIN

### ISSUE THREAD

**Issue by manugoswami** [wxMaxima-developers/wxmaxima#1565]
Hi Developers,

WxMaxima is failing to build in CYGWIN.

Errors below after cmake -- build .

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

In file included from /cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/ww898/utf_selector.hpp:30,
                 from /cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:54:
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/ww898/cp_utfw.hpp:46:2: error: #error Unsupported platform
   46 | #error Unsupported platform
      |  ^~~~~
In file included from /cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:54:
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/ww898/utf_selector.hpp:44:68: error: ‘utfw’ does not name a type; did you mean ‘utf8’?
   44 | template<> struct utf_selector<wchar_t      > final { using type = utfw ; };
      |                                                                    ^~~~
      |                                                                    utf8
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/ww898/utf_selector.hpp: In substitution of ‘template<class Ch> using utf_selector_t = typename ww898::utf::utf_selector<Ch>::type [with Ch = wchar_t]’:
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:59:58:   required from here
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/ww898/utf_selector.hpp:52:7: error: no type named ‘type’ in ‘struct ww898::utf::detail::utf_selector<wchar_t>’
   52 | using utf_selector_t = typename utf_selector<Ch>::type;
      |       ^~~~~~~~~~~~~~
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp: In member function ‘UTF8Decoder::DecodeResult UTF8Decoder::State::Decode(wxInputStream&, size_t, size_t)’:
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:91:18: error: ‘utfwx’ has not been declared
   91 |     (maxWrite >= utfwx::max_supported_symbol_size) ?
      |                  ^~~~~
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:92:17: error: ‘utfwx’ has not been declared
   92 |     maxWrite - (utfwx::max_supported_symbol_size - 1): 0;
      |                 ^~~~~
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:118:25: error: ‘utfwx’ has not been declared
  118 |       auto const size = utfwx::char_size([=]{ return cp; });
      |                         ^~~~~
/cygdrive/D/ons_cb_try/ons_wxmaxima/wxmaxima/src/StreamUtils.cpp:124:5: error: ‘utfwx’ has not been declared
  124 |     utfwx::write(cp, [&](auto ch){ *outPtr++ = ch; });
      |     ^~~~~
make[2]: *** [src/CMakeFiles/wxmaxima.dir/build.make:538: src/CMakeFiles/wxmaxima.dir/StreamUtils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2341: src/CMakeFiles/wxmaxima.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

Kindly support to resolve most urgently.

Warm Regards,
Manu

**Comment by gunterkoenigsmann** [comment]
Only @KubaO knows what that part of the code does.

As a side remark on the wx-dev mailing list vadim has asked if anyone is against removing support for cygwin entirely. Until now no-one opted against it => if you want to use wxwidgets applications under cygwin in the future I advise you to complain there

**Comment by manugoswami** [comment]
Hi ,

Does that mean wx-maxima **_should not be compiled_** with CYGWIN ?

May be there should be way of compiling wx-maxima with X11 as there is issue with STREAM --> Unsupported Platform?

Kindly advise urgently.

Warm Regards,
Manu

**Comment by gunterkoenigsmann** [comment]
As far as I am concerned xMaxima should work on every platform that is supported by wxWidgets. But wxWidgets wants to drop cygwin support and wxMaxima makes heavy use of wxWidgets.

**Comment by gunterkoenigsmann** [comment]
`utfw` might be a `wchar` containing utf8 data....

**Comment by daute** [comment]
Even if wxWidgets is going to drop Cygwin-support one can use an older version in the near future.

Maybe wxWidgets native functions can be used instead of the library we are using (https://github.com/ww898/utf-cpp/)  for Unicode conversion - which seems not to support Cygwin.

**Comment by daute** [comment]
I committed two changes (9a07548fd2b14efac4ef750a5d12ec75cf751074 and 93ead5db7cc258a76732801af4207e8097014532) now, which allowed me to compile and run wxMaxima using Cygwin.
(Consider that as **VERY experimental,** I am not 100% sure, if these commits are correct).

**Comment by daute** [comment]
With commit d44562ac2496e990de4112645afefd978fce86de wxMaxima compiles on the CI system for Cygwin on Github.
Closing this issue.
