### ISSUE TITLE
Alt up arrow gives an error instead of previous command

### ISSUE THREAD

**Issue by ejbarth** [wxMaxima-developers/wxmaxima#1566]
![altupwxmaximabug](https://user-images.githubusercontent.com/36115695/125473527-fbb5c1c9-250e-440d-ac07-4ae3d18eb8fd.png)

wxMaxima version: 21.05.2_MSW
using wxWidgets version: wxWidgets 3.1.4
Maxima version: 5.45.1
Maxima build date: 2021-06-21 17:43:28
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Eric Barth\maxima\
Help dir: C:\maxima-5.45.1\share/doc/wxmaxima

**Comment by daute** [comment]
Strange thing. You are right, but it seems to work, if the 'History' sidebar is visible. At least a 'workaround' - but clearly a bug, where I don't see the solution now. May Gunter knows why?

Best regards, Wolfgang
