### ISSUE TITLE
Github actions: The cached wxWidgets compilation result isn't corrrectly restored in new branches

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1572]
No idea why, still.

**Comment by daute** [comment]
With commit 6fe8b325 662da2b89 and 1424fc64 we do no longer compile wxWidgets, but use the precompiled package (`brew install wxwidgets`).
No need to cache the wxWidgets compilation result, since we do not compile it.
Closing this issue.
