### ISSUE TITLE
Crash  message when demo tensor is repeated.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1574]
I get the message when typing e at the end of demo example E.
It does not happen all of the time.  It may depend on the demo that was run before.
Viktor added demo example 19 in the last update.  I don't know if this is cause this issue.
![image](https://user-images.githubusercontent.com/31253976/130369301-b513c714-623e-4b2e-8f04-fe010c988688.png)
![image](https://user-images.githubusercontent.com/31253976/130369496-18ceae92-5dc6-4736-a47f-59917a0da66e.png)

**Comment by richardgobeli** [comment]
It looks like Viktor forgot the comment at the end of his new demo.

/* End of demo -- comment line needed by MAXIMA to resume demo menu */
I posted bug in Maxima.

**Comment by gunterkoenigsmann** [comment]
If you click on "details":  does the program tell you in which function the error is? If not: which message in the "debug messages" sidebar appears if you tell the program not to crash here?

Format specifiers are mainly used for debug messages.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/130391546-ea6270b9-7895-4cdd-9eac-9e98c7c629f0.png)
![image](https://user-images.githubusercontent.com/31253976/130392101-a0cdee40-d369-4efb-b055-bcfeedc33c2c.png)

**Comment by richardgobeli** [comment]
For me it happens most of the time when complete examples E is pressed and then go thru the whole selected example E.
When it comes back and rewrites the home menu screen, it faults at typing the next key for a new demo.

**Comment by richardgobeli** [comment]
I was doing the demo(tensor);  then E then E;  I complete the Laplace example then it crashes at next character selection.

**Comment by richardgobeli** [comment]
I have looked at this again. I think there is something happening when either the hodge or the levi civita function is called.  After those calls, any time you need to enter a letter or letters at the demo prompt the demo crashes.   It also causes the whole program to stop.   This not only happens with the new Laplacian demo, but also with the hodge star demo.  I test with the Maxima command line and it does not crash.  It only crashes using the WxMaxima version.
I used this version today.
![image](https://user-images.githubusercontent.com/31253976/143326431-8fd49075-af56-4e3e-afb2-d47331798619.png)

**Comment by richardgobeli** [comment]
I think.  I traced this to any demo that uses the levi-civita function causes the next letter or number typed in the selection for next demo. example is demo 4.  When almost to the end of the demo, if a number is typed at the prompt the demo is not ended, but the whole program crashes.
The prompt after %i26, a number will no longer abort the demo, but crash the program.
![image](https://user-images.githubusercontent.com/31253976/145726686-9a17ec96-66b4-42e2-b5c6-f1566ffa1c81.png)

It does not seem to happen when in only Maxima.

**Comment by richardgobeli** [comment]
[crash dump.txt](https://github.com/wxMaxima-developers/wxmaxima/files/7758108/crash.dump.txt)
This is the gdb debugger output from the where command.
This is the version running.
![image](https://user-images.githubusercontent.com/31253976/146996021-4a0018af-c571-4937-a28c-8baddf559199.png)

**Comment by richardgobeli** [comment]
Was the last commit for this bug report.   I think the crash is still here.
I will make a new dump with last nights build.

**Comment by richardgobeli** [comment]
New crash dump.
[crash dump.txt](https://github.com/wxMaxima-developers/wxmaxima/files/7774957/crash.dump.txt)
Did your change get loaded in the last night build?

![image](https://user-images.githubusercontent.com/31253976/147367962-82930dab-ad17-4092-8c8b-0b31e77ad556.png)

**Comment by richardgobeli** [comment]
Gunter,

Can you check this again?   There seems to be a issue with some variable that has the wrong type.
I did a debug dump.

**Comment by richardgobeli** [comment]
version used.
![image](https://user-images.githubusercontent.com/31253976/185577334-bf170c06-7039-4fed-a65a-a4bb20b5cd42.png)
Here is a new gdb report.  It seems to crash when it is drawing the next cell after the red text and the number 3 is typed in the second time the demo is run on the 3. as below:
![image](https://user-images.githubusercontent.com/31253976/185570672-94e42caa-3941-4803-a931-fd311fa1ebc0.png)
It looks like it crashes doing the draw for the first line at stack level #15 just before the (%i1) is typed.
![image](https://user-images.githubusercontent.com/31253976/185571432-d836ecdf-5ac9-4c06-94a1-ea9ac89b8a44.png)
![image](https://user-images.githubusercontent.com/31253976/185572488-92c90b79-e6d3-47ab-a3cd-75a1023d904a.png)
This time it crashed as soon as the 3 is typed. I did not need to type the ; enter here to cause the crash as above.
this back trace is different. Draw is level #11.
![image](https://user-images.githubusercontent.com/31253976/185573425-f673b712-8e9b-40fd-9030-392c91c9fb48.png)
back trace with local variables
![image](https://user-images.githubusercontent.com/31253976/185574912-42ac67c5-6bd2-4a89-8a7b-7fedf5d8482b.png)![image](https://user-images.githubusercontent.com/31253976/185575033-d6981127-6001-41ad-82f7-52480fd61ab2.png)

**Comment by richardgobeli** [comment]
This is still crashing and it now does not like the raw maxima monitor.  It gets many new asserts and the one in demo(tensor) still happens.

**Comment by richardgobeli** [comment]
I see it works now with the version from august 29, 2022.   Thanks.
