### ISSUE TITLE
Honor ./configure option --sysconfdir is not honored

### ISSUE THREAD

**Issue by andrejv** [wxMaxima-developers/wxmaxima#159]
Converted from [SourceForge issue 2888772](http://sourceforge.net/support/tracker.php?aid=2888772), submitted by peti

I built wxMaxima using the configure flag "--prefix=/foo". Now, I would expect the resulting binary to read its global configuration file from /foo/etc/wxMaxima.conf, but it doesn't -- it looks at /etc/wxMaxima.conf. Apparently the path from configure is ignored? 

Is there a way to make mxMaxima use a different path for the system-wide configuration file?

**Comment by KubaO** [comment]
wxMaxima is not using a global configuration file. Closing.
