### ISSUE TITLE
Can't correctly factorize a polinomial whose coefficients have decimals, how can maxima do it?

### ISSUE THREAD

**Issue by VALERYRAMIREZ** [wxMaxima-developers/wxmaxima#1627]
Hi all, how are you?.

I'm trying to create a function that calculates the z-transform of a transfer function using the residues method but for that I need the factors of the characteristic equation and the powers of the factors, so, in order to do that I tried to factorize polinomials with non-integer coefficients but after tried everything that I read I couldn't factorize make maxima to factorize those polinomials the way I need it.

For giving an example, I have this characteristic equation: "s·(s^2+0.1·s)", the factors should be "s^2" and "s + 0.1" but maxima allways gives me "(s^2·(10·s + 1))/10".

Why I'm signalling this?, well, as I learned that maxima treates the outputs equation as list so I can have its dimension and separate the factos by its positions in the list to measure the powers of the factors and do what I need, but like maxima gives me the result that is shown above then the dimension of the list is different and it will make my function to work differently and possibly have errors.

The result that is shown is given by maxima no matter if I use factor, gfactor, or expand or whatever other function that I found and I know that result is because maxima is rationalizing the polinomial before working with it but I don't need that behavior, I only need the pure factors, so, how can I have the result that I want?.

Thanks in advance for the help.

**Comment by gunterkoenigsmann** [comment]
Use exact numbers (1/10) instead of floating-point numbers (0.1).

The problem is that 0.1 cannot be expressed in floating-point numbers without introducing an error that tends to add up (sometimes rapidly) on subsequent operations on that number. See

~~~~
rationalize(0.1);
~~~~
and https://en.wikipedia.org/wiki/Wilkinson%27s_polynomial for details.

If you run your equation through rat() before trying to work on it maxima will try to guess which exact numbers you perhaps meant...

**Comment by gunterkoenigsmann** [comment]
As a sidenode the actual mathematics is done by maxima (https://maxima.sourceforge.net). This project is wxMaxima, which more or less is only a text editor with (hopefully) nice graphical output that uses maxima for doing the mathematics => for complicated problems about maxima itself you'll get better help at https://maxima.sourceforge.net.

**Comment by VALERYRAMIREZ** [comment]
Thanks @gunterkoenigsmann, thanks to the advices that you gave me I've been able to modify my function to work with the rationalized result and at least for now is working
