### ISSUE TITLE
maxima ode2

### ISSUE THREAD

**Issue by chanhojeong1** [wxMaxima-developers/wxmaxima#1645]
![11](https://user-images.githubusercontent.com/101963629/161366801-57e15d03-0e49-461f-b131-c9ab4d2cd171.jpg)
Why is false coming out of the ode2 function here?
![11](https://user-images.githubusercontent.com/101963629/161366801-57e15d03-0e49-461f-b131-c9ab4d2cd171.jpg)

**Comment by daute** [comment]
(As you wrote, it is a *[Maxima](https://maxima.sourceforge.io/)* issue, it has nothing to do with wxMaxima, the graphical frontend).

If `ode2()` cannot obtain a solution for whatever reason, it returns false. (quoted from the Maxima manual).

There is a `contrib_ode` package in Maxima, which extends `ode2()` with additional methods:
https://maxima.sourceforge.io/docs/manual/maxima_singlepage.html#Item_003a-contrib_005fode_002fnode_002fIntroduction-to-contrib_005fode

```
load("contrib_ode");
contrib_ode('diff(y,x)=x^2-y^2,y,x);
```

does get a (rather complex) solution.

Best regards, Wolfgang
