### ISSUE TITLE
Mac WXMaxima version 22.03 - not able to paste into doc

### ISSUE THREAD

**Issue by sbergman123** [wxMaxima-developers/wxmaxima#1648]
Mac WXMaxima version 22.03 - not able to paste into doc from any source other than the open maxima document.  Reverting back to version 19.05.7, the copy&paste works as expected. 
More observations:  
- Copying/pasting via all the available means (menu bar etc) makes no difference.
- The EDIT menu title in wxmaxima 22-03 flashes but the paste doesn't happen.
- I noticed a few prior bugs revolving around this issue back around 2017... Could it have resurfaced?  
- I'm a +1 on the math font error as well [separate issue though]:  
- The *Libertin* and jsMath*   fonts.  Log entry as follows:
- "Font file "/usr/local/Cellar/wxmaxima/22.03.0/share/wxMaxima/fonts/jsMath-cmti10.ttf [NOTE: A listing of 28 *Libertin* and jsMath* fonts.]" cannot be used as it is not inside the font directory "/usr/local/Cellar/wxmaxima/22.03.0/wxMaxima.app/Contents/Macos/Fonts"."
- shuffling and replicating fonts around had no effect.  However I did read that the new version addresses this by adding a compiler option to include a Fonts path...  Thanks guys/gals.  Great work and a fine product.

**Comment by sbergman123** [comment]
[log.txt](https://github.com/wxMaxima-developers/wxmaxima/files/8446303/log.txt)

**Comment by sbergman123** [comment]
logfile of font startup issue in wxmaxima v22-03

**Comment by gunterkoenigsmann** [comment]
Should be resolved with commit 2b41864d8b53138428c49332e45caf0f279e6dff
