### ISSUE TITLE
wxMaxima-22.03.0-win64.exe : matching parentheses or brackets is wrong.

### ISSUE THREAD

**Issue by florinaalex** [wxMaxima-developers/wxmaxima#1649]
When highlighting the matching parentheses or brackets is wrong.

**Comment by florinaalex** [comment]
Hello Gunter,

Please find the attachment showing the issue. With 21.11.0 I haven't had
this problem.

--
Kind regards,
Alexander Erdei

**Comment by gunterkoenigsmann** [comment]
Seems like the attachment didn't arrive. If you make it's filename end in .zip or . txt GitHub might seem it to be harmless and forward it to this ticket system.

**Comment by florinaalex** [comment]
Please find the zip file, presenting the matter.

**Comment by gunterkoenigsmann** [comment]
Seems like the zip file has been filtered out  too. Perhaps we"ll have to resolve to the good old mail. My address is wxMaxima and the server is peterpall.de

**Comment by florinaalex** [comment]
try this one:

https://www.dropbox.com/s/6y4fnmqqmyw8tui/maxima.issue.1649.zip?dl=0

don't need to subscribe to dropbox.

Please let me know if this has worked.

**Comment by gunterkoenigsmann** [comment]
If you wouldn't have told me that I don't have to register a dropbox account I would now have ended up owning one: They asked me 6(!) times in a row to create one without making it clear that this step is optional.

The bad news is: both
````
list_original_obj : []$
appended_list_obj : [1, 2, 3, 4]$
````
and
````
append(list_original_obj, appended_list_obj);
````
work fine on my linux box and I don't own a windows computer so I have no idea how to find out where the problem lies...

**Comment by gunterkoenigsmann** [comment]
Found it:

````
list_original_obj : []$
appended_list_obj : [1, 2, 3, 4]$

append(list_original_obj, appended_list_obj);
````
shows the problem you are seeing => Will try to find out what causes it.
