### ISSUE TITLE
Opaque selection

### ISSUE THREAD

**Issue by Ethereal-Fox** [wxMaxima-developers/wxmaxima#1655]
The selection background overlaps the text.

![Screenshot](https://user-images.githubusercontent.com/103583938/163577852-9e9f7c1f-0297-4d5a-9aa3-b36ed3506ee1.png)

**Comment by Parlazo** [comment]
ahh ... its not just me ... yes i also have this issue

**Comment by gunterkoenigsmann** [comment]
I am still wondering how that might happen: Redrawing a section of the screen works in the following way:

- First a bitmap of the size of the visible window is allocated in memory
- Then the selection background is drawn
- Then the text and all other objects are drawn

=> In theory what you see cannot possibly happen. In reality something seems to deviate from this theory.

Are all objects affected by this phenomenon, or only text?
