### ISSUE TITLE
In MacOs version main toolbar icons are too big and thus clipped

### ISSUE THREAD

**Issue by mlomonaco** [wxMaxima-developers/wxmaxima#1657]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/66616304/164125700-70d04f6f-3ebf-48af-9d96-57479aeae5dc.png">
In version 22.04.00 the situation is as depicted

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...what version of MacOs do you use and do you have a retina screen/a big external screen/a nonstandard resolution scale setting/...?

I guess the

````
    int targetSize = wxMax(m_ppi.x,75) * TOOLBAR_ICON_SCALE * GetContentScaleFactor();
````
in `Toolbar.cpp` possibly should have read:
````
    int targetSize = wxMax(m_ppi.x,75) * TOOLBAR_ICON_SCALE;
````
which saves me from an `#ifdef`.

**Comment by mlomonaco** [comment]
BigSur, the standard MBP 15'' resolution
