### ISSUE TITLE
WxMaxima crash!

### ISSUE THREAD

**Issue by Ethereal-Fox** [wxMaxima-developers/wxmaxima#1658]
**Plot** → **Plot2d** → **Special**

![1](https://user-images.githubusercontent.com/103583938/164222202-38fb2875-579f-42e1-9c8d-8af788af31d7.png)

→ **Parametric plot** (and then I get a crash notification)

![2](https://user-images.githubusercontent.com/103583938/164222343-58ed030d-4917-48a1-9e46-03716c2e4ab7.png)

![3](https://user-images.githubusercontent.com/103583938/164222356-8b02865d-b156-4b68-a9bd-6ba0d5505fb5.png)

**Comment by daute** [comment]
Thanks for the bug report. Should be fixed now (commit [936a3b6]).

It's not nice, there you are right, but not a catastrophic crash - you can click on 'Continue' and wxMaxima continues to work.
Best regards, Wolfgang
