### ISSUE TITLE
Debugging check in this Application has failed

### ISSUE THREAD

**Issue by Ellilech** [wxMaxima-developers/wxmaxima#1662]
I installed Maxima and wxmaxima with homebrew and every time I open the settings in wxmaxima I get this [error](https://drive.google.com/drive/folders/1oR_g2KConGQmz_nyh3ZKWCvaKuhsLL0a?usp=sharing). When I click continue, the error shows up again. When I click stop the whole program closes. When I click the error away everything works fine but I cant resize the settings window and got two scrollbars in the settings window. When I close the settings and reopen them, the error doesn't show up again but I still cant resize the window.

**Comment by gunterkoenigsmann** [comment]
Wow... ...a wxStaticBoxSizer (that draws a box around a set of settings that I want to group) contains a panel that is placed on the panel that contains the setting dialogue page.

If wxWidgets tells me that the wxStaticBoxSizer's panel isn't a child of the panel it is drawn on that seems to indicate an error within wxWidgets. On Linux the whole thing seems to work if I place all elements on the config dialogue page's panel instead on the wxStaticBoxSizer's even if the manual tells me not to do that. But it is the only idea I have on working around this issue...

**Comment by Ellilech** [comment]
Wie kann ich das Problem am Besten lösen? @gunterkoenigsmann

**Comment by gunterkoenigsmann** [comment]
Kann man homebrew irgendwie sagen, dass man einem nightly Build installieren will? Unter Linux kann man auch alternativ der assert-Meldung sagen, dass man sie nicht ca. 100-mal in Folge wegclicken will. Aber weiß nicht, ob das auch auf dem Mac gilt...

**Comment by gunterkoenigsmann** [comment]
Unter Linux und Windows gibt es in dem Dialog auch eine Checkbox, dass man ihn nicht mehr sehen will. Weiß nicht, wie das auf dem Mac ist.

**Comment by Ellilech** [comment]
Ich kenne mich leider nicht so gut aus mit diesen Dingen. Es gibt eine checkbox, dass man die Meldung nicht erneut sieht, aber wenn das Programm erneut geöffnet wird erscheint die Meldung wieder. Die Dateien von Maxima und wxmaxima sind seit der neusten Installation über Macport und Homebrew sowieso total durcheinander und vieles ist im falschen Ordner und mehrere Dateien sind doppelt enthalten...
