### ISSUE TITLE
Feature Request: A tool for easier input of fractions

### ISSUE THREAD

**Issue by FEA-eng** [wxMaxima-developers/wxmaxima#1664]
I think that it would be great to have a tool in wxMaxima that allows users to enter fractions without having to use additional parentheses which can make it hard to properly input complicated expressions without making a mistake. There are already tools for easier creation of equation systems and integrals, for example. Maybe something similar could be added for fractions. It could look like this, for instance:

![fraction tool](https://user-images.githubusercontent.com/59876896/167464849-d5fb8669-2ea1-416d-ad2a-b81e038af30f.jpg)

**Comment by gunterkoenigsmann** [comment]
I never use the menus and wizard dialogues => where do you want this tool to appear? And how should I name the corresponding menu entry?

**Comment by FEA-eng** [comment]
Thank you for the reply. In this case, the usefulness comes from the fact that fewer parentheses are needed and thus long expressions become easier to define. Such a tool is also available in other CAS programs. Maybe it could be added to the Algebra menu due to the lack of more fitting menus. I would name it simply "Create Fraction".

Would it be possible to make this tool create fractions without opening a new input cell as other wizards do ? That way one could define multiple subsequent fractions in a single expression. If it's not doable, no problem.

**Comment by gunterkoenigsmann** [comment]
Tomorrow's Nightly Build will contain that feature.

Did redesign the wizards and their handling, first, in order to make it more useful. Hope it matches your workflow.

**Comment by FEA-eng** [comment]
Great, thank you so much for implementing this.
