### ISSUE TITLE
Opening embedded plots in interactive gnuplot windows

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1680]
When duing a plot e.g.;
wxdraw2d( explicit(  sin(x), x, 0, 10 ));

And right-click to choose to open the plot in an interactive gnuplot window. The gnuplot command windows dosen't show up - only a black window:
![image](https://user-images.githubusercontent.com/2638713/170057981-f46a9739-e99f-40f5-9dab-82003d889f22.png)

However gnuplot itself seems to work if I start
C:\maxima-current\gnuplot\bin\wgnuplot.exe

![image](https://user-images.githubusercontent.com/2638713/170058496-65b8661f-8156-4abd-acf3-e7cbcbc4bf29.png)

Unfortunately it has been some while since I installed a snapshot, so I can only tell that this has occured after the 2022/01/20 snapshot which did work.

Also, if I instead use draw2d( explicit(  sin(x), x, 0, 10 )); - the option to open the gnuplot command window has disappeared - but this might be a pure gnuplot issue. 

Any clue ?

build_info()
version="branch_5_46_base_47_ge71bf5bee_dirty",timestamp="2022-05-23 00:02:45",host=
"x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.2.4",maxima_userdir="C:/Users/xxxx/maxima",
maxima_tempdir="C:/Users/xx/AppData/Local/Temp",maxima_objdir=
"C:/Users/xxx/maxima/binary/branch_5_46_base_47_ge71bf5bee_dirty/sbcl/2_2_4",maxima_frontend="wxMaxima",
maxima_frontend_version="22.04.0-DevelopmentSnapshot_MSW"

**Comment by gunterkoenigsmann** [comment]
I have no idea on how to prevent that black window from opening which is a Gnuplot console.
Might it be that Gnuplot opens the plot window behind that one or (that happens on Windows) outside of the screen?

**Comment by gustavklopp** [comment]
This is a Windows problem apparently. No black window with Linux.

**Comment by gunterkoenigsmann** [comment]
There is a maxima variable for that:
````
gnuplot_command: wgnuplot
````
The annoying side-effect of that would be that each animation frame afterwards steals the mouse and keyboard focus during its creation.

**Comment by ReneSci** [comment]
Sorry - forgot to tell: Even when using that variable setting, the same thing happens

**Comment by gunterkoenigsmann** [comment]
That looks like Gnuplot has somehow changed. The question now is: If I run Gnuplot and feed it the plot file - how do I tell it to open a comand window, as well as the plot?

**Comment by daute** [comment]
I think, I fixed that issue with the two commits.
