### ISSUE TITLE
Where does the description text go?

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1685]
For the menu solve wizard.  All I see when the wizard box opens is just the title text.
Example below solve.  I just see the Solve equation(s) box.  The second parameter text I never see from the commandWiz statement.
Am I missing something?

![image](https://user-images.githubusercontent.com/31253976/171506221-97013cf5-cb86-44c8-9a60-6873f861bc64.png)

case menu_solve:
      CommandWiz(
        _("Solve equation(s)"),
        _("solve() will solve a list of equations only if for n "
          "independent equations there are n variables to solve to.\n"
          "If only one result variable is of interest the other result "
          "variables solve needs to do its work can be used to tell "
          "solve() which variables to eliminate in the solution "
          "for the interesting variable."),wxEmptyString,
        wxT("solve([#1#],[#2#]);"),
        _("Equation(s)"),expr,_("Comma-separated equations"),
        _("Variable(s)"),wxT("x"),_("Comma-separated variables"));
      break;

**Comment by richardgobeli** [comment]
Set some labels.

**Comment by gunterkoenigsmann** [comment]
I am still not completely sure how to handle the dscription text: 

- We have a WrappingStaticText element at hand that looks like it were made for this purpose. But I somehow couldn't get it to work in a wizard. Additionally once one has read the description  it only occupies screen space which isn't good for a dockable window.
- A wxTextCtrl is originally made for inputting text and therefore doesn't look like a description.
- The wxHelpButton looks cool on MS Windows - and ugly on Linux
- And adding the description as a MouseOverToolTip had excactly the effect I feared: Even if you know that there must be a description it isn't easy to find.

=> We'll have to search for another solution...

**Comment by richardgobeli** [comment]
Maybe make it a configuration option to display it when enabled, or it becomes a MouseOver on the title bar if disabled.
