### ISSUE TITLE
MacOS: wxMaxima 22.05.0 crashes after opening Preferences menu

### ISSUE THREAD

**Issue by david-amo** [wxMaxima-developers/wxmaxima#1686]
wxMaxima ver. 22.05.0 crashes (without showing any error) after opening the preferences (wxMaxima->Preferences) menu. The program was compiled from the source code of release version 22.05.0 following the instructions provided on the Compiling.md file. This issue seems similar to #1558 which was reported for ver. 21.02.0 and fixed in subsequent releases.

MacOS version is 12.4 (x86_64 architecture) and wxWidgets version is 3.1.6 (installed using the homebrew package manager). This is the full macOS crash report:

[crash_report_wxmaxima.txt](https://github.com/wxMaxima-developers/wxmaxima/files/8857105/crash_report_wxmaxima.txt)

Thank you in advance.

**Comment by gunterkoenigsmann** [comment]
Just to be sure: Does it crash or does it show about a hundred  dialogues that ask if to crash the program in order to end up in an eventual debugger? (I suspect that dialogue to be worded in a way that is hard to understand)?

**Comment by david-amo** [comment]
> Just to be sure: Does it crash or does it show about a hundred dialogues that ask if to crash the program in order to end up in an eventual debugger? (I suspect that dialogue to be worded in a way that is hard to understand)?

It just crashes, without showing any dialogue.
