### ISSUE TITLE
Build error under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [wxMaxima-developers/wxmaxima#1698]
Arch ships wxwidgets in version 3.2.0 now. wit hat version the build of wxmaxima (git checkout) fails.

[buildlog.txt](https://github.com/wxMaxima-developers/wxmaxima/files/9124101/buildlog.txt)

**Comment by justinkb** [comment]
this is caused by arch wxwidgets-gtk3 package being set up with wxUSE_PRIVATE_FONTS defined to 0

```
/usr/lib/wx/include/gtk3-unicode-3.2/wx/setup.h
474:#define wxUSE_PRIVATE_FONTS 0
```

**Comment by carlosal1015** [comment]
See also https://bugs.archlinux.org/task/75343

**Comment by daute** [comment]
Maybe we should stop using - and bundling - (private) fonts with wxMaxima? And just add a note to the website, that fonts without proper math symbols might cause problems?
And maybe that packagers (e.g. for Linux packages) should add dependencies and how Windows (and Mac) users can install them?

They seem to cause many problems...

Best regards, Wolfgang

**Comment by wenzezlaus** [comment]
As a temporary workaround add cmake option "-DWXM_INCLUDE_FONTS=OFF" in build() section in PKGBUILD

**Comment by wenzezlaus** [comment]
As a temporary workaround use cmake option "-DWXM_INCLUDE_FONTS=OFF"

**Comment by gunterkoenigsmann** [comment]
I am not completely sure if any packager will find a font that is good enough to solve more problems than it causes when it is packaged with wxMaxima. In the meantime I have at least resolved this build error. At least hopefully.

**Comment by wenzezlaus** [comment]
Can't build wxmaxima with commit 05251f6:  got 
error: ‘AddPrivateFont’ is not a member of ‘wxFont’
while compiling main.cpp

**Comment by wenzezlaus** [comment]
Can't build wxmaxima with commit 05251f6 :

error: ‘AddPrivateFont’ is not a member of ‘wxFont’

while compiling main.cpp

**Comment by stefanhusmann** [comment]
Same here, but the workaround ("-DWXM_INCLUDE_FONTS=OFF") works for me.

**Comment by carlosal1015** [comment]
I apply [the patch](https://aur.archlinux.org/cgit/aur.git/commit/?h=wxmaxima&id=82b0e759cc7274a1956a3506fdd8431f8bfd02ae) (A possible workaround) before and after [patch](https://github.com/archlinux/svntogit-packages/commit/193985d71161da4c3bea5e31456d7520c78105b6). Thanks all for help. No need add `-DWXM_INCLUDE_FONTS=OFF`

**Comment by stefanhusmann** [comment]
Yes, this seems to be a downstream error, which has been fixed.

**Comment by justinkb** [comment]
one of the cmake modules also generates a header file that unconditionally refers to AddPrivateFont

**Comment by daute** [comment]
commit 9d298d0 should fix the issue. Build wxMaxima with 
`cmake -DWXM_INCLUDE_FONTS=NO /path/to/wxmaxima-sourcecode`
when the private fonts should be ignored (and the function `AddPrivateFont()` is not available).

**Comment by justinkb** [comment]
Given that this patch also doesn't touch the data/fonts/CMakeLists.txt I doubt this is a proper fix tbh
