### ISSUE TITLE
Maxima manual is full of TeX markup when it is displayed in a browser. 

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1702]
Was the manual displayed differently before it was moved to a browser window?
Is this only in wxMaxima?  How does Maxima display the manual? 

The distribution package is full of math functions in markup codes.

**Comment by gunterkoenigsmann** [comment]
In theory it should come with a JavaScript script that converts TeX to beautiful 2D maths...

**Comment by richardgobeli** [comment]
I see when I run Maxima it converts it correctly into the formated text,
but if I try ? pdf_chi2;   to display it in wxMaxima I get the following error:
![image](https://user-images.githubusercontent.com/31253976/182040633-e69f6595-8b9c-4b30-8b3b-447617bd608c.png)

**Comment by gunterkoenigsmann** [comment]
Normally the manual's html files should automatically download the script.

Is the manual full of TeX markup if it is opened in a regular HTML browser like Chrome, Edge or Firefox - or only in wxMaxima's help viewer?

**Comment by gunterkoenigsmann** [comment]
And we have changed many things in the last days: Is tomorrow's nightly build better or worse?

**Comment by richardgobeli** [comment]
The build has not worked for 6 days. I have build from 7/16/2022.
I don't think it loads the script, if there is not a load command in the beginning of the html file to indicate that it contains TeX.

The help Maxima manual loads a single page copy of manual.  It does not convert the text. 
The ? help fails in wxMaxima with the version I have below.

![image](https://user-images.githubusercontent.com/31253976/182045742-4d66ece3-ad43-44ea-b752-6161fd00dafc.png)

**Comment by gunterkoenigsmann** [comment]
...and the single page manual doesn't contain a <script> Tag that loads MathJaX?

**Comment by gunterkoenigsmann** [comment]
Ok... ...the nightly build works again.

**Comment by gunterkoenigsmann** [comment]
In the help menu and in the config dialogue there now are radio buttons that tel  where something like
~~~~
? elliptic_f;
~~~~
should open the manual. I've unpacked the windows installer using 7zip on linux. In theory it should load the MathJaX stuff that scans the document for TeX and replaces it with 2D maths now, along with a polyfill that defines all the Javascript commands you might need and that your browser happens to not implement.

**Comment by richardgobeli** [comment]
When I select browser the text gets converted, but the main manual always goes to the sidebar and is not converted.
The  ? elliptic_f;  will go to an external browser and get converted.  If I take the URL of the single-page manual and then put it in that browser it also gets converted.
So why can't your code do the same to the whole manual in an external browser?

**Comment by gunterkoenigsmann** [comment]
I can set the default to "open all manual files in an external browser" and the "use the single-page manual". 

But you mean that the single-page manual is displayed correctly with 2D maths in it by the integrated browser and the one-file-per-chapter aren't? In that case the we'll need to find the difference between them that makes the difference.

**Comment by richardgobeli** [comment]
WxMaxim always sends the single-page manual to the sidebar and never gets converted.
If the sidebar is selected the code  ? elliptic_f; does not get converted in the sidebar.
Nothing gets converted in the sidebar and the single-page manual always goes to the sidebar.

When a browser is selected the code ? elliptic_f; opens an external browser and it gets converted. Good.

Because the whole Maxima manual always goes to the sidebar I need to do the following:
The only time the single-page manual gets converted is when I manually get the URL of the single-page manual and I insert it in an external browser.  This is the only way I can get the whole manual to convert.
It looks like the code is in the single-page manual file to load the MathJaX script.
So the manual just needs to go to an external browser before.

**Comment by richardgobeli** [comment]
It is still not working in the sidebar.
The converting does work in the console mode and in the browser mode for the ? function.
The manual and the ? function do not work in the sidebar and the manual always goes to the sidebar.
Can you send the manual to the browser when browser is selected, because I can't search it the sidebar?
![image](https://user-images.githubusercontent.com/31253976/183302146-9132b8bd-405a-4af4-8bb6-335956365293.png)

**Comment by richardgobeli** [comment]
I see you added a config select for where the manual goes. I picked auto and it goes to external.

**Comment by richardgobeli** [comment]
@gunterkoenigsmann 
I just noticed the function above F(x,m,s) is the sum of a fraction and of 1/2   But the text version shows the fraction as one with the denominator being made of 2  space 2 and the sum character is at the end.   It looks like the 1 and 2 of the fraction 1/2 was not moved far enough to the right to be over the dash symbol.   I don't know if that is a wxMaxima issue or that came for Maxima that way.

**Comment by gunterkoenigsmann** [comment]
I don't know if there is a good solution for the latter issue: Maxima currently doesn't inform wxMaxima that the text it sends now needs to be displayed in a font in which all characters are of an equal width so wxMaxima doesn't display it that way.

**Comment by gunterkoenigsmann** [comment]
Now I had one idea and have comitted it as 13bccc7cb..3d09657e4
