### ISSUE TITLE
Wrong printing of a single latin letter with a single underscore

### ISSUE THREAD

**Issue by lvch** [wxMaxima-developers/wxmaxima#1706]
Check out picture below
![prtsc 2022-08-14 22-34-21](https://user-images.githubusercontent.com/6746594/184552340-4cf2ae39-57a6-4335-8ed5-84b569bc694f.png)
:

**Comment by gunterkoenigsmann** [comment]
I believe I know what causes that: `a_b` is an a with a b as a subscript. `a_`  instead is an a without a b as a subscript.

**Comment by richardgobeli** [comment]
It is not treated as a character but as the start of a subscript that is blank.

**Comment by daute** [comment]
You can set, if variables (or only single variables) will be subscripted. Look up `wxdeclare_subscripted()` and `wxsubscripts` in the wxMaxima manual. For example try:

```
wxdeclare_subscripted(a_,false)$ /* Variable "a_" should not be subscripted */
a-a_;
```

**Comment by richardgobeli** [comment]
I see that works and it flags all occurrences of a_ to be text even ccca_.  👍
