### ISSUE TITLE
Restart from beginning button has become very slow.  It takes near 10-seconds to start over.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1715]
I noticed this in the last week or two.

Another big delay was the scanning of the manual the first time loaded.

Then repeating a start is a good 10-second delay in executing the first line.
![image](https://user-images.githubusercontent.com/31253976/190026741-26732067-89c1-439d-809d-a7359a3f41cb.png)

**Comment by richardgobeli** [comment]
Here are the first things done in response to restarting the first line.
![image](https://user-images.githubusercontent.com/31253976/190027534-f988ec8a-a90c-410b-9207-1321d46c0b26.png)

**Comment by richardgobeli** [comment]
This may have been something wrong with my computer.  Seems to be about normal now.

**Comment by gunterkoenigsmann** [comment]
Normally the manual should only be scanned the first time a new maxima Version has been used.

And restarting maxima should wait for the end of that scanning process. Does the debug messages sidebar tell that something went wrong with the manual anchors ca he? That might explain all of your findings

**Comment by richardgobeli** [comment]
I'll need to remember the debug screen.
Here it takes 3 seconds.
![image](https://user-images.githubusercontent.com/31253976/190281720-1df6944c-cb06-43cb-aaab-1eface9e9cd4.png)

**Comment by gunterkoenigsmann** [comment]
Seems like stopping the old maxima needs a whole second.I wonder if on MS Windows there is a good way to kill one's child processes.

...and then the new maxima seems to need the rest of the time to startup.

**Comment by richardgobeli** [comment]
Does the raw XML monitor output the variables every time?
The line below makes a lot of output per cell.  It goes on for pages after the Maxima prompt statement.
Is this done only when the raw monitor sidebar is up?
:lisp-quiet (wx-print-gui-variables)


![image](https://user-images.githubusercontent.com/31253976/190504624-bc5cf2be-62bc-47e1-9701-02590d3deff7.png)

**Comment by gunterkoenigsmann** [comment]
It should only do so if there isn't anything else to do, in the moment.: The command issent to maxima when all of the following conditions are met:

* The event loop of wxMaxima is empty, which means that there are no more key presses, data packets from maxima  mouse events or similar things to process.
* maxima isn't asking a question
* Maxima isn't in lisp mode
* Maxima asks for Input
* And there are no commands in the queue of cömmands that we still need to send to maxima.

**Comment by gunterkoenigsmann** [comment]
What I have changed recently is that wxMaxima waits for the old maxima process to exit before starting a new one. I believe that gets rid of a racing condition on the Mac.

**Comment by richardgobeli** [comment]
The debug messages have the restart taken about 1 second. Build from today.
![image](https://user-images.githubusercontent.com/31253976/191167980-ce8c779a-76e2-4c8d-b9cd-0b49afe94e01.png)
