### ISSUE TITLE
load(draw) doesn't work

### ISSUE THREAD

**Issue by aquaprot** [wxMaxima-developers/wxmaxima#1716]
**load(draw) doesn't work** - 

ubuntu 22.04, 
wxMaxima version: 20.12.1_GTK3_OpenMP201511+Locks
wxWidgets version: wxWidgets 3.0.5
Maxima version: 5.45.1

After using the command load(draw) we obtain the information:
loadfile: _failed to load /usr/share/maxima/5.45.1/share/draw/draw.lisp_

**Comment by daute** [comment]
The same problem will probably occur with command line Maxima, so this is most likely not a wxMaxima problem.

Debian/Ubuntu splits the Maxima-Package into several sub-packages (maxima, maxima-doc, maxima-share, ...) - and you have probably not installed the `maxima-share` package. Try `apt-get install maxima-share` to solve the problem.

I don't know, why they split the package into several sub-packages. In my opinion Maxima should be *one* package.
Best regards, Wolfgang

**Comment by aquaprot** [comment]
The information, which is obtained after the command `apt-get install maxima-share` is following: _maxima-share is already the newest version (5.45.1-8)_. I think, you are right that this is not a wxMaxima problem. 

Best regards, Radek

**Comment by gunterkoenigsmann** [comment]
In a few cases deleting ~/.maxima/binary helps if share packages cannot be loaded.

**Comment by aquaprot** [comment]
> In a few cases deleting ~/.maxima/binary helps if share packages cannot be loaded.

Unfortunately, in this case it doesn't help.
Best regards, Radek

**Comment by gunterkoenigsmann** [comment]
Sounds like I should forward that mail to the maxima-discuss@lists.sourceforge.net list so one of the experts can look at that problem..

**Comment by aquaprot** [comment]
> Sounds like I should forward that mail to the [maxima-discuss@lists.sourceforge.net](mailto:maxima-discuss@lists.sourceforge.net) list so one of the experts can look at that problem..

That is a good idea. It is not the first time - problem with load(draw) in ubuntu distro. Previously, I do not remember exactly the version, but you had to edit draw.lisp file to fix the same problem.
