### ISSUE TITLE
wxWidgets 3.2.1 release

### ISSUE THREAD

**Issue by tanuki-no** [wxMaxima-developers/wxmaxima#1723]
HI! The [wxWidgets 3.2.1](https://wxwidgets.org/news/2022/09/wxwidgets-3.2.1-released/) is out and looks good. What about update to latest version?

P.S. BTW, do you accept patches?

**Comment by gunterkoenigsmann** [comment]
We accept any help you can give us.

**Comment by daute** [comment]
For systems other than Windows, we usually do not provide binaries, they are created e.g. by the maintainers of Linux distributions, etc.
It's also not too hard to compile wxMaxima on Linux/Unix by yourself and using the wxWidgets version you like.

For Windows code for using wxWidgets 3.2.1 is already there:
https://sourceforge.net/p/maxima/code/ci/fdc7b4a
for the included wxMaxima in the Maxima installer. You can use it, if you use my nightly builds of the current wxMaxima and Maxima developmen version.

For creating a wxMaxima only Windows installer, the current wxWidgets version is used too:
https://github.com/wxMaxima-developers/Crosscompiled-Windows-installer/commit/73e89fe28

Best regards, Wolfgang

**Comment by daute** [comment]
I updated wxWidgets in the mentioned repositories to the most recent version 3.2.2.1 now.

And too in the Appveyor/Github CI files, where we compile wxWidgets from source (See commit https://github.com/wxMaxima-developers/wxmaxima/commit/0124e9afee359b22bec47d15dc198f041ab94eef and https://github.com/wxMaxima-developers/wxmaxima/commit/a3f8b6a09b6a653e69b7e1d03bf9e06d46895041).

I am closing this request now.
