### ISSUE TITLE
Right click resets zoom level

### ISSUE THREAD

**Issue by xlucn** [wxMaxima-developers/wxmaxima#1726]
wxMaxima version: 22.09.0_GTK3
using wxWidgets version: wxWidgets 3.2.1
Maxima version: 5.46.0
Maxima build date: 2022-10-28 07:11:17
Host type: x86_64-unknown-linux-gnu
System type: Linux 6.0.2-arch1-1 x86_64
Lisp implementation type: ECL
Lisp implementation version: 21.2.1
wxMaxima's idea of the directory layout is:
User configuration dir: /home/oliver/.local/share/maxima/.maxima/
Help dir: /usr/share/doc/wxmaxima

As the title says, right click in the main notebook area will reset the zoom level.

If this can not be reproduced, please tell me how I can provide more information.

**Comment by gunterkoenigsmann** [comment]
That is wild... ...and I don't even know where to search for the error (and therefore: What to ask)...

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...after looking at the code I guess that is a collision of an ID that wxWidgets generates for some event with the ID of a "set zoom to n%" event...
...no idea what can cause such collisions, though...

**Comment by oliverlew** [comment]
Tried the commit above with AUR package, but issue still exists.

Do I need to make sure if this is related to my personal configuration, or system setup? I have only tried to move away the wxMaxima.conf, which had no effect on this issue.

**Comment by gunterkoenigsmann** [comment]
I *think* I have found a way to ensure that all IDs are generated using the same function. But this is a big change => will need a bit of time for changing the code.

**Comment by oliverlew** [comment]
First, thanks for the big change to address the issue. However, the latest build (AUR package) with commit 248bc1aa5 does not allow me to change zoom at all. I will test on another machine later, but I feel the need to report here first, just in case the issue is not at my end.

**Comment by xlucn** [comment]
@gunterkoenigsmann The issue still exists. Could anyone else reproduce the behavior? I feel like the only one troubled by it.

I am using the latest [wxmaxima-git](https://aur.archlinux.org/packages/wxmaxima-git) package in Arch AUR.

[Screencast from 2023-04-05 13-22-06.webm](https://user-images.githubusercontent.com/12032219/229988394-35bb205c-867f-4da8-87f1-754ac154f03c.webm)

Sorry the gnome screencast tool somehow fails to capture the mouse cursor, but that doesn't matter much.

**Comment by gunterkoenigsmann** [comment]
Found another potential issue. If it is what I found tomorrow's nightly build will contain the fix. If I didn't I have one theory: Could it be that the problem only appears with a specific language being selected? Not that the error resides in the translation io wxMaxima (which might contain bindings that are more fit to a german/french/... keyboard), not in the C++ code.

**Comment by xlucn** [comment]
Tried the latest git `23.04.0.r39.g894c0beaf-1` AUR package, the issue remains. (So probably reopen the issue?)

From your comments, I guess you couldn't reproduce the issue. If so, you don't have to invest too much time in fixing possible causes, in case the issue is at my end (dependencies, GUI environments, etc.). To test it, I might try again later on a clean Arch VM setup if I have the time.

**Comment by xlucn** [comment]
I saw the latest release has fixed the issue. Thanks! I will close this issue now.

However, I tested the 23.10 version and caught some other minor issues regarding to right click and zoom. I will report them later in a new thread.
