### ISSUE TITLE
Gnuplot "Command Line" has been removed

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1732]
In the wxMaxima help files it says:
```
On MS Windows, if in Maxima’s variable gnuplot_command “gnuplot” is replaced by “wgnuplot”, gnuplot offers the possibility
to open a console window, where gnuplot commands can be entered into. Unfortunately, 
enabling this feature causes gnuplot to “steal” the keyboard focus for a short time every time a plot is prepared.
```

This also works very nicely in former times: In the gnuplot window you could call the ``` Command Line ``` by:

![image](https://user-images.githubusercontent.com/2638713/203510088-1494113d-a1db-48ab-ba18-ad8fc5fa051e.png)

This opens an interactive gnuplot command window with many of the gnuplot commands available in menus:

![unnamed2](https://user-images.githubusercontent.com/2638713/203510510-2324dd37-1bbb-4b7e-bf99-02d120e928c6.png)

Unfortunately - the ``` Command Line ``` has been removed (Even when using  ```gnuplot_command  : wgnuplot;```) 

![image](https://user-images.githubusercontent.com/2638713/203511172-c9232ff2-a0d8-4333-b0b1-9e7c19834592.png)

The above gnuplot "Command line" window was recalled by installing an somewhat old version of wxMaxima:
```
wxMaxima version: 17.10.x.unofficial
Maxima version: branch_5_41_base_177_g3d02b5e_dirty
Maxima build date: 2018-02-03 23:06:17
Host type: i686-w64-mingw32
System type: Win32 10.0.19044 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.4.2
```

**Unfortunately I can not tell exactly when the ```Command Line``` disappeared** 

Current version:
```
version="branch_5_46_base_555_g6fa201ff5_dirty",timestamp="2022-11-21 00:01:11",host="x86_64-w64-mingw32",
lisp_name="SBCL",lisp_version="2.2.10",maxima_userdir="C:/Users/xxxx/maxima",maxima_tempdir=
"C:/Users/xxx/AppData/Local/Temp",maxima_objdir=
"C:/Users/xxx/maxima/binary/branch_5_46_base_555_g6fa201ff5_dirty/sbcl/2_2_10",maxima_frontend="wxMaxima",
maxima_frontend_version="22.09.0-DevelopmentSnapshot_MSW"
```

**_Does any of you know where to ask how to get it back - I am really missing it?_**

Kind regards
Rene'

**Comment by daute** [comment]
[Note: that issue has nothing to do with wxMaxima, it also happens when using command line Maxima.]

That version was 5 years old. Some things have changed since then, newer gnuplot version, changes in the Maxima-code, etc.
But after some experiments I found out how you can get it back:

```
draw_renderer : gnuplot;
gnuplot_command : wgnuplot;
draw2d( explicit(sin(x),x,0,5), user_preamble="set term windows")
```
It seems, that that only works with Gnuplot's "windows"-Terminal and if Maxima is not using a pipe.

Does that have the effect you want?
Best regards, Wolfgang

**Comment by ReneSci** [comment]
Yes, this works - I don't know why.... 

Maybe it is related to some changes in the gnuplot environment. I  don't know where to ask.

Thank you for your time and effort !!

I only used that old version because I new that was working so I could get some screen dumps to show. 

I have been looking back. From https://github.com/wxMaxima-developers/wxmaxima/issues/1680 it seems like this behavior started somewhere after late January 2022:

Best regards
Rene'

**Comment by ReneSci** [comment]
However, the wxdraw2d plots then ends up like this (sometimes it helps replotting them):
![image](https://user-images.githubusercontent.com/2638713/204160745-7c2570b5-29e7-410e-abf1-f72eb66b9c24.png)

**Comment by daute** [comment]
I think, I fixed it now.
