### ISSUE TITLE
Lost contact with Maxima kernel

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1735]
Just installed the latest nightly build - it can not even do a
```
build_info();
```
Just mark the cell as being active and stops. 

Can restart using:
![image](https://user-images.githubusercontent.com/2638713/207835468-04ac0f51-44b6-430c-a0be-520479f9855c.png)

Running Windows 11

Have to revert back to yesterdays build

**Comment by gunterkoenigsmann** [comment]
Ok... ...took me 3 days to get the windows 11 VM up and running on my computer (actually mostly waiting time, since my computer is on the slow edge). ...and it seems like sbcl 2.2.11 chokes on wxMathml.lisp => will try to make sbcl 2.2.11 run on my linux system and will try to debug the problem.

**Comment by gunterkoenigsmann** [comment]
SBCL 2.2.11 on Linux works without causing that problem. Seems like I'll have to ask the maxima mailing lisp on how to debug lisp problems.
