### ISSUE TITLE
How could I buid an executable file from the Latest release of WxMaxima for setup on Windows

### ISSUE THREAD

**Issue by idealkindom** [wxMaxima-developers/wxmaxima#1739]
As the title says.

**Comment by idealkindom** [comment]
> There are loads of options to compile wxMaxima. For some of them there are build receipes in the .github folder that Do you want to generate the windows executable on a Linux computer or on a Windows computer? That question might sound strange, but many windows applications are built on Linux, as that is simpler than compiling something on a windows computer. For doing so there is a good description in the crosscompile-windows folder of ([maxima] (https://maxima.sourceforge.net)) Do you already have a compiler installed? If not I prefer msys+mingw - and for many compilers there are half-way human-readable build descriptions in wxMaxima's .github folder. Or do you just want to have the current state of the code running on your system - like I happen to do. In that case just download the installer ([maxima-current-win64.exe](https://wolfgang.dautermann.at/maxima/nightlybuild/maxima-current-win64.exe)) Wolfgang builds every night and install wxMaxima. On Windows computers that is the way I typically use.

Thanks a lot for so detailed and concrete instructions. I feel at present maybe the most convenient way is the last one.

I recalled I once downloaded Wolfgang nightly built Maxima including latest WxMaxima, but the WxMaxima incurr serious bugs, such as totally opposite layout of the manus and words. Anyway , I will try it again. 

Thanks again. I love WxMaxima.

**Comment by idealkindom** [comment]
> There are loads of options to compile wxMaxima. For some of them there are build receipes in the .github folder that Do you want to generate the windows executable on a Linux computer or on a Windows computer? That question might sound strange, but many windows applications are built on Linux, as that is simpler than compiling something on a windows computer. For doing so there is a good description in the crosscompile-windows folder of ([maxima] (https://maxima.sourceforge.net)) Do you already have a compiler installed? If not I prefer msys+mingw - and for many compilers there are half-way human-readable build descriptions in wxMaxima's .github folder. Or do you just want to have the current state of the code running on your system - like I happen to do. In that case just download the installer ([maxima-current-win64.exe](https://wolfgang.dautermann.at/maxima/nightlybuild/maxima-current-win64.exe)) Wolfgang builds every night and install wxMaxima. On Windows computers that is the way I typically use.

Since Maxima 5.46,including the nightly built Maxima, it looks like Windows 7 is not supportted any more. The process of installation is as usual, but it bugs when you run it.

> There are loads of options to compile wxMaxima. For some of them there are build receipes in the .github folder that Do you want to generate the windows executable on a Linux computer or on a Windows computer? That question might sound strange, but many windows applications are built on Linux, as that is simpler than compiling something on a windows computer. For doing so there is a good description in the crosscompile-windows folder of ([maxima] (https://maxima.sourceforge.net)) Do you already have a compiler installed? If not I prefer msys+mingw - and for many compilers there are half-way human-readable build descriptions in wxMaxima's .github folder. Or do you just want to have the current state of the code running on your system - like I happen to do. In that case just download the installer ([maxima-current-win64.exe](https://wolfgang.dautermann.at/maxima/nightlybuild/maxima-current-win64.exe)) Wolfgang builds every night and install wxMaxima. On Windows computers that is the way I typically use.

Since Maxima 5.46,including the nightly built Maxima, it looks like Windows 7 is not supportted any more. The process of installation is as usual, but it bugs when you run it.

**Comment by FEA-eng** [comment]
[gunterkoenigsmann](https://github.com/gunterkoenigsmann) By the way, may I ask if you know when the wxMaxima executable will be officially released? Since March all releases consist only of a source code package. I don't know how often wxMaxima is typically released as a stable version with an installer so sorry if I seem impatient.

**Comment by daute** [comment]
Sorry, for the delay, I build and released a Windows installer now too.

**Comment by gunterkoenigsmann** [comment]
The problem with Windows 7 is that even if neither the wxMaxima nor the maxima team actually tries to break it it nowadays has become hard to support that operating system: 

- All libraries maxima and wxMaxima depend on are (at least officially) no more tested on Windows 7.
- The CRT that provides the I/O (file, network and graphical) and many of the standard C and C++ functions one expects from a system is only supported on Windows 7 for about another 2 weeks. 
- The compilers we use are no more tested on Windows 7.

But if you tell us what bugs you encounter we can at least try to ship around them...

**Comment by FEA-eng** [comment]
> Sorry, for the delay, I build and released a Windows installer now too.

No problem, thank you very much. I guess that built-in update checker considers only new releases posted on http://wxmaxima-developers.github.io/wxmaxima/download.html and not binaries on GitHub, right?

**Comment by daute** [comment]
No, it depends on the file version.txt on the wxmaxima website - which must also be updated, of course...

Done now with the following commit: https://github.com/wxMaxima-developers/wxmaxima/commit/0a71aaa7af6498fc45431969fa7510ac5a9697e3
Sorry.

**Comment by gunterkoenigsmann** [comment]
I was totally convinced I had removed that feature years ago as for the majority of users it isn't really helpful to know that the source code to a new wxMaxima version has been released as that doesn't mean that a new binary package is available anywhere...

**Comment by FEA-eng** [comment]
> Done now with the following commit: [0a71aaa](https://github.com/wxMaxima-developers/wxmaxima/commit/0a71aaa7af6498fc45431969fa7510ac5a9697e3) Sorry.

Great, thank you again.

**Comment by daute** [comment]
Concerning Windows 7: This came up on the Maxima mailing list some time ago - see:
https://sourceforge.net/p/maxima/mailman/message/37798337/
(and the complete thread of this discussion).

The latest Maxima release which run fully on Windows 7 is 5.45.1. If you use CLISP (Maxima is compiled with two Lisp compilers (SBCL and CLISP, the nightly build with three (ABCL too)), it should work on Windows 7 too. At least I hope that.

But one should nor use Win7 anymore, it is no longer supported.
Best regards, Wolfgang
