### ISSUE TITLE
Substitute dialog doesn't show

### ISSUE THREAD

**Issue by rulatir** [wxMaxima-developers/wxmaxima#1744]
Repro:

1. Simplify -> Substitute -> Substitute...

Expected: Substitute dialog.
Actual: Nothing happens, nothing on stdout.

Other input dialogs work, e.g. Equations -> Solve symbolically -> Solve...

wxMaxima 22.12.0 built from [AUR package](https://aur.archlinux.org/packages/wxmaxima).

**Comment by daute** [comment]
Should be fixed with commit 20930bf - thanks for your bug report.
