### ISSUE TITLE
Incorrect font rendering on Windows x64

### ISSUE THREAD

**Issue by RoyalXXX** [wxMaxima-developers/wxmaxima#1753]
I choose a monospace font for the code (Cascadia Mono) and a serif font for the output (Times New Roman), but the program displays everything in the same font (Times New Roman).

![1](https://user-images.githubusercontent.com/125651292/219626012-4f6c584b-5b7c-4263-8c89-31e7fdc0a754.png)
![2](https://user-images.githubusercontent.com/125651292/219626059-223db615-6fa8-4219-a5b6-fe9f8bc98090.png)
![3](https://user-images.githubusercontent.com/125651292/219626079-a40372c8-e89a-46cf-8af3-a0ea653f8ef1.png)

**Comment by gunterkoenigsmann** [comment]
What version of wxMaxima are you using?

**Comment by RoyalXXX** [comment]
@gunterkoenigsmann the latest - wxMaxima 23.02.0-DevelopmentSnapshot

**Comment by gunterkoenigsmann** [comment]
For that version I had rewritten the whole styles system in order to get rid of this kind of errors. Let's hope that I did not introduce more new errors whist doing this...
