### ISSUE TITLE
Bug on positivity check

### ISSUE THREAD

**Issue by toolmathmoodle** [wxMaxima-developers/wxmaxima#1759]
Hi,
I am not sure why wxmaxima is not identify that "a" is positive.

![image](https://user-images.githubusercontent.com/111237208/222064618-36022dc2-349b-4607-8d50-829d03ec85b1.png)

**Comment by dilijev** [comment]
That's an issue with the underlying maxima engine, can you file a bug there?

**Comment by dilijev** [comment]
The prompt transcribed is:

```
a:1-t^2/2; assume(t>-1 and t<1); is(t>0); is(t>-1);
```

The output from maxima is:

```
(%i1) a:1-t^2/2; assume(t>-1 and t<1); is(t>0); is(t>-1);
                                         2
                                        t
(%o1)                               1 - --
                                        2
(%o2)                          [t > - 1, t < 1]
(%o3)                               unknown
(%o4)                                true
```

**Comment by daute** [comment]
The bug was filed as: https://sourceforge.net/p/maxima/bugs/4111/
Closing it here, since it is a limitation of Maxima.
