### ISSUE TITLE
Plotting error with default plot2d and wxplot2d

### ISSUE THREAD

**Issue by juhothomas** [wxMaxima-developers/wxmaxima#1763]
So I'm getting errors trying to do simple plots:

![image](https://user-images.githubusercontent.com/12074496/227383218-dab80162-5731-434e-9d8d-511a458f8df3.png)

build_info(version="5.46.0",timestamp="2022-04-13 23:24:03",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.2.2",maxima_userdir="C:/Users/Thomas/maxima",maxima_tempdir="C:/Users/Thomas/AppData/Local/Temp",maxima_objdir="C:/Users/Thomas/maxima/binary/5_46_0/sbcl/2_2_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.03.0_MSW")

wxMaxima version: 23.03.0_MSW
using wxWidgets version: wxWidgets 3.2.2.1
Maxima version: 5.46.0
Maxima build date: 2022-04-13 23:24:03
Host type: x86_64-w64-mingw32
System type: Win32 10.0.22621 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.2.2
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Thomas\maxima\
Help dir: C:\maxima-5.46.0\share/doc/wxmaxima

My TEMP and TMP environment variables are %USERPROFILE%\AppData\Local\Temp

Windows specs:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎22/‎10/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by juhothomas** [comment]
Gnuplot seems to be dead in this compilation.
I installed the new version of it to the C:\maxima-5.46.0 folder. Changed it's name to gnuplot and now things seem to work

![image](https://user-images.githubusercontent.com/12074496/227705505-bb9d7fde-9f61-4a79-b96b-3238869b3f33.png)

**Comment by daute** [comment]
Thanks for the report. Very strange; I tried now (again) the latest Maxima release, which you were using, with the included Gnuplot on Windows 11 (all updates installed), but it did work for me without problems.

Did the included Gnuplot - when called directly ( e.g. gnuplot or wgnuplot in  `C:\maxima-5.46.0\gnuplot\bin`) - itself work?

Best regards, Wolfgang
(I build the Maxima (and wxMaxima) Windows installer).

**Comment by juhothomas** [comment]
![image](https://user-images.githubusercontent.com/12074496/227737284-dd00215d-08fd-4963-ae66-35d8bee71a31.png)

They neither worked. Gnuplot gave the above message and then exited. Wgnuplot flashed a window for a while then exited. 

Gnuplot version 5.4.(6) works fine.

Cheers, Thomas

**Comment by daute** [comment]
I updated Gnuplot now in the Maxima installer; the next (64bit) release and the upcoming nightly builds will use Gnuplot 5.4.6. (see: https://sourceforge.net/p/maxima/code/ci/b7477363).

See Gnuplot bug https://sourceforge.net/p/gnuplot/bugs/2227/ - according to the related bug report https://sourceforge.net/p/gnuplot/bugs/2304/ the issue was fixed in Gnuplot 5.4.2.
