### ISSUE TITLE
The new nightly build crash with demo(tensor);

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1765]
![image](https://user-images.githubusercontent.com/31253976/230698993-47d3d782-96b1-4623-9fff-7817eb4a8c5e.png)
demo does work in xmaxima.bat but not in wxmaxima.
also the wxbuild_info() does not work. 
I does not format the items in lines anymore
![image](https://user-images.githubusercontent.com/31253976/230699274-210ec8e6-f3cc-4049-9e0f-6bbdcf0a63c3.png)

This is the version.  After entering, the command is displayed, and then the program crashes.
How do you change bash directory so I can type gdb wxmaxima to run it in gdb?

I get this:
![image](https://user-images.githubusercontent.com/31253976/230699168-7d4c6f00-24af-46c5-a192-6bc84547e5c3.png)

**Comment by gunterkoenigsmann** [comment]
The `cd` command (short for changedir) and I've tried to run into trouble with the tensors demo on my own PC and the GitHub CI. Both computers seem not to crash before I run out of ideas.

On the plus side now every commit now is automatically tested with most tensor demos - which should limit the amount of bitrot we can get with tensors without noticing.

The build_info() change was intentional: First I added Al valid info to build_info(). Then my plan was to make the wxMaxima fiction punt to the Maxima one which means less code to maintain for me. It is no more formatted nicely for the eye, but uses a Maxima struct now which is easier to interpret by the machine.

**Comment by richardgobeli** [comment]
Isn't the old wxbuild_info() just a function that formates the lhs of an equation to the rhs and they are both strings for each element of the list?
I'll see if I can get a backtrace of wxmaxima later.

**Comment by richardgobeli** [comment]
from Todays build.  Using windows 10 latest version.
![image](https://user-images.githubusercontent.com/31253976/230752945-07b00044-4216-430c-8b66-1ad4c73f0c46.png)

Complete crash dump for crash during demo(tensor); is attached.
Is this again an issue with WxWidgets string function?

[Crash dump.txt](https://github.com/wxMaxima-developers/wxmaxima/files/11184746/Crash.dump.txt)


Bug report does not print the build_info between the two dotted lines.
![image](https://user-images.githubusercontent.com/31253976/230752863-890c44ea-18cd-4deb-8871-b6814c740faf.png)

**Comment by gunterkoenigsmann** [comment]
That I wouldn't have found without a crash dump. Thanks a lot for providing one.

...and your are right: wxbuild_info() wouldn't have been too much code to maintain. But still if I can integrate functionality directly into maxima I don't want wxMaxima needing to provide the same functionality, as well.

**Comment by richardgobeli** [comment]
Thanks for the quick fix.  I'll look to see if it runs on tonight's build.
Maxima does a nice format for build_info(); Xmaxima is here:
![image](https://user-images.githubusercontent.com/31253976/230778309-e0cbed47-22b8-4320-8f2c-90622d38ea5e.png)
Maxima itself is basically the same.
But why does WxMaxima print as one big list with no formatting?
Is it because the output list is inside the build_info( data list )?

**Comment by gunterkoenigsmann** [comment]
build_info() returns an ordinary struct - but that struct seems to be equipped with an property that tells Maxima:s 2d printer to call a specific function that knows how to properly format it. With enough lisp knowledge one could write such a function for wxMaxima, as well.

**Comment by richardgobeli** [comment]
I see the nightly build still crashes using demo(tensor);
[Crash dump.txt](https://github.com/wxMaxima-developers/wxmaxima/files/11188089/Crash.dump.txt)
![image](https://user-images.githubusercontent.com/31253976/230837519-e1157c04-bbda-4edb-98bf-ef0c233ac3e6.png)
the items are a structure where each item can be retrieved with the following name field example.
build_info()@version   with will return the version.
[build_info.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/11188177/build_info.pdf)
The version = string is only a display format. Each item needs to be retrieved with a field name and not a variable, which means the double single quote on x as build_info()@''x
