### ISSUE TITLE
windows debug issue when saving or loading a file

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1768]
![image](https://user-images.githubusercontent.com/31253976/230836034-c301b3c3-604e-4b3a-b460-3d62036067c3.png)
![image](https://user-images.githubusercontent.com/31253976/230836215-246bb883-c512-4719-9c3e-d66d67b551e4.png)

**Comment by gunterkoenigsmann** [comment]
That looks like for the recent files list I am only allowed to use the menu item IDs once. Currently if I change  items I just empty the menu and add all entries again re-using the IDs I had led generate wxWidgets the last time I populated the menu.

**Comment by gunterkoenigsmann** [comment]
I believe I finally managed to understand that part of the code of wxWidgets. If I did I believe the problem is that wxWidgets has detected that we use the same event ID twice. The question now is: We use literally hundreds of event IDs. How do we debug that?

Is any of you able to get a meaningful backtrace using gdb or similar? That way we could detect one end of the conflict, but naturally most likely not the other....

**Comment by richardgobeli** [comment]
here is a backtrace file after loading a wxmx file and doing the stop at the error screen.
[Dump for 1768.txt](https://github.com/wxMaxima-developers/wxmaxima/files/11223282/Dump.for.1768.txt)
![image](https://user-images.githubusercontent.com/31253976/231793897-5d7f2248-c1c7-48ef-b8a0-933dff683160.png)

**Comment by richardgobeli** [comment]
This is the same version of software.
this error was because of a save.
[Dump from save.txt](https://github.com/wxMaxima-developers/wxmaxima/files/11227516/Dump.from.save.txt)

**Comment by daute** [comment]
This seems to be solved with the current git version. Thanks Gunter!

**Comment by richardgobeli** [comment]
I see a load (itensor) command does not work.  It maybe any load command.
Load (units) also does not work.

**Comment by gunterkoenigsmann** [comment]
Thanks for testing that. What are the symptoms of the load() problem? On my own computer that problem doesn't seem to manifest: Loading itensor produces a handful of warnings, but engineering-format and units load and seem to actually work.

**Comment by richardgobeli** [comment]
It just seems to hang up with the input line highlighted.
![image](https://user-images.githubusercontent.com/31253976/232120418-0be47906-3406-4d4c-9a99-4d774ae25c86.png)
It does allow me to restart.
![image](https://user-images.githubusercontent.com/31253976/232120615-e05c71a8-18c9-4ef5-9f79-c8382f067bdb.png)

**Comment by richardgobeli** [comment]
here is the raw monitor.
![image](https://user-images.githubusercontent.com/31253976/232121225-d259986b-b1a4-4129-a2f6-e30b2077f87f.png)

**Comment by gunterkoenigsmann** [comment]
That was exactly the bit of information I needed in order to find out where the problem lies: You didn't enclose the package name in double quotes. But I did. Thanks a lot!

**Comment by richardgobeli** [comment]
Your Welcome.
