### ISSUE TITLE
Parentheses missing in output after open

### ISSUE THREAD

**Issue by jhkaiser** [wxMaxima-developers/wxmaxima#1779]
Attached you will find a simple wxmx file. When loaded, the parantheses in the numerator of the stored output are missing.  They only appear correctly again after re-evaluation.

**Comment by gunterkoenigsmann** [comment]
Unfortunately the .wxmx file doesn't seem to have arrived here. If you rename it into something that ends in .txt or .zip it is more likely to be accepted by github.

**Comment by jhkaiser** [comment]
Here it is -- with its extension changed to '.txt'.
[test.txt](https://github.com/wxMaxima-developers/wxmaxima/files/11529315/test.txt)
