### ISSUE TITLE
snap: Unable to initialize GTK+

### ISSUE THREAD

**Issue by ng0177** [wxMaxima-developers/wxmaxima#1781]
[wxmaxima](https://snapcraft.io/wxmaxima) yields on various platforms:
```
$ snap run wxmaxima
Authorization required, but no authorization protocol specified
14:37:22: Error: Unable to initialize GTK+, is DISPLAY set properly?
Segmentation fault
```
Just for information.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for this bug report!

I believe the issue is resolved now - and everything should work fine after a 

````
snap refresh
````
on your side. If not please tell me what happens now.

Thanks a lot,

   Gunter.

**Comment by ng0177** [comment]
Welcome. I confirm

snap run wxmaxima

does not have the display variable issue anymore. An error pops up:

locale 'en_US' cannot be set.

and then upon successful start

...unable to set up the help system
...

is reported with the side pane not functioning.

Regards, Thomas
