### ISSUE TITLE
Less left margin when printing

### ISSUE THREAD

**Issue by bllamarodri** [wxMaxima-developers/wxmaxima#1787]
Hi, 
I use Maxima with my students, and I need to print the exams I create for them. Would it be possible for the labels %i1, %o1, etc. to appear when printing, and for the left margin to be smaller? I think it's excessive and causes many expressions to be cut off.
Best regards,

Boni

**Comment by yurytch** [comment]
Would the attached `print to file` output be what you want? The blank indentation between the paper edge and the cells' labels being smaller than usual (usually it's about label's width)?
That seems to be regulated by #define PRINT_MARGIN_HORIZONTAL 50 in `src/graphical_io/Printout.cpp`.
I tried setting it to 5, nothing broke, the result is attached.

![output pdf](https://github.com/wxMaxima-developers/wxmaxima/assets/8167943/d2306b6e-c015-4840-9d58-37448e6ed834)

**Comment by bllamarodri** [comment]
Thank you very much for the help, but I am working with Windows 10, and although I find some folders named src, there is no folder named graphical_io, and no file named Printout.cpp.
I also just realized that there is a problem with the integral symbol when printing.

Best regards,
Boni

[Documento wxMaxima.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/11994915/Documento.wxMaxima.pdf)

**Comment by yurytch** [comment]
I was primarily addressing developers' team, to let them know about a possible solution. Printout.cpp etc. is to be found in the source code archive, not in the binary package.
The question which only you can answer is, do you want *that* kind of the narrowed left margin, or do you want something else?
Integral sign is obviously a material for another issue.

**Comment by gunterkoenigsmann** [comment]
I wonder if a margin of "5" is meant to be 5mm wide. AFAICS the scaling was inconsistent until about 2 minutes ago, though...

**Comment by bllamarodri** [comment]
> The question which only you can answer is, do you want _that_ kind of the narrowed left margin, or do you want something else? Integral sign is obviously a material for another issue.

The margin could be the one you have used in the document.

**Comment by yurytch** [comment]
> I wonder if a margin of "5" is meant to be 5mm wide. 

I've just assured myself that zero in the variable won't lead to anything drastic. Maybe make this a configuration option, later?

**Comment by gunterkoenigsmann** [comment]
Will try to add one. Additionally I will make another attempt on getting the print scale right or at least consistent.

**Comment by gunterkoenigsmann** [comment]
I cannot claim, though,that I have found out what factors affect the print scaling.

**Comment by gunterkoenigsmann** [comment]
In about 20 hours on https://wolfgang.dautermann.at/maxima/nightlybuild/ you can download a windows installer that (hopefully) does exactly what you want. Any testing is welcome!

**Comment by bllamarodri** [comment]
Hello,
I have tried the new version and I get the following error when I try to print. Also, when I want to change the configuration options, the program closes.

[Error.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/12027854/Error.pdf)

**Comment by gunterkoenigsmann** [comment]
That kind of report is very important: I don't own a windows box I can test wxMaxima on - and some problems just don't happen to trigger on Ubuntu. Let's hope that I got it right this time. In about 14 hours the dautermann.at site will contain a (hopefully) corrected wxMaxima version.

**Comment by gunterkoenigsmann** [comment]
About the changes in .cpp and .h files: The files referenced in the commits and yurytch's and my messages refer to changes in the c++ source code of wxMaxima: a more-or-less human-readable description of what the program is supposed to do that is detailled enough that a computer can translate it to a .exe file that actually does do that.

**Comment by bllamarodri** [comment]
Thank you very much. I will check it again.

**Comment by bllamarodri** [comment]
Hi,
I have checked both versions (32 and 64 bit) and they still give the same problems.

**Comment by gunterkoenigsmann** [comment]
Tomorrow's nightly build (hopefully) greatly enhances the printing experience.
