### ISSUE TITLE
Style Configuration is Not Saved - 23.05.1

### ISSUE THREAD

**Issue by LP314159** [wxMaxima-developers/wxmaxima#1789]
After compiling (Gentoo) and installing wxMaxima-23.05.1 the program opens with white background and white text boxes.  If I make changes (Edit -> Configure -> Style) and set the document background and text backgrund to other colors the changes only persist until I exit the program.  No changes are saves.  The program will open again with white background and white text boxes.

Also, if I save the style changes via  Edit -> Configure -> Style -> Save I cannot load the saved file.

To obtain my desired styles I have to manually make changes, Edit -> Configure -> Style, each and every time I run wxMaxima.

This behavior did not occur in previous versions.

Is there anything that I can do to correct this?

wxMaxima 23.05.1
wxWidgets: 3.2.2
Unicode support: yes
Maxima version: 5.47.0

**Comment by yurytch** [comment]
I believe that issue concerns anything with subkey "/color" in the config.
It should be fixed for all such entries with the following patch:

```--- src/TextStyle.cpp.prev	2023-05-29 08:45:54.000000000 +0300
+++ src/TextStyle.cpp	2023-07-06 21:12:06.199866478 +0300
@@ -300,7 +300,7 @@
   long tmpLong;
   double tmpDouble;
 
-  if (config->Read(wxString::Format(k_color, where), &tmpStr)) {
+  if (config->Read(where+k_color, &tmpStr)) {
     wxColor color = wxColor(tmpStr);
     if (color.IsOk())
       SetColor(color);

**Comment by LP314159** [comment]
The patch fixes the issue.  Thanks.

**Comment by yurytch** [comment]
De nada. Needs to be integrated in the trunk yet.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for finding the issue, debugging, the solution and testing!
