### ISSUE TITLE
wxplot2d(4*x^2-8*x+2,[x,-1,2]); gives Wxmaxima Error

### ISSUE THREAD

**Issue by o1957823** [wxMaxima-developers/wxmaxima#1801]
error description is: can't open file '/var/folders/nc/n7pvwk2n1h9fwgmsfkw5jwt40000gn/T/maxout_4758_12.png' (error 2: No such file or directory)

System info
wxWidgets: 3.1.2
Unicode Support: yes
Maxima version: 5.43.0 (x86_64-apple-darwin13.4.0)
Lisp: SBCL 1.5.3

**Comment by gunterkoenigsmann** [comment]
The question now is: Does the file exist? If it doesn't: Could you report to maxima.sf.net that the file isn't generated and no error message appears why that is?

**Comment by o1957823** [comment]
I have done so, ticket: 4183



Op di 12 sep 2023 om 08:59 schreef Gunter Königsman <
***@***.***>:

**Comment by daute** [comment]
As the Maxima bug report 4183 was closed, I assume, that issue can be closed too, ok?
