### ISSUE TITLE
latest win build - ignores view-sidebar

### ISSUE THREAD

**Issue by cooch17** [wxMaxima-developers/wxmaxima#1806]
Just did an in-place update to 23.08.0. Works fine, except, whenever I start wxMaxima, the raw XML monitor is open (far right panel), even though it is not checked/selected in 'View | Sidebars'. If I turn it off during a session, it stays off for the session, but if I close and re-start wxMaxima, the XML monitor shows again. 

Not a huge issue, but though I'd pass it along.

**Comment by gunterkoenigsmann** [comment]
Every issue that is reported can be resolved => will look into it once I have time to. The next two weeks I am extremely busy in real life, though ...

**Comment by gunterkoenigsmann** [comment]
This report has actually helped to resolve a long-standing mac issue. Thanks a lot!

**Comment by cooch17** [comment]
Good. wxMaxima is a superbly crafted front-end to Maxima.
