### ISSUE TITLE
The display of subscipts has been backsliding for long

### ISSUE THREAD

**Issue by idealkindom** [wxMaxima-developers/wxmaxima#1807]
The problem of subscripts output after Maxima 5.43 has long been existing until now.
```
ΔP_r;print(ΔP_r,"=",4.6,".")$
ΔP_r1;print(ΔP_r1,"=",2.3,".")$
ΔP_r[1];print(ΔP_r[1],"=",1.2,".")$
P_r;P_r:4.6;print('ΔP_r,"=",4.6,".")$
P_r1;P_r1:2.3;print('ΔP_r1,"=",2.3,".")$
kill(all)$
P_r[1];P_r[1]:1.2;print('ΔP_r[1],"=",1.2,".")$
```

**Comment by gunterkoenigsmann** [comment]
We still are in urgent need of a lisp programmer who knows how to fix those issues...

**Comment by idealkindom** [comment]
> We still are in urgent need of a lisp programmer who knows how to fix those issues...

why not retreat those relevant features to an older but normal version?

**Comment by gunterkoenigsmann** [comment]
If we find someone who manages to do that without breaking support for characters like ">" again that would be fine

**Comment by idealkindom** [comment]
Al right.Thanks a lot for your explanations.
















At 2023-09-29 13:31:26, "Gunter Königsman" ***@***.***> wrote:

If we find someone who manages to do that without breaking support for characters like ">" again that would be fine

**Comment by robert-dodier** [comment]
I may be able to help with fixing the display of subscripts, however, it's not clear to me what exactly is the problem which has been observed, and in what way it is different from the previous version which didn't have the problem. If someone would post screenshots showing the observed and desired behavior, that would be very helpful for moving this issue forward.

@idealkindom You might work around issues about subscripts represented by underscores, by writing variables with explicit subscripts, e.g. `ΔP

**Comment by robert-dodier** [comment]
Sorry for the noise; somehow I inadvertently closed this ticket while typing ... There must be some keyboard shortcut which I accidentally hit. Anyway I've completed the comment I was trying to make and reopened the ticket.

**Comment by idealkindom** [comment]
> I may be able to help with fixing the display of subscripts, however, it's not clear to me what exactly is the problem which has been observed, and in what way it is different from the previous version which didn't have the problem. If someone would post screenshots showing the observed and desired behavior, that would be very helpful for moving this issue forward.
> 
> @idealkindom You might work around issues about subscripts represented by underscores, by writing variables with explicit subscripts, e.g. `ΔP[r[1]]` or `ΔP[r, 1]` (not sure what the intended notation is).

OK，I pasted the code,which adding in what you proposed as below:
```
ΔP_r;print(ΔP_r,"=",4.6,".")$
ΔP_r1;print(ΔP_r1,"=",2.3,".")$
ΔP_r[1];print(ΔP_r[1],"=",1.2,".")$
P_r;P_r:4.6;print('ΔP_r,"=",4.6,".")$
P_r1;P_r1:2.3;print('ΔP_r1,"=",2.3,".")$kill(all)$
P_r[1];P_r[1]:1.2;print('ΔP_r[1],"=",1.2,".")$kill(all)$
P[r[1]];P[r[1]]:1.2;print('ΔP[r[1]],"=",1.2,".")$kill(all)$
P[r,1];P[r,1]:1.2;print('ΔP[r,1],"=",1.2,".")$
```
Also I attached the screenshot in different version of WxMaxima. If I didn't recall it wrong, I remembered that Maxima 5.43.2 bundled with WxMaxima 19.05.7 is the last version I got consistent rendering of Math especially for subscripts. The download link can be find at Sourceforge:https://sourceforge.net/projects/maxima/files/
<img width="960" alt="Snipaste_2024-08-23_10-59-38" src="https://github.com/user-attachments/assets/95eadd3e-7c11-4226-aa8d-4e0ba5e545cd">

**Comment by idealkindom** [comment]
> I may be able to help with fixing the display of subscripts, however, it's not clear to me what exactly is the problem which has been observed, and in what way it is different from the previous version which didn't have the problem. If someone would post screenshots showing the observed and desired behavior, that would be very helpful for moving this issue forward.
> 
> @idealkindom You might work around issues about subscripts represented by underscores, by writing variables with explicit subscripts, e.g. `ΔP[r[1]]` or `ΔP[r, 1]` (not sure what the intended notation is).

Referring to the screenshot I posted, how do you feel about the difference? For me, the rendering in the latest WxMaxima looks so wierd.

**Comment by idealkindom** [comment]
> Sorry for the noise; somehow I inadvertently closed this ticket while typing ... There must be some keyboard shortcut which I accidentally hit. Anyway I've completed the comment I was trying to make and reopened t
<img width="960" alt="subscript_prob" src="https://github.com/user-attachments/assets/f1eaaddc-4957-4e96-bb79-29e50f93c530">
[example.zip](https://github.com/user-attachments/files/16721607/example.zip)
he ticket.

I attached another screenshot for example together with the wxmx file and corresponding mac file. Pls chk them.

**Comment by robert-dodier** [comment]
@gunterkoenigsmann @daute I think I see where the changed behavior has occurred and I have a proposed bug fix for it.

OP's examples have quoted subscripted variables, e.g. `'F_s[1]`. Maxima considers these as nounified expressions. This causes PROPERTIES to return `[noun]`, and then the attempt to call `(member '$WXXML_SUBSCRIPTED (cadr (properties x))` causes an error because `(cadr (properties x))` is just `$NOUN`, and `member` expects a list. I believe the bug fix is just to say `(cdr (properties x))`. Here is a patch for that.
```
$ diff -u subscriptp-23-11-0.lisp-original subscriptp-23-11-0.lisp-modified 
--- subscriptp-23-11-0.lisp-original	2024-08-24 10:10:11.126197130 -0700
+++ subscriptp-23-11-0.lisp-modified	2024-08-24 10:20:14.990396163 -0700
@@ -24,7 +24,7 @@
 			 ($get sub-symb '$wxxml_subscript)
 			 )
 		     (ignore-errors (not
-				     (member '$WXXML_SUBSCRIPTED (cadr (properties x))))))))
+				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
 	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
 		  (wxxml-alt-copy-text x)
 		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
```
@idealkindom Here is the modified version of the function SUBSCRIPTP. Please save it to a file and try `load("subscriptp-23-11-0.lisp-modified")` and see if you get the previous behavior.
```
(defun subscriptp (x)
  (unless (symbolp x)
    (return-from subscriptp x))
  (let* ((name ($sconcat x))
	 (pos (search "_" name :from-end t)))
    (when pos
      (let* (
	     ;; sub is the part of x after the "_"
	     (sub (subseq name (+ pos 1)))
	     ;; sub-var is the part of x in front of the "_"
	     (sub-var (subseq name 0 pos))
	     (sub-symb (read-from-string (concatenate 'string "$" sub)))
	     ;; sub-int is the part of x after the "_" converted to integer
	     (sub-int (ignore-errors
			(parse-integer sub))))
	(when (and (and (> (length sub-var) 0) (> (length sub) 0) )
		   (or
		    ($get x '$wxxml_subscripted)
		    (and
		     (or sub-int
			 (eq $wxsubscripts '$all)
			 (= (length sub) 1)
			 (= (length sub-var) 1)
			 ($get sub-symb '$wxxml_subscript)
			 )
		     (ignore-errors (not
				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
		  (wxxml-alt-copy-text x)
		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub)))))))))
```

**Comment by robert-dodier** [comment]
For the record, looks like the call to MEMBER was introduced in c46e537.
```
$ git show c46e53703 -- data/wxMathML.lisp
commit c46e53703060a95ad49f846e57252870e0b97fc6
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Mon Nov 16 06:25:36 2020 +0100

    Better docu and priorities for the autosubscript feature

diff --git a/data/wxMathML.lisp b/data/wxMathML.lisp
index 12dbca4..99c226d 100644
--- a/data/wxMathML.lisp
+++ b/data/wxMathML.lisp
@@ -258,12 +258,17 @@
               (sub-int (ignore-errors
                          (parse-integer sub))))
          (when (and (> (length sub-var) 0)
-                    (or sub-int
-                        (eq $wxsubscripts '$all)
-                        (= (length sub) 1)
-                        (= (length sub-var) 1)
-                        ($get x '$wxxml_subscripted)
-                        ($get sub-symb '$wxxml_subscript)))
+                    (or
+                     ($get x '$wxxml_subscripted)
+                     (and
+                      (or sub-int
+                          (eq $wxsubscripts '$all)
+                          (= (length sub) 1)
+                          (= (length sub-var) 1)
+                          ($get sub-symb '$wxxml_subscript)
+                          )
+                      (ignore-errors (not
+                        (member '$WXXML_SUBSCRIPTED (cadr (properties x))))))))
            (format nil  "<munder altCopy=\"~{~a~}\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
                    (mstring x)
                    (or (get sub-var-symb 'wxxmlword)
```

**Comment by idealkindom** [comment]
> subscriptp-23-11-0.lisp-modified

Thanks Robert. However, I'm wondering do you mean I shall copy the code and save in a txt file with the full name"subscriptp-23-11-0.lisp-modified"

**Comment by idealkindom** [comment]
> @gunterkoenigsmann @daute I think I see where the changed behavior has occurred and I have a proposed bug fix for it.
> 
> OP's examples have quoted subscripted variables, e.g. `'F_s[1]`. Maxima considers these as nounified expressions. This causes PROPERTIES to return `[noun]`, and then the attempt to call `(member '$WXXML_SUBSCRIPTED (cadr (properties x))` causes an error because `(cadr (properties x))` is just `$NOUN`, and `member` expects a list. I believe the bug fix is just to say `(cdr (properties x))`. Here is a patch for that.
> 
> ```
> $ diff -u subscriptp-23-11-0.lisp-original subscriptp-23-11-0.lisp-modified 
> --- subscriptp-23-11-0.lisp-original	2024-08-24 10:10:11.126197130 -0700
> +++ subscriptp-23-11-0.lisp-modified	2024-08-24 10:20:14.990396163 -0700
> @@ -24,7 +24,7 @@
>  			 ($get sub-symb '$wxxml_subscript)
>  			 )
>  		     (ignore-errors (not
> -				     (member '$WXXML_SUBSCRIPTED (cadr (properties x))))))))
> +				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
>  	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
>  		  (wxxml-alt-copy-text x)
>  		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
> ```
> 
> @idealkindom Here is the modified version of the function SUBSCRIPTP. Please save it to a file and try `load("subscriptp-23-11-0.lisp-modified")` and see if you get the previous behavior.
> 
> ```
> (defun subscriptp (x)
>   (unless (symbolp x)
>     (return-from subscriptp x))
>   (let* ((name ($sconcat x))
> 	 (pos (search "_" name :from-end t)))
>     (when pos
>       (let* (
> 	     ;; sub is the part of x after the "_"
> 	     (sub (subseq name (+ pos 1)))
> 	     ;; sub-var is the part of x in front of the "_"
> 	     (sub-var (subseq name 0 pos))
> 	     (sub-symb (read-from-string (concatenate 'string "$" sub)))
> 	     ;; sub-int is the part of x after the "_" converted to integer
> 	     (sub-int (ignore-errors
> 			(parse-integer sub))))
> 	(when (and (and (> (length sub-var) 0) (> (length sub) 0) )
> 		   (or
> 		    ($get x '$wxxml_subscripted)
> 		    (and
> 		     (or sub-int
> 			 (eq $wxsubscripts '$all)
> 			 (= (length sub) 1)
> 			 (= (length sub-var) 1)
> 			 ($get sub-symb '$wxxml_subscript)
> 			 )
> 		     (ignore-errors (not
> 				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
> 	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
> 		  (wxxml-alt-copy-text x)
> 		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
> 		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub)))))))))
> ```

Yes, Robert, Great job. I stored your code in a txt file with your named name, which is loaded before I perform the calculation. I'm so glad to find the subscripts are descently displayed now.
However, there is another problem maybe you could lend a help,i.e, with the same wxmx file I uploaded before, there are some"=" sign can not be displayed. I don't know whether it's due to the font setting I made. I set all the fonts in Times New Roman.
Also with the same wxmx file, when I tried to copy some part of the results to word as MathML, the superscripts like squre number "2" are lost.
You could find 3 attached figs, the last 2 depict the problem of lost "=" and lost squre number in word.
<img width="393" alt="Fig 3 copied MathML to word with square number lost" src="https://github.com/user-attachments/assets/dc91bc08-1efe-449f-a3c8-d00dabc6e5d6">
<img width="434" alt="Fig 2 results rendered with equal sign lost" src="https://github.com/user-attachments/assets/2534200d-5c96-4742-9bab-19ca7f124d05">
<img width="463" alt="fig 1 the load" src="https://github.com/user-attachments/assets/5ba5eae5-9c6b-4012-b54a-72c111139aa9">

**Comment by idealkindom** [comment]
> @gunterkoenigsmann @daute I think I see where the changed behavior has occurred and I have a proposed bug fix for it.
> 
> OP's examples have quoted subscripted variables, e.g. `'F_s[1]`. Maxima considers these as nounified expressions. This causes PROPERTIES to return `[noun]`, and then the attempt to call `(member '$WXXML_SUBSCRIPTED (cadr (properties x))` causes an error because `(cadr (properties x))` is just `$NOUN`, and `member` expects a list. I believe the bug fix is just to say `(cdr (properties x))`. Here is a patch for that.
> 
> ```
> $ diff -u subscriptp-23-11-0.lisp-original subscriptp-23-11-0.lisp-modified 
> --- subscriptp-23-11-0.lisp-original	2024-08-24 10:10:11.126197130 -0700
> +++ subscriptp-23-11-0.lisp-modified	2024-08-24 10:20:14.990396163 -0700
> @@ -24,7 +24,7 @@
>  			 ($get sub-symb '$wxxml_subscript)
>  			 )
>  		     (ignore-errors (not
> -				     (member '$WXXML_SUBSCRIPTED (cadr (properties x))))))))
> +				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
>  	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
>  		  (wxxml-alt-copy-text x)
>  		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
> ```
> 
> @idealkindom Here is the modified version of the function SUBSCRIPTP. Please save it to a file and try `load("subscriptp-23-11-0.lisp-modified")` and see if you get the previous behavior.
> 
> ```
> (defun subscriptp (x)
>   (unless (symbolp x)
>     (return-from subscriptp x))
>   (let* ((name ($sconcat x))
> 	 (pos (search "_" name :from-end t)))
>     (when pos
>       (let* (
> 	     ;; sub is the part of x after the "_"
> 	     (sub (subseq name (+ pos 1)))
> 	     ;; sub-var is the part of x in front of the "_"
> 	     (sub-var (subseq name 0 pos))
> 	     (sub-symb (read-from-string (concatenate 'string "$" sub)))
> 	     ;; sub-int is the part of x after the "_" converted to integer
> 	     (sub-int (ignore-errors
> 			(parse-integer sub))))
> 	(when (and (and (> (length sub-var) 0) (> (length sub) 0) )
> 		   (or
> 		    ($get x '$wxxml_subscripted)
> 		    (and
> 		     (or sub-int
> 			 (eq $wxsubscripts '$all)
> 			 (= (length sub) 1)
> 			 (= (length sub-var) 1)
> 			 ($get sub-symb '$wxxml_subscript)
> 			 )
> 		     (ignore-errors (not
> 				     (member '$WXXML_SUBSCRIPTED (cdr (properties x))))))))
> 	  (format nil  "<munder altCopy=\"~A\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
> 		  (wxxml-alt-copy-text x)
> 		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub-var)))
> 		  (format nil "<mi>~a</mi>" (wxxml-fix-string (format nil "~A" sub)))))))))
> ```

Hey,Robert. Thks a lot. Pls Forget the lost"=" problem because I checked the wxmx and mac file, maybe the reason is the code was changed due to some accidental operation. However, the loss of square number during paste of copied MathML to word really could be reproduced.

BTW, I revised the wxMaxmia ini.mac to load the code you provided so that it could automatically load it to perform the rendering.THKS to your great job.

**Comment by idealkindom** [comment]
> For the record, looks like the call to MEMBER was introduced in [c46e537](https://github.com/wxMaxima-developers/wxmaxima/commit/c46e53703060a95ad49f846e57252870e0b97fc6).
> 
> ```
> $ git show c46e53703 -- data/wxMathML.lisp
> commit c46e53703060a95ad49f846e57252870e0b97fc6
> Author: Gunter Königsmann <gunter@peterpall.de>
> Date:   Mon Nov 16 06:25:36 2020 +0100
> 
>     Better docu and priorities for the autosubscript feature
> 
> diff --git a/data/wxMathML.lisp b/data/wxMathML.lisp
> index 12dbca4..99c226d 100644
> --- a/data/wxMathML.lisp
> +++ b/data/wxMathML.lisp
> @@ -258,12 +258,17 @@
>                (sub-int (ignore-errors
>                           (parse-integer sub))))
>           (when (and (> (length sub-var) 0)
> -                    (or sub-int
> -                        (eq $wxsubscripts '$all)
> -                        (= (length sub) 1)
> -                        (= (length sub-var) 1)
> -                        ($get x '$wxxml_subscripted)
> -                        ($get sub-symb '$wxxml_subscript)))
> +                    (or
> +                     ($get x '$wxxml_subscripted)
> +                     (and
> +                      (or sub-int
> +                          (eq $wxsubscripts '$all)
> +                          (= (length sub) 1)
> +                          (= (length sub-var) 1)
> +                          ($get sub-symb '$wxxml_subscript)
> +                          )
> +                      (ignore-errors (not
> +                        (member '$WXXML_SUBSCRIPTED (cadr (properties x))))))))
>             (format nil  "<munder altCopy=\"~{~a~}\"><mrow>~a</mrow><mrow>~a</mrow></munder>"
>                     (mstring x)
>                     (or (get sub-var-symb 'wxxmlword)
> ```

Hey,Robert. I make it clear that the red square notified problem in the fig I attached arouse from the symbol of approx, which you could input in wxMaxima with Esc+a and choosing from the pull list of symbol.
I retested the older version of WxMaxima on this again and it proved to display the approc symbol rightly. What' more, the copy-paste to word of MathML doesn't lose the square number.
<img width="420" alt="Fig5" src="https://github.com/user-attachments/assets/2a2baf30-647d-4b44-86d2-44234ead6372">
<img width="530" alt="FIg 4" src="https://github.com/user-attachments/assets/0c512436-5082-46d6-8385-3301430b5d87">

**Comment by robert-dodier** [comment]
Need to circle back to #1584 and close it after building a new version with proposed patch.

**Comment by robert-dodier** [comment]
I pushed commit [ a22f5a3 ] which fixes the problem described here.
