### ISSUE TITLE
Pasting inside square bracket, and insert Geek symbols doesn't as it should.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1809]
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/f8d823e0-5249-4155-af45-4302f24edc35)
 I can't copy the output text or the input line.  It comes out blank. So I needed to do a picture capture here.

**Comment by richardgobeli** [comment]
I got today's build.  The insert of Greek Letters into normal text lines started to work with this build.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4bcf2127-4ee1-46f5-a797-031730a6ef43)
I copied u,v and I can't paste it insert the square bracket or round brackets.  I can't insert the inside of brackets with the esc mu keys.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/c364ff19-2c69-44a7-8ede-cb505dce7b2d)

**Comment by gunterkoenigsmann** [comment]
That was the thing I was of when trying to get rid of all the warnings from static code analysis tools: it got rid of hard-to-reproduce crashes. But big changes also introduce bugs.

**Comment by richardgobeli** [comment]
This also now looks like it works.

**Comment by gunterkoenigsmann** [comment]
Should be resolved by 3db0287febb05d9af02d3b80544c31756fb96f56.
