### ISSUE TITLE
Right and left arrow keys not working when editing a cell (Windows)

### ISSUE THREAD

**Issue by Binarus** [wxMaxima-developers/wxmaxima#1811]
Dear all,

I've got an issue with wxMaxima 23.05.1 on Windows 10 x64 Enterprise: When editing any line in a cell, the right and left arrow key do not work. Therefore, I have to use the mouse whenever I want to edit anything.

If it matters, the Maxima version is 5.47.0.

I happen to have a Linux system at my hands where that problem does not appear. On the Linux system, the wxMaxima version is 20.12.1. However, I don't believe that the problem is version related. Instead, I believe it depends on the OS.

I apologize if that problem has been addressed already and if I have missed it. I have put a fair amount of time into trying to find a solution without avail, though.

Thanks in advance, and best regards,

Binarus

**Comment by Binarus** [comment]
Thank you very much!

For me, the version that you have linked does not show the problem described above any more.

However, it seems that it introduces another problem: Normally, each cell and its output are marked by a sort of "brace" at the left side. In the version you have linked, that "brace" is missing for every cell except the one the cursor is in. Plus, if I move the mouse pointer outside the cell that contains the cursor, the "brace" for that cell partly vanishes. To be precise, the part that marks the output vanishes (and does not reappear when I move the mouse pointer back into that cell). I have to click again into that cell to make the "brace" reappear completely.

But that's just for your interest. I believe that I shouldn't open an issue for it because I haven't observed it in an official release.

Thanks again, and best regards,

Binarus

**Comment by gunterkoenigsmann** [comment]
I am not unhappy if issues are reported: Without that it is often hard to find them - or, if I find them, sometimes to fix them as sometimes one needs several pairs of eyes until one finds out what triggers it => Will look into that issue in the next few days.

**Comment by gunterkoenigsmann** [comment]
Ok... ...`git bisect` tells me:

The first bad commit could be any of:
5801416c33337d1160529cdcc8ee2fcfc61acdfa
e09b12a8fff3a8cf1204c05e549d1b3de20720e0
ee83a0928dcca81c4a341e392bb11ec33887745c
We cannot bisect more!

**Comment by gunterkoenigsmann** [comment]
That bisect wasn't really helpful: The problem is part of a >700 line restructuration.

**Comment by Binarus** [comment]
If I understand correctly, that problem in the new version appears on Linux as well?

Thank you very much for your hard work; wxMaxima and Maxima rock! Too sad that I am not able to help you with the fix (except by testing).
