### ISSUE TITLE
Ugly integral sign

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1812]
What happened to the integral sign?
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/e883b313-ff62-4b3d-9ddc-790309509c1f)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/8c3a0621-9001-4f9a-ac28-391b9d5f05b2)
I also can't copy any output formulas like the build_info.  
I needed to do a screen capture.

- [ ] https://github.com/wxMaxima-developers/wxmaxima/issues/1815
- [ ] https://github.com/wxMaxima-developers/wxmaxima/issues/1816

**Comment by gunterkoenigsmann** [comment]
The integral sign is a spline. How it looked was highly dependent on the screen resolution and the zoom factor. I corrected that and then tried to find  points that make up a spline that at least half-way looked like a integral sign:

````
    wxPoint points[7] = {
      {sign.x + m_signWCenter + 2 * (m_signWidth / 4),
       sign.y - (m_signHeight - Scale_Px(1)) / 2 + m_signWidth / 4},
      {sign.x + m_signWCenter + m_signWidth / 4,
       sign.y - (m_signHeight - Scale_Px(1)) / 2},
      {sign.x + m_signWCenter, sign.y - (m_signHeight - Scale_Px(1)) / 2 +
       2 * (m_signWidth / 4) + Scale_Px(.35)},

      // The line
      {sign.x + m_signWCenter + Scale_Px(.5), sign.y},

      // Bottom Decoration
      {sign.x + m_signWCenter, sign.y + (m_signHeight - Scale_Px(1)) / 2 -
       2 * (m_signWidth / 4) + Scale_Px(.35)},
      {sign.x + m_signWCenter - m_signWidth / 4,
       sign.y + (m_signHeight - Scale_Px(1)) / 2},
      {sign.x + m_signWCenter - 2 * (m_signWidth / 4),
       sign.y + (m_signHeight - Scale_Px(1)) / 2 - m_signWidth / 4}};
````
Really happy with that outcome I am not => will one day to find better points, but would be happy if anybody else did before me.

**Comment by gunterkoenigsmann** [comment]
The copy issue I cannot reproduce with the current nightly build. I *did* resolve a copy issue a few days back and for a few days the nightly build wasn't working as maxima wouldn't build => that issue might be resolved in the code, already.

**Comment by richardgobeli** [comment]
The copy output now works.

Here is the result when the screen is enlarged to the point where the output goes past the right edge of the screen.
I then make the screen smaller and now the output is messed up.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/3bbde886-a09f-4424-bf6c-2e059c6aa805)
This is before enlarging past edge.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/f4a892f0-5dcd-435f-aaef-8d3632d5c3d5)
(%o3)	build_info(version="branch_5_47_base_431_ge024c7557_dirty",timestamp="2023-10-05 23:54:01",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",maxima_userdir="C:/Users/Richard.000/maxima",maxima_tempdir="C:/Users/Richard.000/AppData/Local/Temp",maxima_objdir="C:/Users/Richard.000/maxima/binary/branch_5_47_base_431_ge024c7557_dirty/sbcl/2_3_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.10.0_DevelopmentSnapshot_MSW")

**Comment by gunterkoenigsmann** [comment]
Wow... ...that kind of bug is hard to find. Thanks! 
But I believe it will be easy to fix. Will do so this weekend

**Comment by gunterkoenigsmann** [comment]
Wow... ...this was actually two bad bugs that have gone unnoticed for years. Thanks for finding them!

**Comment by richardgobeli** [comment]
I tested the rescaling and discovered this.
The input and output parts of the cell somehow have different scales.
The label spacing is also screwed up.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/6b84b0c3-078e-4618-84f7-78cbe2d6cdc6)
When I do the down arrow it gets corrected.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/acd4c9c5-44c1-4f31-9b3d-6dab409ac80e)
This was a screen shot.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/fd5ff621-154d-4f0f-a788-a52bdb6bf066)
this is copy of build info.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/cdd7a9b9-d525-4dc5-9dca-818b9e6236e6)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4e5aab5c-1dd7-4e95-a58e-95cbc09ce39b)

**Comment by gunterkoenigsmann** [comment]
I have split the new issues into sub-issues - and believe to have already resolved one of them. The other (the vertical spacing) I don't seem to be able to reproduce, though.

**Comment by richardgobeli** [comment]
How was the integral sign displayed before these last changes?   Can you duplicate the integral sign like it was before?

**Comment by gunterkoenigsmann** [comment]
Many fonts offer three characters: The top, the middle and the lower end of the integral sign. Sometimes these parts do not align properly, though. Insl some Fonts you get placeholders, instead.

**Comment by gunterkoenigsmann** [comment]
Insieme fonts they aligned, but only when positioned in a way that wxWidgets didn't detect. And if the font didn't offer them wxWidgets didn't detect that, neither so wxMaxima did render the chars and did some plausibility checks with the result. If that check failed wxMaxima did try to draw Integral signs using a spline and due to am error in the formula did actually do a great job on some systems and zoom factors.

**Comment by daute** [comment]
Maybe an SVG graphic instead of a spline is nicer? Is that possible? E.g. 
https://commons.wikimedia.org/wiki/File:Integral_Sign.svg

**Comment by gunterkoenigsmann** [comment]
Thought about that, too. But in the end that svg file would just contain a spline that hits the Right Points which means: just altering the list of points that make up the Integral should get us the result the SVG file gives. All we need is a good idea how our integral should look like.

**Comment by richardgobeli** [comment]
The position of the integral sign moves up when the scale of the text is made bigger.
This is good at the default scale.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/0ef2f27a-f7aa-46a4-b361-eb525bf1d4f7)
Here I zoomed in to make it bigger. The sign did not get bigger and it looks like it was pinned at the top.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/7eac3a3e-8fe0-4454-b475-5ce01191717a)

**Comment by richardgobeli** [comment]
Looks good now.

**Comment by richardgobeli** [comment]
Can you switch the color from black on a white background and gray on a black background?

**Comment by gunterkoenigsmann** [comment]
I believe that in the next Nightly Build the color will be correct.
