### ISSUE TITLE
Botched LaTeX on Dot Multiplication Symbol with 23.08.0

### ISSUE THREAD

**Issue by LP314159** [wxMaxima-developers/wxmaxima#1817]
I usually create workbooks with the "Hide Multiplication Signs" option enabled.  Exporting these workbooks to HTML creates LaTeX expressions that render correctly with MathJax.

For a change, I decided to enable the "Use Centered Dot Character for Multiplication" option.  This has a nice, clean look.  But when exporting these dot-chacter workbooks to HTML, the LaTeX expressions not render at all in MathJax.

Here is an example.

Using the input "x*y + 3*z" produces the following LaTex output.

With hidden multiplication:  \[3 z\operatorname{+}x y\]

With dot-character multiplication:  \[3\mbox{%default\ensuremath{\cdot}}z\operatorname{+}x\mbox{%default\ensuremath{\cdot}}y\]

The latter LaTeX expression does not render when exported to HTML.

I am using wxMaxima-23.08.0 and MathJax-3.2.2.

Since I have only recently used the dot-character option, I don't know if this problem occured with previous versions.

**Comment by georgtree** [comment]
Hello!
I have the same issue on 24.11.0_DevelopmentSnapshot, I see that it fixed by it is still produces %default\ensuremath{\cdot}
