### ISSUE TITLE
An Arctic Code Vault repository has been compromised

### ISSUE THREAD

**Issue by stephenathel** [wxMaxima-developers/wxmaxima#1823]
Ref. sourceforge.net/p/maxima/patches/96/
has caused many wxMaxima files (*.wxm) to fail

Ref. gawxm/GAwxM/General_relativity/cosmic_history.wxm

The function for matrix inversion, invert() now sees the scale factor, A(t) as possibly imaginary. 

This is probably due to changes in the function ct_coords() within the ctensor module.

The GAwxM repository is about ten years old and it would be a shame if all versions remain compromised
 due to a possibly unnecessary change.

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...that is a report for an issue in an un-merged patch in a different project => mentioned it there and will close it for wxMaxima.
