### ISSUE TITLE
Derivatives now show a product sign in front of every variable

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1825]
I think this will screw up later calculations and substitutions.  There is a product in front of the n and r in the derivative.
I did not see this before because I was using derivabbrev:true, which hides this effect.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/fadc27bf-1993-4dc5-ac23-6e810fd73ac5)
It seems to be coming from the mathlisp part of WxMaxima.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/58a3ed08-938e-43b6-8eda-118fbd2af025)

Xmaxima seems to be OK.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/856e84f3-1331-45cd-b92c-a79d99b40fd7)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/33776a99-99d4-4ec4-a7b5-64781dd576d4)

**Comment by richardgobeli** [comment]
This maybe a problem of the xml code of Maxima.

**Comment by gunterkoenigsmann** [comment]
Resolved with 36e05d45cddf627b51a9e527d1cf6b64111faa2a

**Comment by richardgobeli** [comment]
I see this was only a display issue when the multiply sign was being displayed.  It was hidden when I had the product sign hidden.  I see this fix in branch deriv did not get merged with the main master branch yet.

**Comment by richardgobeli** [comment]
I think you got 1/2 of the issue with the independent variable. The product in the numerator is still there.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/2731b4fe-84af-43cf-90d5-e9711987a194)

**Comment by richardgobeli** [comment]
The derivative of an expression is an operator on the expression and the product in front of the  N(r) is really out of place.  At most, it would convert to a parenthesis around the expression N(r) to show that the derivative operator works on the contents of the parenthesis.  I don't understand your FracCell test so I was not going to attempt a fix.
It should be like this in xmaxima.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/b0a2ff91-32ed-4a54-98c6-4492e04e92b8)
