### ISSUE TITLE
The interface does not display properly when another window overlaps it.

### ISSUE THREAD

**Issue by bztd** [wxMaxima-developers/wxmaxima#1826]
I have compiled wxMaxima v23.08.0 and I am using Openbox on Debian. The issue is that when I drag a window over wxMaxima, the window borders remain drawn, as shown in the image on a dark background. This persists until wxMaxima regains focus. This did not happen with version 22.11.1. I don't know if I need to set an additional configuration or if I did something wrong. I just followed the compilation instructions.

![Captura de pantalla de 2023-10-21 16-38-36](https://github.com/wxMaxima-developers/wxmaxima/assets/117551043/55007dff-82a2-4214-b636-6b6a78824d9f)

**Comment by gunterkoenigsmann** [comment]
That looks like a faulty wxWidgets or display driver to me...

**Comment by bztd** [comment]
I used wxMaxima from the official Debian repository and compiled the source code of wxwidgets and wxMaxima, and in both cases I got that result.
