### ISSUE TITLE
Demo does not show prompt in new line

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1827]
The prompt or cursor is at the end of the last line.
 It should prompt in the next line.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/e32afb59-594e-4b91-904e-c0ce08dde81f)

build.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/b8d24877-fb94-4d02-835e-4245ad479359)

**Comment by gunterkoenigsmann** [comment]
I believe that the demo requests exactly this to happen...

**Comment by richardgobeli** [comment]
This is not right.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4dcc4c75-6052-4b69-a67a-cd0100b0ef5b)
It never did this before. The cursor is at the end the mac line.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/5e127e9c-f968-4aa9-a5d9-5838f19a1394)
next stop.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/3d741a67-256d-403f-9a6b-868ea26591b7)

**Comment by richardgobeli** [comment]
this is using xmaxima. It stops ate the next line with a prompt.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/499ca009-4372-445a-9d5e-b5bed7ba45df)

**Comment by richardgobeli** [comment]
Here shows that Maxima is sending a return and then an underscore for a prompt, WxMaxima is not ending the text line and not showing the underscore for a prompt on the next line.  
It stops with the cursor at the end of the text line.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/7f1cdeed-dbd9-426b-91d7-e0dc93cfadfc)

This is the next line with the same response.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/111d8a90-9d9c-4775-9505-c4121aa8baf9)
