### ISSUE TITLE
Abbreviated diff should have parenthesis when there is a product. XML CODE

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1833]
You can see here that there should be brackets around the product or a sum that is inside the derivative when written as a subscript. ein131R is the substitution of N = R\*Z looks like the R(r) is multiplying the diff, but it really is inside the diff.   I don't know if it is the height of the expression that makes it inside the diff N_r, N_rr, and N_zz.   The actual diff equation is below in the text.  The derivabbrev code is hard to read.  It looks like the copy text does not do the product.  RZ is really R\*Z.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/c3ff7927-3c16-4cf7-a6d1-2a100c342762)
(%i228)	ein131;
(%o228)	-(diff(N,r,1)/r)+N/r^2-diff(N,z,2)-diff(N,r,2)=0
(%i229)	depends([R,ψ],[r],[Z],[z]);
(%o229)	[R(r),ψ(r),Z(z)]
(%i230)	eqN:N=R*Z;
(%o230)	N=R*Z
(%i231)	ein131R:subst([eqN],ein131);
(%o231)	-(diff(R*Z,r,1)/r)+(R*Z)/r^2-diff(R*Z,z,2)-diff(R*Z,r,2)=0
 -->	ein131s:expand(ein131R/(R*Z));
(%o233)	-(diff(R*Z,r,1)/(R*Z*r))+1/r^2-diff(R*Z,z,2)/(R*Z)-diff(R*Z,r,2)/(R*Z)=0

**Comment by gunterkoenigsmann** [comment]
My guess is that in order to make this happen one has to manipulate the left and right binding powers. But that aspect of maxima I definitely am no expert in ;-(

**Comment by richardgobeli** [comment]
I guess this may be OK.  the lbp and rbp are already the highest at 200.
below you can see a product is with parentheses, but with a sum, it does not show parentheses.
 
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1d7c43d6-f3b8-4261-92cf-5ad1e9935f31)
binding powers of other operators in expression.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/cafcad08-ed14-4dc2-a77c-941c67cf20b8)
