### ISSUE TITLE
Can't seem to position cursor at the end of a file to insert.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1840]
It is like it is counting wrong to find the end of the file or display.
It will not let me position the cursor at the end of the last statement.

I need to position before that last statement and then scroll with the down arrow to the end or execute the last statement to get to the end of the file.

This is from yesterday's version.
It must have been a bad load.  My work computer seems to work OK.
Sometimes loading a file, I get the lisp-quiet stuff at the end.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/132d2574-7d42-44e7-bbc0-da8dfd774421)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/167c602b-93a6-4e5e-b099-e52a1570a909)

**Comment by gunterkoenigsmann** [comment]
The cursor position problem is not reproducible on my computer - or I am using the program completely different to you.

Getting lisp-quiet commands at the end looks like a hickup during communication with maxima. Will try to look where that can go wrong...

**Comment by richardgobeli** [comment]
This version today.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/ae700cde-0834-41a8-966d-541c3bb43720)

Sometimes loading a file, I get the lisp-quiet stuff at the end.  This is still happening.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/86d74d66-daf8-4908-bf79-fd31185e594e)

**Comment by TomasRiker** [comment]
Maybe this is the same bug:

Start by evaluating 6 (useless) lines:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/295205/21dc754e-37af-4c3e-80c1-90f1aefea896)

Select the last 5 lines:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/295205/892bc641-9699-482e-a9a9-ae881dfaea2c)

Delete them:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/295205/63914da9-19f2-49cc-8cc6-05764de36ae8)

Click somewhere below the cursor, where the deleted lines were before:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/295205/9d51f8d0-ef0f-4aad-a41b-aef2eb846b97)

The cursor is now in a place where it shouldn't be allowed, and nothing can be typed at that location.

**Comment by richardgobeli** [comment]
Yes, that is the same bug, which happens after some editing of the worksheet.

**Comment by DenisSbragion** [comment]
Hello,

this is just to confirm that I have the same problem. Latest wxMaxima (24.02.2) on an up to date Windows 10, recently installed from scratch.

Bye,

Denis

**Comment by richardgobeli** [comment]
The fix for the https://github.com/wxMaxima-developers/wxmaxima/issues/1911 fixes this issue also.

**Comment by gunterkoenigsmann** [comment]
When that bug arrived I hoped it would provide me with the last few puzzle pieces for finding out where this bug comes from...
