### ISSUE TITLE
Context sensitive help, wxMaxima Help, Maxima Help fails to launch

### ISSUE THREAD

**Issue by Rob8135** [wxMaxima-developers/wxmaxima#1848]
Context sensitive help, wxMaxima Help, Maxima Help fails to launch (all recent wxMaxima 23.xx.xx versions). Please see attached error dialog.
 
![wxMaxima Error - Help](https://github.com/wxMaxima-developers/wxmaxima/assets/152169544/45664a60-33fa-426e-bc6c-ab6071641692)

**Comment by gunterkoenigsmann** [comment]
Unfortunately that is a Bug in Ubuntu: Firefox is now a snap and snaps don't have access to data from other programs, currently.

**Comment by Rob8135** [comment]
Thank you for your reply, Gunter, but ... my understanding of Ubuntu is that it is a Linux distribution. This happened on a Windows 10 (22H2) 64-bit machine. In that instance is the 'Firefox is now a snap' still relevant, and if so, how do I alter the installation or configuration command to use e.g., Edge instead?

**Comment by Rob8135** [comment]
Some additional context: I have wxMaxima 23.11.0 and 20.04.0 installed on the same (Windows 10 (22H2) 64-bit) machine. wxMaxima 20.04.0 interfaces with and displays the wxMaxima, Maxima html help files OK (no error dialog) - using the same (current) version of Mozilla Firefox (120.0.1) - whereas wxMaxima 23.11.0 displays the error dialog I reported above.

**Comment by daute** [comment]
Where do all the escaped quotes(`\"`) come from? Strange. I have now a setup (Win10 & Firefox as default browser) and that does not occur here. Can you try changing the help browser - maybe to 'automatic' (if not selected) or select Firefox (or Edge or Chrome) explicitly?

**Comment by Rob8135** [comment]
Thank you, Wolfgang. The issue was resolved by (in wxMaxima 23.11.0, Edit, wxMaxima configuration menu) switching from 'User specified' to 'Autodetect' for 'Help browser' and I cleared the 'User specified' field (out of an abundance of caution). wxMaxima 23.11.0 and 20.04.0 now happily co-exist, and the wxMaxima, Maxima html help files are again available in both versions. (Firefox is my default browser, and wxMaxima is working OK with Firefox to display the help files). I am happy for this ticket #1848 to be closed.

In answer to your question, the escaped quotes were in the 'User specified' field. Please see attached screenshot. The entire content of that field was: "C:\Program Files\Mozilla Firefox\firefox.exe" -osint -url ""
![wxMaxima_configuration_before](https://github.com/wxMaxima-developers/wxmaxima/assets/152169544/490fa4c8-93aa-415e-9155-83f1ab1de83f)

**Comment by daute** [comment]
Ok, thanks for the feedback, I am closing the bug report now.

I really wonder, how Microsoft got the crazy idea, to use a space character in the **standard path** for executable file names.

**Comment by gunterkoenigsmann** [comment]
If they at least would have done so in the English version and additionally would have used the hash character and some unicode codepoints that would at least have ensured that that case is tested.
