### ISSUE TITLE
This maybe an issue with color on the new integral and sum symbol

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1850]
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/12ddc376-6c2b-4ce2-a919-7bd897d0a666)

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1de2f0bd-0f9c-4753-a84b-af15b704d16e)

**Comment by richardgobeli** [comment]
now the color is different as a default.
I have not tried a new color.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/64660d0e-9d47-45f0-9da0-e74c7d0d6236)

**Comment by daute** [comment]
Now the position is okay - at least I hope so...

![sum-sign](https://github.com/wxMaxima-developers/wxmaxima/assets/10107324/0c6edfb1-cf8f-44de-9653-fa0f8512407b)

Gunter fixed the color issue too.

**Comment by richardgobeli** [comment]
Because the scale was changed from 1/2 to 1/3 on the vertical position, it still moves up by small scale changes.  On large changes, it seems to stay in the correct position.
For the integral symbol, Gunter references the SVG file in the middle so that scaling will not move the position up or down.
This may not matter for this small scale, but one never knows what will happen in many years.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/539a467c-c5f3-4556-b9cd-02a15f50abab)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1b5e4194-7fdb-4f84-9c19-3f51f97e7ba0)
