### ISSUE TITLE
Collapsed cell brackets does not stay collapsed

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1853]
When collapsing some cell brackets in order NOT to be evaluated. They do not stay collapsed, but is re-expanded next time I am evaluating the worksheet or part of the worksheet.

It has been like this for a very long  time - just didn't have time to report - sorry ....

**Comment by richardgobeli** [comment]
Are collapsed cells not to be evaluated? When I collapse an assume command it still gets executed.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1caca4d0-2b26-49e3-a9d2-38b162733522)

**Comment by gunterkoenigsmann** [comment]
Actually I have no idea: I have never used collapsing.

**Comment by richardgobeli** [comment]
What does the Crtl-R do?  
Does the visible cell mean not collapsed cells or just the cells visible in the window?
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/5b94c478-6c61-46e0-8a33-e59e978b5607)

**Comment by ReneSci** [comment]
Could it be made so collapsed cells are not evaluated ?

**Comment by gunterkoenigsmann** [comment]
Another excellent question.

No idea what the correct answer would be or if we should add yet another config option. Normally I dislike having too many config options.

**Comment by richardgobeli** [comment]
So far to disable a cell I put a /*  at the beginning of the input line.

**Comment by gunterkoenigsmann** [comment]
> Could it be made so collapsed cells are not evaluated ?

Will Do so as soon I have time to code.

**Comment by ReneSci** [comment]
It works !!
Thanks a lot :-)
