### ISSUE TITLE
Hidden cells are not saved

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1855]
Should a saved file still copy the hidden cells?

**Comment by gunterkoenigsmann** [comment]
It should.

Are you saving the file to `wxm` or to `wxmx`?

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...might it be that the cells are actually saved, but not restored on loading if the `.wxm` format is used?

**Comment by richardgobeli** [comment]
Thanks

**Comment by gunterkoenigsmann** [comment]
Thanks to you for finding this bug!
