### ISSUE TITLE
lisp-quiet glitches on loading a small wxm file.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1856]
This still seems to be happening about a few times a week.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/a5994bcc-ff1b-4003-8227-647216d53439)
this is the version I have. The collapsed cells are not executed.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/6c20d76f-f8b0-4d80-a451-abfaffd11eb5)

**Comment by daute** [comment]
Concerning execution of collapsed cells: In issue #1853 ReneSci wrote, that collapsed cells should not be evaluated and Gunter programmed this.
I really wonder whats the sense of the 'collapsing-feature'...

What are the `lisp-quiet` issues in your wxm file? If it's not top-secret, can you upload the file in the Github bug report?
Best regards, Wolfgang

**Comment by richardgobeli** [comment]
It does not have anything to do with the file.  For me, it has happened on small files and big files with both extensions .wxm and wxmx.

This was the test file I used for my last Maxima bug report.  Here I added a few lines.  It loaded ok today.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/21faaaa0-f881-47d3-afb2-ffc74beef11e)
Just remove the text extension.
[test.wxm.txt](https://github.com/wxMaxima-developers/wxmaxima/files/13674650/test.wxm.txt)

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...what does the lisp-quiet stuff end with if this bug is triggered?

**Comment by gunterkoenigsmann** [comment]
My current guess (and it only is a guess) is that something isn't properly xml-escaped and sometimes on rare occasions contains a literal tag end...

**Comment by gunterkoenigsmann** [comment]
And does this only happen in `wxm` files, but not on loading `wxmx` ones?

**Comment by gunterkoenigsmann** [comment]
And does this only happen when you double-click a `wxm` file, or also, when you open it from wxMaxima?

**Comment by richardgobeli** [comment]
Here I loaded a good-sized file. with wxmx extension.
It maybe happening the first time I load a file after a new version is loaded.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/bb87c0e7-ab28-4b13-bbf2-8be2b62824af)
This is what it looks like when it does not print the list-quiet stuff.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/49fb1705-430b-4992-a78a-db72cb424790)


The info was taken after the bug showed.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/a2b221eb-b4d9-494a-bd73-5b0825f566e0)

**Comment by richardgobeli** [comment]
I have only opened the files from inside WxMaxima.  I can be either file version wxm or wxmx

**Comment by richardgobeli** [comment]
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1c4289f8-8883-4a78-93fb-579a2f1aa1fd)



This just happened today after the new version was loaded and it occurred on the second time I ran the bug report.
This was not the first time loaded or started.



![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/b7230f0a-5411-46af-aae0-dedbdfe3dbd7)


 The bug report data came after the quiet glitch.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/c95adf45-730c-4712-bd17-ca42e6c38b14)

**Comment by gunterkoenigsmann** [comment]
Have now seen an instance of the problem on my computer. Might it have to do with our "Please wait: Am re-indexing the help file" message?

**Comment by richardgobeli** [comment]
I had also thought about it, but was not sure.

**Comment by gunterkoenigsmann** [comment]
That message hinders the GUI from listening to events. If maxima sends us data that is an event...
...perhaps we should get rid of that message. The only problem is: If we don't tell the user very visibly that we will be not reacting for a minute many users will kill wxMaxima before it starts to react, again...

**Comment by gunterkoenigsmann** [comment]
In theory we could prepare the list of manual keywords in the background and halt wxMaxima's GUI only while we replace the old with the new list...

**Comment by gunterkoenigsmann** [comment]
Resolving this even made wxMaxima's code smaller!

Thanks a lot!
