### ISSUE TITLE
Copy/paste  of a whole cell only takes the initial part

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1857]
If I copy (CTRL-C)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/bf962d2b-f091-482c-87ef-5082487e6b07)

And do CTRL-V
I get:
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/34f22c1d-e50d-4f14-8ac2-4edf37704444)

This one did come with the latest nightly build

**Comment by gunterkoenigsmann** [comment]
I cannot reproduce this on my computer => Either I have managed to fix it accidentally or I would need the offending cell contents as text that I can drag-and-drop into my own worksheet.

**Comment by ReneSci** [comment]
Hmm... it also seems to work now :-)

**Comment by ReneSci** [comment]
Hmm... it also seems to work now :-)
