### ISSUE TITLE
The option to NOT match parentheses is gone?

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1859]
A long time ago I raised an issue asking wxMaxima developers to implement an option to NOT match parentheses in the UI. This was done at the time, but now (version 20.12.1) I cannot find this option. In the Edit/Configure/Worksheet menu there is an option "Match parenthesis in text controls" but it only does half of the job -- it stops inserting the matching parenthesis, but it does not stop highlighting the pair when they are manually entered. How do I configure the UI to do this? Thank you.

**Comment by gunterkoenigsmann** [comment]
I always try to reduce the number of options to the minimum, as I want to avoid the situation inkscape confronts me that the options panel asks me questions I don't know how to answer. But if that option is needed I'll re-add it.

**Comment by tigran123** [comment]
Yes, of course it is needed, otherwise I would not have asked for it in the first place. I am sure it is not only me, but millions of other users would find it more convenient to avoid those useless "auto-suggestions" about the matching parentheses, which only distract attention and add nothing useful, imho. I always disable these things via `set blink-matching-paren off` in `~/.inputrc` for ipython and other programs which use this configuration file.

**Comment by daute** [comment]
I don't saw a commit from Gunter re-adding this feature - but both options *are* there - and working?
Edit->Configure->Worksheet->"Highlight the matching parenthesis" (section "Display")
Edit->Configure->Worksheet->"Auto-insert closing parenthesis" (section "Interaction")
Can we close the issue?

But yes, there are many configuration options, which might confuse users.

**Comment by tigran123** [comment]
Not on my system, see screenshot below:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/1933903/2b652db5-fa67-4b33-87ee-ae1ccab571f1)

**Comment by tigran123** [comment]
I didn't compile it from the source code, I just used the version 20.12.1 which comes with Ubuntu 22.04:

```
$ wxmaxima --version
wxMaxima 20.12.1
$ cat /etc/issue
Ubuntu 22.04.4 LTS \l (\U)
Linux \r on \m \t
```

**Comment by tigran123** [comment]
Thank yo, I know, I have compiled wxMaxima before -- e.g. when I filed that original issue when this feature was implemented. I will compile it and let you know if there are any issues.

**Comment by tigran123** [comment]
Yes, I confirm that everything is fine, the option is there and it works, so I can close the issue. The problem is that Ubuntu 22.04 still has the old version, that's all.
