### ISSUE TITLE
Matrix brackets don't scale

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1870]
I need to rerun each statement to get it to rescale.
I did not try the default brackets for matrices.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/452a9270-c66c-49a7-a05b-69da3efd9ca4)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/42ad6609-1961-40d9-8eaf-180468f5887b)

**Comment by gunterkoenigsmann** [comment]
For me only the first line of the worksheet scales any more. Trying to issue a "git bisect" in order to look what caused this.

**Comment by gunterkoenigsmann** [comment]
The issue I see according to `git bisect` seems to be caused by commit c93e3c9e2c86aa7420c436ab038e14ee3b4bf3d8
