### ISSUE TITLE
Sidebars not functioning

### ISSUE THREAD

**Issue by nchencinski** [wxMaxima-developers/wxmaxima#1875]
The greek, symbols and  general math sidebars do not work on wxMaxima 23.05.1 and my previous version. I ran out of options that I know.

**Comment by gunterkoenigsmann** [comment]
What operating stdo you use? And is the issue that if you press the buttons nothing happens?

**Comment by nchencinski** [comment]
Windows operating system. Yes. I choose greek and it blinks and nothing happens.        Thanks             Norbert Sent from my iPhoneOn Jan 1, 2024, at 9:43 PM, Gunter Königsman ***@***.***> wrote:﻿
What operating stdo you use? And is the issue that if you press the buttons nothing happens?

**Comment by nchencinski** [comment]
I received the message that the case was closed.

I downloaded and installed wxMaxima 23.05.1 the latest version available to
me. I am using Windows 11 (build 2262).
   The Only sidebar that works is Statistics,History and Table of contents.
I uninstalled previous versions.
     Norbert Chencinski

**Comment by gunterkoenigsmann** [comment]
Official releases with bug fixes are very infrequent. But a day after the Maxima project resolved the current build issues https://wolfgang.dautermann.at/maxima/nightlybuild/ offers a version with all the bug fixes since then.

**Comment by nchencinski** [comment]
When will that be?Sent from my iPhoneOn Jan 6, 2024, at 2:09 PM, Gunter Königsman ***@***.***> wrote:﻿
Official releases with bug fixes are very infrequent. But a day after the Maxima project resolved the current build issues https://wolfgang.dautermann.at/maxima/nightlybuild/ offers a version with all the bug fixes since then.

**Comment by nchencinski** [comment]
Hello
      When I try to download version 23.12.0 i always end up with 21.05.2
          Something is not working as it should.
                 Still have the same problem with Sidebars. Same version
                      Sorry to bother you so much

                               Norbert
