### ISSUE TITLE
greek letter side pane right click menu no effect.

### ISSUE THREAD

**Issue by daute** [wxMaxima-developers/wxmaxima#1878]
With commit 1453e4dc1c07c74203c2c85b6a268e73d06ceaa6 I learned, that the symbols side bar has a right click menu.

The greek letters side bar also have one - but it does not work, no change of the checkboxes or displayed symbols if one clicks on the checkboxes.

**Comment by daute** [comment]
Maybe just removing these menus and displaying **all** greek characters unconditionally would be the easiest?

**Comment by gunterkoenigsmann** [comment]
I personally dislike the "I won't show you these characters aa I don't believe you are able to handle it" approach. But the maxima-discuss mailing list insisted on it and even suggested that lookalike characters like I, l, X and x are problematic.

**Comment by gunterkoenigsmann** [comment]
Resolves with 998c8dd3761f948650546d9c4a8fd195b9a304c0.
