### ISSUE TITLE
Search boxes (table of contents, history, unicode side bar)

### ISSUE THREAD

**Issue by daute** [wxMaxima-developers/wxmaxima#1879]
These three sidebars have search boxes. In the history sidebar the 'tooltip' (that one can enter a regex) is not shown.

And maybe just using a regular wxWidgets search box (https://docs.wxwidgets.org/3.0/classwx_search_ctrl.html) would be better? Yes, regular expressions are more powerful, but does a regular user use it?

One might remember, that one did enter something, where one squared a mathematical term - so search for "`^2`"...
Ah - no, in a regular expression "`^`" means the beginning of a line, so one must search for "`\^2`" to find that expression...

**Comment by gunterkoenigsmann** [comment]
For short lists of short text pieces I not sure if regEx search has advantages over a normal text search, too, and see the same disadvantages as you do.

About the wxSearchCtrl I didn't know. But I would tell that with it's two buttons this control is too wide for a sidebar and I don't see the use case for adding these two buttons.

Is the missing tooltip just a missing `SetTooltip()` command?
