### ISSUE TITLE
The wizard genmatrix is a bit confusing.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1880]
The reason it is confusing is the martic is generated from a list of lists.
This is done by the first list being the columns of the first row numbered by i.
But matrices usually use the first number to be the rows and the second index to be the columns.
So the number of the first variable should j for the column and i for the rows.

The second reason is the limits are the width and height and not rows and columns.
I don't know if it was done this way for a reason.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/72d1db0a-9518-40ee-a2d4-5a75f989dbcd)

**Comment by daute** [comment]
Closing the ticket, my commit https://github.com/wxMaxima-developers/wxmaxima/commit/a04f1ee0d53663537808ab7c25d10f07c9146b47 fixed it as requested.

**Comment by richardgobeli** [comment]
Thanks!
