### ISSUE TITLE
Running the new build I get this debugging message.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1881]
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/cdb70016-551f-4dc9-b2e7-50944341c33c)

This is the build I used.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4adecdf2-72c4-40a0-88b6-e517b82df7cf)

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...seems like I change the checkmark of an item with no corresponding entry in the menu I try to change it in. Can you get any hint on which menu that happens with or where that is triggered from?

**Comment by ReneSci** [comment]
I get the same message - right at start-up of wxMaxima even before attempting to do anything:
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/5a01c497-4e68-4d11-bc2a-139a27fa2fd5)

**Comment by ReneSci** [comment]
After pressing "Continue" twice, one can edit the worksheet (inclusive copy/paste)
BUT when I press "SHIFT" + "ENTER" to evaluate an expression, the error message appears again twice:

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/24d30bb7-6a11-4585-9a7e-eac412e539f4)

**Comment by gunterkoenigsmann** [comment]
Hmm... ...since I cannot reproduce this on linux and I found the bug in the only system specific piece of menu code I believe to have resolved the issue now. If not - can any of you produce a symbolic backtrace? Else I will try to review all menu check commands as soon as I can.

**Comment by richardgobeli** [comment]
I keep forgeting how to run the gdb from Cygwin64 terminal.  I will need to write a document this next time and save it.

**Comment by richardgobeli** [comment]
I keep getting this error in the gdb debugger.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/75aca7e9-0028-480a-a278-f32c7ade1fea)

**Comment by richardgobeli** [comment]
This is the backtrace I get after executing the stop command in the wxmaxima debug box.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/af95845a-be91-40c1-a3ec-0a8316a8094c)

**Comment by richardgobeli** [comment]
This does work now.  It only crashed the first time I started It probably needed to run at least one time to fix the bug in the settings.

Thanks.
