### ISSUE TITLE
using Context-Sensitive Help (F1) freezes wxMaxima

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1887]
build_info(version="branch_5_47_base_788_gc39acb24d",timestamp="2024-01-22 13:12:06",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",maxima_userdir="C:/Users/xxx/maxima",maxima_tempdir="C:/Users/xxxx/AppData/Local/Temp",maxima_objdir="C:/Users/xxx/maxima/binary/branch_5_47_base_788_gc39acb24d/sbcl/2_3_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.12.0-DevelopmentSnapshot_MSW")

**Comment by daute** [comment]
Closing this issue. In issue #1888 Rene wrote, that that is solved now too.
