### ISSUE TITLE
The latest Nightly build (2024-01-23) fails on uninstalling the previous version of wxMaxima

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1888]
The previous version installed from the day before:

build_info(version="branch_5_47_base_788_gc39acb24d",timestamp="2024-01-22 13:12:06",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",maxima_userdir="C:/Users/xxx/maxima",maxima_tempdir="C:/Users/xx/AppData/Local/Temp",maxima_objdir="C:/Users/xx/maxima/binary/branch_5_47_base_788_gc39acb24d/sbcl/2_3_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.12.0-DevelopmentSnapshot_MSW")

**Comment by daute** [comment]
Any error messages? Here it asked, if it should uninstall an older version before the installation of the current version  (not that from one day before) and it did it without problems.
Can you uninstall it by yourself (not automatically with a new installation)?

Maybe permission problems? The former version was installed using admin permissions and now not?

**Comment by ReneSci** [comment]
I always have to use "Run as administrator" to install wxMaxima. It normally works like a charm.
First message:
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/eff04920-39c5-44ed-a907-c23310c7c2ea)
Then after "Yes":
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/cc39cd5b-b5bc-4920-a6cb-afa7cb949cad)

Could manually uninstall the build from the day before and install this one

**Comment by daute** [comment]
I think I solved it. I tried to compile the Maxima installer using an older CMake version (included in Ubuntu), that seems to cause the error. Since yesterday the nightly build using a current CMake again and it seems to work now.

**Comment by ReneSci** [comment]
It works now - thanks.
Also, the context-sensitive help function works now :-)

**Comment by daute** [comment]
Thanks, closing that issue.
I documented in the Maxima repo, that older CMake versions might cause problems:
https://sourceforge.net/p/maxima/code/ci/ac414b63de5b2a148b7057bda33ab7fcd395ae8c/
