### ISSUE TITLE
Add option to turn off bracket auto-insertion.

### ISSUE THREAD

**Issue by vext01** [wxMaxima-developers/wxmaxima#189]
It would be nice to have an option to remove preemptive insertion of closing brackets. I find this most annoying!

I am using wxmaxima-11.08.0 and Maxima-5.25.

**Comment by tigran123** [comment]
I disabled the option you mentioned above, but it still highlights the matching parentheses which is quite irritating. (but at least it disabled auto-insertion of parentheses, which is good).
