### ISSUE TITLE
Icons, inappropriate location

### ISSUE THREAD

**Issue by bztd** [wxMaxima-developers/wxmaxima#1892]
When building the flatpak the icons are not installed in the proper location.

They are installed in:
$prefix/share/wxMaxima

when it should be:
$prefix/share/icons/hicolor/128x128/apps/
$prefix/share/icons/hicolor/scalable/apps/

respectively.
​

**Comment by daute** [comment]
Thats already the case.
See commit
https://github.com/wxMaxima-developers/wxmaxima/commit/4f1dbfb6
and the correction of this commit
https://github.com/wxMaxima-developers/wxmaxima/commit/8b0d964d4.
