### ISSUE TITLE
Feature request: make restarting maxima accessible through keyboard

### ISSUE THREAD

**Issue by QMeqGR** [wxMaxima-developers/wxmaxima#1893]
Would it be possible to add a keyboard shortcut to restart maxima? There are times when I'm developing scripts and I end up needing to do that quite a bit. wxMaxima is great! Thank you!

**Comment by gunterkoenigsmann** [comment]
`Ctrl+R` restarts Maxima and re-evaluates all cells. I always use this one.

If that doesn't work out for you: What key combo do you propose for that feature?

**Comment by QMeqGR** [comment]
Thanks for the quick reply. How about Ctrl+m?

**Comment by gunterkoenigsmann** [comment]
Hope you aren't too angry if I try if `Ctrl+Alt+R` feels more logical for this purpose.

**Comment by QMeqGR** [comment]
That works for me. Thanks so much!

**Comment by gunterkoenigsmann** [comment]
Seems like I still have to find a bug before it actually works.
