### ISSUE TITLE
Fontconfig warning

### ISSUE THREAD

**Issue by jimishol** [wxMaxima-developers/wxmaxima#1897]
I am on opensuse tubleweed and use wxmaxima 24.02.0

Upon starting wxmaxima a terminal window pops up and see the warning
`Fontconfig warning: ignoring .UTF-8: not a valid language tag`
It remains the same warning whatever language I choose in options. My /etc/locale.conf contains LANG=el_GR.UTF-8. I have  both
```
/usr/share/X11/locale/el_GR.UTF-8/ and
/usr/lib/locale/el_GR.utf8/ directories.
```

It might affect another annoying bug or feature I experience. Upon every save, a file or identical files are created in my home directory (or in directory from where the wxmaxima is launched-I did not checked) that I occasionally manually delete them.
The names of the files I see now are
```
 ?M-&^?^?嘣 ?^?M-1M-3M-1 ?M-?^?^?M-,ma uses temp directwx
 ?M-,^?M- M-5喾 ?M-#^?^?M-+ ?^?M-#M- M-"ma uses temp dir
 ?M-&嘛 ?^?M-4M-& ?M-'ma uses temp directwxmaxima.ac
```
 and all contains
 
```
# This file allows users to add their own symbols
# to wxMaxima's autocompletion feature.
# If a useful built-in symbol of Maxima is lacking
# in wxMaxima's autocompletion please inform the wxMaxima
# maintainers about this!
# 
# The format of the entries in this file is:
# FUNCTION: myfunction
# OPTION: myvariable
# UNIT: myunit
# Template: mycommand(<expr>, <x>)
```
There is no functional problem but it would be nice if the warning could be fixed, if the files were named correctly and if the last would be created by some option and not forcefully.

**Comment by gunterkoenigsmann** [comment]
And what does wxMaxima answer if you type
```
load("operatingsystem");
getenv("LANG");
```

**Comment by gunterkoenigsmann** [comment]
I believe the current nightly build resolves the issue with the strange files appearing...

**Comment by jimishol** [comment]
Sorry, it is not really a window that opens after launching from some .desktop file. I see this window because i launch specific file from vifm browser by the command
:!wxmaxima %c
So, the terminal or shell? is from the :! part of the command.
The output you asked is
```
(%i2)	load("operatingsystem");
	getenv("LANG");
(%o1)	"/usr/share/maxima/5.47.0/share/contrib/operatingsystem/operatingsystem.mac"

(%o2)	".UTF-8"
```
