### ISSUE TITLE
po4a-translate

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1899]
```po4a``` tells:
```
po4a-translate is deprecated. The unified po4a(1) program is more convenient and less error prone.
```

**Comment by daute** [comment]
Closing this issue. We are using po4a instead of po4a-translate now.

**Comment by cooljeanius** [comment]
> Closing this issue. We are using po4a instead of po4a-translate now.

Is this change backportable to older versions?

**Comment by gunterkoenigsmann** [comment]
I seem to remember that po4a included the translate functionality many years ago so I hope it is. 
With the oldest Ubuntu Ubuntu still supports wxMaxima compiles which might be a good sign.

**Comment by daute** [comment]
Po4a can be used without installation (without admin permissions) too:
https://github.com/mquinson/po4a?tab=readme-ov-file#use-without-installation

Set `PERLLIB` and `PATH` so that it can be found during the cmake-call, for example:
```
PERLLIB=/path/to/po4a-checkout/po4a/lib PATH=/path/to/po4a-checkout:$PATH cmake path-to-wxmaxima-source
```
Best regards, Wolfgang
