### ISSUE TITLE
selective package loading in terminal vs wxmaxima

### ISSUE THREAD

**Issue by QMeqGR** [wxMaxima-developers/wxmaxima#1902]
Sometimes I use maxima in a terminal for simple calculations. When I do I like to adjust the input and output colors by putting the following in my maxima-init.mac:

```
load("alt-display.mac")$
cs(s) := printf(false,"~a[~am",ascii(27),s)$
set_prompt(prefix,cs("1;36"),suffix,cs("0;36"),
                general,cs("0;93"),epilog,cs("00;"));
```

But this conflicts with wxmaxima when it gets loaded. Is there a way I can tell wxmaxima not to load this code?

**Comment by daute** [comment]
First idea: 
Maxima knows the command line parameter `--init-mac=<filename>`. You can configure wxMaxima (Configuration -> Maxima -> Additional parameters for Maxima) to tell Maxima that it should use another (or an empty) file instead, when it is called as a wxMaxima subprocess.

Second idea:
wxMaxima set the Maxima variable `maxima_frontend` to `wxMaxima`. Check this variable in your `maxima_init.mac` and do your settings only, if the variable does not have this value.

Best regards, Wolfgang

**Comment by QMeqGR** [comment]
Thanks!  The first idea works (but it's --init=<filename>).
