### ISSUE TITLE
Search up does not work

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1913]
This is with the Windows nightly build from 2024-05-05 on Windows 11.

Reproduction sequence:
- Create a new document
- Create 3 input cells with just `A` in it and evaluate the cells
- Place the cursor after the ; of the last cell
- Press Ctrl+F, enter A, select up

Observed:
- the A in the last cell is selected, but pressing Find Next does not move the selection up

**Comment by gunterkoenigsmann** [comment]
Resolved with 97b57f595d4cd824f57fd5f9f6ab5836896feec2

**Comment by richardgobeli** [comment]
It no longer wraps around searching down.
Can you make it so it will wrap around in either direction?

**Comment by gunterkoenigsmann** [comment]
I am convinced that I didn't change that code path (which is quite independent from the one used for searching up) - and in my tests wrapping search in downwards direction works => What am I doing differently?

**Comment by gunterkoenigsmann** [comment]
In theory C++ and wxWidgets together should make the whole thing quite machine-independent. I half hope that you need an exact trigger in order to reproduce the problem that doesn't involve the OS version as all other bugs normally require loads of detective work.

**Comment by richardgobeli** [comment]
I checked it.  It does work on the Windows 10 computer.  I just did not go past the Wrapped Search notification window to see that it did wrap around.
Where do I now pick the type of font to use on the build_info output that would be constant spacing?

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/a5bb63c3-8369-4e30-950e-d94475930d8d)

**Comment by gunterkoenigsmann** [comment]
The font settings I am still not entirely sure about.
