### ISSUE TITLE
Reading tab-delimited datafiles

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1920]
I often use maxima/wxMaxima to read tab-delimited data files and is has been working like charm when using

```
Stream : openr(directory(DataFile[1])[1]);
" some loop :" ;
dataLine : readline(Stream);
- "data-handling code"

```

However during some of the latest Nightly Builds the readline() noes not read the TAB-character anymore  :-(

I has to revert back to a build I have on my computer from 2024/01/30 to get it to work

The next build, I have stored on my computer, is 2024/03/20, but this one and later builds contains the above failure.

I would be very pleased if you can help !

Runs wxMaxima on windows 11 / 64 bit

**Comment by ReneSci** [comment]
The problem starts somewhere after build 2024/01/30 inclusive the latest build.

Unfortunately, I have to use the above manual (my own programming) to read the data files as they contain data in a mixed way:

```
/* Length=43.10 */
/* IntTime=30000 */
/* StrobeDelay=10000 */
/* Lamppower=1 */
/* Navg=33 */
/* UTCTime=20240507-143923 */
/* Latitude=nan */
/* Longitude=nan */
/* Speed=nan */
/* Heading=nan */
/* Temp=31.812000 */
189.182373 {tab} 0.427444
189.313156 {tab} 0.427444
189.443924 {tab} 0.427444
.
.

```

**Comment by ReneSci** [comment]
(%i190)	build_info();
(%o190)	build_info(version=""branch_5_47_base_1182_gdc9d6aaaf"",timestamp=""2024-05-23 23:52:16"",host=""x86_64-w64-mingw32"",lisp_name=""SBCL"",lisp_version=""2.4.4"",maxima_userdir=
""C:/Users/xxxxx/maxima"",maxima_tempdir=""C:/Users/xxx/AppData/Local/Temp"",maxima_objdir=""C:/Users/xxx/maxima/binary/branch_5_47_base_1182_gdc9d6aaaf/sbcl/2_4_4"",
maxima_frontend=""wxMaxima"",maxima_frontend_version=""24.05.0_DevelopmentSnapshot_MSW"")

**Comment by daute** [comment]
This seems to be a Maxima issue and should be reported at the Maxima bugtracker, not here.

**Comment by ReneSci** [comment]
is that here ?
https://sourceforge.net/p/maxima/bugs/

**Comment by gunterkoenigsmann** [comment]
Either that or https://sourceforge.net/p/maxima/mailman/maxima-discuss/.

They will definitely ask you for the symptom of the problem, which means: what exactly has changed for you.

**Comment by ReneSci** [comment]
Thanks. I did make a post there :-)

**Comment by ReneSci** [comment]
Arghh...  my colleague has apparently decided to change
"Vertical tab" (ascii 11) with "Horizontal tab" (ascii 9)

Also, the previous versions of maxima/wxMaxima has chaged the display of the string from:

"Old" maxima/wxMaxima:
--------------------------------------------
headerLine : readline(Stream);
"189.184875�22.000000"

map(cint, charlist(headerLine));
[49,56,57,46,49,56,52,56,55,53,9,50,50,46,48,48,48,48,48,48,13]

"New maxima/wxMaxima :
---------------------------------------------
headerLine : readline(Stream);
"189.18487522.000000"

map(cint, charlist(headerLine));
[49,56,57,46,49,56,52,56,55,53,9,50,50,46,48,48,48,48,48,48,13]

------------------
I did not previously include ascii 9 handling in my code together with wxMaxima not displaying
the tab (189.184875�22.000000) anymore - that what did confuse me :-(
Thanks for reminding me on map(cint, charlist(headerLine)) !! - I apologize for bothering you ...

**Comment by daute** [comment]
Closing the issue, not a wxMaxima bug. That the tab did not display as "�" (which is not a tabulator), is maybe an improved UTF-8 support of (wx)Maxima.
