### ISSUE TITLE
Sometimes attempt to place cursor at end of document causes jump to random previous cell

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1938]
I am working with wxMaxima 23.11.0 on Ubuntu, installed via Flatpak.

I have a document which has many cells. Sometimes when I scroll to the end of the document and then click below the last cell, in hope of placing the cursor at the end, the display jumps to a previous cell and puts the cursor there.

I am trying to reproduce the problematic behavior right now and placing the cursor is successful, so I guess it doesn't happen consistently.

**Comment by daute** [comment]
Maybe this is related to issue https://github.com/wxMaxima-developers/wxmaxima/issues/1840
(which should be fixed in recent versions)?

**Comment by robert-dodier** [comment]
I've updated (via Flatpak) to wxMaxima 24.08.0 and I can't reproduce the problem. I'll close this bug accordingly.
