### ISSUE TITLE
elliptic_e(1,1.23) fails

### ISSUE THREAD

**Issue by rfateman** [wxMaxima-developers/wxmaxima#1941]
(%i39)	elliptic_e(1,1.23);
Maxima encountered a Lisp error:
 The value
   ((MPLUS SIMP) 0.822727348982166 ((MTIMES SIMP) 0.16698253315507405 $%I))
 is not of type
   NUMBER
Automatically continuing.

............
build_info(version="5.47.0",timestamp="2023-06-02 20:31:42",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",

-------------------------------------------------------------

**Comment by daute** [comment]
This is an issue of Maxima (what does the mathematics in the background) and should be reported there:
https://sourceforge.net/p/maxima/bugs/

Best regards, Wolfgang

**Comment by rfateman** [comment]
Thanks for your quick response!  I meant to post it to maxima, not wxmaxima.

But while I have your attention:   this command works
:lisp (defun $addone(x)(add x 1))

but if the lisp definition runs over 2 lines, it fails...
:lisp (defun $addone(x)
  (add x 1))

Refusing to send cell to maxima: Mismatched parenthesis

thanks for your work on wxmaxima!!
Richard

**Comment by daute** [comment]
(Concerning the comment about `:lisp`): That is the same as in command line Maxima, there one can not use multiple lines in `:lisp`:

```
%i3) :lisp (defun $addone(x)
Maxima encountered a Lisp error:

 
READ: input stream #<INPUT STRING-INPUT-STREAM> ends within an object

Automatically continuing.
```

For that `to_lisp()` / `(to-maxima)` is required (but it seems, that that does not work properly in wxMaxima, that is correct...). Eg. the following example (in **one** input field) does not work:
```
to_lisp();
(deffun $addone(x)
  (add x 1))
(to-maxima)
```

**Comment by daute** [comment]
Typo from me, sorry, it does work. No double `f` in `deffun`. Thats `defun`!
