### ISSUE TITLE
Downloads page is confusing

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1944]
The downloads page (https://wxmaxima-developers.github.io/wxmaxima/download.html) is confusing. I don't think there's any rationale for that -- it just needs to be more strongly organized.

The large blue buttons call the user's attention but some of them lead to the Maxima Sourceforge project download page and link to older versions while some of them lead to the wxMaxima Github download page and link to newer versions. One couldn't possibly guess that's what's happening. 

A minimal change to clarify somewhat is to just change the text on the blue buttons to match what is actually available there.

Also to move the initial statement "All files released so far are available from Github" to be close to the button for wxMaxima and change the text so that it says "All wxMaxima releases are available from Github".

A less important item -- some of the links for third party installers are pretty far out of date. e.g. the ppa link is several years out of date. Maybe move the out of date links to a section specifically devoted to historical releases, or just cut them entirely.

**Comment by daute** [comment]
I hope, it is clearer now...

**Comment by robert-dodier** [comment]
Thanks, that's great. I'll close this ticket now.
