### ISSUE TITLE
Semicolon in :lisp input causes Lisp error "end of file on string input stream"

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1953]
I'm working with wxMaxima 24.08.0_DevelopmentSnapshot on Ubuntu. 

Looks like the input parser which gathers input for `:lisp` doesn't recognize semicolons which are part of the input. E.g.
```
:lisp (print ";")
```
provokes
```
end of file on #<SB-IMPL::STRING-INPUT-STREAM {1003C88DC3}>
```
I guess the input parser is stripping off comments. I wonder if it's possible to send the whole input, comments and all, to the Lisp processor, which will ignore comments as necessary.

**Comment by daute** [comment]
Hm.
Why is the ";" printed twice? [You see, I am still a Lisp rookie...]

And the (command line) Maxima output is different than Lisp itself (tested: clisp, gcl, ecl):

Lisp itself outputs the ";" two times with quotes:
~~~
$ clisp -q
[1]> (print ";")

";" 
";"
[2]> 
~~~

Maxima omits the quotes in the second output (that's the version included in Ubuntu 20.04, the current Git version does the same):
~~~
$ maxima

Maxima 5.43.2 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.12
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) :lisp (print ";")

";" 
;
~~~

It seems the string is sent to Maxima correctly (as one can see in the XML output), but the returned XML seems different (no XML at all in the Lisp output) compared to `disp(";")$`. (if I test the XML output with ` maxima --init-lisp=path/to/wxMathML.lisp`).

Best regards, Wolfgang
