### ISSUE TITLE
Multiplication sign appears as asterisk instead of centered dot in "Copy as MathML" and then paste into a Word document

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1956]
As reported by @Idealkindom in issue #1942, multiplication signs appear as asterisks instead of centered dot in "Copy as MathML" and then pasting into a Word document.

 See the wxmx file "Diaohuan-GB 50010-2010.wxmx" which I'll attach to this bug report. The wxmx is contained in the zip file "idealkindom-Diaohuan-GB.50010-2010.zip".

Note carefully that *the multiplication signs appear correctly as centered dots in the wxMaxima notebook, but appear as asterisk when copying to Word via "Copy as MathML".*

See also "wxMaxima.problem.20240903.zip" which contains settings exported from wxMaxima which may be relevant to this problem.

Let's focus on *this one problem* in this ticket. If we encounter additional problems, let's *open additional tickets, one for each problem.*

Thanks to everyone for working on this stuff, especially idealkindom, I appreciate your continued help very much.

[wxMaxima.problem.20240903.zip](https://github.com/user-attachments/files/17092227/wxMaxima.problem.20240903.zip)

[idealkindom-Diaohuan-GB.50010-2010.zip](https://github.com/user-attachments/files/17092229/idealkindom-Diaohuan-GB.50010-2010.zip)

**Comment by idealkindom** [comment]
Hey, Robert, you're the one that should be Thanked so much for your perseverance on these bugs hanging on for nearly 4 years as I remember.

**Comment by daute** [comment]
I am pretty sure, I solved this some days ago with commit: https://github.com/wxMaxima-developers/wxmaxima/commit/e1a2d0f58870327b9d709ce4fc8ed57c7e3d5750
But I don't have Microsoft Word here on my developer machine, so I can not verify it and I don't want to close the issue by myself.
Best regards, Wolfgang

**Comment by idealkindom** [comment]
> I am pretty sure, I solved this some days ago with commit: [e1a2d0f](https://github.com/wxMaxima-developers/wxmaxima/commit/e1a2d0f58870327b9d709ce4fc8ed57c7e3d5750) But I don't have Microsoft Word here on my developer machine, so I can not verify it and I don't want to close the issue by myself. Best regards, Wolfgang

Hey, Daute, if it's convenient, do you mind sharing your wxm or wxmx file so I could play to see the result.

I am using 20240921 nightly built Maxima now.
If you have a little free time pls just try with the zip Robert attached above. However, since you have no MS word installed, it's hard to test on your computer.

**Comment by idealkindom** [comment]
> I am pretty sure, I solved this some days ago with commit: [e1a2d0f](https://github.com/wxMaxima-developers/wxmaxima/commit/e1a2d0f58870327b9d709ce4fc8ed57c7e3d5750) But I don't have Microsoft Word here on my developer machine, so I can not verify it and I don't want to close the issue by myself. Best regards, Wolfgang

Oh yes, Wolgang. I have just tested the nightly built maxima of 20240923, the cener-dot can be pasted descently in word now.

Please review the isssue #1952 if you are interested.

Thanks a lot.

Best regards.

**Comment by idealkindom** [comment]
> As reported by @idealkindom in issue #1942, multiplication signs appear as asterisks instead of centered dot in "Copy as MathML" and then pasting into a Word document.
> 
> See the wxmx file "Diaohuan-GB 50010-2010.wxmx" which I'll attach to this bug report. The wxmx is contained in the zip file "idealkindom-Diaohuan-GB.50010-2010.zip".
> 
> Note carefully that _the multiplication signs appear correctly as centered dots in the wxMaxima notebook, but appear as asterisk when copying to Word via "Copy as MathML"._
> 
> See also "wxMaxima.problem.20240903.zip" which contains settings exported from wxMaxima which may be relevant to this problem.
> 
> Let's focus on _this one problem_ in this ticket. If we encounter additional problems, let's _open additional tickets, one for each problem._
> 
> Thanks to everyone for working on this stuff, especially idealkindom, I appreciate your continued help very much.
> 
> [wxMaxima.problem.20240903.zip](https://github.com/user-attachments/files/17092227/wxMaxima.problem.20240903.zip)
> 
> [idealkindom-Diaohuan-GB.50010-2010.zip](https://github.com/user-attachments/files/17092229/idealkindom-Diaohuan-GB.50010-2010.zip)

Hey Robert, I have just tested nightly built maxima of 20240923, with which the results could be rightly copied and pasted to MS word as MathML concerning the display of center-dot muliplication operator.

Here I attached the screenshot.
<img width="657" alt="Snipaste_2024-09-24_18-54-31" src="https://github.com/user-attachments/assets/645fd14a-2640-49da-90d9-d6837b7ca93f">
Also thanks to@daute ,at last together with your hard work, these four-year old bugs are fixed, as I think.

**Comment by robert-dodier** [comment]
Hmm, I rebuilt wxMaxima with the current version (including e1a2d0) and when I open Diaohuan-GB 50010-2010.wxmx, the first time I highlight some stuff and select "Copy as MathML", the copied stuff has centered dots.

However, if I clear the output via Cell >> Remove all Output and then Cell >> Evaluate all Cells, and then highlight and "Copy as MathML", then the copied stuff contains asterisks.

By the way, I am working on Linux and I don't have Word installed, so I am just pasting it as plain text on the console (via `cat > /dev/null`). I can see all the operators and variables that way.

**Comment by idealkindom** [comment]
So Robert just keep your way of fixing. Another issue say #1952 if is in your interest maybe you would have a view on it.

在 2024-09-24 20:39:43，"Robert Dodier" ***@***.***> 写道：


Hmm, I rebuilt wxMaxima with the current version (including e1a2d0) and when I open Diaohuan-GB 50010-2010.wxmx, the first time I highlight some stuff and select "Copy as MathML", the copied stuff has centered dots.

However, if I clear the output via Cell >> Remove all Output and then Cell >> Evaluate all Cells, and then highlight and "Copy as MathML", then the copied stuff contains asterisks.

By the way, I am working on Linux and I don't have Word installed, so I am just pasting it as plain text on the console (via cat > /dev/null). I can see all the operators and variables that way.

**Comment by daute** [comment]
It depends, how 'use centered dot character for multiplication' is configured. When it is set to on (and the cells are re-evaluated) the centered dot is used (in the document AND the MathML export), otherwise the "*".

However, the wxmx file format contains the output too, so that the worksheet can be immediately displayed. If the centered dot was saved there (because it was saved with the centered dot active), the dot will be displayed and will be part of the MathML export (but it seems as an identifier `<mi>·</mi>` not an operator `<mo>·</mo>`, which has no visual effect, because a cursive dot is still a dot...
Wolfgang

**Comment by robert-dodier** [comment]
Oh, I take it back, I was mistaken. I was actually running an older version. With version e0a575 (most recent as of today), I see the centered dot both in the notebook (Diaohuan-GB 50010-2010.wxmx) and in the "Copy as MathML" export. 

I am going to go ahead and close this bug report, since I see the correct behavior and @idealkindom also sees the correct behavior per their previous comment (https://github.com/wxMaxima-developers/wxmaxima/issues/1956#issuecomment-2370935212).
