### ISSUE TITLE
Approximately-equal sign displayed as empty box in stuff copied to MS Word

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1958]
As stated in issue #1942, approximately-equal signs are displayed as empty boxes when copying from a notebook to MS Word.

@idealkindom If you have an example of a notebook and Word document which shows this error, can you attach them to this bug report.

I have looked at this problem and I believe that it has to do with the font that is selected. If it appears that it is not a bug in wxMaxima, we can close this ticket, otherwise we will continue to work on it.

**Comment by idealkindom** [comment]
Hey， the wxmx file I uploaded before contains the usage of approc symbols, I think it's fixed together with double quotes or something else, which can be seen from the screenshot I attached here.
<img width="637" alt="Snipaste_2024-09-25_11-52-08" src="https://github.com/user-attachments/assets/83486084-690b-4906-96f3-b27c454f45df">

**Comment by robert-dodier** [comment]
@idealkindom OK, great, looks like it is working correctly for you. I'll close this bug report.
