### ISSUE TITLE
wxMaxima.pot creation not possible

### ISSUE THREAD

**Issue by NorwayFun** [wxMaxima-developers/wxmaxima#1965]
Hello,
My name is Temuri and I do translation of various opensource projects to Georgian.
File wxMaxima.pot, mentioned for locales (not manual) is not in git tree, nor I found way to generate it.
Any suggetions please?

BR, Temuri

**Comment by yurchor** [comment]
Actually, this file is created when you build wxMaxima. But yes, this can be an obstacle for the new translations.

**Comment by NorwayFun** [comment]
Just compiled it from git source and there's no .pot file anyways..

**Comment by daute** [comment]
Added wxMaxima.pot to Git with commit 7a8fcc0c3cee2006717f16b2136a0d44e33a45d5.
And added instructions to Compiling.md (commit a60d5790b0a5894013a35e90146505176450709b).
