### ISSUE TITLE
Missing files in release

### ISSUE THREAD

**Issue by carlosal1015** [wxMaxima-developers/wxmaxima#1970]
In the latest release, missing files Version-24.11.0.tar.gz, Version-24.11.0.tar.gz.asc
```
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/wxmaxima-developers/wxmaxima/releases/download/Version-24.11.0/Version-24.11.0.tar.gz.asc
```

**Comment by daute** [comment]
Hi,
most of the last releases were made by @gunterkoenigsmann and he usually uploaded a pgp signature of the files; this one by me (@daute). He did not respond to my mail, I hope, he is fine.

You can verify, that these files are **really** the wxMaxima source code, by checking, that the git tag (https://github.com/wxMaxima-developers/wxmaxima/archive/refs/tags/Version-24.11.0.tar.gz) is identical to the released tar.gz and that the release was made automatically by Github ("github-actions released this yesterday") on the release page.

I will add a Windows installer for wxMaxima-24.11.0 soon.

Best regards, Wolfgang

**Comment by mmtung** [comment]
Hello, I hope that the issue with the stale link is resolved soon. Best, Michael

**Comment by daute** [comment]
I can not add a signature with @gunterkoenigsmann's PGP key. And creating a new - untrusted - key now is useless. If you believe, that the release would contain malicious code, without Gunters signature, don't use it.
I added a link to the exact code changes (between the Git tags `Version-24.08.0` and `Version-24.11.0`). And added a Windows installer now.

Best regards, Wolfgang
