### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by IInatas** [wxMaxima-developers/wxmaxima#1974]
Dear Dev Team

I have issues compiling the latest versions of wxmaxima under Manjaro. I tried the AUR as well as "git clone", but the compile process stopped at the same spot.

``` bash
[ 80%] Building CXX object src/CMakeFiles/wxmaxima.dir/dialogs/BinaryNameCtrl.cpp.o
[ 81%] Linking CXX executable wxmaxima
[ 81%] Built target wxmaxima
[ 81%] Generating wxmaxima.zh_CN.html
pandoc: wxmaxima.zh_CN.md: withBinaryFile: does not exist (No such file or directory)
make[2]: *** [info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/build.make:73: info/wxmaxima.zh_CN.html] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1906: info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/all] Fehler 2
make: *** [Makefile:166: all] Fehler 2
```
Do you have suggestions how to proceed from this point ?

regards,
Marcus

**Comment by daute** [comment]
Is `po4a` installed? That is used to create the localized documentation.
Best regards, Wolfgang

**Comment by daute** [comment]
And I am not familiar with Manjaro Linux. It can be a missing dependency? It is Arch based, right? So maybe that package is missing: https://archlinux.org/packages/extra/x86_64/perl-syntax-keyword-try/

Another "solution": If po4a is **not** installed, wxMaxima is build without localized documentation, so maybe uninstalling po4a (probably a broken installation...) might help.

Best regards, Wolfgang

**Comment by IInatas** [comment]
Dear Wolfgang,

thank you for the hint with the perk package it was missing. After installation of the perl-syntax-keyword-try package it worked flawless.

Compiled like charme.

regards,
Marcus
