### ISSUE TITLE
extra asterisks --  d/dx  comes out as d/d*x

### ISSUE THREAD

**Issue by rfateman** [wxMaxima-developers/wxmaxima#1977]
why the asterisks?  Did I set something in my environment?
![image](https://github.com/user-attachments/assets/0a0db91b-e120-4755-94e8-9a2c8c62f209)
 
(%i1)	diff(h(x),x);
displays as  
   
  d
-----*h(x)
d*x

 if I set_display('ascii)  it does not have asterisks.

-------------------------------------------------------------

build_info(version="5.47.0",timestamp="2023-06-02 20:31:42",host="x86_64-w64-mingw32",lisp_name="SBCL",
lisp_version="2.3.2",maxima_userdir="C:/Users/fatem/maxima",maxima_tempdir="C:/Users/fatem/AppData/Local/Temp",
maxima_objdir="C:/Users/fatem/maxima/binary/5_47_0/sbcl/2_3_2",maxima_frontend="wxMaxima",
maxima_frontend_version="23.05.1_MSW")
-------------------------------------------------------------

**Comment by daute** [comment]
Maybe something (wrong) with the options 'Use centered dot character for multiplication' and/or 'Hide multiplication signs if possible'. 
Does it work with the recent release (24.11.0)? I was not able to reproduce it with this version.
Best regards, Wolfgang

**Comment by rfateman** [comment]
Hi Wolfgang ..
The bug disappears in 24.11.0_DevelopmentSnapshot.
Actually, I see that I can fix this in the 23.. version .. but I had to
remember that
the settings options are hidden under the label Edit/Configuration /
Display ...  Then, following
your hint --  If I turn off "hide multiplication signs, if possible," it
work correctly.
The 24.11.0 version works with either setting.
Thanks and best wishes for the holidays/ new year!
Richard

**Comment by daute** [comment]
Thanks. So I will close the ticket, if it works with the recent release (and there is a workaround for older releases).

Best regards, Wolfgang (& also best wishes for X-mas and the new year)
