### ISSUE TITLE
Unicode characters throw wxMaxima for a loop

### ISSUE THREAD

**Issue by rfritz** [wxMaxima-developers/wxmaxima#204]
On my system, if I enter a non-ascii character in a Maxima command line, Maxima accepts it. But wxMaxima goes into a loop. For instance, Maxima will accept:
        (%i4) "x̄"=1;
        (%o4)                               x̄ = 1

But type `"x̄"=1` and press shift-enter in wxMaxima and this is the output, repeated over and over:
    Maxima encountered a Lisp error:
     decoding error on stream
     #<SB-SYS:FD-STREAM for "socket 127.0.0.1:61565, peer: 127.0.0.1:4010"
       {100506E7A1}>
     (:EXTERNAL-FORMAT :ASCII):
       the octet sequence (204) cannot be decoded.
    Automatically continuing.
    To enable the Lisp debugger set _debugger-hook_ to nil.

**Comment by s-m-h** [comment]
where do I place the .sbclrc file on a windows 7 computer. I can confirm that on my CentOs system the method described by andrejv works, but for some reason the wxMaxima 15.04.0 on windows still does encounters lisp errors, although I put the file into the users home directory

**Comment by gunterkoenigsmann** [comment]
If anybody finds it out out I will put this information into the manual.

Am 12. Juni 2015 19:19:12 MESZ, schrieb s-m-h <notifications@github.com>:
>where do I place the .sbclrc file on a windows 7 computer. I can
>confirm that on my CentOs system the method described by andrejv works,
>but for some reason the wxMaxima 15.04.0 on windows still does
>encounters lisp errors, although I put the file into the users home
>directory
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/204#issuecomment-111563684

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by andrejv** [comment]
The .sbclrc file should be placed in your home directory. Where exactly that is depends on some variables so I can't say exactly where it is. You can find out by enetering

    :lisp (user-homedir-pathname)

but this should not be the first input in a wxmaxima session.

**Comment by s-m-h** [comment]
Even with the file in the place mentioned in wxMaxima using the above command I get the following output for
```
:lisp (sb-impl::default-external-format)
CP1252
```

**Comment by andrejv** [comment]
Another way to get the name of the file is

    :lisp (sb-impl::userinit-pathname)

**Comment by s-m-h** [comment]
Hi andrejv,
I used maxima for a second, apperently the syntax is wrong and maxima prints the warnings of parsing the .sbclrc. 
the working contents of the .sbclrc is
´´´
(setf sb-impl::*default-external-format* :utf-8)
´´´
I found this here:
https://github.com/snmsts/roswell/issues/5
Thanks for the quick response!!!
