### ISSUE TITLE
Changelog on website

### ISSUE THREAD

**Issue by dilijev** [wxMaxima-developers/wxmaxima#300]
Since this project doesn't use semantic versioning, it is difficult to tell what has changed and how much has changed between versions. Between some releases, the changes are fairly sparse.

I think a changelog listing major changes would be helpful. It doesn't need to be particularly retroactive, but starting from the gap between the previous release and the next release would be good.

**Comment by gunterkoenigsmann** [comment]
Did try to summarize the changes since the last version. Don't like the idea of maintaining two changelogs. But perhaps a link from the website to the ChangeLog file would do, too.

**Comment by dilijev** [comment]
Or AJAX to load the changelog file into the website.


Sincerely,
Doug Ilijev
