### ISSUE TITLE
wxMaxima requires liblzma in MacOS X 10.8

### ISSUE THREAD

**Issue by mardukbp** [wxMaxima-developers/wxmaxima#475]
I installed the latest version of wxMaxima in a fresh install of MacOS X 10.8. On double click the program crashed. The error report indicated that it could not find `liblzma.5.dylib` in `/usr/lib`. I [installed](http://macpkg.sourceforge.net/) the library and problem solved.

**Comment by KubaO** [comment]
Lots has changed in the build system since. This issue should be reopened if current builds exhibit this problem.
