### ISSUE TITLE
Getting help for the command at point needs improvement

### ISSUE THREAD

**Issue by mardukbp** [wxMaxima-developers/wxmaxima#485]
With the cursor in a Maxima command pressing F1 opens the help browser in the Index tab and the right pane shows the chapter of the documentation where that command is described. However it is still required to click on Find to go to the anchor.

Moreover, if the name of the command at point is a substring of other command names, the help browser should show the documentation for the exact match.

**Comment by gunterkoenigsmann** [comment]
If this is possible I always pledge for fixing problems at the point they help most applications simultaneously. In the current case this would be yelp, the application that serves as the help browser for gnome and that IMHO could really be equipped with more powerful search facilities.
If the problem can be fixed from the manual I would opt for doing so on maxima's side instead: I am quite comfortable with wxMaxima being non-maxima-version-specific. If it would come with an own maxima manual this would make it incompatible with all maxima versions that don't fit our maxima manual.

**Comment by mardukbp** [comment]
I agree with everything. However, I am in Arch Linux + awesome WM and do not have yelp installed. I believe that the wxMaxima help browser is handled by wxWidgets. I do not think that the points raised in this issue require modification of the Maxima manual. I will investigate what can be done and report back here.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!
If you find a way to impove the help browser wxWidgets uses - virtually hundreds of applications will profit from your work.
Kind regards,

        Gunter.

**Comment by gunterkoenigsmann** [comment]
Took a while. But the current wxMaxima release finally uses the system HTML browser instead.
