### ISSUE TITLE
Opening files

### ISSUE THREAD

**Issue by dpgoldenberg** [wxMaxima-developers/wxmaxima#536]
I'm not sure if this is a bug, but it seems inconsistent with the way other programs behave, at least on a Mac.

If a file is open with a window, the Open command tries to replace the contents of the existing window with that of the new file, instead of creating a new window.  If the existing file has been changed since last being saved, the Open command will first ask if the existing file should be saved, which is good.  

But, I think it would be better if the newly opened file went in a new window.

Thanks,
David

**Comment by KubaO** [comment]
@gunterkoenigsmann Does this still reproduce for you? I classify it as a bug.

**Comment by gunterkoenigsmann** [comment]
Unfortunately I don't have a mac I can test this on..

**Comment by dpgoldenberg** [comment]
I have to admit that I forgot all about this! In wxMaxima 16.04, this is fixed. I have no idea when it was fixed, but thanks!
David

**Comment by KubaO** [comment]
Awesome. Thank you for the confirmation!
