### ISSUE TITLE
Help:Failed to open an image file.Error:tanceID>xmp.iid:70BF

### ISSUE THREAD

**Issue by JohnHuang-China** [wxMaxima-developers/wxmaxima#554]
Error:
E:/Program Files/Maxima-sbcl-5.37.0/share/maxima/5.37.0/share/numericalio/numericalio.mac:1:38:incorrect syntax: parser: incomplete number; missing exponent?
tanceID>xmp.iid:70BF

Here's the report: 
The Maxima bug database is available at
    http://sourceforge.net/tracker/?atid=104933&group_id=4933&func=browse
Submit bug reports by following the 'Add new' link on that page.
The wxMaxima bug database is available at
    https://github.com/andrejv/wxmaxima/issues?direction=desc&sort=created&state=open
Submit bug reports by following the 'New issue' link on that page.
## Please include the following information with your bug report:

wxMaxima version: 15.8.0
Maxima version: 5.37.0
Maxima build date: 2015-08-19 10:45:51
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

Sure that the file is on C: and is able to be opened.

---I tried to use a stream:
s:openr("(the adress)");
---And it returned:
s
Stream [CHARACTER]

Thanks for anyone who gives me a hand!

**Comment by gunterkoenigsmann** [comment]
I can at least try - and have a few theories:

The error message seems to indicate that you are trying to open a image using the numericalio package. In this case a

     show_image("image.png");

should do the trick. If it doesn't I assume that the path to the image contains a character that confuses the lisp your maxima was compiled with. I know this to happen on turkish computers with files in the default user's directory and the default desktop location that is shown as "Documents" in the windows explorer but really is a long path with a few special non ascii-characters inside it. Moving the file to a folder directly on the C: drive that contains only ASCII characters solves this problem. 

If this doesn't help either: Could you give us the exact line of wxMaxima code that causes the problem?

Thanks a lot,

and kind regards,

    Gunter.

**Comment by JohnHuang-China** [comment]
![error](https://cloud.githubusercontent.com/assets/13872416/9538947/e7ff26a0-4d7c-11e5-802d-b76d07db427f.png)
Like this.

**Comment by gunterkoenigsmann** [comment]
This really is weird.

Two ideas:
 * Does the file work if the escaped backslash (\\) is replaced by a slash (/)?
 * Could you try if a .png file instead of the .jpg one works? There are many flavours of the .jpg format. Not that wxWidgets lacks the support for the specific compression method or something a.jpg is using.

Kind regards,

     Gunter.

**Comment by KubaO** [comment]
`show_image("C:\\wc\\wxmaxima\\data\\maxima.png");` works for me. I assume that whatever caused this has been fixed in the meantime.

**Comment by gunterkoenigsmann** [comment]
The only instance of this that still remains: wWidgets currently doesn't know how to deal with the type of animated gif files gnuplot produces.

**Comment by KubaO** [comment]
That can be fixed by writing an image plugin and just having it with wxMaxima sources. It might be nice. But I hate the mess that gnuplot is. There was a plot package for FORTRAN that at least worked well last time I used it 15 years ago for a uni course, lol.

**Comment by gunterkoenigsmann** [comment]
Maxima invented openplot for this reason.  The conclusion was that gnuplot is quirky. But everyone writing their own gnuplot doesn't tend to be a good solution to that problem.

**Comment by gunterkoenigsmann** [comment]
Perhaps the main problem isn't gnuplot, anyway, but that I have changed Maxima only a year ago to forward error messages from gnuplot to the user....
