### ISSUE TITLE
Changing fonts and font size

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#560]
I have now found out to reproduce the phenomenon that lead me to believe that wxMaxima's input cells support only fixed-width fonts:
- Set the default font to a 12pt font
- Close maxima
- Input some text
- Set the default font to 14pt. The text now is displayed with bigger characters
- Try to select a piece of text.

On both linux and windows the selection now is out-of-sync with the actual width of the characters until  the next start of wxMaxima. A rough guess: Might it be that we don't inform the parser about the change?

**Comment by gunterkoenigsmann** [comment]
Seems like this issue is reproducible only using certain fonts. On my ubuntu box the font "Sans" allows to trigger it.

**Comment by KubaO** [comment]
This may be related to the missing font resolution in before the style overhaul. Now the default font (which is just a request) replaces itself by the actual font it resolved to on the target system, and that font is saved to the configuration. Could you try and see if it still happens?
