### ISSUE TITLE
some text on menus at wxMaxima are not in English

### ISSUE THREAD

**Issue by Mikaa** [wxMaxima-developers/wxmaxima#571]
wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-22 00:07:32

Host type: x86_64-slackware-linux-gnu
System type: 
gcc -O2 -fPIC -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O -falign-functions=4 -DENABLE_UNICODE -DDYNAMIC_FFI -DDYNAMIC_MODULES -I.  /usr/lib64/libreadline.so -lncurses -ldl /usr/lib64/libavcall.a /usr/lib64/libcallback.a  -L/usr/lib64 -lsigsegv -L/usr/lib64 -lc libgnu_cl.a 
SAFETY=0 TYPECODES WIDE_HARD GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.9
libreadline 6.3
libffcall 1.11 GNU C 4.8.4 X86_64
Lisp implementation type: CLISP
## Lisp implementation version: 2.49 (2010-07-07) (built 3635681717) (memory 3651858454)

Like said in the topic some menu text at wxMaxima not in English, also running 'wxmaxima --help' produce (I highlighted foreign word ) text:
'A feature-rich graphical user interface for the computer algebra system maxima
**Gebruik**: wxmaxima [-v] [-h] [-o <str>] [-b] [input file]
  -v, --version     Output the version info
  -h, --help        show this help message
  -o, --open=<str>  open a file
  -b, --batch       run the file and exit afterwards. Halts on questions and stops on errors.'

my locale is LANG=fi_FI.UTF-8 and I'm running Slackware Linux.

**Comment by gunterkoenigsmann** [comment]
We still don't have a translator for your language so if you would be willing to do this job I will provide you with a file containing all the strings that need translating.
Some standardised things like the overall structure of a help message or some menu items common to many programme along with their respective icons are provided by wxWidgets, though. And wxWidgets has been translated. In case that these translations aren't correct feel free to file a bug at the wxWidgets project site.

Kind regards,

  Gunter.

Am 22. September 2015 05:16:04 MESZ, schrieb Mikaa <notifications@github.com>:
>(%i1) wxbug_report()$
>The Maxima bug database is available at
>  http://sourceforge.net/tracker/?atid=104933&group_id=4933&func=browse
>Submit bug reports by following the 'Add new' link on that page.
>The wxMaxima bug database is available at
>https://github.com/andrejv/wxmaxima/issues?direction=desc&sort=created&state=open
>Submit bug reports by following the 'New issue' link on that page.
>Please include the following information with your bug report:
>-------------------------------------------------------------
>wxMaxima version: 15.8.2
>Maxima version: 5.37.2
>Maxima build date: 2015-09-22 00:07:32
>
>Host type: x86_64-slackware-linux-gnu
>System type: 
>gcc -O2 -fPIC -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit
>-Wreturn-type -Wmissing-declarations -Wno-sign-compare
>-Wno-format-nonliteral -O -falign-functions=4 -DENABLE_UNICODE
>-DDYNAMIC_FFI -DDYNAMIC_MODULES -I.  /usr/lib64/libreadline.so
>-lncurses -ldl /usr/lib64/libavcall.a /usr/lib64/libcallback.a 
>-L/usr/lib64 -lsigsegv -L/usr/lib64 -lc libgnu_cl.a 
>SAFETY=0 TYPECODES WIDE_HARD GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED
>TRIVIALMAP_MEMORY
>libsigsegv 2.9
>libreadline 6.3
>libffcall 1.11 GNU C 4.8.4 X86_64
>Lisp implementation type: CLISP
>Lisp implementation version: 2.49 (2010-07-07) (built 3635681717)
>(memory 3651858454)
>-------------------------------------------------------------
>
>Like said in the topic some menu text at wxMaxima not in English, also
>running 'wxmaxima --help' produce (I highlighted foreign word ) text:
>'A feature-rich graphical user interface for the computer algebra
>system maxima
>**Gebruik**: wxmaxima [-v] [-h] [-o <str>] [-b] [input file]
>  -v, --version   	Output the version info
>  -h, --help      	show this help message
>  -o, --open=<str>	open a file
>-b, --batch     	run the file and exit afterwards. Halts on questions
>and stops on errors.'
>
>my locale is LANG=fi_FI.UTF-8 and I'm running Slackware Linux.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/571

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Mikaa** [comment]
Sure I can translate if provided a file, but even starting with 'LC_ALL=en_US.utf8 wxmaxima' does not give menu text in same language. Any hints to get all to same language?

**Comment by gunterkoenigsmann** [comment]
It seems like wxWidgets determines the language by looking at 
environment variables just like you guessed:

    if (!wxGetNonEmptyEnvVar(wxS("LC_ALL"), &langFull) &&
        !wxGetNonEmptyEnvVar(wxS("LC_MESSAGES"), &langFull) &&
        !wxGetNonEmptyEnvVar(wxS("LANG"), &langFull))

Which shell are you using? My guess would be that the variable isn't 
passed to wxMaxima - or that a different language has been set in 
wxMaxima's configuration dialogue. With my bash the following works:

     export LC_ALL=en_US.utf8;wxmaxima

Did find a bug searching for this info anyway: The help message is 
output before the configuration dialogue is read.

---

If you would be willing to help translating: I did put a file with all 
strings that can be translated here:

https://github.com/andrejv/wxmaxima/tree/master/locales/fi.po

It is quite large but some strings clearly are more important than 
others.

Thanks a lot,
and kind regards,

    Gunter.

**Comment by Mikaa** [comment]
my bash is version 4.3.39(1)-release (x86_64-slackware-linux-gnu). For some reason starting with 'LC_ALL=en_US.utf8 wxmaxima' works on my laptop but not on my desktop.

**Comment by gunterkoenigsmann** [comment]
I have the impression that passing variables to applications without using the export command only works sporadically in bash: You can find this form in many blogs around the web. But it has never worked out for me.

     export LC_ALL=en_US.utf8;wxmaxima

should always work, though.

Kind regards,
     Gunter.
