### ISSUE TITLE
Direct PDF export?

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#585]
We cannot ship mikTeX or TeTeX with wxMaxima: They are both too big and too hard to package. But we could either find a magic way to export pdf ourself - or export to TeX and then run a

```
 pdftex -interaction scrollmode
```

showing the result in a new window in the case TeX doesn't complete successfully.

**Comment by KubaO** [comment]
Since we have a complete text layout tree, it shouldn't be too hard to get rudimentary PDF output, as long as one can find a decent PDF output library with few or no dependencies. It'd be a nice feature, but as all such things it takes time...

**Comment by gunterkoenigsmann** [comment]
I am still playing with the thought of trying to convince CMake to do the following:

 - Try to detect if wxPDF is installed on the current system and if it is to link wxMaxima against it.
 - if wxPDF isn't installed: Add all .cpp files in src/wxPDF to the sources list and all .h files in src/wxPDF to the compiler's search path.

wxPDF should be of a license that allows us to bundle it with wxMaxima - and should support the wxDC we use for drawing the worksheet.

**Comment by daute** [comment]
Most operating systems nowadays support 'Print to PDF' without additional third party software. Closing this issue.
