### ISSUE TITLE
New way of getting unicode letters (greek) in gnuplot

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#590]
When using the [ESC] l [ESC] in a string to e.g. a plot label, yields a nice lambda in a wxdraw2D plot but not in a draw2D (windowed) plot.
However: Using {\symbol l} in e.g. a plot label dosen't give a lambda in wxdraw2D but now gives a lambda in drad2D ??

Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Technically both draw and wxdraw should both create a 
maxout_xxxx.gnuplot file that should be identical save the "set 
terminal" command at it's beginning. Both therefore should contain the 
\symbol command or the unicode char. To me this therefore looks like 
gnuplot is supporting different things when using different output 
formats. If this still happens with the current gnuplot release perhaps 
you should report it to the gnuplot project: A packager of a windows 
installer of maxima is free to choose the gnuplot version.

In my experience the clisp installer contains a fairly powerful 
gnuplot. Currently I am thinking if I will try copying it over to the 
directory the sbcl installer has installed its gnuplot into to get a 
fast sbcl maxima with all the gnuplot features.


Kind regards,

   Gunter.

**Comment by ReneSci** [comment]
Sounds as a quite good idea if that can be done. Qestion: how different are
the two gnuplot versions in their interfaces towards wxMaxima and vise
versa, any risk that a lot of error can be introduced ?
Kind regards
Rene'


2015-10-08 7:09 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
Gnuplot is a very feature-full toolkit => The chances that all features work reliably in any given release lies way below 100%. In my experience the same is true for all big software packages. Gnuplot at least has the advantage that it is possible (even if not too easy, sometimes) to switch versions in order to get a certain feature.

The newest gnuplot for example places a border at the top and the left of my plots and I don't know how to get rid of it.

**Comment by ReneSci** [comment]
About the border at the top and the left.  I get the same. 
If I then opens the gnuplot command window and just press [Replot] - the plot goes fine. Hope it gives you a clue.
Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Gnuplot propeerly supports unicode for several years now => closing this issue.
