### ISSUE TITLE
Most of the Mathematical Symbols not usable under windows

### ISSUE THREAD

**Issue by RolandSalz** [wxMaxima-developers/wxmaxima#644]
Most symbols from the table "Mathematcal Symbols" cannot be used under Windows 7, because they are not representable. See my mail "Strange behavior of Mathematical Symbols" to the Maxima mailing list from Dec 4, 2015 for details.

**Comment by KubaO** [comment]
Please confirm whether the issue still occurs under Windows 7 in the nightly build. Thank you!

**Comment by KubaO** [comment]
I don't have a Win 7 VM handy to investigate. Feel free to reopen if this is still an issue for you on the release version, and make sure that you've cleared all settings, i.e. use Registry Editor to remove the entire `Computer\HKEY_CURRENT_USER\SOFTWARE\wxMaxima` key (you can export it to a file first to back it up before you remove it).
