### ISSUE TITLE
How to input Greek symbols

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#710]
I've looked through the documentation and I don't see this specific question. How does one input a symbol comprising Greek characters? e.g. ΔΘΓ as one symbol. And I guess it's also necessary that wxMaxima should be able to display the result. Is it necessary to install jsMath  fonts in order to be able to see the result? Or does it just look nicer if you do?

Do the solutions for the above questions depend on whether one is using Linux, MacOS, or Windows? Does it depend on the Lisp implementation?

Thanks in advance for any light you can shed on these questions.

**Comment by andrejv** [comment]
This is available if the lisp supports Unicode.

To enter a Greek character manually, press the Escape key, type Gamma and Escape again. You need o repeat this for each character.

There is also a Greek characters pane (View->Greek characters from the menu). This enables enering Greek unicode characters with the mouse.

**Comment by gunterkoenigsmann** [comment]
![Uploading wxMaxima.png…]()

Added a screen shot showing the symbols sidebars of wxMaxima.

I have never seen a bug report telling that greek letters didn't work in any installation which I hope is a sign that whatever fonts we use are quite complete in the default setup of most systems. But we have had some bug reports from users using a CJK language that could be traced back to windows installations lacking the parenthesis characters ("(" and ")") - which stuck me as weird: I believed that even if the language of a country doesn't use the standard ASCII characters they would be shipped with windows, anyways.

**Comment by gunterkoenigsmann** [comment]
![wxmaxima](https://cloud.githubusercontent.com/assets/5041537/14935296/520ff068-0ecc-11e6-83ca-ead9396e7b58.png)

**Comment by leo-butler** [comment]
> This is available if the lisp supports Unicode.

The Maxima package unicodedata bridges this gap for non-unicode aware lisps (e.g. gcl). Attached is a screenshot showing this.
![unicodedata](https://cloud.githubusercontent.com/assets/616229/15556858/a91461d2-2295-11e6-9651-372d1509d551.png)

**Comment by gunterkoenigsmann** [comment]
Theoretically yes. But in reality the requirement is slightly less severe: If maxima just pretends that every character which has its 1st bit set is an ordinary letter there is no difference to real unicode support from the user's view. Unfortunately I was able to make maxima currently work fine with sbcl and clisp under windows during an interactive session. But we have yet to find out how to make it do so, too, on loading .mac files.

On linux computers all lisps I have tried seem to support unicode in their default setup.

**Comment by gunterkoenigsmann** [comment]
Even if I cannot reproduce Issue #725 I assume that at least one of maxima's program seems not to handle unicode gracefully. Slightly related: #732 indicates that if the user name contains unicode characters maxima won't be able to create files in maxima_tempdir (which normally contains the username in a way). This is especially bad since maxima might by default be installed into a directory whose name is the local translation of "c:\Programs" - which could contain unicode chars, as well.
