### ISSUE TITLE
gradef with Greek characters doesn't work

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#725]
The following code does not use the information of gradef for Greek characters

derivabbrev:true$
if get('ctensor,'version)=false then load(ctensor)$
ct_coordsys(exteriorschwarzschild,all)$
cv_coords:[T,R,Θ,Φ]$
depends(cv_coords,s)$
gradef(t,s,T)$
gradef(r,s,R)$
gradef(θ,s,Θ)$
gradef(φ,s,Φ)$
cgeodesic(true)$

Please notice that the first and second geodesics are OK, that is, the information in gradef has been used to substitute diff(t,s) with T and diff(t,s,2) with diff(T,s); diff(r,s) with R and diff(r,s,2) with diff(R,s).
The third and fourth geodesics are not OK there has been no substitution at all.
diff(θ,t) should have been substituted by Θ and diff(θ,t,2) by diff(Θ,t);
diff(φ, t) should have been substituted by Φ and diff(φ,t,2) by diff(Φ, t)

Thanks,

Daniel Volinski

build_info(version="5.38.0_dirty",timestamp="2016-04-03 10:09:05",
host="i686-w64-mingw32",lisp_name="CLISP",lisp_version=
"2.49 (2010-07-07) (built on maxima [192.168.43.2])")

**Comment by gunterkoenigsmann** [comment]
On my linux computer it seems to work...

At least the following shows the expected output:
    gradef(θ,s,Θ);
    diff(θ,s);

**Comment by danielvolinski** [comment]
The code I sent you does not work on Windows.
Could you please try the code above on Linux?
Thanks,

**Comment by danielvolinski** [comment]
I closed the issue by mistake, sorry!

**Comment by gunterkoenigsmann** [comment]
Did do so. But perhaps the problem is that I don't know how the output is supposed to look like: For me everything looks fine.

**Comment by danielvolinski** [comment]
The error is in the third and fourth geodesics, the information in gradef is NOT used.
 diff(θ,t) should have been substituted by Θ and diff(θ,t,2) by diff(Θ,t);
 diff(φ, t) should have been substituted by Φ and diff(φ,t,2) by diff(Φ, t)

**Comment by gunterkoenigsmann** [comment]
On 01.06.2016 17:35, danielvolinski wrote:
> The error is in the third and fourth geodesics, the information in
> gradef is NOT used.
> diff(θ,t) should have been substituted by Θ and diff(θ,t,2) by diff(Θ,t);
> diff(φ, t) should have been substituted by Φ and diff(φ,t,2) by diff(Φ, t)
OK... ...this explains why you could be confident that I am able to spot
the problem. But I am still unsure how such a thing can happen:

On my linux computer the result doesn't contain a diff. And the windows
computer treads each unicode chars as one (ascii code 0...127) up to
four (mostly chinese and other symbols from languages that need loads of
them) letters. Will try to get hold of a windows computer tomorrow and
investigate further.

I assume, though, that it is a problem on the maxima, not on the
wxMaxima side and that even the lisp wizards from the maxima-discuss
mailing list will have trouble tracking it down.


Kind regards,

  Gunter.

**Comment by danielvolinski** [comment]
I tried to feed the same code into XMaxima and command line maxima, but they did not accept the Greek characters at all, they only accept Greek literal names. So I think is a problem with WxMaxima
Thanks,
Daniel

**Comment by danielvolinski** [comment]
The lack of diff may be caused by the fact you have derivabbrev:true.

**Comment by danielvolinski** [comment]
I see the same error in the latest version of wxMaxima

wxMaxima version: 16.4.2
Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

**Comment by gunterkoenigsmann** [comment]
Weird: On all windows systems I have managed to get access to either this problem didn't appear - or it was prevented from appearing by some program refusing to send greek letters to maxima which made testing near-to impossible. Seems like greek, russian, chinese and other unicode letters still tend to do strange things on some systems, though...

**Comment by gunterkoenigsmann** [comment]
If you replace the greek characters by "a", "b", "c" and "d" the result doesn't change => seems linke this is a maxima problem that doesn't involve greek characters.
