### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by tinjaca** [wxMaxima-developers/wxmaxima#728]
*********************\* Problem 66 ***************
Input:
"<": wrong number of arguments.
 -- an error. To debug this try: debugmode(true);
Evaluation took:
  3.069 seconds of real time
  1.937500 seconds of total run time (1.515625 user, 0.421875 system)
  [ Run times consist of 0.079 seconds GC time, and 1.859 seconds non-GC time. ]
  63.15% CPU
  1,548 forms interpreted
  2,589 lambdas converted
  5,205,121,040 processor cycles
  115,082,424 bytes consed
  before it was aborted by a non-local transfer of control.

**Comment by gunterkoenigsmann** [comment]
This sounds weird - and requires additional troubleshooting:
We are proud that this isn't user-visible. But the program you are using is split into several projects:  
 - wxMaxima displays the nice 2d maths and provides the gui and the editor while
 -  maxima (which can be found at http://maxima.sf.net) does do the actual math.
 - The lisp that runs maxima and does a lot of background work
...and every of these programs can cause a test failure.

Could you test if maxima shows this error message if it isn't started by wxMaxima but started from a console? If it does I ask you to report the problem to http://maxima.sourceforge.net.

What will be needed, too, as information is the output of 
     build_info();
and
     wxbuild_info();
These show which lisp you are using and the versions of all the affected programs.

Thanks in advance,
and kind regards,

    Gunter.

**Comment by tinjaca** [comment]
Thanks for your answer;
It´s a problem with wxMaxima, because maxima hava no problem.
build_info
(version="5.38.1_5_gdf93b7b_dirty",timestamp="2016-05-13
22:35:09",host="i686-w64-mingw32",lisp_name="SBCL",lisp_version="1.3.5")
nice regards

2016-05-29 10:45 GMT-05:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
Will try to get hold of a windows machine tomorrow and see if I can
reproduce the problem.

Kind regards,

 Gunter.

**Comment by gunterkoenigsmann** [comment]
I wasn't able to reproduce this on any of the windows computers I had access to: I ran

     run_testsuite();

on the following systems:
 - wxMaxima 5.38.0 with the current nightly build of wxMaxima
 - wxMaxima 5.38.1 with the build of wxMaxima it came with
 - The current nightly build of wxMaxima in combination with the current git version of maxima running sbcl and clisp on linux.

...which doesn't mean that the problem isn't there. It just means that I have no means of triggering it and therefore of tracking it down. You can ask the maxima-discuss mailing list, though, if they have an idea what went wrong. They will ask for the output of build_info() again and for all information what this step named "Problem 66" might be: Sometimes by adding additional tests the numbers change. Sorry that I cannot be of more help in the moment.

**Comment by KubaO** [comment]
Just checked. The output is all good on Windows :)

```
No unexpected errors found out of 11,637 tests.
Evaluation took:
  91.272 seconds of real time
  89.984375 seconds of total run time (83.0000000 user, 6.984375 system)
  [ Run times consist of 1.928 seconds GC time, and 88.057 seconds non-GC time. ]
  98.59% CPU
  21,869 forms interpreted
  13,773 lambdas converted
  236,761,705,803 processor cycles
  35,555,273,536 bytes consed
```

```
version="5.43.2",timestamp="2020-01-27 18:44:09",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="1.4.14",maxima_userdir="C:/Users/mxu/maxima",maxima_tempdir="C:/Users/mxu/AppData/Local/Temp",maxima_objdir="C:/Users/mxu/maxima/binary/5_43_2/sbcl/1_4_14",maxima_frontend="wxMaxima",maxima_frontend_version="20.06.6-DevelopmentSnapshot_MSW"
```
