### ISSUE TITLE
Blurry rendering in 1c0e260

### ISSUE THREAD

**Issue by rend3r** [wxMaxima-developers/wxmaxima#749]
Another regression in the master.

My build:

<img width="860" alt="master" src="https://cloud.githubusercontent.com/assets/12601181/17085744/ab532adc-51e8-11e6-8d2e-b2d1a0f254c5.png">

wxMaxima version: 16.4.x-unofficial
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:35:09
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.5

Wolfgang Dautermann's build:

<img width="786" alt="wd_build" src="https://cloud.githubusercontent.com/assets/12601181/17085740/9b512594-51e8-11e6-8465-577def84290f.png">

wxMaxima version: 16.4.2
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:35:09
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.5

The only difference is i am using wxWidgets 3.1.0 but Wolfgang used wxWidgets 3.0.2.

Scaling is changed at Appearance and Personalization > Display dpiscaling (dpiscaling from commandline/run) to Larger - 150%
Screen resolution: 3840x2160
Diagonal: 27''
Windows 7 x64

**Comment by gunterkoenigsmann** [comment]
This might be caused by the manifest of your version of the application not having dpiAware set to  true:
 - Windows tells wxWidgets if your screen begins with a red pixel, then continues with a green one and ends with a blue one so it can make the edges of displayed characters end in the middle of a pixel making them sharper.
 - if a letter extends to the middle of a pixel wxWidgets can make this letter half-black in order to improve the visual quality again
 - and if windows doesn't know that wxWidgets can deal with high-dpi displays it tells wxWidgets that you have a low-resolution screen and then scales the resulting image using antialiassing so the result won't get blocky but blurred instead.
I tried shipping a .manifest file with wxMaxima that seems to be loaded depending on how the application was compiled. But it might be that there are additional steps to do here in order to make a compiler include the manifest. Unfortunately I don't have a windows computer I can experiment with this on so if you have any idea on how to improve this situation I would be very grateful.

Kind regards,
Gunter.

**Comment by rend3r** [comment]
> This might be caused by the manifest of your version of the application not having dpiAware set to true

You are right, but, i think, situation is more complicated.
- http://trac.wxwidgets.org/ticket/16116
In 3.1.0 branch of wxWidgets SetProcessDPIAware() has been removed. That's why Wolfgang's build works fine even if i delete manifest.
- http://csi-windows.com/blog/all/27-csi-news-general/245-find-out-why-your-external-manifest-is-being-ignored
According this article Windows does not honor external manifest sometimes. That's why my build has blurry rendering - i'v just replaced old executable with new one.

How i "fixed" the issue:
- Make new manifest 
[wxmaxima.manifest.txt](https://github.com/andrejv/wxmaxima/files/384539/wxmaxima.manifest.txt)
- Embeded it with Resource Editor
- Renamed resulting exe to something like wxmaxima_new.exe

It's dirty workaround and as you already said, it's better if compiler include the manifest.

**Comment by gunterkoenigsmann** [comment]
> You are right, but, i think, situation is more complicated.
Arrgh!

I don't have a windows machine I can compile things on and the nightly
build that gives me only one shot a day is a horrible way to solve
complicated things => I don't think I am the right person to fix
something that falls into this category for windows.
> 
> How i "fixed" the issue:
> 
>   * Make new manifest wxmaxima.manifest.txt
>     <https://github.com/andrejv/wxmaxima/files/384539/wxmaxima.manifest.txt>
> 
>   * Embeded it with Resource Editor
>   * Renamed resulting exe to something like wxmaxima_new.exe
> 
> It's dirty workaround and as you already said, it's better if compiler
> include the manifest.
There might be an automated way to call a command-line tool that does do
such a thing from the command-line. Don't know if that somehow is a way
one can go.

On the other hand: useful command-line tools that are installed on
systems by default are a truly rare thing on windows and if they are the
right way to go I don't really know...

Kind regards,

 Gunter.

**Comment by rend3r** [comment]
I think I find proper solution to embed custom manifest into resulting exe.

Change current Resources.rc

```
icon0 ICON "maximaicon.ico"
icon1 ICON "wxmac-doc.ico"

#include <wx/msw/wx.rc>
```
to

```
icon0 ICON "maximaicon.ico"
icon1 ICON "wxmac-doc.ico"

#define wxUSE_NO_MANIFEST 1
#include <wx/msw/wx.rc>

#if defined(WX_CPU_AMD64)
1 24 "wxmaxima.manifest"
#elif defined(WX_CPU_X86)
1 24 "wxmaxima64.manifest"
#else
#error "One of WX_CPU_XXX constants must be defined."
#endif
```

That's [disable](http://docs.wxwidgets.org/3.1/page_wxusedef.html) build object from default manifests shipped with wxWidgets and push windres use updated wxmaxima and wxmaxima64 manifests. Default manifests could be find in wx.rc

```
#if defined(WX_CPU_AMD64)
wxMANIFEST_ID 24 "wx/msw/amd64.manifest"
#elif defined(WX_CPU_IA64)
wxMANIFEST_ID 24 "wx/msw/ia64.manifest"
#elif defined(WX_CPU_X86)
wxMANIFEST_ID 24 "wx/msw/wx.manifest"
```

Have no clue how edit autotools scripts - just put wxmaxima.manifest and wxmaxima64.manifest to art directory. No error while windres do its work:

`windres --include-dir /home/denis/wxWidgets-3.1.0/include --include-dir ./../art ./Resources.rc -o Resources.o`

**Comment by gunterkoenigsmann** [comment]
I (hopefully) have implemented everything now, but cannot test it, as I don't own a windows PC. What I don't understand: Do we really need a separate manifest for 64-bit?

**Comment by rend3r** [comment]
>Do we really need a separate manifest for 64-bit?

I'v just blindly copypaste define from wx.rc. The difference between amd64 and wx manifests:

```
@@ -5 +5 @@
-    processorArchitecture="x86"
+    processorArchitecture="amd64"
@@ -16 +16 @@
-            processorArchitecture="X86"
+            processorArchitecture="amd64"
```

But according to [StackOverflow](https://stackoverflow.com/questions/26378957/cant-execute-64-bit-version-of-my-program) we can safely use **processorArchitecture="*"**

I recommend use this manifest

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
      <application> 
          <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
          <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
          <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
          <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
          <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      </application> 
  </compatibility>
  <assemblyIdentity
    version="0.64.1.0"
    processorArchitecture="*"
    name="Controls"
    type="win32"
  />
  <dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="*"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
  </dependency>
  <ms_asmv3:trustInfo xmlns:ms_asmv3="urn:schemas-microsoft-com:asm.v3">
    <ms_asmv3:security>
      <ms_asmv3:requestedPrivileges>
        <ms_asmv3:requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </ms_asmv3:requestedPrivileges>
    </ms_asmv3:security>
  </ms_asmv3:trustInfo>
  <ms_asmv3:application xmlns:ms_asmv3="urn:schemas-microsoft-com:asm.v3">
    <ms_asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>True/PM</dpiAware>
    </ms_asmv3:windowsSettings>
  </ms_asmv3:application>
</assembly>
```
_<dpiAware>True/PM</dpiAware>_ - [description](https://msdn.microsoft.com/ru-ru/library/windows/desktop/dn469266(v=vs.85).aspx)

_requestedExecutionLevel level="asInvoker" uiAccess="false"_ explicitly point to user right

_supportedOS Id_ as it say - Vista, 7, 8, 8.1, 10 support and potentially avoids Program Compatibility Assistant checks.

**Comment by gunterkoenigsmann** [comment]
I added your manifest to the ressources file. Now Wolfgang's nightly windows build returns a warning: 

http://cdash.dautermann.at/viewBuildError.php?type=1&buildid=648

Could you look into it?

Thanks a lot,
and kind regards,

  Gunter.

**Comment by rend3r** [comment]
>I added your manifest to the ressources file.

Did you? Current master does not contain it https://github.com/andrejv/wxmaxima/blob/master/data/wxmaxima.manifest

>Now Wolfgang's nightly windows build returns a warning
>Could you look into it?

I suppose winres supports only 1 include-dir path https://sourceware.org/binutils/docs/binutils/windres.html and your last change in src/Makefile.am broke it
`--include-dir $(srcdir)/../data --include-dir $(srcdir)/../art`

**Comment by rend3r** [comment]
Under MSYS2 build I could not get neither the warning nor winres output now. Winres just does not run to make object.

**Comment by rend3r** [comment]
You can remove copying manifest from wxMaxima.win target in makefile btw

**Comment by gunterkoenigsmann** [comment]
Tried to switch to a minimal manifest: I don't want t set the supported OS as we never tried to actively break anything and therefore might be compatible with XP and with windows 11 (They told us there never will be one. But do you believe them?) 

...Also removed the copying of the manifest.

**Comment by rend3r** [comment]
How look current nighly builds.
standart, shipped with installer:

> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
>   <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
>     <asmv3:windowsSettings
>         xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
>       <dpiAware>true</dpiAware>
>     </asmv3:windowsSettings>
>   </asmv3:application>
>   <description>wxMaxima</description>
> </assembly>

<img width="705" alt="wxm1" src="https://cloud.githubusercontent.com/assets/12601181/23634474/6425a9f6-02db-11e7-9120-c937dbf45479.png">

patched with manifest proposed in https://github.com/andrejv/wxmaxima/issues/749#issuecomment-254055431

<img width="705" alt="wmx2" src="https://cloud.githubusercontent.com/assets/12601181/23634475/6426c778-02db-11e7-8559-a8dc0c1fa6ed.png">

**Comment by rend3r** [comment]
wxMaxima 17.05
<img width="851" alt="wxmaxima1705" src="https://user-images.githubusercontent.com/12601181/29489340-8a71cabc-8527-11e7-8516-55436e6a07d0.png">
Now, I could not get modern visual styles even with updated manifest.

**Comment by rend3r** [comment]
Bumping the issue. Latest nightly is affected - ugly buttons, dropdown lists, etc. Maybe we should open ticket in wxWindjet bug tracker?

**Comment by gunterkoenigsmann** [comment]
The changes on Oct 24 have changed rendering on the windows computer I have access to with Wolfgang's Nightly build. The computer isn't exactly high-dpi, though, so I cannot tell if they actually resolve the issue.

**Comment by rend3r** [comment]
If you told about https://github.com/andrejv/wxmaxima/commit/da7b591c05d9a747b5dfcbb9b7d0508d6df69512 and https://github.com/andrejv/wxmaxima/commit/39a70fbea3e87c41a6105ad5ba40f8487f164990 nothing changes for me.  At least since wxMaxima 17.05 versions visual styles issue is not related with manifest anymore (16.12 could be fixed with manifest, look at my previous comments). Maybe you have changed drawning code and broke the msw port?

**Comment by gunterkoenigsmann** [comment]
Lennart had a go at this issue. I hope it is finally resolved now.

**Comment by rend3r** [comment]
@gunterkoenigsmann nope (at least for maxima-clisp-sbcl-current-win64.exe 27-Jan-2018 00:18 nightly).
Look at this https://www.dropbox.com/s/0b79smibgquadah/msw_wxmaxima.mp4?dl=0
1) Quick resize with small amounts leads to sudden window expanding.
2) Really slow button repainting (visual noticed blinking).
3) Weird vertical bars when resizing panels. Panels aren't repainted on the fly.
4) Buttons is still broken.
