### ISSUE TITLE
The possibility of opening the gnuplot command window dissapeard

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#771]
Former issue #745 
(https://github.com/andrejv/wxmaxima/issues/745)

Previously, when using draw2d to open/plot in a gnuplot window, it was possible within this window to open another window - the gnuplot command window.

In the current release of wxmaxima, it seems like this possibility has gone.
Is there a way to get it back ?

I have tried to replace the installed gnuplot (the whole gnuplot directory under the Maxima directory) with the working version (4.6) . It did not help nor change anything. 

By the way the current wxmaxima version is pacaked with same gnuplot version 4.6 as the former wxmaxima - which was working - came with.

wxMaxima version: 16.4.2
Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL

Kind regards

Rene'

**Comment by gunterkoenigsmann** [comment]
I might have one idea: Could you try changing the maxima variable

      gnuplot_command

from "gnuplot.exe" to "wgnuplot.exe"?

wgnuplot.exe causes constant flickering of the active window on calculating animations and catches the focus for short instances so keys entered on the keyboard get missing when one types while cells containing draw and plot commands are evaluated. But perhaps wgnuplot contained the feature: The draw package has changed from wgnuplot to gnuplot a while ago.

**Comment by ReneSci** [comment]
Yes, the
gnuplot_command : "wgnuplot.exe";

Does give the feature back.

Eventually, the user can switch between gnuplt and wgnuplot when creating
animations etc.

Thank you for your help.
Regards
Rene'



2016-10-03 16:46 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
A thing that came to my mind when I saw your bug report was:

Currently draw allows for a fairly huge number of different objects -
which is great.

...and it allows to specify raw gnuplot commands as user_preamble and as
user_postamble. But currently there is no way of adding raw gnuplot
commands to the middle of the scene. Don't know if that would be worth a
feature request for maxima as I don't know if that is what you use the
command window for.


Kind regards,

 Gunter.

**Comment by ReneSci** [comment]
Yes, I do use especially the user_preamble, in fact I have made a
"standard" plot set-up, which I often put in top of my working sheet. I
have not tried (or even knew about) user_postamble.


set_draw_defaults(
dimensions    = [1500, 800],
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set
font 'Areal, 8 '", "set zero 10^-100",  "set format y '%0.3se%03S'", "unset
clip", "set autoscale y", "set autoscale y2" ],
xtics  = twoLineDataXtics[1],
xtics_rotate = true,
font = "Times",
font_size = 12,
title = PlotTitle,
xlabel = "Time",
ylabel = PlotYlabel,
ylabel_secondary = PlotY2label,
grid = true,
palette = gray,
point_type = 0,
point_size = 1,
points_joined = true);

I use the gnuplot command for fine-tuning a plot to become "nice" e.c. for
a presentation and for exploring gnuplot commanda/possibilities.

Regarding your suggestion
 "But currently there is no way of adding raw gnuplot
commands to the middle of the scene. Don't know if that would be worth a
feature request for maxima as I don't know if that is what you use the
command window for."

If this opens for more individual setting for each plot on a graph, it
could indeed be a nice freature.

Could it be possible to e.g. right-click on a graph in the worksheet and
open the gnuplot command window to modify the plot ?

I could also sometimes need a third and a fourth y-axix, but I know that
this is a gnuplot feature.

A suggestion: like the other nice wizards (for entering e.g. matrices,
duing basic plots etc.) you have introduced, my suggestion could be: why
not have a wizard for creating a user_preamble line like e.g. this - or
even a whole plot set-up:
"user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set
font 'Areal, 8 '", "set zero 10^-100",  "set format y '%0.3se%03S'", "unset
clip", "set autoscale y", "set autoscale y2" ],"

Kind regards
Rene'


2016-10-05 7:22 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
> 
> Could it be possible to e.g. right-click on a graph in the worksheet and
> open the gnuplot command window to modify the plot ?
> 
This is technically possible but unfortuately quite complicated to do:
Maxima creates one file with maxima commands and one file with data for
the plot and reuses both files for all plots. Right-clicking on a plot
that isn't the last one in the worksheet would first of all require the
maxima team to change this.

> I could also sometimes need a third and a fourth y-axix, but I know that
> this is a gnuplot feature.
It is. ...but sometimes the gnuplot guys respond quite fast to feature
requests...

> A suggestion: like the other nice wizards (for entering e.g. matrices,
> duing basic plots etc.) you have introduced, 
This was Andrej, not me.

> my suggestion could be: why
> not have a wizard for creating a user_preamble line like e.g. this - or
> even a whole plot set-up:
> "user_preamble = ["set xtics out", "set mxtics 10", "set ytics out", "set
> font 'Areal, 8 '", "set zero 10^-100", "set format y '%0.3se%03S'", "unset
> clip", "set autoscale y", "set autoscale y2" ],"
There is a similar feature: set_draw_defaults and set_plot_defaults or
similar.

---

As I never use the wizards I won't be the one who will write the code
for wizard feature requests. But if you file a new feature request
ticket perhaps one of the other developers will.

Kind regards,

 Gunter.

**Comment by ReneSci** [comment]
It seems like no mater whether the option 
gnuplot_command : "wgnuplot.exe";
is used or the default gnuplot_command,

Using any font settings: either in the user_preamble like this:

set_draw_defaults(
dimensions    = [1500, 800],
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", **"set font 'Areal, 8 '",** "set zero 10^-100", 
"set format y '%0.3se%03S'", "unset clip", "set autoscale y",  "set autoscale x" ],
  font_size      = 12,
     title          = PlotTitle,
xlabel         = PlotXlabel,
ylabel         = PlotYlabel,
    grid           = true,
    palette        = gray,
 point_type    = 0,
   point_size    = 1,
points_joined = true);

- Or by using the option  font = "Times", 

set_draw_defaults(
dimensions    = [1500, 800],
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set zero 10^-100", 
"set format y '%0.3se%03S'", "unset clip", "set autoscale y",  "set autoscale x" ],
  **font           = "Times",** 
 font_size      = 12,
     title          = PlotTitle,
xlabel         = PlotXlabel,
ylabel         = PlotYlabel,
    grid           = true,
    palette        = gray,
 point_type    = 0,
   point_size    = 1,
points_joined = true);

makes the with_slider_draw( ) and the wxdraw2d() do crazy with error messages like:

Message from maxima's stderr stream: 
(gnuplot.exe:9148): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.

(gnuplot.exe:7960): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.

(gnuplot.exe:8512): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.

(gnuplot.exe:1792): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.

(gnuplot.exe:8056): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.


after using a  with_slider_draw( ) the slider_draw-plot appears everywhere - even as an output for wxdraw2d() 

**Version:**
(%i19)	wxbuild_info()$
wxMaxima version: 16.12.x-unofficial
	Maxima version: 5.39.0_2_g5a49f11_dirty
	Maxima build date: 2016-12-11 23:20:41
	Host type: i686-w64-mingw32
	System type: 
	gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
	SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
	libsigsegv 2.8
	libiconv 1.13
	libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
	Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on maxima [10.0.3.1])


Any clue?

Kind regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Unfortunately I have no idea what fonts the gnuplot the windows installer is packaged with comes with. Also I am unsure why it is apparently not able to read system fonts. I would have expected it to be able to load Times... ...and I would not be surprised if "Arial" instead of "Areal" doesn't do the trick. That means: If gnuplotwants the exact name that has been written in the font "Times New Roman" might work instead of "Times".

**Comment by daute** [comment]
Fixed with commits:
https://github.com/wxMaxima-developers/wxmaxima/commit/7a480abe6f771cd04205b1340118e255a1825845
https://github.com/wxMaxima-developers/wxmaxima/commit/094cd8cc7940740c7c41ea3fd745f2b9efc2deef
https://github.com/wxMaxima-developers/wxmaxima/commit/7a480abe6f771cd04205b1340118e255a1825845

wgnuplot can be found, even if wxMaxima is installed alone and the change of the terminal restores the Gnuplot command line possibility.
