### ISSUE TITLE
Alert of unexpected quit on MacOS X

### ISSUE THREAD

**Issue by tomio-arisaka** [wxMaxima-developers/wxmaxima#881]
I compiled and checked the file "wxmaxima-6d1e1bef49de3da4f5f97af7adba5da3622051f3.zip" on MacOS X.
I have a trouble with this version.

(1) I launched wxMaxima, then an empty window was opened.

(2) I selected the menu "Help->Maxima help", then the window "Help: wxMaxima Manual" was opened.

(3) I selected the menu "wxMaxima->Quit Wxmaxima", then I got the next alert.

![08](https://cloud.githubusercontent.com/assets/27427563/25166456/78152a06-2516-11e7-92ed-5291259d611c.png)
![09](https://cloud.githubusercontent.com/assets/27427563/25166461/8105a636-2516-11e7-94ca-d82c1dc8b4b9.png)
![10](https://cloud.githubusercontent.com/assets/27427563/25166467/86db9e08-2516-11e7-8a50-dfbd6e65829d.png)
[Crash_log.zip](https://github.com/andrejv/wxmaxima/files/932069/Crash_log.zip)

**Comment by tomio-arisaka** [comment]
I compiled and checked the file "wxmaxima-fa8078ba4c8a899d85721f3f73bcd533e32184bf.zip" on MacOS X.
This version of wxMaxima does not fix the problem.

The crash log is attached.
[crash_log_0421.zip](https://github.com/andrejv/wxmaxima/files/947631/crash_log_0421.zip)

**Comment by andrejv** [comment]
Which version of wxWidgets do you have? This looks more like a wxWidgets but. The error comes from the Help Window which tries to write some settings.

**Comment by tomio-arisaka** [comment]
Thanks for your response.

I have a version 3.0.2 of wxWidgets which is compiled with MacPorts.

**Comment by gunterkoenigsmann** [comment]
In the meantime I have spent much time in avoiding any possibility to do a double-free => With a bit of luck the error is gone in the new release, either because we happen no more to trigger the wxWidgets problem or because it is corrected.

**Comment by KubaO** [comment]
This was an error in `wxHtmlHelpWindow`, that we can do little about. Closing, especially that we don't use that widget anymore, and use the system html browser instead.
