### ISSUE TITLE
Help window scroll problem

### ISSUE THREAD

**Issue by oheid** [wxMaxima-developers/wxmaxima#927]
The wxMaxima help window doesn't allow to scroll down. Neither slider nor page down button works, which renders most of the help text inaccessible.
I could reproduce this in versions 14.0.9, 15.08.2, 16.04.2, 16.12.2 and 17.05.1, and they all have the same problem (built as Fedora 24, 25, 26, 28 rawhide rpms). The latest 17.05.1 version seems to have an additional problem with the help window background color: It randomly switches between grey and white during redraws.

**Comment by gunterkoenigsmann** [comment]
Unfortunately the help window isn't drawn by wxMaxima itself. Instead wxMaxima tells wxWidgets to tell the operating system to startup the default help browser application. Seems like fedora is broken here...

**Comment by KubaO** [comment]
I believe that this should be closed, since there's nothing we can fix here, and there's no real workaround either, I don't think. The user can select a different help browser of course.

**Comment by gunterkoenigsmann** [comment]
Definitively should be closed: We have since changed the help browser from the broken wxWidgets one to the system's default HTML browser.
