### ISSUE TITLE
A "Reset all to default" button for the config dialogue

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#934]
The code currently doesn't prepare implementing this button => loads of work. But it would be practical.

**Comment by endolith** [comment]
In the meantime, how do we reset all settings to defaults?

**Comment by KubaO** [comment]
There isn’t anything that does it. You have to do it manually or by removing the registry key for wxMaxima, or by removing the configuration file.
