### ISSUE TITLE
Windows printing of worksheet has line to line spacing of 1.25 inches

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#947]
I have search the issues and see this is an on going problem.

I can't get wxmaxima to print a worksheet.  It comes out super big and gets about 16 characters in a line.

I tried to export to html file, but loading into Chrome almost works.

None of the escape codes with backslash are converted.
A backslash is codes as \backslash.  as below:
![capture](https://user-images.githubusercontent.com/31253976/34425978-6d8f5e96-ebf7-11e7-99d0-cee147953154.PNG)

![capture](https://user-images.githubusercontent.com/31253976/34425966-38e2c2b4-ebf7-11e7-9e1f-4ceb3da3da3b.PNG)

**Comment by gunterkoenigsmann** [comment]
The backslash issue is in MathJax. If you export maths ans svg or as bitmap it won't occur.

Did you try the Nightly build? I hoped that the printing scale is finally fixed there...

**Comment by richardgobeli** [comment]
I tried the build from 12/29/2017 and the print is still very big.  I did not see a reference for the commit of this bug fix.
What I did find is the jacobian did complete with 0 erros, but the program hung up and the result was not printed.
below is the code example where it does work.
![capture](https://user-images.githubusercontent.com/31253976/34444671-59e774ca-ec95-11e7-95d3-50309e50d7bc.PNG)

**Comment by gunterkoenigsmann** [comment]
Weird: On my computer the Jacobian works fine (nightly build of wxMaxima and maxima) => Either our computers are different in an aspect important for this problem. Or I have typed it wrong. As github won't let you attach .wxmx files I can play with you can send them to wxMaxima (at) physikbuch (dot) de

...for the other problem tomorrow's nightly build might provide a solution - or make things worse. Or none of these options: I seem still not to have understood how scaling for printing on windows works.

**Comment by richardgobeli** [comment]
Sorry that was a bad install.  the jacobian does work OK. 
The print is still not good.

**Comment by richardgobeli** [comment]
Can I see what wxmaxima thinks the print PPI and screen PPI is?

**Comment by gunterkoenigsmann** [comment]
Let's hope that my last commit compiles.

**Comment by richardgobeli** [comment]
Do I need to wait until tomorrow?

**Comment by gunterkoenigsmann** [comment]
Unfortunately this is the case.

**Comment by richardgobeli** [comment]
I did not see a message box showing the printer data.  Where is it suppose to be?

**Comment by gunterkoenigsmann** [comment]
I'm theory it should open when you try to print... ...will try to find out what is wrong.

**Comment by richardgobeli** [comment]
I think it opens and then just disappears very quickly.  It is so fast that I just see an outline of a small rectangle.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the message box should work tomorrow.

And I would like to ask you: As I don't own a windows box: Could you test tomorrow, if autocompletion on pressing "Ctrl+Space" still is usable tomorrow? I *think* I have found a way of drastically improving it but naturally I cannot test if that is true.

**Comment by richardgobeli** [comment]
I am not familiar with auto completion.  What should I test?
Yes, I will test tomorrow.

**Comment by gunterkoenigsmann** [comment]
Cool! Just type in the first few letters of a command, for example

     sol

...and press <Ctrl>+Enter.
In theory a drop-down menu should appear allowing you to select a possible command name using the cursor keys or the mouse pointer. And my hope is that if you also can type in additional letters in this situation. The last time I tried to add the latter I broke this feature for Windows. In the meantime I have added code that forwards key presses from the main window to the pop-up. Let's hope that this finally works.

Thanks in advance,
 Gunter.

**Comment by gunterkoenigsmann** [comment]
I meant Ctrl+Enter. Seems like GitHub interpreted this as a html-style markup...

**Comment by richardgobeli** [comment]
The screen resolution does not look right.  I have a HD monitor with 1920x1080p in landscape mode.
here is the box:
![capture](https://user-images.githubusercontent.com/31253976/34464712-9b5e9de8-ee52-11e7-8285-010874229c39.PNG)

**Comment by gunterkoenigsmann** [comment]
Ok... ...96dpi means your monitor is approximately 30cm wide. Which might be a very rough guess that either wxWidgets or Windows makes and which might explain that some users claim the icons to be way too big/to small...

...but not all is lost here: The user can adjust the zoom factor.

What I now have been told is: wxWidgets tells Windows the pt size of the font to use and windows scales this to a size in pixels according to the screen, not the printer dpi rate. My guess was that printer_dpi/screen_dpi is the correct scale factor to make the font size right for the printer.

Let's give it another try.

**Comment by richardgobeli** [comment]
The printing is getting better, but it is still very small.
![capture](https://user-images.githubusercontent.com/31253976/34504509-98bab6ec-efe4-11e7-8ac3-d9fa9c8a43d2.PNG)
My screen is 1920 x 1080p.  The direction 1920 is 20.5 inches or 52.07 cm.

The ratio between the screen and the printed text is about 10.75 to 1.5 on the printed paper.

**Comment by gunterkoenigsmann** [comment]
Ok... ...for some users the result was vastly wrong still => let's hope that 590c370970f8f63da39e802519ec06402099fc6d repairs the thing - and doesn't break it completely.

**Comment by richardgobeli** [comment]
The print scale does not seem to be linear in one direction.  If the horizontal is less than half the page width, a factor of 2 times will not work.  the most it would take to fill the page is a factor of about 1.4.

**Comment by richardgobeli** [comment]
The scale factor seems to be an area scale factor.
This would indicate that the scale factor is the square root of the linear scale factor.

**Comment by gunterkoenigsmann** [comment]
It nearly looked this way. But I've looked into the code - the scale factor is a simple multiplication applied to both the x and the y extend to objects...

...In the meantime Lennart has done much work on Printing. Hope that this fixes everything and that there isn't another (yet unknown) factor...

**Comment by richardgobeli** [comment]
I looked at this for me to double the x axis I just need to set the factor at 1.414 = sqrt(2) or to half the length I use 0.707 = 1/Sqrt(2).  Maybe I am doing something wrong.  I'll look at this again.

**Comment by KubaO** [comment]
I believe this is now fixed in the master. Please re-open this issue only if it is happening for you on either master branch or the nightly build.
