### ISSUE TITLE
make and cmake produce binaries with different version information

### ISSUE THREAD

**Issue by ckoe-bccms** [wxMaxima-developers/wxmaxima#962]
Hello everybody,

I discovered that binaries built using "make" display a different version number when queried with wxbuild_info() than binaries built using the "cmake" procedure.

I used the wxmaxima-Version-17.10.1.tar.gz from the wxmaxima download page with md5sum 89cbf027a90f711aa66951ffaa081551. From that I used the following procedure to compile and install (to different paths) two wxmaxima binaries:

cd /mnt/ramfs
tar -zxvf wxmaxima-Version-17.10.1.tar.gz
mkdir install_make
cd wxmaxima-Version-17.10.1
./bootstrap
./configure --prefix=/mnt/ramfs/install_make
make; make allmo; make install

cd /mnt/ramfs
mkdir install_cmake
rm -r wxmaxima-Version-17.10.1; tar -zxvf wxmaxima-Version-17.10.1.tar.gz
cd wxmaxima-Version-17.10.1
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/mnt/ramfs/install_cmake ..
cmake --build .
cmake --build . -- install

The binary /mnt/ramfs/install_make/bin/wxmaxima identifies as
 wxMaxima version: 16.12.x-unofficial
while the binary /mnt/ramfs/install_cmake/bin/wxmaxima identifies as
wxMaxima version: 17.10.1
This obvioulsy can lead to some confusion.

Further remarks. The build instructions in wxmaxima-Version-17.10.1/README.md concerning the make build lack a hint that "./bootstrap" needs to be executed first to generate ./configure.

Generally, I would recommend  including a hint that the install location can be changed by using "./configure --prefix=$INSTALL_DIR" or "cmake -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR" so that it becomes clear that no sudo privileges are needed to sucessfully install a working version of wxmaxima. Of course installing to /usr/local with root privileges has the advantage of /usr/local/bin being usually included in the users default PATH, which might appear to be more user-friendly at first. 
However, I consider the usage of "sudo" without second thoughts to install unpackaged software which may in principle modify arbitrary locations without an easy way to revert during install to be not the best style. Even in the most benign case a simple mistake in the make/cmake files is in principle sufficient to have unexpected side effects.

Best Regards

Christof

**Comment by LennartF22** [comment]
This affects (at least) the autoconf.cf of the following branches/tags:

[branch/Version-17.10](https://github.com/andrejv/wxmaxima/blob/Version-17.10/configure.ac)
[tag/Version-17.10.1](https://github.com/andrejv/wxmaxima/blob/Version-17.10.1/configure.ac)
[tag/Version-17.10.0](https://github.com/andrejv/wxmaxima/blob/Version-17.10.0/configure.ac)

Should be an easy fix for somebody with write access to this repository, as only the fourth line needs to be changed @gunterkoenigsmann. You can also fix this by yourself locally.

If printing is frequently used, the current unofficial version should be considered anyway, as it fixes many major problems that can occur with printing (although the unofficial version might introduce new bugs that aren't known yet).

Kind regards,
Lennart

**Comment by gunterkoenigsmann** [comment]
The file configure.ac no more exists...
...and with cmake I have no idea on how to make this work again.

**Comment by ckoe-bccms** [comment]
Hello,

yes, the current git head is cmake build only according to README.md. In that case I would still kindly ask you to include a hint how to set the installation target directory by hand when using cmake, i.e. cmake -DCMAKE_INSTALL_PREFIX:PATH=$PATH_TO_INSTALL_TO

I am on a "real" workstation which is managed centrally. I have no permission to install to /usr/local and frankly getting this information from cmake (e.g. trying cmake --help) is a catastrophe compared to configure --help. In the end I was glad about finding that information on stackoverflow.

Finally, instead of or in addition to "wxMaxima version: 17.10.x.unofficial" which is what the current git head displays I would suggest including the git revision (usually the first 6 to 8 characters). With that one could be sure which source was used. This is quite common for git managed projects, so I assume it should be simple.

Best Regards

Christof

**Comment by daute** [comment]
If wxMaxima is build from a git checkout, the (short) git revision is now printed in the about-window and when calling
wxmaxima --version
Added the hint how to install in a special PREFIX to README.md.
(commits:  https://github.com/andrejv/wxmaxima/commit/c18f36051f786d962fa03f8a29d41b908f3002b2, https://github.com/andrejv/wxmaxima/commit/5d12dfc078ed8d291adf7c14fe3bb341dae3eba9 and https://github.com/andrejv/wxmaxima/commit/7712f64fe26a4aeed363576b49d6676dacf1bee5)

**Comment by ckoe-bccms** [comment]
Hello,

thank you very much for these changes !

Best Regards

Christof

**Comment by KubaO** [comment]
This is an aspect of #1300. Closing.
