### ISSUE TITLE
Printing does not completely print the output, if it is longer than 1 page.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#970]
I don't know if this was reported as an issue or as an improvement before.

A demo(tensor) command will do many pages of output.
If you want to print the demo session it will only print the input command and the output up to only one page.
If you type another command at the end of the demo session, that command will be put at the top of the second page.

This means that any command with long output will be printed only on one page with the input command at the top and you will only see the amount of output that fits on that page.
This is not dependent on the lengths of the output lines.
I can see where it is hard to wrap the long lines of the output or input, but the print function should be able to print all of the output lines even if they get truncated in length.

A multiple input line of 4 or 5  statements ending in a semicolons can produce many lines of output that are longer than 1 page.
This will also be truncated to one page.
Thanks,
Richard

**Comment by richardgobeli** [comment]
Printing demos.
Because the printing does not split command lines the demo looks like one line and only prints the first page of the demo.
Would it be possible that when printing a demo line that the print routine goes one level deeper to decide how big a command input and output line is. This way the whole demo content would be printed as a normal WxMaxima session and after the demo line is over it goes back up one level for printing normal lines again.

**Comment by Parlazo** [comment]
i actualy never saw a demo and do not know which demo you mean if there is one

can you show us such a critical simple line or command in question?

**Comment by richardgobeli** [comment]
demo(tensor); is a good example.

**Comment by gunterkoenigsmann** [comment]
The problem is that the print algorithm decides after which `GroupCell` there should be a page break. This makes printing simple since it allows us to recreate each page as a worksheet containing only the necessary GroupCells and then to re-use the normal display algorithms for printing. Sometimes a GroupCell is higher than a page, though, so in reality we would need a way to print partial GroupCells, instead.
