### ISSUE TITLE
integration flaw

### ISSUE THREAD

**Issue by geandersoncarvalho** [wxMaxima-developers/wxmaxima#988]
I believe that maxima did a wrong integration. The result is attached. The $b$ in the denominator should not be there.
![git](https://user-images.githubusercontent.com/19229331/38032978-4214c426-3275-11e8-8ab2-d2cde8eae281.png)

**Comment by richardgobeli** [comment]
simplify using radcan(%) will reduce the fraction inside the log.
which gives  
![image](https://user-images.githubusercontent.com/31253976/38068785-997a2f9a-32d8-11e8-8637-67e2e353a64d.png)

![image](https://user-images.githubusercontent.com/31253976/38068832-dde92730-32d8-11e8-8a5e-d1e8181027ff.png)
![image](https://user-images.githubusercontent.com/31253976/38068860-ecb03d76-32d8-11e8-82c7-9be6e700bffc.png)

**Comment by gunterkoenigsmann** [comment]
If you have found an integration which you believe to be obviously wrong I would additionally like to  ask you if you are willing to report this integral to: https://sourceforge.net/p/maxima/bugs/ - which is the program that does the actual mathemetics: wxMaxima does all it can to hide the fact that the functionality is divided into two separate programs. But under the hood wxMaxima only displays the maths, handles the input and starts maxima - which does the actual calculations.

---

For radcan (which is very powerful and important to know) normally Richard Fateman (who wrote radcan) gives a caveat: If a function like sqrt(), asin() or atan() has more than one solution radcan picks one and ignores the rest. Which normally is no problem as radcan does a great job in finding the solution that counts. But sometimes it hides answers that are true, too.

**Comment by KubaO** [comment]
If anything, this is a maxima problem. Closing.
