### ISSUE TITLE
wximplicit_plot problem on ubuntu

### ISSUE THREAD

**Issue by tamslinn** [wxMaxima-developers/wxmaxima#997]
Hi, I am getting an error when using the command wximplicit_plot.

```
(%i1)	load(implicit_plot);
(%o1)	"/usr/share/maxima/5.32.1/share/contrib/implicit_plot.lisp"
(%i14)	wximplicit_plot(x^2+y^2=1,[x,-2,2],[y,-2,2]);
```

I get a pop up which says "can't open file /home/tamsin/maxout_7009_7.png
Which I guess isn't the actual error, I'm not sure how to find more useful logs?

Further info - if I run implicit_plot without the wx, I do get a graph in a new window.
When I start wxmaxima I get the following error, but this doesn;t seem to affect anything else

> Maxima encountered a Lisp error:
>  Error in MACSYMA-TOP-LEVEL [or a callee]: The function (MLIST SIMP) is undefined.
> Automatically continuing.
> To enable the Lisp debugger set *debugger-hook* to nil.
> 

Thanks for any help in tracking down the cause of this.

Installation Details
wxMaxima version: 18.02.0
Maxima version: 5.32.1
Maxima build date: 2014-01-10 01:52:55
Host type: x86_64-unknown-linux-gnu
System type: BSD BSD NIL
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.10
wxMaxima's idea of the directory layout is:
Icon dir: /usr/share/wxMaxima
User configuration dir: /home/tamsin/
Help dir: /usr/share/doc/wxmaxima
Maxima lisp dir: /usr/share/maxima//5.32.1

**Comment by gunterkoenigsmann** [comment]
That looks strange. Does the problem still occur if you uninstall maxima and install a version from https://code.launchpad.net/~maxima-developers/+archive/ubuntu/maxima-nightly instead? In theory it doesn't matter too much which Ubuntu version this version was compiled for: Each maxima binary tries to include the whole runtime it needs in order to work correctly.

**Comment by tamslinn** [comment]
Hi, Thanks for the reply I tried to install the nightly build by adding the PPA but I get this error when installing:

```
Preparing to unpack .../maxima-common_5.41.0-24~201804271623~ubuntu14.04.1_all.deb ...
Unpacking maxima-common (5.41.0-24~201804271623~ubuntu14.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/maxima-common_5.41.0-24~201804271623~ubuntu14.04.1_all.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/maxima.1.gz', which is also in package maxima 5.32.1-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package maxima-sbcl.
Preparing to unpack .../maxima-sbcl_5.41.0-24~201804252139~ubuntu14.04.1_amd64.deb ...
Unpacking maxima-sbcl (5.41.0-24~201804252139~ubuntu14.04.1) ...
Preparing to unpack .../maxima_5.41.0-24~201804271623~ubuntu14.04.1_all.deb ...
Unpacking maxima (5.41.0-24~201804271623~ubuntu14.04.1) over (5.32.1-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
install-info: warning: no info dir entry in `/usr/share/info/maxima-index.lisp.gz'
Errors were encountered while processing:
 /var/cache/apt/archives/maxima-common_5.41.0-24~201804271623~ubuntu14.04.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by gunterkoenigsmann** [comment]
That looks like you'll have to uninstall Ubuntu's Maxima first before installing the one from the PPA...

**Comment by tamslinn** [comment]
I've managed to install the latest version. I was still havig the same error

```
load(implicit_plot);
(%o1)   "/usr/share/maxima/5.32.1/share/contrib/implicit_plot.lisp"
```

Then I noticed it was still trying to load the extension from the 5.32.1 directory, which doesn't exist.

From the menu  chose Maxima > Add to Path, and added the directory /usr/share/maxima/5.41post/share/contrib

Now when I load the extension, it comes from the right directory and wximplicit_plot works

```
(%i3)   load(implicit_plot);
(%o3)   "/usr/share/maxima/5.41post/share/contrib/implicit_plot.lisp"
```

I'm not sure where it is picking up the 5.32.1 path from, is there somewhere I can change it? as otherwise I have to add the correct path each time I open wxmaxima.

Thanks for your help!

**Comment by gunterkoenigsmann** [comment]
Sorry for the long delay of my answer.

That nearly looks like you have all the files of the new maxima installed, but the binaries from the old one still exist as does the /usr/bin/maxima from the old install.

If you type

     which maxima

into the console you should see what executable is being used. I believe this will be /usr/bin/maxima

You can just open it with a text editor and replace the "5.32.1" by a "5.41post". Then it should invoke the new maxima.

In the meantime I hope I have managed to change the .deb files to tell the debian installer in a cleaner way what to uninstall before installing the maxima from the ppa. I hope this will avoid the problems you have encountered. Sorry that I have misused you as a tester here - even if I believed that no more testers are needed as the ppa ran for a long time now without anyone complaining.

**Comment by tamslinn** [comment]
Thanks and sorry for the slow reply too. Editing this file worked, so I'll close the issue.

**Comment by tamslinn** [comment]
Hi, sorry I still have a problem with this.

I uninstalled everything, checked it was gone, then reinstalled. I had to install manually package by package

apt-get install maxima-common
apt-get install maxima-sbcl

> apt-get install maxima-sbcl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  maxima wxmaxima
Suggested packages:
  texmacs
Recommended packages:
  maxima-doc
The following NEW packages will be installed
  maxima maxima-sbcl wxmaxima
0 to upgrade, 3 to newly install, 0 to remove and 63 not to upgrade.
Need to get 10.4 MB/14.1 MB of archives.
After this operation, 94.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
WARNING: The following packages cannot be authenticated!
  maxima-sbcl maxima wxmaxima
Install these packages without verification? [y/N] y
Get:1 http://ppa.launchpad.net/maxima-developers/maxima-nightly/ubuntu/ trusty/main maxima-sbcl amd64 5.41.0-27~201806112108~ubuntu14.04.1 [10.3 MB]
Get:2 http://ppa.launchpad.net/maxima-developers/maxima-nightly/ubuntu/ trusty/main maxima all 5.41.0-27~201806112108~ubuntu14.04.1 [62.5 kB]
Fetched 10.4 MB in 11s (922 kB/s)                                              
Selecting previously unselected package maxima-sbcl.
(Reading database ... 1835379 files and directories currently installed.)
Preparing to unpack .../maxima-sbcl_5.41.0-27~201806112108~ubuntu14.04.1_amd64.deb ...
Unpacking maxima-sbcl (5.41.0-27~201806112108~ubuntu14.04.1) ...
Selecting previously unselected package maxima.
Preparing to unpack .../maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb ...
Unpacking maxima (5.41.0-27~201806112108~ubuntu14.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb (--unpack):
 trying to overwrite '/usr/share/info/maxima-index.lisp.gz', which is also in package maxima-common 5.41.0-27~201806112108~ubuntu14.04.1
Selecting previously unselected package wxmaxima.
Preparing to unpack .../wxmaxima_18.02.0-2~ppa1~trusty_amd64.deb ...
Unpacking wxmaxima (18.02.0-2~ppa1~trusty) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
install-info: warning: no info dir entry in `/usr/share/info/maxima-index.lisp'
install-info: warning: no info dir entry in `/usr/share/info/maxima-index.lisp.gz'
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

It actually did install wxmaxima which is working, but my package manager is broken with a red warning icon and the message "Error: BrokenCount > 0"

If I run apt-get update I get the following:

> W: Ignoring Provides line with DepCompareOp for package maxima-doc
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima
W: Ignoring Provides line with DepCompareOp for package maxima

Because the package manager is broken I can't update other software. Thanks for any suggestions

**Comment by gunterkoenigsmann** [comment]
The warning

    WARNING: The following packages cannot be authenticated!
    maxima-sbcl maxima wxmaxima

seems to indicate that you did an

    sudo apt-add-repository

in order to tell your system to download the ppa files.

    sudo apt-get update

somehow resulted in an error which means that the `apt-add-repository` somehow has failed.

But for the actual problem I think I have a workaround:

    sudo apt-get remove -f maxima
    sudo apt-get install maxima-sbcl

Afterwards maxima should work. Now I have to find out why "maxima" isn't a virtual package but one that actually contains data files.

Thanks a lot for this bug report!

 Gunter.

**Comment by tamslinn** [comment]
thanks for the reply. I tried to remove maxima but it wasn't installed. I followed the instructions and got the error at the end of this. Does this help:

> tamsin@zen:~$ sudo apt-get remove -f maxima
[sudo] password for tamsin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'maxima' is not installed, so not removed
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies.
 wxmaxima : Depends: maxima (>= 5.32) but it is not going to be installed
            Recommends: maxima-doc but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
tamsin@zen:~$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  maxima
The following NEW packages will be installed
  maxima
0 to upgrade, 1 to newly install, 0 to remove and 63 not to upgrade.
2 not fully installed or removed.
Need to get 0 B/62.5 kB of archives.
After this operation, 90.1 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 1835461 files and directories currently installed.)
Preparing to unpack .../maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb ...
Unpacking maxima (5.41.0-27~201806112108~ubuntu14.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb (--unpack):
 trying to overwrite '/usr/share/info/maxima-index.lisp.gz', which is also in package maxima-common 5.41.0-27~201806112108~ubuntu14.04.1
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
install-info: warning: no info dir entry in `/usr/share/info/maxima-index.lisp'
install-info: warning: no info dir entry in `/usr/share/info/maxima-index.lisp.gz'
Errors were encountered while processing:
 /var/cache/apt/archives/maxima_5.41.0-27~201806112108~ubuntu14.04.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by gunterkoenigsmann** [comment]
If I interpret this right
- the wxMaxima you have installed tries to install "maxima" besides "maxima-common" and "maxima-sbcl" because it wants "maxima-doc" in a specific version
- and the package installer you have doesn't understand that both packages are already provided by "maxima-common".

The wxMaxima packages found at https://launchpad.net/~blahota/+archive/ubuntu/wxmaxima and https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies should not do so - so replacing your wxMaxima by them might fix this problem, as well.

**Comment by KubaO** [comment]
This would be a packaging problem, then, that we have no control over. The remainder of this issue is tracked in #1106.
